{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-device",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.device.yearclass",
          "module": "yearclass",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-device-4.2.0.aar",
          "url": "expo-device-4.2.0.aar",
          "size": 24088,
          "sha512": "534bcdf93948af61afeeb63722b4f89946a0bf5fd84bb4e15699a627441b79299ab0f8703c3b52b142479399390ace99cb956107522bbf7925beef9c6a8db4ab",
          "sha256": "436fd79da7ab7d8ed312f5a3d7c303cfec109be658bb0ac3c21c9724740ff995",
          "sha1": "2471b05774f481e6199611118f8c825d925d5fd8",
          "md5": "de38b5f23349de346752bcc06069d8d7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.device.yearclass",
          "module": "yearclass",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-device-4.2.0.aar",
          "url": "expo-device-4.2.0.aar",
          "size": 24088,
          "sha512": "534bcdf93948af61afeeb63722b4f89946a0bf5fd84bb4e15699a627441b79299ab0f8703c3b52b142479399390ace99cb956107522bbf7925beef9c6a8db4ab",
          "sha256": "436fd79da7ab7d8ed312f5a3d7c303cfec109be658bb0ac3c21c9724740ff995",
          "sha1": "2471b05774f481e6199611118f8c825d925d5fd8",
          "md5": "de38b5f23349de346752bcc06069d8d7"
        }
      ]
    }
  ]
}
