{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-firebase-core",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.1.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common",
          "version": {
            "requires": "20.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-firebase-core-5.0.0.aar",
          "url": "expo-firebase-core-5.0.0.aar",
          "size": 18915,
          "sha512": "facc3067c11fd38f20036a5e652029f928260196a0ed68c9b77c8476d72041b531cb3e6d805e0e418776a84326a5ea6f9249afc80773f4bf4073eccca05ec3f5",
          "sha256": "62df6dfa968be0ddfa11bdde740b08a4efefed7f3b164f973f6a0546ef8cf810",
          "sha1": "c242a17570f5dec772b953f07523ff7030853689",
          "md5": "a97256bd36b940fe4d022ceba6cf545d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.1.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-firebase-core-5.0.0.aar",
          "url": "expo-firebase-core-5.0.0.aar",
          "size": 18915,
          "sha512": "facc3067c11fd38f20036a5e652029f928260196a0ed68c9b77c8476d72041b531cb3e6d805e0e418776a84326a5ea6f9249afc80773f4bf4073eccca05ec3f5",
          "sha256": "62df6dfa968be0ddfa11bdde740b08a4efefed7f3b164f973f6a0546ef8cf810",
          "sha1": "c242a17570f5dec772b953f07523ff7030853689",
          "md5": "a97256bd36b940fe4d022ceba6cf545d"
        }
      ]
    }
  ]
}
