{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-file-system",
    "version": "14.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-file-system-14.0.0.aar",
          "url": "expo-file-system-14.0.0.aar",
          "size": 83174,
          "sha512": "5fcd4edbc10cca22b3d0490afb7d7e4ae100ef88cf22917b0563da23c33699a283942cab67343de4c3377af4d9bd9a85edd7aa7a5fef6a43cf9a047cad1f81b5",
          "sha256": "0c25038036a34b9a5deddd904b3c2879cd5ac41ef50a14d458d230032e1440fa",
          "sha1": "b58a95e0e768df2cf7924e7ba34a0d01f9d75961",
          "md5": "755a2a73a69361e22cb4ef90e8b9c256"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-file-system-14.0.0.aar",
          "url": "expo-file-system-14.0.0.aar",
          "size": 83174,
          "sha512": "5fcd4edbc10cca22b3d0490afb7d7e4ae100ef88cf22917b0563da23c33699a283942cab67343de4c3377af4d9bd9a85edd7aa7a5fef6a43cf9a047cad1f81b5",
          "sha256": "0c25038036a34b9a5deddd904b3c2879cd5ac41ef50a14d458d230032e1440fa",
          "sha1": "b58a95e0e768df2cf7924e7ba34a0d01f9d75961",
          "md5": "755a2a73a69361e22cb4ef90e8b9c256"
        }
      ]
    }
  ]
}
