/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifdef ABI47_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// FB Internal: FBCoreModulesPlugins.h is autogenerated by the build system.
#import <ABI47_0_0React/ABI47_0_0FBCoreModulesPlugins.h>

#else

// OSS-compatibility layer

#import <Foundation/Foundation.h>

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"

#ifdef __cplusplus
extern "C" {
#endif

// ABI47_0_0RCTTurboModuleManagerDelegate should call this to resolve module classes.
Class ABI47_0_0RCTCoreModulesClassProvider(const char *name);

// Lookup functions
Class ABI47_0_0RCTAccessibilityManagerCls(void) __attribute__((used));
Class ABI47_0_0RCTAppearanceCls(void) __attribute__((used));
Class ABI47_0_0RCTDeviceInfoCls(void) __attribute__((used));
Class ABI47_0_0RCTExceptionsManagerCls(void) __attribute__((used));
Class ABI47_0_0RCTPlatformCls(void) __attribute__((used));
Class ABI47_0_0RCTClipboardCls(void) __attribute__((used));
Class ABI47_0_0RCTI18nManagerCls(void) __attribute__((used));
Class ABI47_0_0RCTSourceCodeCls(void) __attribute__((used));
Class ABI47_0_0RCTActionSheetManagerCls(void) __attribute__((used));
Class ABI47_0_0RCTAlertManagerCls(void) __attribute__((used));
Class ABI47_0_0RCTAsyncLocalStorageCls(void) __attribute__((used));
Class ABI47_0_0RCTTimingCls(void) __attribute__((used));
Class ABI47_0_0RCTStatusBarManagerCls(void) __attribute__((used));
Class ABI47_0_0RCTKeyboardObserverCls(void) __attribute__((used));
Class ABI47_0_0RCTAppStateCls(void) __attribute__((used));
Class ABI47_0_0RCTPerfMonitorCls(void) __attribute__((used));
Class ABI47_0_0RCTDevMenuCls(void) __attribute__((used));
Class ABI47_0_0RCTDevSettingsCls(void) __attribute__((used));
Class ABI47_0_0RCTRedBoxCls(void) __attribute__((used));
Class ABI47_0_0RCTLogBoxCls(void) __attribute__((used));
Class ABI47_0_0RCTWebSocketExecutorCls(void) __attribute__((used));
Class ABI47_0_0RCTWebSocketModuleCls(void) __attribute__((used));
Class ABI47_0_0RCTDevLoadingViewCls(void) __attribute__((used));
Class ABI47_0_0RCTDevSplitBundleLoaderCls(void) __attribute__((used));
Class ABI47_0_0RCTEventDispatcherCls(void) __attribute__((used));

#ifdef __cplusplus
}
#endif

#pragma GCC diagnostic pop

#endif // ABI47_0_0RN_DISABLE_OSS_PLUGIN_HEADER
