/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function generateKeyAsync(): Promise<any> {
  return 'mock-key';
}

export async function attestKeyAsync(key: string, challenge: string): Promise<any> {
  return 'mock-attestation';
}

export async function generateAssertionAsync(key: string, challenge: string): Promise<string> {
  return '';
}

export async function requestIntegrityCheckAsync(challenge: string): Promise<string> {
  return '';
}

export async function prepareIntegrityTokenProviderAsync(
  cloudProjectNumber: string
): Promise<void> {}
