{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-task-manager",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-task-manager-10.2.0.aar",
          "url": "expo-task-manager-10.2.0.aar",
          "size": 50783,
          "sha512": "18a87a7ca213efaff0f904fecb6979a32ef927b6498d86316be786f6db77dc521b262b063a644275620a335aac4e1e28f94453bddcca8cdabb62b86187e32d1b",
          "sha256": "59d811ce2e0a0c8033f6c5dfd68746f7483f528fcab5e9932cf5b9b369a2c2a1",
          "sha1": "dcb2e69117aa24f1e5cd467a3ea4f016b4f91f98",
          "md5": "7e728505362e08ee6e27b303f6649f82"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "unimodules-app-loader",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-task-manager-10.2.0.aar",
          "url": "expo-task-manager-10.2.0.aar",
          "size": 50783,
          "sha512": "18a87a7ca213efaff0f904fecb6979a32ef927b6498d86316be786f6db77dc521b262b063a644275620a335aac4e1e28f94453bddcca8cdabb62b86187e32d1b",
          "sha256": "59d811ce2e0a0c8033f6c5dfd68746f7483f528fcab5e9932cf5b9b369a2c2a1",
          "sha1": "dcb2e69117aa24f1e5cd467a3ea4f016b4f91f98",
          "md5": "7e728505362e08ee6e27b303f6649f82"
        }
      ]
    }
  ]
}
