{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-gl",
    "version": "11.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-gl-11.2.2.aar",
          "url": "expo-gl-11.2.2.aar",
          "size": 40014,
          "sha512": "a766864335c4c7b710dd453a9fd76ebdfde4047ea04aa750353987a828e6786d08e3ffb985220710328659a3f2905381810d4a156d104af0ea7e0a955e7362e8",
          "sha256": "6f76dda2c2a9f9652b22e3cf2cb5786723b2e4c2457b8ec6869ee3462ae1e95d",
          "sha1": "25b1ac87c2ba5d13439916ac9ff54b326a77daca",
          "md5": "b790a867980a5fcde614828dddacbc77"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-gl-cpp",
          "version": {
            "requires": "11.2.1"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-gl-11.2.2.aar",
          "url": "expo-gl-11.2.2.aar",
          "size": 40014,
          "sha512": "a766864335c4c7b710dd453a9fd76ebdfde4047ea04aa750353987a828e6786d08e3ffb985220710328659a3f2905381810d4a156d104af0ea7e0a955e7362e8",
          "sha256": "6f76dda2c2a9f9652b22e3cf2cb5786723b2e4c2457b8ec6869ee3462ae1e95d",
          "sha1": "25b1ac87c2ba5d13439916ac9ff54b326a77daca",
          "md5": "b790a867980a5fcde614828dddacbc77"
        }
      ]
    }
  ]
}
