require File.join(`node --print "require.resolve('react-native/package.json')"`, "../scripts/react_native_pods")
require File.join(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`, "../native_modules")
require File.join(`node --print "require.resolve('@unimodules/react-native-adapter/package.json')"`, "../scripts/autolinking")

platform :ios, '11.0'

target 'bare-sandbox' do
  use_expo_modules!

  config = use_native_modules!

  pod 'expo-dev-menu', path: '../../../packages/expo-dev-menu', :configurations => :debug
  pod 'expo-dev-launcher', path: '../../../packages/expo-dev-launcher', :configurations => :debug

  use_react_native!(:path => config["reactNativePath"])
end
