{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-contacts",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-contacts-10.2.0.aar",
          "url": "expo-contacts-10.2.0.aar",
          "size": 55294,
          "sha512": "7aaf55eefdc6593b584ce342d9271bb4e0a944f78c5cf13d8d27a6ea0423a575b396726bcbd1f6fb27a65dce2c0c8d620c2a79a4918fe362892eed402914f4b8",
          "sha256": "853be86906c03e47f070848eb53f84cfb11a199f0692fe7e0e651ca297c2fc8e",
          "sha1": "bb26a238b0b492b4d9ea12e02b1c27f13c376709",
          "md5": "4b4a100db5c201deff2e596c1a54fd5d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-contacts-10.2.0.aar",
          "url": "expo-contacts-10.2.0.aar",
          "size": 55294,
          "sha512": "7aaf55eefdc6593b584ce342d9271bb4e0a944f78c5cf13d8d27a6ea0423a575b396726bcbd1f6fb27a65dce2c0c8d620c2a79a4918fe362892eed402914f4b8",
          "sha256": "853be86906c03e47f070848eb53f84cfb11a199f0692fe7e0e651ca297c2fc8e",
          "sha1": "bb26a238b0b492b4d9ea12e02b1c27f13c376709",
          "md5": "4b4a100db5c201deff2e596c1a54fd5d"
        }
      ]
    }
  ]
}
