{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-media-library",
    "version": "14.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "expo-media-library-14.1.0.aar",
          "url": "expo-media-library-14.1.0.aar",
          "size": 119066,
          "sha512": "73d7ca5b3d96c869a6b0e1b8d71be04369bbbbfe6e44e3958887e55e0c7148aedd8a35277f3271e7729b447c7c7f677a5ced6f1299660f3003b1a300bd397e92",
          "sha256": "9235e1ba16173bed7cf80bc332178f788fce7523fc93ed888f2fcb34748949ae",
          "sha1": "783be1ce4c27f54ef533d677d3a466cbd8a8dbc8",
          "md5": "ccff546104ee7df6fdd8dfc1672c9b70"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-media-library-14.1.0.aar",
          "url": "expo-media-library-14.1.0.aar",
          "size": 119066,
          "sha512": "73d7ca5b3d96c869a6b0e1b8d71be04369bbbbfe6e44e3958887e55e0c7148aedd8a35277f3271e7729b447c7c7f677a5ced6f1299660f3003b1a300bd397e92",
          "sha256": "9235e1ba16173bed7cf80bc332178f788fce7523fc93ed888f2fcb34748949ae",
          "sha1": "783be1ce4c27f54ef533d677d3a466cbd8a8dbc8",
          "md5": "ccff546104ee7df6fdd8dfc1672c9b70"
        }
      ]
    }
  ]
}
