/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function getCellularGenerationAsync(): Promise<number> {
  return 0;
}

export async function allowsVoipAsync(): Promise<boolean | undefined> {
  return false;
}

export async function getIsoCountryCodeAsync(): Promise<string | undefined> {
  return '';
}

export async function getCarrierNameAsync(): Promise<string | undefined> {
  return '';
}

export async function getMobileCountryCodeAsync(): Promise<string | undefined> {
  return '';
}

export async function getMobileNetworkCodeAsync(): Promise<string | undefined> {
  return '';
}
