{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-battery",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-battery-6.2.0.aar",
          "url": "expo-battery-6.2.0.aar",
          "size": 25647,
          "sha512": "d2921e72637897e3a63e75174dc0cb2d8b7edea5de1bdbf26946ad61d2e5d8b2dfa01485c4c840d1dbb04899c162e6001808e0f3c4b0f6ef122d919cda148f4d",
          "sha256": "90aa95b778c8c4cdc0d6c4881bcd9b2bd7e96023e9a1c7dd5c01f9dbb0e68fe9",
          "sha1": "4d1be62f75e08633900e5c1d030623621bf86f2e",
          "md5": "fcd2b651927e0164d8f14e4ddfc64f27"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-battery-6.2.0.aar",
          "url": "expo-battery-6.2.0.aar",
          "size": 25647,
          "sha512": "d2921e72637897e3a63e75174dc0cb2d8b7edea5de1bdbf26946ad61d2e5d8b2dfa01485c4c840d1dbb04899c162e6001808e0f3c4b0f6ef122d919cda148f4d",
          "sha256": "90aa95b778c8c4cdc0d6c4881bcd9b2bd7e96023e9a1c7dd5c01f9dbb0e68fe9",
          "sha1": "4d1be62f75e08633900e5c1d030623621bf86f2e",
          "md5": "fcd2b651927e0164d8f14e4ddfc64f27"
        }
      ]
    }
  ]
}
