/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type LocalAuthenticationOptions = any;

export type Void = any;

export async function hasHardwareAsync(): Promise<boolean> {
  return false;
}

export async function isEnrolledAsync(): Promise<boolean> {
  return false;
}

export async function supportedAuthenticationTypesAsync(): Promise<number[]> {
  return [];
}

export async function getEnrolledLevelAsync(): Promise<number> {
  return 0;
}

export async function authenticateAsync(options: LocalAuthenticationOptions): Promise<Void> {
  return null; // TODO: Replace with mock for value of type Void.
}
