import { collapseVersion } from './paths.ts';
import { type RedirectRule } from './redirects.ts';
import { type LinkReport, type PageIssue, type ReportEntry } from './scan.ts';

function plural(count: number, word: string): string {
  return `${count} ${word}${count === 1 ? '' : 's'}`;
}

function sumCounts(entries: ReportEntry[]): number {
  return entries.reduce((total, entry) => total + entry.count, 0);
}

type AnchorGroup = {
  page: string;
  versions: number;
  hashes: string[];
  sources: string[];
  selfOnly: boolean;
};

function groupAnchorsByPage(entries: ReportEntry[]): AnchorGroup[] {
  const groups = new Map<
    string,
    { versions: Set<string>; hashes: Set<string>; sources: Set<string> }
  >();

  for (const entry of entries) {
    const hashIndex = entry.target.indexOf('#');
    const targetPage = entry.target.slice(0, hashIndex);
    const hash = entry.target.slice(hashIndex + 1);
    const page = collapseVersion(targetPage);

    const group = groups.get(page) ?? {
      versions: new Set(),
      hashes: new Set(),
      sources: new Set(),
    };
    const versionMatch = targetPage.match(/^\/versions\/([^/]+)/);
    if (versionMatch) {
      group.versions.add(versionMatch[1]);
    }
    group.hashes.add(hash);
    for (const source of entry.pages) {
      group.sources.add(collapseVersion(source));
    }
    groups.set(page, group);
  }

  return [...groups.entries()]
    .map(([page, group]) => ({
      page,
      versions: Math.max(1, group.versions.size),
      hashes: [...group.hashes],
      sources: [...group.sources].sort(),
      selfOnly: group.sources.size === 1 && group.sources.has(page),
    }))
    .sort((a, b) => b.hashes.length - a.hashes.length);
}

export function composePageView(
  issuesByPage: Map<string, PageIssue[]>,
  dangling: RedirectRule[]
): string {
  const lines: string[] = [];

  for (const rule of dangling) {
    lines.push(
      `\x1b[31m✗\x1b[0m dangling redirect  ${rule.source} → ${rule.destination} (target does not exist)`
    );
  }
  if (dangling.length > 0 && issuesByPage.size > 0) {
    lines.push('');
  }

  const pages = [...issuesByPage.keys()].sort();
  pages.forEach((page, index) => {
    lines.push(`\x1b[1m${page}\x1b[0m`);
    for (const issue of issuesByPage.get(page)!) {
      const notes = [
        ...(issue.kind === 'anchor' && issue.self ? ['self'] : []),
        ...(issue.count > 1 ? [plural(issue.count, 'link')] : []),
      ];
      const suffix = notes.length > 0 ? ` (${notes.join(', ')})` : '';
      if (issue.kind === 'broken') {
        lines.push(`  \x1b[31m✗\x1b[0m page      ${issue.target}${suffix}`);
      } else if (issue.kind === 'anchor') {
        const location = issue.self ? `#${issue.hash}` : `${issue.target}#${issue.hash}`;
        lines.push(`  \x1b[31m✗\x1b[0m anchor    ${location}${suffix}`);
      } else {
        lines.push(`  \x1b[33m⚠\x1b[0m redirect  ${issue.target}${suffix}`);
      }
    }
    if (index < pages.length - 1) {
      lines.push('');
    }
  });

  return lines.join('\n');
}

export function composeLinkReport(
  report: LinkReport,
  options: { date: Date; runUrl?: string }
): { title: string; body: string; hasFindings: boolean } {
  const anchorTotal = sumCounts(report.brokenAnchors);
  const viaTotal = sumCounts(report.viaRedirect);
  const anchorGroups = groupAnchorsByPage(report.brokenAnchors);
  const distinctAnchors = anchorGroups.reduce((total, group) => total + group.hashes.length, 0);

  const dateLabel = options.date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });

  const headline = [
    ...(report.broken.length > 0 ? [plural(report.broken.length, 'broken page')] : []),
    plural(distinctAnchors, 'broken anchor'),
    plural(report.danglingRedirects.length, 'dangling redirect'),
  ].join(', ');
  const title = `Docs link report: ${headline} (${dateLabel})`;

  const lines: string[] = [];
  lines.push('Weekly automated link check of the exported docs site.');
  if (options.runUrl) {
    lines.push('', `Generated by this [Docs link health reporter run](${options.runUrl}).`);
  }
  lines.push(
    '',
    `Scanned **${report.pagesScanned.toLocaleString('en-US')} pages**, checked **${report.internalLinksChecked.toLocaleString('en-US')} internal links**.`,
    '',
    `### ${report.broken.length > 0 ? '🚨 ' : ''}Broken page paths: ${report.broken.length}`,
    ''
  );

  if (report.broken.length === 0) {
    lines.push('None. Nothing ships a 404 this week. 🎉');
  } else {
    lines.push('| Dead page | Links | Linked from |', '|---|---|---|');
    for (const entry of report.broken) {
      lines.push(`| \`${entry.target}\` | ${entry.count} | ${plural(entry.pageCount, 'page')} |`);
    }
  }

  lines.push('', `### Dangling redirects: ${report.danglingRedirects.length}`, '');
  if (report.danglingRedirects.length === 0) {
    lines.push('None.');
  } else {
    lines.push('| Source in `_redirects` | Points to (missing) |', '|---|---|');
    for (const rule of report.danglingRedirects) {
      lines.push(`| \`${rule.source}\` | \`${rule.destination}\` |`);
    }
  }

  lines.push(
    '',
    `### Broken anchors: ${plural(distinctAnchors, 'distinct dead anchor')} on ${plural(anchorGroups.length, 'page')}`,
    ''
  );
  if (anchorTotal === 0) {
    lines.push('None. 🎉');
  } else {
    const renderGroup = (group: AnchorGroup) => {
      const versionsLabel = group.versions > 1 ? ` (${group.versions} versions)` : '';
      const selfLabel = group.selfOnly ? ', all self-links' : ':';
      lines.push(
        `**\`${group.page}\`**${versionsLabel} — ${plural(group.hashes.length, 'dead anchor')}${selfLabel}`,
        '',
        group.hashes.map(hash => `\`#${hash}\``).join(', '),
        ''
      );
      if (!group.selfOnly) {
        lines.push(
          `Linked from ${plural(group.sources.length, 'page')}: ${group.sources.map(source => `\`${source}\``).join(', ')}`,
          ''
        );
      }
    };

    const sdkGroups = anchorGroups.filter(group => group.page.startsWith('/versions/'));
    const otherGroups = anchorGroups.filter(group => !group.page.startsWith('/versions/'));
    if (sdkGroups.length > 0) {
      lines.push('#### SDK/API reference pages — fix in package TSDoc, then regenerate data', '');
      sdkGroups.forEach(renderGroup);
    }
    if (otherGroups.length > 0) {
      lines.push('#### Guides and other pages — fix the links or restore the heading', '');
      otherGroups.forEach(renderGroup);
    }
  }

  lines.push(
    '',
    `### Links relying on a redirect: ${viaTotal} links → ${plural(report.viaRedirect.length, 'target')}`,
    ''
  );
  if (viaTotal === 0) {
    lines.push('None.');
  } else {
    lines.push(
      'These work today but should point at final destinations.',
      '',
      '| Target | Links | Linked from |',
      '|---|---|---|'
    );
    for (const entry of report.viaRedirect) {
      lines.push(`| \`${entry.target}\` | ${entry.count} | ${plural(entry.pageCount, 'page')} |`);
    }
  }

  lines.push(
    '',
    '---',
    '',
    'Reproduce locally: `pnpm export && pnpm check-internal-links` in `docs/`.',
    ''
  );

  return {
    title,
    body: lines.join('\n'),
    hasFindings: report.broken.length + report.danglingRedirects.length + anchorTotal > 0,
  };
}
