export const nonLinkableTypes = [
  '_default',
  '_ImmutableHeaders',
  '_ImmutableRequest',
  'ActivityFamily',
  'AndroidBarcode',
  'AndroidSymbol',
  'AndroidSymbolWeight',
  'AnimationObject',
  'ArrayBufferLike',
  'ArrayBufferView',
  'AudioTrackChangeEventPayload',
  'AvailableAudioTracksChangeEventPayload',
  'AvailableSubtitleTracksChangeEventPayload',
  'B',
  'BackButtonDisplayMode',
  'BackgroundNotificationResult',
  'BasicTextStyle',
  'BlurEffectTypes',
  'BlurViewState',
  'BottomTabNavigationEventMap',
  'BottomTabNavigationOptions',
  'Buffer',
  'BufferEncoding',
  'BufferSource',
  'Calendar',
  'CalendarDialogOpenParamsNext',
  'CalendarDialogParamsNext',
  'CheckboxElementColors',
  'CodedError',
  'ColorSchemeName',
  'ColorValue',
  'ComponentClass',
  'ComponentProps',
  'ComponentType',
  'ContainerType',
  'ContentAlignment',
  'Context',
  'ContextMenuContentProps',
  'DeletingOptions',
  'DependencyList',
  'DownloadProgressData',
  'E',
  'EmitterSubscription',
  'EncryptionKey',
  'EventListenerCallback',
  'EventMapBase',
  'EventMapCore',
  'EventName',
  'EventSubscription',
  'EventType',
  'ExpandedFullScreenSearchBarProps',
  'FC',
  'FileSystemDirectory',
  'FileSystemDownloadTask',
  'FileSystemDownloadResult',
  'FileSystemFile',
  'FileSystemNetworkTaskProgressCallback',
  'FileSystemUploadTask',
  'FileSystemUploadOptions',
  'FileSystemUploadResult',
  'FileWriteOptions',
  'FloatingToolbarExitAlwaysScrollBehavior',
  'ForwardRefExoticComponent',
  'FunctionComponent',
  'GeneratedHref',
  'GestureResponderEvent',
  'GetPermissionMethod',
  'HorizontalAlignment',
  'HorizontalArrangement',
  'ImageContentFit',
  'ImageContentPositionString',
  'ImageDecodeFormat',
  'ImageRef',
  'InferEventParameter',
  'JSXElementConstructor',
  'K',
  'LeadingIconProps',
  'LeadingProps',
  'LinePattern',
  'LinkPreviewStyle',
  'Listener',
  'LoaderFunctionResult',
  'MakeDirectoryOptions',
  'MaterialIcon',
  'MaterialShapeName',
  'MaybeNotificationResponse',
  'ModifiableAttendeeProperties',
  'ModifierConfig',
  'ModuleType',
  'NamedColor',
  'NamedExoticComponent',
  'NameT',
  'NativeBoundaryEventCallback',
  'NativeShapeProps',
  'NativeSyntheticEvent',
  'NativeTabNavigationEventMap',
  'NavigationAction',
  'NavigationContainerRefWithCurrent',
  'NavigationProp',
  'NavigatorProps',
  'NotificationTimeoutError',
  'Options',
  'P',
  'Parameters',
  'ParamList',
  'ParamListBase',
  'ParsedQs',
  'PartialState',
  'PathUtilities',
  'Payload',
  'PermissionExpiration',
  'PermissionHookBehavior',
  'PermissionHookOptions',
  'PermissionResponse',
  'PermissionStatus',
  'PlaceholderProps',
  'PressablePropsWithoutFunctionChildren',
  'PrimitiveBaseProps',
  'PropsWithChildren',
  'PropsWithoutRef',
  'ProtectedProps',
  'ProxyNativeModule',
  'React.FC',
  'ReactElement',
  'ReadingOptions',
  'Ref',
  'RelocatingOptions',
  'RequestPermissionMethod',
  'RequiredBy',
  'ResolvedSharePayload',
  'ReturnType',
  'RNHostProps',
  'RouteInputParams',
  'RouteName',
  'RouteOutputParams',
  'RouteParamInput',
  'RouteParams',
  'RouteSegments',
  'ScreenListeners',
  'ScreenTrigger',
  'SealedData',
  'SearchBarProps',
  'ServiceActionResult',
  'SetBadgeCountOptions',
  'Shape',
  'SharePayload',
  'SharingOptions',
  'SlotChildProps',
  'SourceSkipsKeys',
  'SplitHostProps',
  'SQLiteTaggedQueryResult',
  'StyleProp',
  'SubmenuElement',
  'SubmenuProps',
  'SupportingContentProps',
  'SwitchElementColors',
  'T',
  'TabsScreenProps',
  'TaskOptions',
  'TEventListener',
  'TEventMap',
  'TEventName',
  'TEventsMap',
  'ThumbContentProps',
  'TInitialValue',
  'ToolbarPlacement',
  'TOptions',
  'TParams',
  'TrailingProps',
  'Transaction',
  'TRoute',
  'TSegments',
  'TState',
  'UnknownInputParams',
  'UnknownOutputParams',
  'UpdatesNativeStateMachineContext',
  'UploadProgressData',
  'UseFontHook',
  'VerticalAlignment',
  'VerticalArrangement',
  'ViewEvent',
  'WritingOptions',
];

/**
 * List of type names that should not be visible in the docs.
 */
export const omittableTypes = [
  // Internal React type that adds `ref` prop to the component
  'RefAttributes',
];

/**
 * Map of internal entity/type names that should be replaced with something more developer-friendly.
 */
export const replaceableTypes: Partial<Record<string, string>> = {
  ForwardRefExoticComponent: 'Component',
  LocationAccuracy: 'Accuracy',
  LocationActivityType: 'ActivityType',
  LocationGeofencingRegionState: 'GeofencingRegionState',
};

/**
 * Map of entity/type names that should be linked to user specified source, internal or external.
 */
export const hardcodedTypeLinks: Record<string, string> = {
  ArrayBuffer:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer',
  Asset: '/versions/latest/sdk/asset/#asset',
  AsyncIterableIterator:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator',
  AuthSessionOpenOptions: '/versions/latest/sdk/webbrowser/#authsessionopenoptions',
  Blob: 'https://developer.mozilla.org/en-US/docs/Web/API/Blob',
  CameraPosition: '/versions/latest/sdk/maps/#cameraposition-2',
  ColorValue: 'https://reactnative.dev/docs/colors',
  CommonViewModifierProps: 'modifiers',
  Component: 'https://react.dev/reference/react/Component',
  CreateURLOptions: '/versions/latest/sdk/linking/#createurloptions',
  Date: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date',
  // React Navigation
  DefaultNavigatorOptions:
    'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  DeviceSensor: '/versions/latest/sdk/sensors',
  Element: 'https://www.typescriptlang.org/docs/handbook/jsx.html#function-component',
  Error: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error',
  Exclude:
    'https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers',
  ExpoConfig:
    'https://github.com/expo/expo/blob/main/packages/%40expo/config-types/src/ExpoConfig.ts',
  Extract: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union',
  FileHookTransformFunction:
    '/versions/latest/sdk/fingerprint/#filehooktransformfunctionsource-chunk-isendoffile-encoding',
  // Conflicts with the File class from expo-file-system@next. TODO: Fix this.
  // File: 'https://developer.mozilla.org/en-US/docs/Web/API/File',
  FileList: 'https://developer.mozilla.org/en-US/docs/Web/API/FileList',
  Headers: 'https://developer.mozilla.org/en-US/docs/Web/API/Headers',
  HTMLAnchorElement: 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement',
  HTMLInputElement: 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement',
  ImageSourcePropType: 'https://reactnative.dev/docs/image#imagesource',
  IterableIterator:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator',
  KeepAwakeListener: '/versions/latest/sdk/keep-awake/#keepawakelistenerevent',
  KeyboardTypeOptions: 'https://reactnative.dev/docs/textinput#keyboardtype',
  LocationCallback: '/versions/latest/sdk/location/#locationcallbacklocation',
  LocationErrorCallback: '/versions/latest/sdk/location/#locationerrorcallbackreason',
  LocationHeadingCallback: '/versions/latest/sdk/location/#locationheadingcallbacklocation',
  MediaTrackSettings: 'https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings',
  MessageEvent: 'https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent',
  MouseEvent: 'https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent',
  NativeStackNavigationOptions: 'https://reactnavigation.org/docs/native-stack-navigator#options',
  NavigationContainerRef: 'https://reactnavigation.org/docs/navigating-without-navigation-prop',
  NavigationOptions: 'https://reactnavigation.org/docs/screen-options/',
  NavigationState: 'https://reactnavigation.org/docs/navigation-state',
  NavigatorID: 'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  Omit: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys',
  OrientationChangeListener:
    '/versions/latest/sdk/screen-orientation/#orientationchangelistenerevent',
  PackagerAsset: 'https://github.com/facebook/react-native/blob/main/packages/assets/registry.js',
  Partial: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype',
  Pick: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys',
  Platform: 'https://reactnative.dev/docs/platform',
  ProcessedColorValue: 'https://reactnative.dev/docs/colors',
  Promise:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
  PromiseLike:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
  PromptMethod: '/versions/latest/sdk/auth-session/#promptmethodoptions',
  PureComponent: 'https://react.dev/reference/react/PureComponent',
  PushTokenListener: '/versions/latest/sdk/notifications/#pushtokenlistenertoken',
  ReactNode: 'https://reactnative.dev/docs/react-node',
  ReadableStream: 'https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream',
  Readonly: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype',
  RefObject: 'https://react.dev/reference/react/useRef',
  RegExp: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp',
  Required: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype',
  ReturnKeyTypeOptions: 'https://reactnative.dev/docs/textinput#returnkeytype',
  Response: 'https://developer.mozilla.org/en-US/docs/Web/API/Response',
  RootParamList: 'https://reactnavigation.org/docs/typescript/#navigator-specific-types',
  RouteProp: 'https://reactnavigation.org/docs/glossary-of-terms/#route-object',
  SFSymbol: 'https://github.com/nandorojo/sf-symbols-typescript',
  SFSymbols6_0: 'https://github.com/nandorojo/sf-symbols-typescript',
  SFSymbols7_0: 'https://github.com/nandorojo/sf-symbols-typescript',
  ShareOptions: 'https://reactnative.dev/docs/share#share',
  SpeechEventCallback: '/versions/latest/sdk/speech/#speecheventcallback',
  SpeechSynthesisEvent: 'https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent',
  SpeechSynthesisUtterance:
    'https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance',
  SQLiteStorageSetItemUpdateFunction:
    '/versions/latest/sdk/sqlite/#sqlitestoragesetitemupdatefunctionprevvalue',
  SyntheticEvent: 'https://react.dev/reference/react-dom/components/common#react-event-object',
  TabNavigationState:
    'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  TabRouterOptions: 'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  TaskManagerTaskExecutor: '/versions/latest/sdk/task-manager/#taskmanagertaskexecutorbody',
  TemplateStringsArray:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TemplateStringsArray',
  Text: 'https://reactnative.dev/docs/text',
  TextProps: 'https://reactnative.dev/docs/text#props',
  TextStyle: 'https://reactnative.dev/docs/text-style-props',
  Uint8Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array',
  URLListener: '/versions/latest/sdk/linking/#urllistenerevent',
  View: 'https://reactnative.dev/docs/view',
  ViewProps: 'https://reactnative.dev/docs/view#props',
  ViewStyle: 'https://reactnative.dev/docs/view-style-props',
  WebBrowserOpenOptions: '/versions/latest/sdk/webbrowser/#webbrowseropenoptions',
  WebBrowserWindowFeatures: '/versions/latest/sdk/webbrowser/#webbrowserwindowfeatures',
  WebGL2RenderingContext: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext',
  WebGLFramebuffer: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGLFramebuffer',
  WebGLTexture: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGLTexture',
  WritableStream: 'https://developer.mozilla.org/en-US/docs/Web/API/WritableStream',
};

export const sdkVersionHardcodedTypeLinks: Record<string, Record<string, string | null>> = {
  'v53.0.0': {
    CameraPosition: '/versions/v53.0.0/sdk/maps/#cameraposition-2',
    EventEmitter: '/versions/v53.0.0/sdk/expo/#eventemitter',
    NativeModule: '/versions/v53.0.0/sdk/expo/#nativemodule',
    SharedObject: '/versions/v53.0.0/sdk/expo/#sharedobject',
    SharedRef: '/versions/v53.0.0/sdk/expo/#sharedref',
  },
  'v54.0.0': {
    BufferOptions: '/versions/v54.0.0/sdk/video/#bufferoptions-1',
    CameraPosition: '/versions/v54.0.0/sdk/maps/#cameraposition-2',
    EventEmitter: '/versions/v54.0.0/sdk/expo/#eventemittertype',
    Href: '/versions/v54.0.0/sdk/router/#hreft',
    NativeModule: '/versions/v54.0.0/sdk/expo/#nativemoduletype',
    SharedObject: '/versions/v54.0.0/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/v54.0.0/sdk/expo/#sharedreftype',
  },
  'v55.0.0': {
    BufferOptions: '/versions/v55.0.0/sdk/video/#bufferoptions-1',
    ButtonElementColors: '/versions/v55.0.0/sdk/ui/jetpack-compose/button/#buttonelementcolors',
    CameraPosition: '/versions/v55.0.0/sdk/maps/#cameraposition-2',
    CornerRadii: '/versions/v55.0.0/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/v55.0.0/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/v55.0.0/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/v55.0.0/sdk/router/#hreft',
    NativeModule: '/versions/v55.0.0/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/v55.0.0/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/v55.0.0/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/v55.0.0/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/v55.0.0/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/v55.0.0/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/v55.0.0/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/v55.0.0/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/v55.0.0/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/v55.0.0/sdk/expo/#sharedreftype',
    TabsProps: '/versions/v55.0.0/sdk/router/ui/#tabsprops',
    TriggerProps: '/versions/v55.0.0/sdk/router/ui/#triggerprops',
    VectorIconProps: '/versions/v55.0.0/sdk/router/#vectoriconprops',
  },
  latest: {
    BufferOptions: '/versions/latest/sdk/video/#bufferoptions-1',
    ButtonElementColors: '/versions/latest/sdk/ui/jetpack-compose/button/#buttonelementcolors',
    CameraPosition: '/versions/latest/sdk/maps/#cameraposition-2',
    CornerRadii: '/versions/latest/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/latest/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/latest/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/latest/sdk/router/#hreft',
    NativeModule: '/versions/latest/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/latest/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/latest/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/latest/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/latest/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/latest/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/latest/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/latest/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/latest/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/latest/sdk/expo/#sharedreftype',
    TabsProps: '/versions/latest/sdk/router/ui/#tabsprops',
    TriggerProps: '/versions/latest/sdk/router/ui/#triggerprops',
    VectorIconProps: '/versions/latest/sdk/router/#vectoriconprops',
  },
  'v56.0.0': {
    BufferOptions: '/versions/unversioned/sdk/video/#bufferoptions-1',
    ButtonElementColors: '/versions/unversioned/sdk/ui/jetpack-compose/button/#buttonelementcolors',
    CameraPosition: '/versions/unversioned/sdk/maps/#cameraposition-2',
    CornerRadii: '/versions/unversioned/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/unversioned/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/unversioned/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/unversioned/sdk/router/#hreft',
    HrefObject: '/versions/unversioned/sdk/router/#hrefobject',
    NativeModule: '/versions/unversioned/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/unversioned/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/unversioned/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/unversioned/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/unversioned/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/unversioned/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/unversioned/sdk/expo/#sharedreftype',
    SingularOptions: '/versions/unversioned/sdk/router/#singularoptions',
    StackToolbarBadgeProps: '/versions/unversioned/sdk/router/stack/#stacktoolbarbadgeprops',
    StackToolbarIconProps: '/versions/unversioned/sdk/router/stack/#stacktoolbariconprops',
    StackToolbarLabelProps: '/versions/unversioned/sdk/router/stack/#stacktoolbarlabelprops',
    TabsProps: '/versions/unversioned/sdk/router/ui/#tabsprops',
    TriggerProps: '/versions/unversioned/sdk/router/ui/#triggerprops',
    VectorIconProps: '/versions/unversioned/sdk/router/#vectoriconprops',
  },
  unversioned: {
    BufferOptions: '/versions/unversioned/sdk/video/#bufferoptions-1',
    ButtonElementColors: '/versions/unversioned/sdk/ui/jetpack-compose/button/#buttonelementcolors',
    CameraPosition: '/versions/unversioned/sdk/maps/#cameraposition-2',
    CornerRadii: '/versions/unversioned/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/unversioned/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/unversioned/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/unversioned/sdk/router/#hreft',
    HrefObject: '/versions/unversioned/sdk/router/#hrefobject',
    NativeModule: '/versions/unversioned/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/unversioned/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/unversioned/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/unversioned/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/unversioned/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/unversioned/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/unversioned/sdk/expo/#sharedreftype',
    SingularOptions: '/versions/unversioned/sdk/router/#singularoptions',
    StackToolbarBadgeProps: '/versions/unversioned/sdk/router/stack/#stacktoolbarbadgeprops',
    StackToolbarIconProps: '/versions/unversioned/sdk/router/stack/#stacktoolbariconprops',
    StackToolbarLabelProps: '/versions/unversioned/sdk/router/stack/#stacktoolbarlabelprops',
    TabsProps: '/versions/unversioned/sdk/router/ui/#tabsprops',
    TriggerProps: '/versions/unversioned/sdk/router/ui/#triggerprops',
    VectorIconProps: '/versions/unversioned/sdk/router/#vectoriconprops',
  },
};

export const packageLinks: Record<string, string> = {
  'expo-manifests': 'manifests',
};
