export const nonLinkableTypes = [
  '_default',
  '_ImmutableHeaders',
  '_ImmutableRequest',
  'Action',
  'ActivityFamily',
  'AndroidBarcode',
  'AndroidSplashConfig',
  'AndroidSymbol',
  'AndroidSymbolWeight',
  'AnimationObject',
  'AppearSymbolEffect',
  'ArrayBufferLike',
  'ArrayBufferView',
  'AudioTrackChangeEventPayload',
  'AvailableAudioTracksChangeEventPayload',
  'AvailableSubtitleTracksChangeEventPayload',
  'B',
  'BackButtonDisplayMode',
  'BackgroundNotificationResult',
  'BasePageEvent',
  'BaseTextFieldProps',
  'BasicTextStyle',
  'BlurEffectTypes',
  'BlurViewState',
  'BottomTabNavigationEventMap',
  'BottomTabNavigationOptions',
  'BounceSymbolEffect',
  'BreatheSymbolEffect',
  'Buffer',
  'BufferEncoding',
  'BufferSource',
  'Calendar',
  'CalendarDialogOpenParamsNext',
  'CalendarDialogParamsNext',
  'CodedError',
  'ColorSchemeName',
  'ComponentClass',
  'ComponentProps',
  'ComponentType',
  'ConfigurationType',
  'ContainerType',
  'ContentAlignment',
  'Context',
  'ContextMenuContentProps',
  'DefaultRouterOptions',
  'DeletingOptions',
  'DependencyList',
  'Descriptor',
  'DisappearSymbolEffect',
  'DownloadProgressData',
  'DrawOffSymbolEffect',
  'DrawOnSymbolEffect',
  'DropdownMenuItemProps',
  'E',
  'EmitterSubscription',
  'EncryptionKey',
  'EventConsumer',
  'EventListenerCallback',
  'EventMap',
  'EventMapBase',
  'EventMapCore',
  'EventName',
  'EventSubscription',
  'EventType',
  'ExpandedFullScreenSearchBarProps',
  'ExperimentalStackNavigatorProps',
  'ExpoEventEmitter',
  'FC',
  'FileSystemDirectory',
  'FileSystemDownloadResult',
  'FileSystemDownloadTask',
  'FileSystemFile',
  'FileSystemNetworkTaskProgressCallback',
  'FileSystemUploadOptions',
  'FileSystemUploadResult',
  'FileSystemUploadTask',
  'FileWriteOptions',
  'FloatingToolbarExitAlwaysScrollBehavior',
  'ForwardRefExoticComponent',
  'FunctionComponent',
  'GeneratedHref',
  'GestureResponderEvent',
  'GetPermissionMethod',
  'HorizontalAlignment',
  'HorizontalArrangement',
  'ImageContentFit',
  'ImageContentPositionString',
  'ImageDecodeFormat',
  'ImageRef',
  'InferEventParameter',
  'IOSSplashConfig',
  'JSXElementConstructor',
  'K',
  'LeadingIconProps',
  'LeadingProps',
  'LinePattern',
  'LinkPreviewStyle',
  'Listener',
  'LoaderFunctionResult',
  'MakeDirectoryOptions',
  'MaterialIcon',
  'MaterialShapeName',
  'MaybeNotificationResponse',
  'MenuComponentProps',
  'MetadataAlternates',
  'MetadataAppleWebApp',
  'MetadataAppLinks',
  'MetadataAuthor',
  'MetadataFacebook',
  'MetadataFormatDetection',
  'MetadataIcons',
  'MetadataItunes',
  'MetadataOpenGraph',
  'MetadataPinterest',
  'MetadataRobots',
  'MetadataTwitter',
  'MetadataVerification',
  'ModifiableAttendeeProperties',
  'ModifierConfig',
  'ModuleType',
  'MultiShareAction',
  'NamedColor',
  'NamedExoticComponent',
  'NameT',
  'NativeBoundaryEventCallback',
  'NativeShapeProps',
  'NativeStackHeaderBackProps',
  'NativeStackHeaderItemProps',
  'NativeStackHeaderProps',
  'NativeStackNativeProps',
  'NativeStackScreenProps',
  'NativeSyntheticEvent',
  'NativeTabNavigationEventMap',
  'NativeTheme',
  'NavigationAction',
  'NavigationContainerRefWithCurrent',
  'NavigationHelpers',
  'NavigationHelpersCommon',
  'NavigationHelpersRoute',
  'NavigationProp',
  'NavigationRoute',
  'NavigatorContentProps',
  'NavigatorOptions',
  'NavigatorProps',
  'NotificationTimeoutError',
  'NumericFontWeight',
  'ObservableState',
  'Options',
  'P',
  'Parameters',
  'ParamList',
  'ParamListBase',
  'ParsedQs',
  'PartialState',
  'PathUtilities',
  'Payload',
  'Permission',
  'PermissionExpiration',
  'PermissionHookBehavior',
  'PermissionHookMethods',
  'PermissionHookOptions',
  'PermissionResponse',
  'PlaceholderProps',
  'PlatformIconIOS',
  'PlatformSelect',
  'PopoverViewProps',
  'PressablePropsWithoutFunctionChildren',
  'PrimitiveBaseProps',
  'PrivateValueStore',
  'Props',
  'PropsType',
  'PropsWithChildren',
  'PropsWithoutRef',
  'ProtectedProps',
  'ProviderProps',
  'ProxyNativeModule',
  'PullToRefreshIndicatorProps',
  'PulseSymbolEffect',
  'React.FC',
  'ReactElement',
  'ReactNavigationState',
  'ReadingOptions',
  'Ref',
  'RelocatingOptions',
  'RequestPermissionMethod',
  'RequiredBy',
  'ResolvedSharePayload',
  'ReturnType',
  'RNHostProps',
  'RotateSymbolEffect',
  'RouteInputParams',
  'RouteName',
  'RouteOutputParams',
  'RouteParamInput',
  'RouteParams',
  'RouterFactory',
  'RouterOptions',
  'RouteSegments',
  'ScaleSymbolEffect',
  'ScreenListeners',
  'ScreenTrigger',
  'ScrollableWrapper',
  'ScrollEdgeEffect',
  'SealedData',
  'SearchBarProps',
  'ServerDocumentData',
  'ServiceActionResult',
  'SetBadgeCountOptions',
  'Shape',
  'ShapeProps',
  'ShapeRecordProps',
  'SharedHeaderItem',
  'SharedStateChangeEvent',
  'SharePayload',
  'SharingOptions',
  'SingleShareAction',
  'SlotChildProps',
  'SourceSkipsKeys',
  'SplitHostProps',
  'SQLiteBindBlobValue',
  'SQLiteTaggedQueryResult',
  'StackActionHelpers',
  'StackActionType',
  'StandardNavigator',
  'StandardNavigatorCreatePropsFactoryDeps',
  'StandardRouterNavigatorProps',
  'State',
  'StyleProp',
  'SubmenuElement',
  'SubmenuProps',
  'SupportingContentProps',
  'SwipeActionsGroupProps',
  'T',
  'TabActionHelpers',
  'TabActionType',
  'TabsHostProps',
  'TabsScreenProps',
  'TaskOptions',
  'TEventListener',
  'TEventMap',
  'TEventName',
  'TEventsMap',
  'Theme',
  'ThumbContentProps',
  'TInitialValue',
  'ToolbarPlacement',
  'TOptions',
  'TParams',
  'TrailingProps',
  'Transaction',
  'TriggerProps',
  'TRoute',
  'TSegments',
  'TSharedObject',
  'TState',
  'UniversalHostProps',
  'UnknownInputParams',
  'UnknownOutputParams',
  'UpdatesNativeStateMachineContext',
  'UploadProgressData',
  'UrlObject',
  'UseFontHook',
  'VariableColorSymbolEffect',
  'VerticalAlignment',
  'VerticalArrangement',
  'ViewEvent',
  'WiggleSymbolEffect',
  'WritingOptions',
];

/**
 * List of type names that should not be visible in the docs.
 */
export const omittableTypes = [
  // Internal React type that adds `ref` prop to the component
  'RefAttributes',
];

/**
 * Map of internal entity/type names that should be replaced with something more developer-friendly.
 */
export const replaceableTypes: Partial<Record<string, string>> = {
  ForwardRefExoticComponent: 'Component',
  LocationAccuracy: 'Accuracy',
  LocationActivityType: 'ActivityType',
  LocationGeofencingRegionState: 'GeofencingRegionState',
};

/**
 * Map of entity/type names that should be linked to user specified source, internal or external.
 */
export const hardcodedTypeLinks: Record<string, string> = {
  AbortSignal: 'https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal',
  AlbumRef: '/versions/latest/sdk/media-library/#album',
  AlbumsOptions: '/versions/latest/sdk/media-library-legacy/#albumsoptions',
  ArrayBuffer:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer',
  Asset: '/versions/latest/sdk/asset/#asset',
  AsyncIterableIterator:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator',
  AssetRef: '/versions/latest/sdk/media-library/#asset',
  AssetsOptions: '/versions/latest/sdk/media-library-legacy/#assetsoptions',
  AuthSessionOpenOptions: '/versions/latest/sdk/webbrowser/#authsessionopenoptions',
  BackBehavior: '/versions/latest/sdk/router/native-tabs/#backbehavior',
  Blob: 'https://developer.mozilla.org/en-US/docs/Web/API/Blob',
  CameraPosition: '/versions/latest/sdk/maps/#cameraposition-2',
  ClosedRangeDate: 'https://developer.apple.com/documentation/swift/closedrange',
  ColorValue: 'https://reactnative.dev/docs/colors',
  CommonViewModifierProps: 'modifiers',
  Component: 'https://react.dev/reference/react/Component',
  CreateURLOptions: '/versions/latest/sdk/linking/#createurloptions',
  Date: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date',
  // React Navigation
  DefaultNavigatorOptions:
    'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  DeviceSensor: '/versions/latest/sdk/sensors',
  Element: 'https://www.typescriptlang.org/docs/handbook/jsx.html#function-component',
  Error: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error',
  Exclude:
    'https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers',
  ExpoConfig:
    'https://github.com/expo/expo/blob/main/packages/%40expo/config-types/src/ExpoConfig.ts',
  Extract: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union',
  File: '/versions/latest/sdk/filesystem/#file',
  FileHookTransformFunction:
    '/versions/latest/sdk/fingerprint/#filehooktransformfunctionsource-chunk-isendoffile-encoding',
  FileList: 'https://developer.mozilla.org/en-US/docs/Web/API/FileList',
  FloatingActionButtonProps:
    '/versions/latest/sdk/ui/jetpack-compose/floatingactionbutton/#floatingactionbuttonprops',
  Float32Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array',
  Float64Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array',
  GlobalEvent: '/versions/latest/sdk/ui/swift-ui/modifiers/#globalevent',
  Headers: 'https://developer.mozilla.org/en-US/docs/Web/API/Headers',
  HrefObject: '/versions/latest/sdk/router/#hrefobject',
  HTMLAnchorElement: 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement',
  HTMLInputElement: 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement',
  ImageSourcePropType: 'https://reactnative.dev/docs/image#imagesource',
  Int16Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array',
  Int32Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array',
  Int8Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array',
  IterableIterator:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator',
  KeepAwakeListener: '/versions/latest/sdk/keep-awake/#keepawakelistenerevent',
  KeyboardTypeOptions: 'https://reactnative.dev/docs/textinput#keyboardtype',
  LiveActivityComponent: '/versions/latest/sdk/widgets/#liveactivitycomponentprops-environment',
  LiveActivityEnvironment: '/versions/latest/sdk/widgets/#liveactivityenvironment',
  LoaderFunction: '/versions/latest/sdk/server/#loaderfunctionrequest-params',
  Location: '/versions/latest/sdk/media-library/#location',
  LocationCallback: '/versions/latest/sdk/location/#locationcallbacklocation',
  LocationErrorCallback: '/versions/latest/sdk/location/#locationerrorcallbackreason',
  LocationHeadingCallback: '/versions/latest/sdk/location/#locationheadingcallbacklocation',
  MediaLibraryAssetInfoQueryOptions:
    '/versions/latest/sdk/media-library-legacy/#medialibraryassetinfoqueryoptions',
  MediaTrackSettings: 'https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings',
  MemoExoticComponent: 'https://react.dev/reference/react/memo',
  MessageEvent: 'https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent',
  MotionActivityCallback: '/versions/latest/sdk/location/#motionactivitycallbackactivity',
  MouseEvent: 'https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent',
  NativeStackNavigationEventMap: '/versions/latest/sdk/router/#nativestacknavigationeventmap',
  NativeStackNavigationOptions: 'https://reactnavigation.org/docs/native-stack-navigator#options',
  NavigationContainerRef: 'https://reactnavigation.org/docs/navigating-without-navigation-prop',
  NavigationOptions: 'https://reactnavigation.org/docs/screen-options/',
  NavigationState: 'https://reactnavigation.org/docs/navigation-state',
  NavigatorID: 'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  Omit: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys',
  OrientationChangeListener:
    '/versions/latest/sdk/screen-orientation/#orientationchangelistenerevent',
  PackagerAsset: 'https://github.com/facebook/react-native/blob/main/packages/assets/registry.js',
  Partial: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype',
  PedometerUpdateCallback: '/versions/latest/sdk/pedometer/#pedometerupdatecallbackresult',
  PermissionStatus: '/versions/latest/sdk/expo/#permissionstatus',
  Pick: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys',
  Platform: 'https://reactnative.dev/docs/platform',
  ProcessedColorValue: 'https://reactnative.dev/docs/colors',
  Promise:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
  PromiseLike:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
  PromptMethod: '/versions/latest/sdk/auth-session/#promptmethodoptions',
  PureComponent: 'https://react.dev/reference/react/PureComponent',
  PushTokenListener: '/versions/latest/sdk/notifications/#pushtokenlistenertoken',
  ReactNode: 'https://reactnative.dev/docs/react-node',
  ReadableStream: 'https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream',
  Readonly: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype',
  RefObject: 'https://react.dev/reference/react/useRef',
  RelocationOptions: '/versions/latest/sdk/filesystem/#relocationoptions',
  RegExp: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp',
  Required: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype',
  ReturnKeyTypeOptions: 'https://reactnative.dev/docs/textinput#returnkeytype',
  Response: 'https://developer.mozilla.org/en-US/docs/Web/API/Response',
  RootParamList: 'https://reactnavigation.org/docs/typescript/#navigator-specific-types',
  RouteProp: 'https://reactnavigation.org/docs/glossary-of-terms/#route-object',
  ScrollGeometry: '/versions/latest/sdk/ui/swift-ui/scrollview/#scrollgeometry',
  ScrollPhase: '/versions/latest/sdk/ui/swift-ui/scrollview/#scrollphase',
  SFSymbol: 'https://github.com/nandorojo/sf-symbols-typescript',
  SFSymbols6_0: 'https://github.com/nandorojo/sf-symbols-typescript',
  SFSymbols7_0: 'https://github.com/nandorojo/sf-symbols-typescript',
  SharedRefType: '/versions/latest/sdk/expo/#sharedreftype',
  ShareOptions: 'https://reactnative.dev/docs/share#share',
  SingularOptions: '/versions/latest/sdk/router/#singularoptions',
  SpeechEventCallback: '/versions/latest/sdk/speech/#speecheventcallbackthis-ev',
  SpeechSynthesisEvent: 'https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent',
  SpeechSynthesisUtterance:
    'https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance',
  SQLiteProviderProps: '/versions/latest/sdk/sqlite/#sqlitesqliteprovider',
  SQLiteStorageSetItemUpdateFunction:
    '/versions/latest/sdk/sqlite/#sqlitestoragesetitemupdatefunctionprevvalue',
  StackNavigationState: '/versions/latest/sdk/router/#stacknavigationstate',
  StackScreenBackButtonProps: '/versions/latest/sdk/router/stack/#stackscreenbackbuttonprops',
  StackScreenProps: '/versions/latest/sdk/router/stack/#stackscreenprops',
  StackTitleProps: '/versions/latest/sdk/router/stack/#stacktitleprops',
  StackToolbarBadgeProps: '/versions/latest/sdk/router/stack/#stacktoolbarbadgeprops',
  StackToolbarIconProps: '/versions/latest/sdk/router/stack/#stacktoolbariconprops',
  StackToolbarLabelProps: '/versions/latest/sdk/router/stack/#stacktoolbarlabelprops',
  StandardNavigatorEventMapBase: '/versions/latest/sdk/router/#standardnavigatoreventmapbase',
  SyntheticEvent: 'https://react.dev/reference/react-dom/components/common#react-event-object',
  TabNavigationState:
    'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  TabRouterOptions: 'https://reactnavigation.org/docs/custom-navigators/#type-checking-navigators',
  TaskManagerTaskExecutor: '/versions/latest/sdk/task-manager/#taskmanagertaskexecutorbody',
  TemplateStringsArray:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TemplateStringsArray',
  Text: 'https://reactnative.dev/docs/text',
  TextProps: 'https://reactnative.dev/docs/text#props',
  TextStyle: 'https://reactnative.dev/docs/text-style-props',
  Uint16Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array',
  Uint32Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array',
  Uint8Array:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array',
  Uint8ClampedArray:
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray',
  UnitPointValue: '/versions/latest/sdk/ui/swift-ui/modifiers/#unitpointvalue',
  URLListener: '/versions/latest/sdk/linking/#urllistenerevent',
  View: 'https://reactnative.dev/docs/view',
  ViewProps: 'https://reactnative.dev/docs/view#props',
  ViewStyle: 'https://reactnative.dev/docs/view-style-props',
  WebBrowserOpenOptions: '/versions/latest/sdk/webbrowser/#webbrowseropenoptions',
  WebBrowserWindowFeatures: '/versions/latest/sdk/webbrowser/#webbrowserwindowfeatures',
  WebGL2RenderingContext: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext',
  WebGLFramebuffer: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGLFramebuffer',
  WebGLTexture: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGLTexture',
  WritableStream: 'https://developer.mozilla.org/en-US/docs/Web/API/WritableStream',
};

export const sdkVersionHardcodedTypeLinks: Record<string, Record<string, string | null>> = {
  'v54.0.0': {
    AlbumRef: '/versions/v54.0.0/sdk/media-library/#albumref',
    AssetRef: '/versions/v54.0.0/sdk/media-library/#assetref',
    AVMetadata: '/versions/v54.0.0/sdk/av/#avmetadata',
    AVPlaybackSource: '/versions/v54.0.0/sdk/av/#avplaybacksource',
    AVPlaybackStatus: '/versions/v54.0.0/sdk/av/#avplaybackstatus',
    AVPlaybackStatusToSet: '/versions/v54.0.0/sdk/av/#avplaybackstatustoset',
    BufferOptions: '/versions/v54.0.0/sdk/video/#bufferoptions-1',
    CameraPosition: '/versions/v54.0.0/sdk/maps/#cameraposition-2',
    EventEmitter: '/versions/v54.0.0/sdk/expo/#eventemittertype',
    Href: '/versions/v54.0.0/sdk/router/#hreft',
    NativeModule: '/versions/v54.0.0/sdk/expo/#nativemoduletype',
    Playback: '/versions/v54.0.0/sdk/av/#playback',
    SharedObject: '/versions/v54.0.0/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/v54.0.0/sdk/expo/#sharedreftype',
    SQLiteProviderProps: '/versions/v54.0.0/sdk/sqlite/#sqliteproviderprops',
  },
  'v55.0.0': {
    AlbumRef: '/versions/v55.0.0/sdk/media-library/#albumref',
    AssetRef: '/versions/v55.0.0/sdk/media-library/#assetref',
    BufferOptions: '/versions/v55.0.0/sdk/video/#bufferoptions-1',
    ButtonColors: '/versions/v55.0.0/sdk/ui/jetpack-compose/button/#buttoncolors',
    CameraPosition: '/versions/v55.0.0/sdk/maps/#cameraposition-2',
    CheckboxColors: '/versions/v55.0.0/sdk/ui/jetpack-compose/checkbox/#checkboxcolors',
    ClosedRangeDate: '/versions/v55.0.0/sdk/ui/swift-ui/progressview/#closedrangedate',
    CornerRadii: '/versions/v55.0.0/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/v55.0.0/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/v55.0.0/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/v55.0.0/sdk/router/#hreft',
    NativeModule: '/versions/v55.0.0/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/v55.0.0/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/v55.0.0/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/v55.0.0/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/v55.0.0/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/v55.0.0/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/v55.0.0/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/v55.0.0/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/v55.0.0/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/v55.0.0/sdk/expo/#sharedreftype',
    SQLiteProviderProps: '/versions/v55.0.0/sdk/sqlite/#sqliteproviderprops',
    TabsProps: '/versions/v55.0.0/sdk/router/ui/#tabsprops',
    TabTriggerProps: '/versions/v55.0.0/sdk/router/ui/#tabtriggerprops',
    VectorIconProps: '/versions/v55.0.0/sdk/router/#vectoriconprops',
  },
  'v56.0.0': {
    AlbumRef: '/versions/v56.0.0/sdk/media-library/#album',
    AssetRef: '/versions/v56.0.0/sdk/media-library/#asset',
    BufferOptions: '/versions/v56.0.0/sdk/video/#bufferoptions-1',
    ButtonColors: '/versions/v56.0.0/sdk/ui/jetpack-compose/button/#buttoncolors',
    CameraPosition: '/versions/v56.0.0/sdk/maps/#cameraposition-2',
    CheckboxColors: '/versions/v56.0.0/sdk/ui/jetpack-compose/checkbox/#checkboxcolors',
    CornerRadii: '/versions/v56.0.0/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/v56.0.0/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/v56.0.0/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/v56.0.0/sdk/router/#hreft',
    HrefObject: '/versions/v56.0.0/sdk/router/#hrefobject',
    NativeModule: '/versions/v56.0.0/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/v56.0.0/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/v56.0.0/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/v56.0.0/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/v56.0.0/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/v56.0.0/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/v56.0.0/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/v56.0.0/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/v56.0.0/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/v56.0.0/sdk/expo/#sharedreftype',
    SingularOptions: '/versions/v56.0.0/sdk/router/#singularoptions',
    SQLiteProviderProps: '/versions/v56.0.0/sdk/sqlite/#sqliteproviderprops',
    StackToolbarBadgeProps: '/versions/v56.0.0/sdk/router/stack/#stacktoolbarbadgeprops',
    StackToolbarIconProps: '/versions/v56.0.0/sdk/router/stack/#stacktoolbariconprops',
    StackToolbarLabelProps: '/versions/v56.0.0/sdk/router/stack/#stacktoolbarlabelprops',
    SwitchColors: '/versions/v56.0.0/sdk/ui/jetpack-compose/switch/#switchcolors',
    TabsProps: '/versions/v56.0.0/sdk/router/ui/#tabsprops',
    TabTriggerProps: '/versions/v56.0.0/sdk/router/ui/#tabtriggerprops',
    VectorIconProps: '/versions/v56.0.0/sdk/router/#vectoriconprops',
  },
  'v57.0.0': {
    BufferOptions: '/versions/v57.0.0/sdk/video/#bufferoptions-1',
    ButtonColors: '/versions/v57.0.0/sdk/ui/jetpack-compose/button/#buttoncolors',
    CameraPosition: '/versions/v57.0.0/sdk/maps/#cameraposition-2',
    CheckboxColors: '/versions/v57.0.0/sdk/ui/jetpack-compose/checkbox/#checkboxcolors',
    CornerRadii: '/versions/v57.0.0/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/v57.0.0/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/v57.0.0/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/v57.0.0/sdk/router/#hreft',
    HrefObject: '/versions/v57.0.0/sdk/router/#hrefobject',
    NativeModule: '/versions/v57.0.0/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/v57.0.0/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/v57.0.0/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/v57.0.0/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/v57.0.0/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/v57.0.0/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/v57.0.0/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/v57.0.0/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/v57.0.0/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/v57.0.0/sdk/expo/#sharedreftype',
    SingularOptions: '/versions/v57.0.0/sdk/router/#singularoptions',
    StackToolbarBadgeProps: '/versions/v57.0.0/sdk/router/stack/#stacktoolbarbadgeprops',
    StackToolbarIconProps: '/versions/v57.0.0/sdk/router/stack/#stacktoolbariconprops',
    StackToolbarLabelProps: '/versions/v57.0.0/sdk/router/stack/#stacktoolbarlabelprops',
    SwitchColors: '/versions/v57.0.0/sdk/ui/jetpack-compose/switch/#switchcolors',
    TabsProps: '/versions/v57.0.0/sdk/router/ui/#tabsprops',
    TabTriggerProps: '/versions/v57.0.0/sdk/router/ui/#tabtriggerprops',
    VectorIconProps: '/versions/v57.0.0/sdk/router/#vectoriconprops',
  },
  latest: {
    BufferOptions: '/versions/latest/sdk/video/#bufferoptions-1',
    ButtonColors: '/versions/latest/sdk/ui/jetpack-compose/button/#buttoncolors',
    CameraPosition: '/versions/latest/sdk/maps/#cameraposition-2',
    CheckboxColors: '/versions/latest/sdk/ui/jetpack-compose/checkbox/#checkboxcolors',
    CornerRadii: '/versions/latest/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/latest/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/latest/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/latest/sdk/router/#hreft',
    HrefObject: '/versions/latest/sdk/router/#hrefobject',
    NativeModule: '/versions/latest/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/latest/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/latest/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/latest/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/latest/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/latest/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/latest/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/latest/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/latest/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/latest/sdk/expo/#sharedreftype',
    SingularOptions: '/versions/latest/sdk/router/#singularoptions',
    StackToolbarBadgeProps: '/versions/latest/sdk/router/stack/#stacktoolbarbadgeprops',
    StackToolbarIconProps: '/versions/latest/sdk/router/stack/#stacktoolbariconprops',
    StackToolbarLabelProps: '/versions/latest/sdk/router/stack/#stacktoolbarlabelprops',
    SwitchColors: '/versions/latest/sdk/ui/jetpack-compose/switch/#switchcolors',
    TabsProps: '/versions/latest/sdk/router/ui/#tabsprops',
    TabTriggerProps: '/versions/latest/sdk/router/ui/#tabtriggerprops',
    VectorIconProps: '/versions/latest/sdk/router/#vectoriconprops',
  },
  unversioned: {
    BufferOptions: '/versions/unversioned/sdk/video/#bufferoptions-1',
    ButtonColors: '/versions/unversioned/sdk/ui/jetpack-compose/button/#buttoncolors',
    CameraPosition: '/versions/unversioned/sdk/maps/#cameraposition-2',
    CheckboxColors: '/versions/unversioned/sdk/ui/jetpack-compose/checkbox/#checkboxcolors',
    CornerRadii: '/versions/unversioned/sdk/ui/jetpack-compose/shape/#cornerradii',
    EventEmitter: '/versions/unversioned/sdk/expo/#eventemittertype',
    ExpoModifier: '/versions/unversioned/sdk/ui/jetpack-compose/modifiers/#expomodifier',
    Href: '/versions/unversioned/sdk/router/#hreft',
    HrefObject: '/versions/unversioned/sdk/router/#hrefobject',
    NativeModule: '/versions/unversioned/sdk/expo/#nativemoduletype',
    NativeTabsTriggerBadgeProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggerbadgeprops',
    NativeTabsTriggerIconProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggericonprops',
    NativeTabsTriggerLabelProps:
      '/versions/unversioned/sdk/router/native-tabs/#nativetabstriggerlabelprops',
    ScrubbingModeOptions: '/versions/unversioned/sdk/video/#scrubbingmodeoptions-1',
    SeekTolerance: '/versions/unversioned/sdk/video/#scrubbingmodeoptions-1',
    ShapeJSXElement: '/versions/unversioned/sdk/ui/jetpack-compose/shape/#shapejsxelement',
    SharedObject: '/versions/unversioned/sdk/expo/#sharedobjecttype',
    SharedRef: '/versions/unversioned/sdk/expo/#sharedreftype',
    SharedRefType: '/versions/unversioned/sdk/expo/#sharedreftype',
    SingularOptions: '/versions/unversioned/sdk/router/#singularoptions',
    StackToolbarBadgeProps: '/versions/unversioned/sdk/router/stack/#stacktoolbarbadgeprops',
    StackToolbarIconProps: '/versions/unversioned/sdk/router/stack/#stacktoolbariconprops',
    StackToolbarLabelProps: '/versions/unversioned/sdk/router/stack/#stacktoolbarlabelprops',
    SwitchColors: '/versions/unversioned/sdk/ui/jetpack-compose/switch/#switchcolors',
    TabsProps: '/versions/unversioned/sdk/router/ui/#tabsprops',
    TabTriggerProps: '/versions/unversioned/sdk/router/ui/#tabtriggerprops',
    VectorIconProps: '/versions/unversioned/sdk/router/#vectoriconprops',
  },
};

export const packageLinks: Record<string, string> = {
  'expo-manifests': 'manifests',
};
