import type { ExportedSurface, TypeNode } from '@expo/expo-modules-macros-plugin';

import { renderSurface } from '../renderSurface';

const Bool: TypeNode = { kind: 'primitive', name: 'Bool', typeof: 'boolean' };
const Int: TypeNode = { kind: 'primitive', name: 'Int', typeof: 'number' };
const Double: TypeNode = { kind: 'primitive', name: 'Double', typeof: 'number' };
const Str: TypeNode = { kind: 'primitive', name: 'String', typeof: 'string' };

const FILE = '/repo/packages/expo-video/ios/Demo.swift';

/** The surface `scan-exports` reports for the sample in the scanner's own docs. */
const sampleSurface: ExportedSurface = {
  enums: [],
  unions: [],
  records: [
    {
      name: 'Options',
      file: FILE,
      properties: [
        { name: 'quality', type: Double, optional: false, required: false },
        {
          name: 'name',
          type: { kind: 'optional', typeof: 'object', wrapped: Str },
          optional: true,
          required: false,
        },
        {
          name: 'tags',
          type: { kind: 'array', typeof: 'object', element: Str },
          optional: false,
          required: true,
        },
      ],
    },
  ],
  sharedObjects: [
    {
      name: 'VideoPlayer',
      jsName: 'Player',
      file: FILE,
      events: [],
      constructorParameters: [
        { label: 'url', name: 'url', type: Str, optional: false },
        {
          label: 'options',
          name: 'options',
          type: {
            kind: 'optional',
            typeof: 'object',
            wrapped: { kind: 'ref', typeof: 'object', name: 'Options' },
          },
          optional: true,
        },
      ],
      properties: [
        { name: 'isPlaying', jsName: 'isPlaying', type: Bool, readonly: false, static: false },
        { name: 'duration', jsName: 'duration', type: Double, readonly: true, static: false },
      ],
      functions: [
        {
          name: 'seekTo',
          jsName: 'seek',
          parameters: [{ label: '_', name: 'time', type: Double, optional: false }],
          async: false,
          throws: true,
          static: false,
        },
        {
          name: 'load',
          jsName: 'load',
          parameters: [
            { label: 'from', name: 'url', type: Str, optional: false },
            {
              label: 'onProgress',
              name: 'onProgress',
              type: {
                kind: 'function',
                typeof: 'function',
                parameters: [Double],
                async: false,
                throws: false,
              },
              optional: false,
            },
          ],
          returns: { kind: 'dictionary', typeof: 'object', key: Str, value: Int },
          async: true,
          throws: true,
          static: false,
        },
        {
          name: 'create',
          jsName: 'create',
          parameters: [],
          returns: { kind: 'ref', typeof: 'object', name: 'VideoPlayer' },
          async: false,
          throws: false,
          static: true,
        },
      ],
    },
  ],
  modules: [
    {
      name: 'MyModule',
      jsName: 'MyModule',
      file: FILE,
      events: [],
      functions: [
        {
          name: 'greet',
          jsName: 'greet',
          parameters: [
            { label: '_', name: 'name', type: Str, optional: false },
            { label: 'loudly', name: 'loudly', type: Bool, optional: true },
          ],
          returns: Str,
          async: false,
          throws: false,
          static: false,
        },
      ],
      properties: [
        { name: 'version', jsName: 'version', type: Str, readonly: true, static: false },
      ],
    },
  ],
};

const emptySurface: ExportedSurface = {
  modules: [],
  sharedObjects: [],
  records: [],
  enums: [],
  unions: [],
};

describe(renderSurface, () => {
  it('renders records, shared objects extending SharedObject, and modules extending NativeModule, in dependency order', () => {
    const result = renderSurface(sampleSurface);
    expect(result.warnings).toEqual([]);
    expect(result.source).toBe(
      `// @generated by expo-modules-cli. Do not edit by hand.
// Regenerate with \`expo-modules generate-types\`.

import type { NativeModule, SharedObject } from 'expo';

export type Options = {
  quality?: number;
  name?: string | null;
  tags: string[];
};

export declare class Player extends SharedObject {
  constructor(url: string, options?: Options | null);
  isPlaying: boolean;
  readonly duration: number;
  seek(time: number): void;
  load(url: string, onProgress: (arg0: number) => void): Promise<Record<string, number>>;
  static create(): Player;
}

export declare class MyModule extends NativeModule {
  readonly version: string;
  greet(name: string, loudly?: boolean): string;
}
`
    );
  });

  it('returns null source for an empty surface', () => {
    expect(renderSurface(emptySurface).source).toBeNull();
  });

  it('keeps an omittable parameter required when a required one follows it', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [
            {
              name: 'f',
              jsName: 'f',
              parameters: [
                { label: 'a', name: 'a', type: Int, optional: true },
                { label: 'b', name: 'b', type: Int, optional: false },
              ],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('f(a: number | undefined, b: number): void;');
  });

  it('does not double-wrap a promise returned from an async function', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [
            {
              name: 'f',
              jsName: 'f',
              parameters: [],
              returns: { kind: 'promise', typeof: 'object', value: Int },
              async: true,
              throws: false,
              static: false,
            },
            {
              name: 'g',
              jsName: 'g',
              parameters: [],
              async: true,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('f(): Promise<number>;');
    expect(result.source).toContain('g(): Promise<void>;');
  });

  it('maps well-known expo-modules-core types and imports the ones core exports', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [
            {
              name: 'fill',
              jsName: 'fill',
              parameters: [
                {
                  label: 'array',
                  name: 'array',
                  type: { kind: 'ref', typeof: 'object', name: 'TypedArray' },
                  optional: false,
                },
                {
                  label: 'buffer',
                  name: 'buffer',
                  type: { kind: 'ref', typeof: 'object', name: 'ArrayBuffer' },
                  optional: false,
                },
              ],
              returns: { kind: 'ref', typeof: 'object', name: 'TypedArray' },
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toBe(
      `// @generated by expo-modules-cli. Do not edit by hand.
// Regenerate with \`expo-modules generate-types\`.

import type { NativeModule, TypedArray } from 'expo';

export declare class M extends NativeModule {
  fill(array: TypedArray, buffer: ArrayBuffer): TypedArray;
}
`
    );
  });

  it('lets a scanned type shadow a well-known core type of the same name', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [{ name: 'TypedArray', file: FILE, properties: [] }],
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [
            {
              name: 'a',
              jsName: 'a',
              type: { kind: 'ref', typeof: 'object', name: 'TypedArray' },
              readonly: true,
              static: false,
            },
          ],
          functions: [],
        },
      ],
    });
    expect(result.source).toContain("import type { NativeModule } from 'expo';");
    expect(result.source).not.toContain('TypedArray }');
    expect(result.source).toContain('readonly a: TypedArray;');
  });

  it('skips a declaration whose TypeScript name is already taken and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [{ name: 'Options', file: FILE, properties: [] }],
      sharedObjects: [
        {
          name: 'PlayerOptions',
          jsName: 'Options',
          file: FILE,
          events: [],
          functions: [],
          properties: [],
        },
      ],
    });
    expect(result.source).toContain('export type Options = {};');
    expect(result.source).not.toContain('class Options');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'PlayerOptions',
        message:
          "another declaration already uses the TypeScript name 'Options', so this one was skipped",
      },
    ]);
  });

  it('quotes member names that are not identifiers and renames reserved-word parameters', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [
            { name: 'someName', jsName: 'some-name', type: Int, readonly: true, static: false },
          ],
          functions: [
            {
              name: 'doIt',
              jsName: 'do-it',
              parameters: [{ label: 'default', name: 'default', type: Int, optional: false }],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain('readonly "some-name": number;');
    expect(result.source).toContain('"do-it"(default_: number): void;');
  });

  it('escapes line terminators in quoted member names', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [
        {
          name: 'R',
          file: FILE,
          properties: [{ name: 'with\nnewline', type: Int, optional: false, required: true }],
        },
      ],
    });
    expect(result.source).toContain('"with\\nnewline": number;');
  });

  it('skips a member whose JS name is already taken by another member and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      sharedObjects: [
        {
          name: 'Counter',
          jsName: 'Counter',
          file: FILE,
          events: [],
          properties: [
            { name: 'value', jsName: 'value', type: Int, readonly: true, static: false },
            { name: 'valueAgain', jsName: 'value', type: Str, readonly: false, static: false },
          ],
          functions: [
            {
              name: 'getValue',
              jsName: 'value',
              parameters: [],
              returns: Int,
              async: false,
              throws: false,
              static: false,
            },
            // A static member lives in a different namespace, so it does not collide.
            {
              name: 'staticValue',
              jsName: 'value',
              parameters: [],
              returns: Int,
              async: false,
              throws: false,
              static: true,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('readonly value: number;');
    expect(result.source).not.toContain('value: string;');
    expect(result.source).not.toContain('  value(): number;');
    expect(result.source).toContain('static value(): number;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'Counter.valueAgain',
        message: "another member already uses the JS name 'value', so this one was skipped",
      },
      {
        file: FILE,
        location: 'Counter.getValue',
        message: "another member already uses the JS name 'value', so this one was skipped",
      },
    ]);
  });

  it('keeps functions sharing a JS name, which TypeScript reads as overloads', () => {
    const fn = (name: string, type: TypeNode) => ({
      name,
      jsName: 'load',
      parameters: [{ label: 'x', name: 'x', type, optional: false }],
      async: false,
      throws: false,
      static: false,
    });
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [fn('loadString', Str), fn('loadInt', Int)],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain('load(x: string): void;');
    expect(result.source).toContain('load(x: number): void;');
  });

  it('skips a record property whose name repeats an earlier one and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [
        {
          name: 'R',
          file: FILE,
          properties: [
            { name: 'a', type: Int, optional: false, required: true },
            { name: 'a', type: Str, optional: false, required: true },
          ],
        },
      ],
    });
    expect(result.source).toContain('a: number;');
    expect(result.source).not.toContain('a: string;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'R.a',
        message: "another member already uses the JS name 'a', so this one was skipped",
      },
    ]);
  });

  it('skips a shared object or record whose name is not an identifier and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [{ name: 'Bad-Name', file: FILE, properties: [] }],
      sharedObjects: [
        {
          name: 'Player',
          jsName: 'my player',
          file: FILE,
          events: [],
          functions: [],
          properties: [],
        },
      ],
    });
    expect(result.source).toBeNull();
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'Bad-Name',
        message: "'Bad-Name' is not a valid TypeScript identifier, so its declaration was skipped",
      },
      {
        file: FILE,
        location: 'Player',
        message: "'my player' is not a valid TypeScript identifier, so its declaration was skipped",
      },
    ]);
  });

  it('renders a string enum as a TS enum of its cases, declared before the records that use it', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [
        {
          name: 'DigestAlgorithm',
          file: FILE,
          rawType: Str,
          cases: [
            { name: 'sha1', rawValue: 'SHA-1' },
            { name: 'sha256', rawValue: 'SHA-256' },
            { name: 'quoted', rawValue: "it's" },
            { name: 'plain' },
          ],
        },
      ],
      records: [
        {
          name: 'Options',
          file: FILE,
          properties: [
            {
              name: 'algorithm',
              type: { kind: 'ref', typeof: 'string', refKind: 'enum', name: 'DigestAlgorithm' },
              optional: false,
              required: true,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain(
      [
        'export enum DigestAlgorithm {',
        "  sha1 = 'SHA-1',",
        "  sha256 = 'SHA-256',",
        "  quoted = 'it\\'s',",
        "  plain = 'plain',",
        '}',
      ].join('\n')
    );
    expect(result.source).toContain('algorithm: DigestAlgorithm;');
    expect(result.source!.indexOf('export enum DigestAlgorithm')).toBeLessThan(
      result.source!.indexOf('export type Options')
    );
  });

  it('renders an integer enum with the written raw values and leaves the carried ones to TS', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [
        {
          name: 'KeySize',
          file: FILE,
          rawType: Int,
          cases: [{ name: 'a' }, { name: 'b' }, { name: 'c', rawValue: '5' }, { name: 'd' }],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain(
      ['export enum KeySize {', '  a,', '  b,', '  c = 5,', '  d,', '}'].join('\n')
    );
  });

  it('normalizes integer literals in any base to decimal, as Swift reads them', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [
        {
          name: 'Bases',
          file: FILE,
          rawType: Int,
          cases: [
            { name: 'octalLooking', rawValue: '0123' },
            { name: 'hex', rawValue: '0xFF' },
            { name: 'binary', rawValue: '0b101' },
            { name: 'octal', rawValue: '0o17' },
            { name: 'separated', rawValue: '1_000' },
            { name: 'negative', rawValue: '-1' },
            { name: 'decimal', rawValue: '1.5' },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain(
      [
        'export enum Bases {',
        '  octalLooking = 123,',
        '  hex = 255,',
        '  binary = 5,',
        '  octal = 15,',
        '  separated = 1000,',
        '  negative = -1,',
        '  decimal = 1.5,',
        '}',
      ].join('\n')
    );
  });

  it('renders an integer enum with a raw value TS would evaluate differently as number and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [
        {
          name: 'Flags',
          file: FILE,
          rawType: Int,
          cases: [
            { name: 'a', rawValue: '1' },
            { name: 'b', rawValue: '1 << 40' },
          ],
        },
      ],
    });
    expect(result.source).toContain('export type Flags = number;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'Flags.b',
        message:
          "raw value '1 << 40' cannot be evaluated without compiling, so the enum was rendered as number",
      },
    ]);
  });

  it('quotes an enum case name that is not an identifier', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [
        {
          name: 'Odd',
          file: FILE,
          rawType: Str,
          cases: [{ name: 'kebab-case', rawValue: 'kebab-case' }, { name: 'default' }],
        },
      ],
    });
    expect(result.source).toContain(
      ['export enum Odd {', '  "kebab-case" = \'kebab-case\',', "  default = 'default',", '}'].join(
        '\n'
      )
    );
  });

  it('drops the backticks Swift needs around reserved words from every name', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [
        {
          name: 'Kind',
          file: FILE,
          rawType: Str,
          cases: [{ name: '`default`', rawValue: 'd' }],
        },
      ],
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [
            { name: '`class`', jsName: '`class`', type: Int, readonly: true, static: false },
          ],
          functions: [
            {
              name: '`default`',
              jsName: '`default`',
              parameters: [{ label: '`in`', name: '`in`', type: Int, optional: false }],
              returns: Int,
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain("  default = 'd',");
    expect(result.source).toContain('  readonly class: number;');
    expect(result.source).toContain('  default(in_: number): number;');
  });

  it('renders an empty enum as an empty TS enum', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [{ name: 'Empty', file: FILE, rawType: Int, cases: [] }],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain('export enum Empty {}\n');
  });

  it('renders an enum without a raw type as unknown and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      enums: [{ name: 'Bare', file: FILE, cases: [{ name: 'a' }, { name: 'b' }] }],
    });
    expect(result.source).toContain('export type Bare = unknown;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'Bare',
        message:
          'the enum has no raw type, so its JS representation is not known and it was rendered as unknown',
      },
    ]);
  });

  it('renders a union as the union of its member payload types, after the types it refers to', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [{ name: 'Options', file: FILE, properties: [] }],
      unions: [
        {
          name: 'Source',
          file: FILE,
          members: [
            { name: 'url', type: Str },
            {
              name: 'options',
              type: { kind: 'ref', typeof: 'object', refKind: 'record', name: 'Options' },
            },
            { name: 'ids', type: { kind: 'array', typeof: 'object', element: Int } },
          ],
        },
      ],
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [
            {
              name: 'load',
              jsName: 'load',
              parameters: [
                {
                  label: 'source',
                  name: 'source',
                  type: { kind: 'ref', typeof: 'object', refKind: 'union', name: 'Source' },
                  optional: false,
                },
              ],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain('export type Source = string | Options | number[];');
    expect(result.source).toContain('load(source: Source): void;');
    expect(result.source!.indexOf('export type Options')).toBeLessThan(
      result.source!.indexOf('export type Source')
    );
  });

  it('renders a union without members as never and warns', () => {
    const result = renderSurface({
      ...emptySurface,
      unions: [{ name: 'Empty', file: FILE, members: [] }],
    });
    expect(result.source).toContain('export type Empty = never;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'Empty',
        message: 'the union has no members, so it was rendered as never',
      },
    ]);
  });

  it('reports warnings with the Swift location of the offending member', () => {
    const result = renderSurface({
      ...emptySurface,
      sharedObjects: [
        {
          name: 'VideoPlayer',
          jsName: 'Player',
          file: FILE,
          events: [],
          properties: [
            {
              name: 'status',
              jsName: 'status',
              type: { kind: 'ref', typeof: 'object', name: 'PlaybackStatus' },
              readonly: true,
              static: false,
            },
            { name: 'untyped', jsName: 'untyped', readonly: true, static: false },
          ],
          functions: [
            {
              name: 'move',
              jsName: 'move',
              parameters: [
                {
                  label: 'to',
                  name: 'point',
                  type: { kind: 'unknown', text: '(Int, Int)' },
                  optional: false,
                },
              ],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('readonly status: unknown;');
    expect(result.source).toContain('readonly untyped: unknown;');
    expect(result.source).toContain('move(point: unknown): void;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'VideoPlayer.status',
        message: "unresolved type 'PlaybackStatus' rendered as unknown",
      },
      {
        file: FILE,
        location: 'VideoPlayer.untyped',
        message: 'type could not be determined from the declaration, rendered as unknown',
      },
      {
        file: FILE,
        location: 'VideoPlayer.move(point)',
        message: "unmodeled Swift type '(Int, Int)' rendered as unknown",
      },
    ]);
  });

  it('renders the events of a module and a shared object as the events map of their base class', () => {
    const result = renderSurface({
      ...emptySurface,
      records: [
        {
          name: 'PlaybackStatus',
          file: FILE,
          properties: [{ name: 'isPlaying', type: Bool, optional: false, required: true }],
        },
      ],
      sharedObjects: [
        {
          name: 'VideoPlayer',
          jsName: 'Player',
          file: FILE,
          constructorParameters: [],
          events: [
            {
              name: 'onStatusChange',
              jsName: 'statusChange',
              payload: { kind: 'ref', typeof: 'object', name: 'PlaybackStatus' },
              sync: false,
            },
            { name: 'onEnded', jsName: 'ended', sync: true },
          ],
          properties: [],
          functions: [],
        },
      ],
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [
            {
              name: 'onChange',
              jsName: 'change',
              payload: { kind: 'array', typeof: 'object', element: Str },
              sync: false,
            },
          ],
          properties: [
            { name: 'version', jsName: 'version', type: Str, readonly: true, static: false },
          ],
          functions: [],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toBe(
      `// @generated by expo-modules-cli. Do not edit by hand.
// Regenerate with \`expo-modules generate-types\`.

import type { NativeModule, SharedObject } from 'expo';

export type PlaybackStatus = {
  isPlaying: boolean;
};

export declare class Player extends SharedObject<{
  statusChange(payload: PlaybackStatus): void;
  ended(): void;
}> {
  constructor();
}

export declare class M extends NativeModule<{
  change(payload: string[]): void;
}> {
  readonly version: string;
}
`
    );
  });

  it('quotes an event name that is not an identifier, and skips a repeated one with a warning', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [
            { name: 'onSomeEvent', jsName: 'some-event', payload: Int, sync: false },
            { name: 'onFirst', jsName: 'shared', sync: false },
            { name: 'onSecond', jsName: 'shared', payload: Int, sync: false },
            {
              name: 'onOdd',
              jsName: 'odd',
              payload: { kind: 'unknown', text: '(Int, Int)' },
              sync: false,
            },
          ],
          properties: [],
          functions: [],
        },
      ],
    });
    expect(result.source).toContain(`export declare class M extends NativeModule<{
  "some-event"(payload: number): void;
  shared(): void;
  odd(payload: unknown): void;
}> {}
`);
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'M.onSecond',
        message: "another event already uses the JS name 'shared', so this one was skipped",
      },
      {
        file: FILE,
        location: 'M.onOdd',
        message: "unmodeled Swift type '(Int, Int)' rendered as unknown",
      },
    ]);
  });

  it('maps the concrete typed array classes to the JS globals of the same name', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [
            {
              name: 'digest',
              jsName: 'digest',
              parameters: [
                {
                  label: 'data',
                  name: 'data',
                  type: { kind: 'ref', typeof: 'object', name: 'Uint8Array' },
                  optional: false,
                },
                {
                  label: 'weights',
                  name: 'weights',
                  type: { kind: 'ref', typeof: 'object', name: 'Float32Array' },
                  optional: false,
                },
              ],
              returns: { kind: 'ref', typeof: 'object', name: 'BigUint64Array' },
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain("import type { NativeModule } from 'expo';");
    expect(result.source).toContain(
      'digest(data: Uint8Array, weights: Float32Array): BigUint64Array;'
    );
  });

  it('gives a shared object without a JS constructor a private one', () => {
    const result = renderSurface({
      ...emptySurface,
      sharedObjects: [
        {
          name: 'Counter',
          jsName: 'Counter',
          file: FILE,
          events: [],
          properties: [
            { name: 'count', jsName: 'count', type: Int, readonly: true, static: false },
          ],
          functions: [],
        },
      ],
    });
    expect(result.warnings).toEqual([]);
    expect(result.source).toContain(`export declare class Counter extends SharedObject {
  private constructor();
  readonly count: number;
}
`);
  });

  it('reports a parameter warning under its Swift name, not the renamed TypeScript one', () => {
    const result = renderSurface({
      ...emptySurface,
      modules: [
        {
          name: 'M',
          jsName: 'M',
          file: FILE,
          events: [],
          properties: [],
          functions: [
            {
              name: 'doIt',
              jsName: 'doIt',
              parameters: [
                {
                  label: 'default',
                  name: 'default',
                  type: { kind: 'unknown', text: '(Int, Int)' },
                  optional: false,
                },
              ],
              async: false,
              throws: false,
              static: false,
            },
          ],
        },
      ],
    });
    expect(result.source).toContain('doIt(default_: unknown): void;');
    expect(result.warnings).toEqual([
      {
        file: FILE,
        location: 'M.doIt(default)',
        message: "unmodeled Swift type '(Int, Int)' rendered as unknown",
      },
    ]);
  });
});
