/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export function closeSync(databaseName: string): any {}

export async function exec(
  databaseName: string,
  queries: any[][],
  readOnly: boolean
): Promise<(any | undefined)[]> {
  return [];
}

export async function close(databaseName: string): Promise<any> {}

export async function deleteAsync(databaseName: string): Promise<any> {}
