{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-sqlite",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-sqlite-10.2.0.aar",
          "url": "expo-sqlite-10.2.0.aar",
          "size": 27582,
          "sha512": "20b6590fcbe2144cc1b829c705b1e8f1cbe2ab921a34425afd4e2e1218a852a12e10002588e336aae97616f5bb17abc0c6059836363cb9dc6c06594de96bb6ef",
          "sha256": "6a609a96ca40607df4f28d15dad8194b30e67378dfc1fc208f6e267db15667d2",
          "sha1": "17958034d64c41d5f6512d143a6803485946a973",
          "md5": "5137b00eeae72b29b1ac2657bc3b793e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-sqlite-10.2.0.aar",
          "url": "expo-sqlite-10.2.0.aar",
          "size": 27582,
          "sha512": "20b6590fcbe2144cc1b829c705b1e8f1cbe2ab921a34425afd4e2e1218a852a12e10002588e336aae97616f5bb17abc0c6059836363cb9dc6c06594de96bb6ef",
          "sha256": "6a609a96ca40607df4f28d15dad8194b30e67378dfc1fc208f6e267db15667d2",
          "sha1": "17958034d64c41d5f6512d143a6803485946a973",
          "md5": "5137b00eeae72b29b1ac2657bc3b793e"
        }
      ]
    }
  ]
}
