/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type URL = any;

export async function downloadAsync(
  url: URL,
  md5Hash: string | undefined,
  type: string
): Promise<any> {}
