source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

MODULES_DIR = '../../../packages'

target 'expo-firebase' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.9.0",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true
  
  pod 'EXAdsAdMob', :path => [MODULES_DIR, 'expo-ads-admob', 'ios'] * '/'
  pod 'EXBarCodeScanner', :path => [MODULES_DIR, 'expo-barcode-scanner', 'ios' ] * '/'
  pod 'EXBarCodeScannerInterface', :path => [MODULES_DIR, 'expo-barcode-scanner-interface', 'ios' ] * '/'
  pod 'EXCamera', :path => [MODULES_DIR, 'expo-camera', 'ios' ] * '/'
  pod 'EXCameraInterface', :path => [MODULES_DIR, 'expo-camera-interface', 'ios' ] * '/'
  pod 'EXConstants', :path => [MODULES_DIR, 'expo-constants', 'ios' ] * '/'
  pod 'EXConstantsInterface', :path => [MODULES_DIR, 'expo-constants-interface', 'ios' ] * '/'
  pod 'EXContacts', :path => [MODULES_DIR, 'expo-contacts', 'ios' ] * '/'
  pod 'EXCore', :path => [MODULES_DIR, 'expo-core', 'ios' ] * '/'
  pod 'EXFaceDetectorInterface', :path => [MODULES_DIR, 'expo-face-detector-interface', 'ios' ] * '/'
  pod 'EXFileSystem', :path => [MODULES_DIR, 'expo-file-system', 'ios' ] * '/'
  pod 'EXFileSystemInterface', :path => [MODULES_DIR, 'expo-file-system-interface', 'ios' ] * '/'
  pod 'EXFont', :path => [MODULES_DIR, 'expo-font', 'ios' ] * '/'
  pod 'EXFontInterface', :path => [MODULES_DIR, 'expo-font-interface', 'ios' ] * '/'
  pod 'EXGL', :path => [MODULES_DIR, 'expo-gl', 'ios' ] * '/'
  pod 'EXImageLoaderInterface', :path => [MODULES_DIR, 'expo-image-loader-interface', 'ios' ] * '/'
  pod 'EXLocalAuthentication', :path => [MODULES_DIR, 'expo-local-authentication', 'ios' ] * '/'
  pod 'EXLocalization', :path => [MODULES_DIR, 'expo-localization', 'ios' ] * '/'
  pod 'EXLocation', :path => [MODULES_DIR, 'expo-location', 'ios' ] * '/'
  pod 'EXMediaLibrary', :path => [MODULES_DIR, 'expo-media-library', 'ios' ] * '/'
  pod 'EXPaymentsStripe', :path => [MODULES_DIR, 'expo-payments-stripe', 'ios' ] * '/'
  pod 'EXPermissions', :path => [MODULES_DIR, 'expo-permissions', 'ios' ] * '/'
  pod 'EXPermissionsInterface', :path => [MODULES_DIR, 'expo-permissions-interface', 'ios' ] * '/'
  pod 'EXPrint', :path => [MODULES_DIR, 'expo-print', 'ios' ] * '/'
  pod 'EXReactNativeAdapter', :path => [MODULES_DIR, 'expo-react-native-adapter', 'ios' ] * '/'
  pod 'EXSegment', :path => [MODULES_DIR, 'expo-analytics-segment', 'ios' ] * '/'
  pod 'EXSensors', :path => [MODULES_DIR, 'expo-sensors', 'ios' ] * '/'
  pod 'EXSensorsInterface', :path => [MODULES_DIR, 'expo-sensors-interface', 'ios' ] * '/'
  pod 'EXSMS', :path => [MODULES_DIR, 'expo-sms', 'ios' ] * '/'
  
  # Start Firebase 
  pod 'EXFirebaseApp', :path => [MODULES_DIR, 'expo-firebase-app', 'ios'] * '/'
  pod 'EXFirebaseAnalytics', :path => [MODULES_DIR, 'expo-firebase-analytics', 'ios'] * '/'
  pod 'EXFirebaseAuth', :path => [MODULES_DIR, 'expo-firebase-auth', 'ios'] * '/'
  pod 'EXFirebaseCrashlytics', :path => [MODULES_DIR, 'expo-firebase-crashlytics', 'ios'] * '/'
  pod 'EXFirebaseDatabase', :path => [MODULES_DIR, 'expo-firebase-database', 'ios'] * '/'
  pod 'EXFirebaseFirestore', :path => [MODULES_DIR, 'expo-firebase-firestore', 'ios'] * '/'
  pod 'EXFirebaseFunctions', :path => [MODULES_DIR, 'expo-firebase-functions', 'ios'] * '/'
  pod 'EXFirebaseInstanceID', :path => [MODULES_DIR, 'expo-firebase-instance-id', 'ios'] * '/'
  pod 'EXFirebaseLinks', :path => [MODULES_DIR, 'expo-firebase-links', 'ios'] * '/'
  pod 'EXFirebaseInvites', :path => [MODULES_DIR, 'expo-firebase-invites', 'ios'] * '/'
  pod 'EXFirebaseMessaging', :path => [MODULES_DIR, 'expo-firebase-messaging', 'ios'] * '/'
  pod 'EXFirebaseNotifications', :path => [MODULES_DIR, 'expo-firebase-notifications', 'ios'] * '/'
  pod 'EXFirebasePerformance', :path => [MODULES_DIR, 'expo-firebase-performance', 'ios'] * '/'
  pod 'EXFirebaseRemoteConfig', :path => [MODULES_DIR, 'expo-firebase-remote-config', 'ios'] * '/'
  pod 'EXFirebaseStorage', :path => [MODULES_DIR, 'expo-firebase-storage', 'ios'] * '/'
  # End Firebase
  
  pod 'EXGL-CPP', :path => [MODULES_DIR, 'expo-gl-cpp', 'cpp' ] * '/'
  
  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? target.pod_name
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
    # Can't specify this in the React podspec because we need
    # to use those podspecs for detached projects which don't reference ExponentCPP.
    if target.pod_name.start_with?('React')
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      end
    end
    # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
    # RCT_ENABLE_PACKAGER_CONNECTION disabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
    end

    end
  end
end
