{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-av",
    "version": "11.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-okhttp",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "3.14.9"
          }
        }
      ],
      "files": [
        {
          "name": "expo-av-11.2.1.aar",
          "url": "expo-av-11.2.1.aar",
          "size": 250628,
          "sha512": "273c0c51476e2068108a8fc5d77cb2c876312cbb155e7ff8fb73369ee6e9bdcc343ef4ccbd26996e93c64cf30e6870763d5cad5d6d2d2e406af84d206b7c03ba",
          "sha256": "a1a503f4656de148e7cc72a781ee0f8e8a102b3c266ad15ff5dd4390462c8379",
          "sha1": "0bf1d050492847320561074407f7597df20a76a7",
          "md5": "8650de6d945cfa690a1ca5f48937096c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "extension-okhttp",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "3.14.9"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-native",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-av-11.2.1.aar",
          "url": "expo-av-11.2.1.aar",
          "size": 250628,
          "sha512": "273c0c51476e2068108a8fc5d77cb2c876312cbb155e7ff8fb73369ee6e9bdcc343ef4ccbd26996e93c64cf30e6870763d5cad5d6d2d2e406af84d206b7c03ba",
          "sha256": "a1a503f4656de148e7cc72a781ee0f8e8a102b3c266ad15ff5dd4390462c8379",
          "sha1": "0bf1d050492847320561074407f7597df20a76a7",
          "md5": "8650de6d945cfa690a1ca5f48937096c"
        }
      ]
    }
  ]
}
