{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-screen-capture",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-screen-capture-4.2.0.aar",
          "url": "expo-screen-capture-4.2.0.aar",
          "size": 22416,
          "sha512": "a53cf2755270f2e1e7ec2144fbecee503988a15d2a747e92335a9acf0ee0f80310a663aa473949465c07153b29525774ccad4e0d9867cbb485a77e52dcdc1fe9",
          "sha256": "804150e357230493e893e492b484bae46724fa6b25ad3a12fc07203eb6aefafc",
          "sha1": "0d94f7fa38104b3f1ef812417d2b5e042b9266ff",
          "md5": "85b0906c2f7eb718abcfb979a35ad3fe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-screen-capture-4.2.0.aar",
          "url": "expo-screen-capture-4.2.0.aar",
          "size": 22416,
          "sha512": "a53cf2755270f2e1e7ec2144fbecee503988a15d2a747e92335a9acf0ee0f80310a663aa473949465c07153b29525774ccad4e0d9867cbb485a77e52dcdc1fe9",
          "sha256": "804150e357230493e893e492b484bae46724fa6b25ad3a12fc07203eb6aefafc",
          "sha1": "0d94f7fa38104b3f1ef812417d2b5e042b9266ff",
          "md5": "85b0906c2f7eb718abcfb979a35ad3fe"
        }
      ]
    }
  ]
}
