packages:
  - apps/*
  - packages/*
  - packages/@expo/*
  - tools
  - apps/brownfield-tester/expo-app
  - apps/bare-expo/e2e/image-comparison

ignoreWorkspaceCycles: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - fmerge
  - protobufjs
  - unrs-resolver

linkWorkspacePackages: deep

loglevel: info

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - better-sqlite3
  - fsevents
  - sharp
  - workerd

patchedDependencies:
  '@react-native-community/netinfo': patches/@react-native-community+netinfo.patch
  '@react-native/dev-middleware': patches/@react-native+dev-middleware.patch
  react-native-reanimated: patches/react-native-reanimated.patch
  react-native-view-shot: patches/react-native-view-shot.patch
  react-native-worklets: patches/react-native-worklets.patch
  react-server-dom-webpack: patches/react-server-dom-webpack.patch

preferWorkspacePackages: true
