{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-firebase-analytics",
    "version": "7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.1.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "version": {
            "requires": "20.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "expo-firebase-analytics-7.0.0.aar",
          "url": "expo-firebase-analytics-7.0.0.aar",
          "size": 18842,
          "sha512": "6b450d197d2741a52d36f3de302c8fa793a7cc8246d67a7fed21dc47261e41fc5ebf15c0d9a8fc406599ab1273e65382b3bec8e38c81b9e27b7c73d9f41c9305",
          "sha256": "61e9de17b2462f444deec148457abb2f7740f2c6fa87a4a3a3a98d025639967c",
          "sha1": "cb049559fc1186fbf36ec14d3d0bb588705e2c9c",
          "md5": "2744e695f5f4b48ea1f540d08ef2709f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "20.1.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-common",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "version": {
            "requires": "20.1.2"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-firebase-core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-firebase-analytics-7.0.0.aar",
          "url": "expo-firebase-analytics-7.0.0.aar",
          "size": 18842,
          "sha512": "6b450d197d2741a52d36f3de302c8fa793a7cc8246d67a7fed21dc47261e41fc5ebf15c0d9a8fc406599ab1273e65382b3bec8e38c81b9e27b7c73d9f41c9305",
          "sha256": "61e9de17b2462f444deec148457abb2f7740f2c6fa87a4a3a3a98d025639967c",
          "sha1": "cb049559fc1186fbf36ec14d3d0bb588705e2c9c",
          "md5": "2744e695f5f4b48ea1f540d08ef2709f"
        }
      ]
    }
  ]
}
