name: 'EAS Build'
description: 'Composite action to run eas build'

inputs:
  platform:
    description: 'platform'
    required: true
  profile:
    description: 'Build profile from eas.json'
    required: true
  projectRoot:
    description: 'Relative path to root of the EAS project'
    required: true
  expoToken:
    description: 'Expo token'
    required: true
  noWait:
    description: 'Exit immediately after build is scheduled'
    required: false
  message:
    description: 'Message attached to the build'
    required: false

outputs:
  build_id:
    description: 'EAS Build ID'
    value: ${{ steps.build_start.outputs.build_id }}

runs:
  using: 'composite'
  steps:
    - name: Start build
      shell: bash
      id: build_start
      run: |
        if [[ -z "${COMMIT_MESSAGE}" ]]; then
          COMMIT_MESSAGE=$(git log -1 --pretty=oneline | head -c1000)
        fi
        MESSAGE="${MESSAGE:-$COMMIT_MESSAGE}"
        BUILD_ID=$(eas build -p $PLATFORM --profile $EAS_BUILD_PROFILE --message "$MESSAGE" --non-interactive --json --no-wait | jq -r ".[0].id")
        echo build_id="$BUILD_ID" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.projectRoot }}
      env:
        EXPO_TOKEN: ${{ inputs.expoToken }}
        EAS_BUILD_PROFILE: ${{ inputs.profile }}
        PLATFORM: ${{ inputs.platform }}
        MESSAGE: ${{ inputs.message }}
        EAS_DANGEROUS_OVERRIDE_ANDROID_APPLICATION_ID: host.exp.exponent
    - name: Wait for build to finish
      shell: bash
      if: ${{ !inputs.noWait }}
      run: |
        while true
        do
          STATUS=$(eas build:view $BUILD_ID --json 2>/dev/null | jq -r ".status" || true)
          if [[ "$STATUS" == "ERRORED" || "$STATUS" == "CANCELLED" ]] ; then
            echo "Build failed"
            exit 1;
          elif [[ "$STATUS" == "FINISHED" ]]; then
            echo "Build finished succesfully"
            exit 0
          fi
          sleep 60
        done
      working-directory: ${{ inputs.projectRoot }}
      env:
        EXPO_TOKEN: ${{ inputs.expoToken }}
        EAS_BUILD_PROFILE: ${{ inputs.profile }}
        BUILD_ID: ${{ steps.build_start.outputs.build_id }}
