import type { ScanStats } from '@expo/expo-modules-macros-plugin';
import fs from 'fs';
import path from 'path';

import { scanPackage } from '../scanner/scan';
import { GENERATED_HEADER_LINE, renderSurface, type RenderWarning } from './renderSurface';

export type GenerateTypesOptions = {
  /** The Expo module package to scan. Absolute. */
  packageDir: string;
  /** The TypeScript file to write. Absolute. */
  outputPath: string;
  /** A scanner executable to use instead of the one shipped with the macros plugin. */
  scannerPath?: string;
};

export type GenerateTypesResult = {
  /** The file written, or `null` when the package exports nothing. */
  outputPath: string | null;
  /**
   * A file this tool generated earlier and removed because the package no longer exports anything,
   * or `null` when nothing was removed.
   */
  removedOutputPath: string | null;
  warnings: RenderWarning[];
  stats: ScanStats;
  counts: {
    modules: number;
    sharedObjects: number;
    records: number;
    enums: number;
    unions: number;
  };
};

/**
 * Scans one Expo module package for its JS-exported native types and writes them as a single
 * TypeScript file. Nothing is written when the package exports no types; a file this tool generated
 * on an earlier run is removed then, so no stale declarations stay behind. The output file is only
 * ever replaced or removed when it carries this tool's header, so a hand-written file at the same
 * path is never lost.
 */
export async function generateTypes({
  packageDir,
  outputPath,
  scannerPath,
}: GenerateTypesOptions): Promise<GenerateTypesResult> {
  const { exports: surface, stats } = await scanPackage(packageDir, { binaryPath: scannerPath });
  const { source, warnings } = renderSurface(surface);
  const counts = {
    modules: surface.modules.length,
    sharedObjects: surface.sharedObjects.length,
    records: surface.records.length,
    enums: surface.enums.length,
    unions: surface.unions.length,
  };
  const existing = await readOwnership(outputPath);
  if (source === null) {
    if (existing !== 'owned') {
      return { outputPath: null, removedOutputPath: null, warnings, stats, counts };
    }
    await fs.promises.unlink(outputPath);
    return { outputPath: null, removedOutputPath: outputPath, warnings, stats, counts };
  }
  if (existing === 'foreign') {
    throw new Error(
      `Refusing to overwrite ${outputPath}: the file was not generated by expo-modules-cli, since it ` +
        `does not start with the generated-file header. Move or rename that file, or pass another ` +
        `output path with --out.`
    );
  }
  await fs.promises.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.promises.writeFile(outputPath, source);
  return { outputPath, removedOutputPath: null, warnings, stats, counts };
}

/**
 * Whether the file at `outputPath` is absent, was generated by this tool (`owned`), or is anyone
 * else's (`foreign`). Throws when the path exists but cannot be read as a file.
 */
async function readOwnership(outputPath: string): Promise<'absent' | 'owned' | 'foreign'> {
  let content: string;
  try {
    content = await fs.promises.readFile(outputPath, 'utf8');
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      return 'absent';
    }
    throw new Error(
      `Could not read ${outputPath} (${error.code ?? error.message}). The output path must be a ` +
        `readable file, so check that it is not a directory and that you have permission to read ` +
        `it, or pass another output path with --out.`
    );
  }
  return content.startsWith(GENERATED_HEADER_LINE) ? 'owned' : 'foreign';
}
