import type { ScanStats } from '@expo/expo-modules-macros-plugin';
import fs from 'fs';
import path from 'path';

import { scanPackage } from '../scanner/scan';
import {
  GENERATED_HEADER_LINE,
  renderSurface,
  type DeclarationCounts,
  type RenderedDeclaration,
  type RenderWarning,
} from './renderSurface';

export type GenerateTypesOptions = {
  /** The Expo module package to scan. Absolute. */
  packageDir: string;
  /** The TypeScript file to write. Absolute. */
  outputPath: string;
  /** A scanner executable to use instead of the one shipped with the macros plugin. */
  scannerPath?: string;
  /** Report what a run would do without touching the file: `stale` instead of a write or removal. */
  check?: boolean;
};

export type GenerateTypesOutcome =
  /** The file was written with new content. */
  | { kind: 'written'; outputPath: string }
  /** The file already held exactly this content, so it was left untouched. */
  | { kind: 'unchanged'; outputPath: string }
  /** The package exports nothing and a file this tool generated earlier was removed. */
  | { kind: 'removed'; outputPath: string }
  /** The package exports nothing and there was no generated file to remove. */
  | { kind: 'empty' }
  /** With `check`: the file is missing, outdated, or no longer needed, and a run would write or remove it. */
  | { kind: 'stale'; outputPath: string; expected: 'written' | 'removed' };

export type GenerateTypesResult = {
  outcome: GenerateTypesOutcome;
  warnings: RenderWarning[];
  stats: ScanStats;
  /** Declarations written, per kind; skipped ones are not counted. */
  counts: DeclarationCounts;
  /** The declarations written, in file order. Empty when the package exports nothing. */
  declarations: RenderedDeclaration[];
};

/**
 * Scans one Expo module package for its JS-exported native types and writes them as a single
 * TypeScript file, leaving the file untouched when it already holds that content. Nothing is
 * written when the package exports no types; a file this tool generated on an earlier run is
 * removed then, so no stale declarations stay behind. The output file is only ever replaced or
 * removed when it carries this tool's header, so a hand-written file at the same path is never
 * lost. With `check`, the file is not touched at all and a pending write or removal is reported as
 * `stale`.
 */
export async function generateTypes({
  packageDir,
  outputPath,
  scannerPath,
  check = false,
}: GenerateTypesOptions): Promise<GenerateTypesResult> {
  const { exports: surface, stats } = await scanPackage(packageDir, { binaryPath: scannerPath });
  const { source, warnings, counts, declarations } = renderSurface(surface);
  const existing = await readExisting(outputPath);
  const outcome = await settle(outputPath, source, existing, check);
  return { outcome, warnings, stats, counts, declarations };
}

/** Applies the rendered source to the file on disk, or with `check` only says what that would do. */
async function settle(
  outputPath: string,
  source: string | null,
  existing: ExistingFile,
  check: boolean
): Promise<GenerateTypesOutcome> {
  if (source === null) {
    if (existing.kind !== 'owned') {
      return { kind: 'empty' };
    }
    if (check) {
      return { kind: 'stale', outputPath, expected: 'removed' };
    }
    await fs.promises.unlink(outputPath);
    return { kind: 'removed', outputPath };
  }
  if (existing.kind === 'foreign') {
    throw new Error(
      `Refusing to overwrite ${outputPath}: the file was not generated by expo-modules-cli, since it ` +
        `does not start with the generated-file header. Move or rename that file, or pass another ` +
        `output path with --out.`
    );
  }
  if (existing.kind === 'owned' && existing.content === source) {
    return { kind: 'unchanged', outputPath };
  }
  if (check) {
    return { kind: 'stale', outputPath, expected: 'written' };
  }
  await fs.promises.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.promises.writeFile(outputPath, source);
  return { kind: 'written', outputPath };
}

type ExistingFile =
  | { kind: 'absent' }
  /** A file this tool generated, with its current content. */
  | { kind: 'owned'; content: string }
  /** Anyone else's file. */
  | { kind: 'foreign' };

/** Reads the file at `outputPath` and says whose it is. Throws when it exists but cannot be read. */
async function readExisting(outputPath: string): Promise<ExistingFile> {
  let content: string;
  try {
    content = await fs.promises.readFile(outputPath, 'utf8');
  } catch (error: any) {
    if (error.code === 'ENOENT') {
      return { kind: 'absent' };
    }
    throw new Error(
      `Could not read ${outputPath} (${error.code ?? error.message}). The output path must be a ` +
        `readable file, so check that it is not a directory and that you have permission to read ` +
        `it, or pass another output path with --out.`
    );
  }
  return content.startsWith(GENERATED_HEADER_LINE)
    ? { kind: 'owned', content }
    : { kind: 'foreign' };
}
