import type {
  ExportedEnum,
  ExportedEvent,
  ExportedFunction,
  ExportedModule,
  ExportedParameter,
  ExportedProperty,
  ExportedRecord,
  ExportedSharedObject,
  ExportedSurface,
  ExportedUnion,
} from '@expo/expo-modules-macros-plugin';

import { isIdentifier, memberName, parameterName, stripBackticks } from './identifiers';
import { renderReturnType, renderType, type RenderContext } from './renderType';

export type RenderWarning = {
  /** Absolute path of the Swift file declaring the member. */
  file: string;
  /** The member in Swift names: `Type.member`, or `Type.function(parameter)` for a parameter. */
  location: string;
  message: string;
};

export type RenderedSurface = {
  /** The declaration file contents, or `null` when the surface exports nothing. */
  source: string | null;
  warnings: RenderWarning[];
  /** How many declarations of each kind the source holds; skipped ones are not counted. */
  counts: DeclarationCounts;
  /** The declarations the source holds, in the order they appear in it. */
  declarations: RenderedDeclaration[];
};

export type RenderedDeclaration = {
  kind: 'enum' | 'record' | 'union' | 'shared object' | 'module';
  /** The TypeScript name: the JS name for modules and shared objects, the Swift name otherwise. */
  name: string;
  swiftName: string;
  /** Absolute path of the Swift file declaring it. */
  file: string;
};

export type DeclarationCounts = {
  modules: number;
  sharedObjects: number;
  records: number;
  enums: number;
  unions: number;
};

type ContextFactory = (file: string, location: string) => RenderContext;

/**
 * Tracks the member names emitted into one declaration body. A property must be unique; a function
 * may repeat another function's name (TypeScript reads that as an overload) but not a property's.
 * Static and instance members live in separate namespaces.
 */
class MemberNames {
  private properties = new Set<string>();
  private functions = new Set<string>();

  claimProperty(key: string): boolean {
    if (this.properties.has(key) || this.functions.has(key)) {
      return false;
    }
    this.properties.add(key);
    return true;
  }

  claimFunction(key: string): boolean {
    if (this.properties.has(key)) {
      return false;
    }
    this.functions.add(key);
    return true;
  }
}

function memberTakenWarning(name: string): string {
  return `another member already uses the JS name '${name}', so this one was skipped`;
}

/** The first line of every generated file; identifies files this tool owns. */
export const GENERATED_HEADER_LINE = '// @generated by expo-modules-cli. Do not edit by hand.';

const HEADER = `${GENERATED_HEADER_LINE}\n// Regenerate with \`expo-modules generate-types\`.\n`;

/**
 * The package that generated files import Expo's own types from. Every Expo module declares `expo`
 * as a peer dependency, while `expo-modules-core` reaches it only transitively.
 */
const EXPO_PACKAGE = 'expo';

/**
 * Swift types provided by `expo-modules-core` that the scanner reports as plain references, with the
 * TypeScript type each converts to and from. A type with `from` is imported from that module; the
 * others are TypeScript globals. The concrete typed array classes carry the names of their JS
 * counterparts, so each maps to the global of the same name.
 */
const CORE_TYPES: Record<string, { name: string; from?: string }> = {
  TypedArray: { name: 'TypedArray', from: EXPO_PACKAGE },
  ArrayBuffer: { name: 'ArrayBuffer' },
  ...Object.fromEntries(
    [
      'Int8Array',
      'Int16Array',
      'Int32Array',
      'Uint8Array',
      'Uint8ClampedArray',
      'Uint16Array',
      'Uint32Array',
      'Float32Array',
      'Float64Array',
      'BigInt64Array',
      'BigUint64Array',
    ].map((name) => [name, { name }])
  ),
};

/** The base class of every native module instance on the JS side. */
const NATIVE_MODULE_BASE = { name: 'NativeModule', from: EXPO_PACKAGE };

/** The base class of every shared object instance on the JS side. */
const SHARED_OBJECT_BASE = { name: 'SharedObject', from: EXPO_PACKAGE };

/** Names a scanned declaration cannot take without clashing with a base class import. */
const BASE_CLASS_NAMES = new Set([NATIVE_MODULE_BASE.name, SHARED_OBJECT_BASE.name]);

/**
 * Renders a scanned surface as one TypeScript declaration file: enums first, then records, unions,
 * shared objects, and modules, so every declaration precedes the ones that reference it. References to
 * types the `expo` package provides become type-only imports.
 */
export function renderSurface(scanned: ExportedSurface): RenderedSurface {
  const surface = withoutBackticks(scanned);
  const warnings: RenderWarning[] = [];

  // A declaration whose TS name is not an identifier, names a base class this file imports, or
  // repeats one already declared in this file, cannot be emitted; it is reported and left out, so
  // references to it resolve as unknown rather than to an invalid or ambiguous declaration.
  const declaredNames = new Set<string>();
  const declarable = <T extends { name: string; file: string }>(
    items: T[],
    tsName: (item: T) => string
  ) =>
    items.filter((item) => {
      const name = tsName(item);
      const problem = !isIdentifier(name)
        ? `'${name}' is not a valid TypeScript identifier, so its declaration was skipped`
        : BASE_CLASS_NAMES.has(name)
          ? `the TypeScript name '${name}' belongs to the base class imported from '${EXPO_PACKAGE}', ` +
            'so this declaration was skipped'
          : declaredNames.has(name)
            ? `another declaration already uses the TypeScript name '${name}', so this one was skipped`
            : null;
      if (problem) {
        warnings.push({ file: item.file, location: item.name, message: problem });
        return false;
      }
      declaredNames.add(name);
      return true;
    });
  const enums = declarable(surface.enums, (enumeration) => enumeration.name);
  const records = declarable(surface.records, (record) => record.name);
  const unions = declarable(surface.unions, (union) => union.name);
  const sharedObjects = declarable(surface.sharedObjects, (sharedObject) => sharedObject.jsName);
  const modules = declarable(surface.modules, (module) => module.jsName);

  // Swift type name -> the TS name it is declared under in this file.
  const refs = new Map<string, string>();
  for (const enumeration of enums) {
    refs.set(enumeration.name, enumeration.name);
  }
  for (const record of records) {
    refs.set(record.name, record.name);
  }
  for (const union of unions) {
    refs.set(union.name, union.name);
  }
  for (const sharedObject of sharedObjects) {
    refs.set(sharedObject.name, sharedObject.jsName);
  }
  for (const module of modules) {
    refs.set(module.name, module.jsName);
  }

  // Module specifier -> type names to import from it.
  const imports = new Map<string, Set<string>>();
  const addImport = ({ name, from }: { name: string; from: string }) => {
    const names = imports.get(from) ?? new Set<string>();
    names.add(name);
    imports.set(from, names);
  };
  const resolveRef = (name: string): string | undefined => {
    const local = refs.get(name);
    if (local) {
      return local;
    }
    const coreType = CORE_TYPES[name];
    if (coreType?.from) {
      addImport({ name: coreType.name, from: coreType.from });
    }
    return coreType?.name;
  };
  if (modules.length > 0) {
    addImport(NATIVE_MODULE_BASE);
  }
  if (sharedObjects.length > 0) {
    addImport(SHARED_OBJECT_BASE);
  }

  const makeContext: ContextFactory = (file, location) => ({
    resolveRef,
    warn: (message) => {
      warnings.push({ file, location, message });
    },
  });

  // The events type of a class takes a name derived from the class; when a scanned declaration
  // already owns that name, the map is inlined into the `extends` clause instead.
  const claimTypeName = (name: string): boolean => {
    if (declaredNames.has(name)) {
      return false;
    }
    declaredNames.add(name);
    return true;
  };

  const declarations = [
    ...enums.map((enumeration) => renderEnum(enumeration, makeContext)),
    ...records.map((record) => renderRecord(record, makeContext)),
    ...unions.map((union) => renderUnion(union, makeContext)),
    ...sharedObjects.flatMap((sharedObject) =>
      renderSharedObject(sharedObject, makeContext, claimTypeName)
    ),
    ...modules.flatMap((module) => renderModule(module, makeContext, claimTypeName)),
  ];
  const counts: DeclarationCounts = {
    modules: modules.length,
    sharedObjects: sharedObjects.length,
    records: records.length,
    enums: enums.length,
    unions: unions.length,
  };
  const rendered: RenderedDeclaration[] = [
    ...enums.map((e) => ({ kind: 'enum' as const, name: e.name, swiftName: e.name, file: e.file })),
    ...records.map((r) => ({
      kind: 'record' as const,
      name: r.name,
      swiftName: r.name,
      file: r.file,
    })),
    ...unions.map((u) => ({
      kind: 'union' as const,
      name: u.name,
      swiftName: u.name,
      file: u.file,
    })),
    ...sharedObjects.map((so) => ({
      kind: 'shared object' as const,
      name: so.jsName,
      swiftName: so.name,
      file: so.file,
    })),
    ...modules.map((m) => ({
      kind: 'module' as const,
      name: m.jsName,
      swiftName: m.name,
      file: m.file,
    })),
  ];
  if (declarations.length === 0) {
    return { source: null, warnings, counts, declarations: rendered };
  }
  const importBlock = [...imports.entries()]
    .map(([from, names]) => `import type { ${[...names].sort().join(', ')} } from '${from}';\n`)
    .join('');
  const sections = importBlock ? [HEADER, importBlock, ...declarations] : [HEADER, ...declarations];
  return { source: sections.join('\n'), warnings, counts, declarations: rendered };
}

/**
 * An `Enumerable` enum crosses the boundary as its raw value, so it renders as a TS enum whose
 * members carry the Swift case names and raw values. Cases without a written value are left
 * without one too: TS fills them in with the same rule as Swift, `0` for the first case and one
 * more than the predecessor for each next one.
 */
function renderEnum(enumeration: ExportedEnum, makeContext: ContextFactory): string {
  const { name, file, rawType, cases } = enumeration;
  const ctx = makeContext(file, name);
  if (!rawType) {
    ctx.warn(
      'the enum has no raw type, so its JS representation is not known and it was rendered as unknown'
    );
    return `export type ${name} = unknown;\n`;
  }
  let members: string[];
  if (rawType.kind === 'primitive' && rawType.typeof === 'string') {
    // A string case without a written value takes its own name; the scanner already applied that.
    members = cases.map(
      (enumCase) =>
        `${memberName(enumCase.name)} = ${stringLiteral(enumCase.rawValue ?? enumCase.name)}`
    );
  } else if (rawType.kind === 'primitive' && rawType.typeof === 'number') {
    const rendered = renderIntegerMembers(enumeration, makeContext);
    if (rendered === null) {
      return `export type ${name} = number;\n`;
    }
    members = rendered;
  } else {
    ctx.warn(
      `raw type '${rawType.kind === 'primitive' ? rawType.name : rawType.kind}' is neither a string ` +
        'nor a number, so the enum was rendered as unknown'
    );
    return `export type ${name} = unknown;\n`;
  }
  if (members.length === 0) {
    return `export enum ${name} {}\n`;
  }
  return `export enum ${name} {\n${members.map((member) => `  ${member},\n`).join('')}}\n`;
}

/**
 * An integer or floating-point literal as Swift spells it: optional minus, then decimal, `0x`, `0b`,
 * or `0o` digits with optional `_` separators, or a decimal with a fraction.
 */
const NUMERIC_LITERAL =
  /^\s*(-?)(?:(0[xX][0-9a-fA-F_]+|0[bB][01_]+|0[oO][0-7_]+)|(\d[\d_]*)(\.\d[\d_]*)?)\s*$/;

/**
 * An integer enum's members with each written raw value normalized to a decimal literal, or `null`
 * when a value is an expression, which the caller renders as `number`. Only literals pass: Swift
 * reads `0123` as decimal while TS rejects it, and JS bitwise operators and shifts work on 32 bits,
 * so `1 << 40` would silently change value.
 */
function renderIntegerMembers(
  enumeration: ExportedEnum,
  makeContext: ContextFactory
): string[] | null {
  const members: string[] = [];
  for (const enumCase of enumeration.cases) {
    if (enumCase.rawValue === undefined) {
      members.push(memberName(enumCase.name));
      continue;
    }
    const literal = normalizeNumericLiteral(enumCase.rawValue);
    if (literal === null) {
      makeContext(enumeration.file, `${enumeration.name}.${enumCase.name}`).warn(
        `raw value '${enumCase.rawValue}' cannot be evaluated without compiling, so the enum was ` +
          'rendered as number'
      );
      return null;
    }
    members.push(`${memberName(enumCase.name)} = ${literal}`);
  }
  return members;
}

/** The decimal spelling of a Swift numeric literal, or `null` when the text is not one. */
function normalizeNumericLiteral(text: string): string | null {
  const match = NUMERIC_LITERAL.exec(text);
  if (!match) {
    return null;
  }
  const [, sign, prefixed, integer, fraction] = match;
  if (prefixed) {
    return `${sign}${BigInt(prefixed.replace(/_/g, '')).toString()}`;
  }
  const digits = (integer ?? '').replace(/_/g, '');
  if (fraction) {
    return `${sign}${Number(`${digits}${fraction.replace(/_/g, '')}`)}`;
  }
  return `${sign}${BigInt(digits).toString()}`;
}

/** A single-quoted TypeScript string literal with escapes for quotes, backslashes, and line breaks. */
function stringLiteral(value: string): string {
  const escaped = JSON.stringify(value).slice(1, -1).replace(/\\"/g, '"').replace(/'/g, "\\'");
  return `'${escaped}'`;
}

/**
 * A `@Union` decodes from whichever member payload matches first, so in TS it is the union of the
 * member types. Member names are Swift-side only and do not appear.
 */
function renderUnion(union: ExportedUnion, makeContext: ContextFactory): string {
  const ctx = makeContext(union.file, union.name);
  if (union.members.length === 0) {
    ctx.warn('the union has no members, so it was rendered as never');
    return `export type ${union.name} = never;\n`;
  }
  const members = union.members.map((member) =>
    renderType(member.type, makeContext(union.file, `${union.name}.${member.name}`))
  );
  return `export type ${union.name} = ${members.join(' | ')};\n`;
}

function renderRecord(record: ExportedRecord, makeContext: ContextFactory): string {
  const names = new MemberNames();
  const members: string[] = [];
  for (const property of record.properties) {
    const ctx = makeContext(record.file, `${record.name}.${property.name}`);
    if (!names.claimProperty(property.name)) {
      ctx.warn(memberTakenWarning(property.name));
      continue;
    }
    const type = renderType(property.type, ctx);
    members.push(`${memberName(property.name)}${property.required ? '' : '?'}: ${type};`);
  }
  return block(`export type ${record.name} = {`, members, '};');
}

/** The events type (when it got its own declaration) and the class, in that order. */
function renderSharedObject(
  sharedObject: ExportedSharedObject,
  makeContext: ContextFactory,
  claimTypeName: (name: string) => boolean
): string[] {
  const members: string[] = [];
  const names = new MemberNames();
  if (sharedObject.constructorParameters) {
    const parameters = renderParameters(
      sharedObject.constructorParameters,
      sharedObject.file,
      `${sharedObject.name}.init`,
      makeContext
    );
    members.push(`constructor(${parameters});`);
  } else {
    // Without a `@JS init`, JS cannot construct the object; only native code hands out instances. A
    // private constructor tells TypeScript the same, instead of the implied public no-argument one.
    members.push('private constructor();');
  }
  for (const property of sharedObject.properties) {
    const rendered = renderProperty(property, sharedObject, makeContext, names, {
      includeStatic: true,
    });
    if (rendered) {
      members.push(rendered);
    }
  }
  for (const fn of sharedObject.functions) {
    const rendered = renderFunction(fn, sharedObject, makeContext, names, { includeStatic: true });
    if (rendered) {
      members.push(rendered);
    }
  }
  const events = renderEvents(sharedObject, sharedObject.jsName, makeContext, claimTypeName);
  const base = `${SHARED_OBJECT_BASE.name}${events.typeArgument}`;
  const declaration = block(
    `export declare class ${sharedObject.jsName} extends ${base} {`,
    members,
    '}'
  );
  return events.declaration ? [events.declaration, declaration] : [declaration];
}

/** The events type (when it got its own declaration) and the class, in that order. */
function renderModule(
  module: ExportedModule,
  makeContext: ContextFactory,
  claimTypeName: (name: string) => boolean
): string[] {
  // JS only ever sees the module instance that `requireNativeModule` returns, so a member the Swift
  // side declares `static` is still an instance member of that class in TS.
  const names = new MemberNames();
  const members = [
    ...module.properties.map((property) =>
      renderProperty(property, module, makeContext, names, { includeStatic: false })
    ),
    ...module.functions.map((fn) =>
      renderFunction(fn, module, makeContext, names, { includeStatic: false })
    ),
  ].filter((member): member is string => member !== null);
  const events = renderEvents(module, module.jsName, makeContext, claimTypeName);
  const base = `${NATIVE_MODULE_BASE.name}${events.typeArgument}`;
  const declaration = block(
    `export declare class ${module.jsName} extends ${base} {`,
    members,
    '}'
  );
  return events.declaration ? [events.declaration, declaration] : [declaration];
}

type Owner = { name: string; file: string };
type EventOwner = Owner & { events: ExportedEvent[] };

type RenderedEvents = {
  /** `export type XEvents = { ... };`, or absent when the map was inlined or there are no events. */
  declaration?: string;
  /** The type argument for the base class: `<XEvents>`, `<{ ... }>`, or empty without events. */
  typeArgument: string;
};

/**
 * The events map of a module or shared object: one listener signature per event under its JS name,
 * declared as `export type <JsName>Events` and passed to the base class, the way hand-written
 * modules do. When a scanned declaration already owns that name, the map is inlined into the type
 * argument instead. A repeated JS name is skipped with a warning, since the map holds one signature
 * per name.
 */
function renderEvents(
  owner: EventOwner,
  jsName: string,
  makeContext: ContextFactory,
  claimTypeName: (name: string) => boolean
): RenderedEvents {
  const taken = new Set<string>();
  const listeners: string[] = [];
  for (const event of owner.events) {
    const ctx = makeContext(owner.file, `${owner.name}.${event.name}`);
    if (taken.has(event.jsName)) {
      ctx.warn(`another event already uses the JS name '${event.jsName}', so this one was skipped`);
      continue;
    }
    taken.add(event.jsName);
    const payload = event.payload ? `payload: ${renderType(event.payload, ctx)}` : '';
    listeners.push(`${memberName(event.jsName)}(${payload}): void;`);
  }
  if (listeners.length === 0) {
    return { typeArgument: '' };
  }
  const typeName = `${jsName}Events`;
  if (!claimTypeName(typeName)) {
    makeContext(owner.file, owner.name).warn(
      `another declaration already uses the TypeScript name '${typeName}', so the events map was inlined`
    );
    return { typeArgument: `<{\n${listeners.map((listener) => `  ${listener}\n`).join('')}}>` };
  }
  return {
    declaration: block(`export type ${typeName} = {`, listeners, '};'),
    typeArgument: `<${typeName}>`,
  };
}

type MemberOptions = { includeStatic: boolean };

/** Renders one property, or `null` when its name is already taken in the body. */
function renderProperty(
  property: ExportedProperty,
  owner: Owner,
  makeContext: ContextFactory,
  names: MemberNames,
  { includeStatic }: MemberOptions
): string | null {
  const ctx = makeContext(owner.file, `${owner.name}.${property.name}`);
  if (!names.claimProperty(memberKey(property.jsName, includeStatic && property.static))) {
    ctx.warn(memberTakenWarning(property.jsName));
    return null;
  }
  let type: string;
  if (property.type) {
    type = renderType(property.type, ctx);
  } else {
    ctx.warn('type could not be determined from the declaration, rendered as unknown');
    type = 'unknown';
  }
  const modifiers = `${includeStatic && property.static ? 'static ' : ''}${property.readonly ? 'readonly ' : ''}`;
  return `${modifiers}${memberName(property.jsName)}: ${type};`;
}

/** Renders one function, or `null` when a property already owns its name in the body. */
function renderFunction(
  fn: ExportedFunction,
  owner: Owner,
  makeContext: ContextFactory,
  names: MemberNames,
  { includeStatic }: MemberOptions
): string | null {
  const location = `${owner.name}.${fn.name}`;
  if (!names.claimFunction(memberKey(fn.jsName, includeStatic && fn.static))) {
    makeContext(owner.file, location).warn(memberTakenWarning(fn.jsName));
    return null;
  }
  const parameters = renderParameters(fn.parameters, owner.file, location, makeContext);
  const returns = renderReturnType(fn.returns, fn.async, makeContext(owner.file, `${location}()`));
  return `${includeStatic && fn.static ? 'static ' : ''}${memberName(fn.jsName)}(${parameters}): ${returns};`;
}

function renderParameters(
  parameters: ExportedParameter[],
  file: string,
  location: string,
  makeContext: ContextFactory
): string {
  const lastRequiredIndex = parameters.findLastIndex((parameter) => !parameter.optional);
  return parameters
    .map((parameter, index) => {
      const name = parameterName(parameter.name, index);
      // The warning names the parameter as Swift declares it, even when TS needs another name.
      const type = renderType(parameter.type, makeContext(file, `${location}(${parameter.name})`));
      if (!parameter.optional) {
        return `${name}: ${type}`;
      }
      // TypeScript only allows optional parameters at the end of the list. Swift allows a defaulted
      // parameter before a required one, so such a parameter accepts `undefined` explicitly instead.
      return index < lastRequiredIndex ? `${name}: ${type} | undefined` : `${name}?: ${type}`;
    })
    .join(', ');
}

/** The namespace-qualified key a member occupies in its body. */
function memberKey(jsName: string, isStatic: boolean): string {
  return isStatic ? `static ${jsName}` : jsName;
}

/** Lays out a declaration body with two-space indentation and a trailing newline. */
function block(open: string, members: string[], close: string): string {
  if (members.length === 0) {
    return `${open}${close}\n`;
  }
  return `${open}\n${members.map((member) => `  ${member}`).join('\n')}\n${close}\n`;
}

/**
 * The surface with Swift backticks removed from every declaration, member, event, case, and
 * parameter name, so `` `default` `` renders as `default`.
 */
function withoutBackticks(surface: ExportedSurface): ExportedSurface {
  const parameter = (p: ExportedParameter): ExportedParameter => ({
    ...p,
    label: stripBackticks(p.label),
    name: stripBackticks(p.name),
  });
  const fn = (f: ExportedFunction): ExportedFunction => ({
    ...f,
    name: stripBackticks(f.name),
    jsName: stripBackticks(f.jsName),
    parameters: f.parameters.map(parameter),
  });
  const property = (p: ExportedProperty): ExportedProperty => ({
    ...p,
    name: stripBackticks(p.name),
    jsName: stripBackticks(p.jsName),
  });
  const event = (e: ExportedEvent): ExportedEvent => ({
    ...e,
    name: stripBackticks(e.name),
    jsName: stripBackticks(e.jsName),
  });
  return {
    ...surface,
    enums: surface.enums.map((e) => ({
      ...e,
      name: stripBackticks(e.name),
      cases: e.cases.map((c) => ({ ...c, name: stripBackticks(c.name) })),
    })),
    records: surface.records.map((r) => ({
      ...r,
      name: stripBackticks(r.name),
      properties: r.properties.map((p) => ({ ...p, name: stripBackticks(p.name) })),
    })),
    unions: surface.unions.map((u) => ({
      ...u,
      name: stripBackticks(u.name),
      members: u.members.map((m) => ({ ...m, name: stripBackticks(m.name) })),
    })),
    sharedObjects: surface.sharedObjects.map((so) => ({
      ...so,
      name: stripBackticks(so.name),
      jsName: stripBackticks(so.jsName),
      constructorParameters: so.constructorParameters?.map(parameter),
      functions: so.functions.map(fn),
      properties: so.properties.map(property),
      events: so.events.map(event),
    })),
    modules: surface.modules.map((m) => ({
      ...m,
      name: stripBackticks(m.name),
      jsName: stripBackticks(m.jsName),
      functions: m.functions.map(fn),
      properties: m.properties.map(property),
      events: m.events.map(event),
    })),
  };
}
