name: Updates E2E (CLI)

on:
  push:
    branches: [main, 'sdk-*']
    paths:
      - apps/expo-workflow-testing/.eas/workflows/updates-e2e-cli.yml
      - packages/expo-updates/cli/**
  pull_request:
    branches: [main]
    paths:
      - apps/expo-workflow-testing/.eas/workflows/updates-e2e-cli.yml
      - packages/expo-updates/cli/**
  schedule:
    - cron: '0 18 * * SUN' # 18:00 UTC every Sunday

jobs:
  cli:
    runs_on: linux-medium
    image: latest
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Run CLI tests
        id: cli
        working_directory: ../../packages/expo-updates      
        run: |
          yarn test:e2e-cli --ci --runInBand
