name: Updates E2E (fingerprint)

on:
  push:
    branches: [main, 'sdk-*']
    paths:
      - apps/expo-workflow-testing/.eas/workflows/updates-e2e-fingerprint.yml
      - packages/expo-asset/**
      - packages/expo-manifests/**
      - packages/expo-updates-interface/**
      - packages/expo-updates/**
      - templates/expo-template-bare-minimum/**
  pull_request:
    paths:
      - apps/expo-workflow-testing/.eas/workflows/updates-e2e-fingerprint.yml
      - packages/expo-asset/**
      - packages/expo-manifests/**
      - packages/expo-updates-interface/**
      - packages/expo-updates/**
      - templates/expo-template-bare-minimum/**
  schedule:
    - cron: '0 19 * * SUN' # 18:00 UTC every Sunday

defaults:
  tools:
    node: 22.14.0
    yarn: 1.22.22

jobs:
  ios:
    runs_on: macos-large
    image: latest
    steps:
      - uses: eas/install_maestro
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Set up Updates E2E fingerprint project
        id: setup
        working_directory: ../..
        env:
          UPDATES_HOST: localhost
          UPDATES_PORT: "4747"
        run: |
          yarn --silent ts-node --transpile-only ./packages/expo-updates/e2e/setup/create-fingerprint-eas-project.ts
          ls -la ../updates-e2e
      - name: Prepare E2E project
        id: prepare
        working_directory: ../../../updates-e2e
        run: |
          yarn generate-test-update-bundles ios test-update-1
          yarn ios:pod-install
      - name: Build E2E test app (release)
        id: buildrelease
        working_directory: ../../../updates-e2e
        run: |
          yarn maestro:ios:release:build
      - uses: eas/start_ios_simulator
        with:
          device_identifier: iPhone 17
      - name: Run Maestro tests (release)
        id: testrelease
        working_directory: ../../../updates-e2e
        run: |
          ./maestro/maestro-test-executor.sh ./maestro/tests/updates-e2e-fingerprint.yml ios release
  android:
    runs_on: linux-large-nested-virtualization
    image: latest
    steps:
      - uses: eas/install_maestro
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Set up Updates E2E fingerprint project
        id: setup
        working_directory: ../..
        env:
          UPDATES_HOST: localhost
          UPDATES_PORT: "4747"
        run: |
          yarn --silent ts-node --transpile-only ./packages/expo-updates/e2e/setup/create-fingerprint-eas-project.ts
          ls -la ../updates-e2e
      - name: Prepare E2E project
        id: prepare
        working_directory: ../../../updates-e2e
        run: |
          yarn generate-test-update-bundles android test-update-1
      - uses: eas/start_android_emulator
        with:
          device_name: pixel_4
      - name: Build E2E test app (release)
        id: buildrelease
        working_directory: ../../../updates-e2e
        run: |
          rm -rf android/app/build
          yarn maestro:android:release:build
          # Regenerate bundles with correct fingerprint
          yarn generate-test-update-bundles android test-update-1
          rm -rf android/app/build
          yarn maestro:android:release:build
      - name: Run Maestro tests (release)
        id: testrelease
        working_directory: ../../../updates-e2e
        run: |
          ./maestro/maestro-test-executor.sh ./maestro/tests/updates-e2e-fingerprint.yml android release
