/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function getIosIdForVendorAsync(): Promise<string | undefined> {
  return '';
}

export async function getInstallationTimeAsync(): Promise<number> {
  return 0;
}

export async function getApplicationReleaseTypeAsync(): Promise<number> {
  return 0;
}

export async function getPushNotificationServiceEnvironmentAsync(): Promise<string | undefined> {
  return '';
}
