/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type URL = any;

export type ImageCachePolicy = any;

export type CGSize = any;

export type ImageSource = any;

export type ContentFit = any;

export type ContentPosition = any;

export type ImageTransition = any;

export type UIColor = any;

export type ImagePriority = any;

export async function prefetch(
  urls: URL[],
  cachePolicy: ImageCachePolicy,
  headersMap:
    | {
        [key: string]: string;
      }
    | undefined
): Promise<any> {}

export async function generateBlurhashAsync(url: URL, numberOfComponents: CGSize): Promise<any> {}

export async function clearMemoryCache(): Promise<boolean> {
  return false;
}

export async function clearDiskCache(): Promise<any> {}

export async function getCachePathAsync(cacheKey: string): Promise<any> {}

export type ViewProps = {
  source: ImageSource[] | undefined;
  placeholder: ImageSource[] | undefined;
  contentFit: ContentFit | undefined;
  placeholderContentFit: ContentFit | undefined;
  contentPosition: ContentPosition | undefined;
  transition: ImageTransition | undefined;
  blurRadius: number | undefined;
  tintColor: UIColor | undefined;
  priority: ImagePriority | undefined;
  cachePolicy: ImageCachePolicy | undefined;
  enableLiveTextInteraction: boolean | undefined;
  accessible: boolean | undefined;
  accessibilityLabel: string | undefined;
  recyclingKey: string | undefined;
  allowDownscaling: boolean | undefined;
  autoplay: boolean | undefined;
  onLoadStart: (event: any) => void;
  onProgress: (event: any) => void;
  onError: (event: any) => void;
  onLoad: (event: any) => void;
};

export function View(props: ViewProps) {}
