{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-ads-admob",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-ads-admob-13.0.0.aar",
          "url": "expo-ads-admob-13.0.0.aar",
          "size": 43218,
          "sha512": "92808261f97a94e892ae53c9fc73896cf4bcf02d248d9bbb803826b23a369df18ae76bc4b37decc086b795cb0b5c1571d3ba54010aa2e4042d80143189b187c9",
          "sha256": "9e834464ffd50710e3a87a500378471ca49d77b737e3e658d7f5da5f150988f4",
          "sha1": "c35c76a135097be2a7000a38c509dedad02e8d82",
          "md5": "da72ad23401c8883e471e3cbb3c94492"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "20.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "androidx.work:work-runtime:2.1.0 pulled from\n      play-services-ads has a bug using PendingIntent without\n      FLAG_IMMUTABLE or FLAG_MUTABLE and will fail in Apps\n      targeting S+."
        }
      ],
      "files": [
        {
          "name": "expo-ads-admob-13.0.0.aar",
          "url": "expo-ads-admob-13.0.0.aar",
          "size": 43218,
          "sha512": "92808261f97a94e892ae53c9fc73896cf4bcf02d248d9bbb803826b23a369df18ae76bc4b37decc086b795cb0b5c1571d3ba54010aa2e4042d80143189b187c9",
          "sha256": "9e834464ffd50710e3a87a500378471ca49d77b737e3e658d7f5da5f150988f4",
          "sha1": "c35c76a135097be2a7000a38c509dedad02e8d82",
          "md5": "da72ad23401c8883e471e3cbb3c94492"
        }
      ]
    }
  ]
}
