/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type CGColor = any;

export type CGPoint = any;

export type CGFloat = any;

export type ViewProps = {
  colors: CGColor[];
  startPoint: CGPoint | undefined;
  endPoint: CGPoint | undefined;
  locations: CGFloat[] | undefined;
};

export function View(props: ViewProps) {}
