//  Copyright © 2019 650 Industries. All rights reserved.

import Foundation
import EXManifests

@objcMembers
public class EXUpdatesBareUpdate: EXUpdatesUpdate {
  /**
   * Method for initializing updates from the bare-bones-styles manifests embedded in application
   * binaries. These manifest objects are generated by the script at
   * expo-updates/scripts/createManifest.js and describe the update embedded by react-native in the
   * application binary. They contain the minimum amount of information needed to reliably identify
   * the update and insert it into SQLite.
   */
  public static func update(
    withBareManifest: EXManifestsBareManifest,
    config: EXUpdatesConfig,
    database: EXUpdatesDatabase?
  ) -> EXUpdatesUpdate {
    let manifest = withBareManifest

    let updateId = manifest.rawId()
    let commitTime = manifest.commitTimeNumber()
    let assets = manifest.assets()

    let uuid = UUID(uuidString: updateId).require("update ID should be a valid UUID")

    var processedAssets: [EXUpdatesAsset] = []

    // use unsanitized id value from manifest
    let bundleKey = String(format: "bundle-%@", updateId)
    let jsBundleAsset = EXUpdatesAsset(key: bundleKey, type: EXUpdatesBareEmbeddedBundleFileType)
    jsBundleAsset.isLaunchAsset = true
    jsBundleAsset.mainBundleFilename = EXUpdatesBareEmbeddedBundleFilename
    processedAssets.append(jsBundleAsset)

    assets?.forEach { assetDict in
      let packagerHash: String = assetDict.requiredValue(forKey: "packagerHash")
      let type: String = assetDict.requiredValue(forKey: "type")
      let mainBundleDir: String? = assetDict.optionalValue(forKey: "nsBundleDir")
      let mainBundleFilename: String = assetDict.requiredValue(forKey: "nsBundleFilename")

      let key = packagerHash
      let asset = EXUpdatesAsset(key: key, type: type)
      asset.mainBundleDir = mainBundleDir
      asset.mainBundleFilename = mainBundleFilename
      processedAssets.append(asset)
    }

    let update = EXUpdatesUpdate.init(
      manifest: manifest,
      config: config,
      database: database,
      updateId: uuid,
      scopeKey: config.scopeKey.require("Must supply scopeKey in configuration"),
      commitTime: Date(timeIntervalSince1970: Double(commitTime) / 1000),
      runtimeVersion: EXUpdatesUtils.getRuntimeVersion(with: config),
      keep: true,
      status: EXUpdatesUpdateStatus.StatusEmbedded,
      isDevelopmentMode: false,
      assetsFromManifest: processedAssets
    )

    if update.runtimeVersion.contains(",") {
      let exception = NSException(
        name: NSExceptionName.internalInconsistencyException,
        reason: "Should not be initializing EXUpdatesBareUpdate in an environment with multiple runtime versions.",
        userInfo: [:]
      )
      exception.raise()
    }

    return update
  }
}
