name: Android Client - EAS Build (migrated to EAS)

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/android/**
  push:
    branches: [main, sdk-*]
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/android/**
  schedule:
    - cron: '20 5 * * *' # 5:20 AM UTC time every day

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

# note that there are also hooks in the `scripts` directory that run at different moments of the build process such as checking out the react-native submodule
jobs:
  build_android:
    name: Android Client Build
    type: build
    env:
      EAS_BUILD_PROFILE: unversioned-client
    params:
      platform: android
      profile: unversioned-client
  notify_failure:
    name: 🔔 Notify on Slack
    after: [build_android]
    steps:
      - run: |
          BUILD_STATUS="${{ after.build_android.status }}"
          COMMIT_SHA="${{ github.sha }}"
          BRANCH="${{ github.ref_name }}"
          WF_ID="${{ workflow.id }}"

          echo "Build Status: $BUILD_STATUS"
          echo "Branch: $BRANCH"
          echo "Commit: $COMMIT_SHA"
          echo "WF_ID: $WF_ID"

          if [ "$BUILD_STATUS" = "failure" ]; then
            curl -X POST "$SLACK_WEBHOOK_ANDROID" \
              -H 'Content-Type: application/json' \
              -d "{
                \"text\": \"🚨 Expo Go (Android) build failed\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Expo Go (Android) build failed*\"
                    }
                  },
                  {
                    \"type\": \"section\",
                    \"fields\": [
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Workflow:*\n<https://expo.dev/accounts/expo-ci/projects/unversioned-expo-go/workflows/$WF_ID|$WF_ID>\"
                      },
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Branch:*\n<https://github.com/expo/expo/tree/$BRANCH|$BRANCH>\"
                      },
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Commit:*\n<https://github.com/expo/expo/commit/$COMMIT_SHA|$COMMIT_SHA>\"
                      }
                    ]
                  }
                ]
              }"
          fi
