name: iOS Client - EAS Build (migrated to EAS)

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  push:
    branches: [main, sdk-*]
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  schedule:
    - cron: '20 5 * * *' # 5:20 AM UTC time every day

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

# note that there are also hooks in the `scripts` directory that run at different moments of the build process such as checking out the react-native submodule
jobs:
  build_ios:
    # TODO vonovak: the original GH action ran conditionally https://github.com/expo/expo/pull/25607 - not able to express that with EAS Workflows as of 8/25
    name: iOS Client Build
    type: build
    env:
      EAS_BUILD_PROFILE: unversioned-client
    params:
      platform: ios
      profile: unversioned-client

  notify_failure:
    name: 🔔 Notify on Slack
    after: [build_ios]
    if: ${{ after.build_ios.status == 'failure' }}
    type: slack
    params:
      webhook_url: ${{ SLACK_WEBHOOK_IOS }}
      payload:
        blocks:
          - type: header
            text:
              type: plain_text
              text: '🚨 Expo Go (iOS) build failed'
          - type: section
            fields:
              - type: mrkdwn
                text: "*Workflow:*\n<https://expo.dev/accounts/expo-ci/projects/unversioned-expo-go/workflows/${{ workflow.id }}|${{ workflow.id }}>"
              - type: mrkdwn
                text: "*Branch:*\n<https://github.com/expo/expo/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
              - type: mrkdwn
                text: "*Commit:*\n<https://github.com/expo/expo/commit/${{ github.sha }}|${{ github.sha }}>"
              - type: mrkdwn
                text: "*Event:*\n${{ github.event_name }}"
