name: iOS Client (Expo Go) - EAS Build

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  push:
    branches: [main, sdk-*]
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  schedule:
    - cron: '20 5 * * *' # 5:20 AM UTC time every day

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

# note that there are also hooks in the `scripts` directory that run at different moments of the build process such as checking out the react-native submodule
jobs:
  build_ios:
    if: ${{ !(github.event_name == 'pull_request' && github.triggering_actor == 'dependabot[bot]') }}
    name: iOS Client Build
    type: build
    env:
      EAS_BUILD_PROFILE: unversioned-client
    params:
      platform: ios
      profile: unversioned-client

  # see "Currently only hardcoded strings are supported. Using webhooks stored in env are upcoming but not yet supported."
  # https://docs.expo.dev/eas/workflows/pre-packaged-jobs/#slack
  # you can use https://github.com/expo/expo/pull/40224/commits/e5295e8518d07e9b16ad3ed23c46977232b6bb90 when the limitation drops
  notify_failure:
    if: ${{ failure() && (github.event_name == 'schedule' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/sdk-')) }}
    name: 🔔 Notify on Slack
    after: [build_ios]
    steps:
      - run: |
          BUILD_STATUS="${{ after.build_ios.status }}"
          COMMIT_SHA="${{ github.sha }}"
          BRANCH="${{ github.ref_name }}"
          WF_ID="${{ workflow.id }}"

          echo "Build Status: $BUILD_STATUS"
          echo "Branch: $BRANCH"
          echo "Commit: $COMMIT_SHA"
          echo "WF_ID: $WF_ID"

          curl -X POST "$SLACK_WEBHOOK_IOS" \
            -H 'Content-Type: application/json' \
            -d "{
              \"text\": \"🚨 Expo Go (iOS) build failed\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Expo Go (iOS) build failed*\"
                  }
                },
                {
                  \"type\": \"section\",
                  \"fields\": [
                    {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Workflow:*\n<https://expo.dev/accounts/expo-ci/projects/unversioned-expo-go/workflows/$WF_ID|$WF_ID>\"
                    },
                    {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Branch:*\n<https://github.com/expo/expo/tree/$BRANCH|$BRANCH>\"
                    },
                    {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Commit:*\n<https://github.com/expo/expo/commit/$COMMIT_SHA|$COMMIT_SHA>\"
                    }
                  ]
                }
              ]
            }"
