namespace ReactNativeAsyncStorage{
[webhosthidden]
[default_interface]
runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider {
  ReactPackageProvider();
};
} // namespace ReactNativeAsyncStorage
