import type { ExpoConfig } from 'expo/config';
import { WarningAggregator, withAppDelegate, withInfoPlist } from 'expo/config-plugins';
import fs from 'fs';
import path from 'path';
import resolveFrom from 'resolve-from';

import { withIosSceneSupport } from '../iosSceneSupport';

jest.mock('resolve-from', () => {
  const actual = jest.requireActual('resolve-from');
  return Object.assign(jest.fn(actual), { silent: jest.fn(actual.silent) });
});

jest.mock('expo/config-plugins', () => {
  const plugins = jest.requireActual('expo/config-plugins');
  return {
    ...plugins,
    WarningAggregator: { addWarningIOS: jest.fn() },
    withAppDelegate: jest.fn().mockImplementation((config) => config),
    withInfoPlist: jest.fn().mockImplementation((config) => config),
  };
});

const WRAPPED_STARTUP = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
`;

const WINDOW_ASSIGNMENT = '    window = UIWindow(frame: UIScreen.main.bounds)';
const START_REACT_NATIVE = `    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)`;
const WINDOW_ASSIGNMENT_MARKER =
  '    // @generated by expo-build-properties: ios.enableSceneSupport window assignment';
const START_REACT_NATIVE_MARKER =
  '    // @generated by expo-build-properties: ios.enableSceneSupport React Native startup';

/** The published Expo SDK 57 bare template AppDelegate. */
const LEGACY_APP_DELEGATE = fs.readFileSync(
  path.join(__dirname, 'fixtures/sdk57-AppDelegate.swift'),
  'utf8'
);

/** An earlier SDK 57 template revision without the `#if os(iOS) || os(tvOS)` wrapper. */
const LEGACY_APP_DELEGATE_UNWRAPPED = LEGACY_APP_DELEGATE.replace(
  WRAPPED_STARTUP,
  WRAPPED_STARTUP.split('\n').slice(1, -2).join('\n') + '\n'
);

const SCENE_APP_DELEGATE = LEGACY_APP_DELEGATE.replace(
  'class AppDelegate: ExpoAppDelegate {',
  'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {'
)
  .replace(WINDOW_ASSIGNMENT, WINDOW_ASSIGNMENT_MARKER)
  .replace(START_REACT_NATIVE, START_REACT_NATIVE_MARKER);

const SCENE_MANIFEST = {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: 'EXExpoAppSceneDelegate',
      },
    ],
  },
};

const BASE_INFO_PLIST = { CFBundleDisplayName: 'HelloWorld' };

function makeConfig(sdkVersion?: string): ExpoConfig {
  return { name: 'HelloWorld', slug: 'hello-world', sdkVersion };
}

function runPlugin({
  appDelegate,
  enabled,
  infoPlist = BASE_INFO_PLIST,
  language = 'swift',
}: {
  appDelegate: string;
  enabled: boolean;
  infoPlist?: Record<string, unknown>;
  language?: string;
}) {
  const results: { appDelegate?: string; infoPlist?: Record<string, unknown> } = {};

  (withAppDelegate as jest.Mock).mockImplementation((config, action) => {
    const next = action({
      ...config,
      modResults: { path: 'ios/HelloWorld/AppDelegate.swift', language, contents: appDelegate },
    });
    results.appDelegate = next.modResults.contents;
    return next;
  });
  (withInfoPlist as jest.Mock).mockImplementation((config, action) => {
    const next = action({ ...config, modResults: { ...infoPlist } });
    results.infoPlist = next.modResults;
    return next;
  });

  withIosSceneSupport(makeConfig('57.0.23'), { ios: { enableSceneSupport: enabled } });
  return results;
}

describe(withIosSceneSupport, () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('does nothing when enableSceneSupport is not set', () => {
    const config = makeConfig('57.0.23');

    expect(withIosSceneSupport(config, {})).toBe(config);
    expect(withIosSceneSupport(config, { ios: {} })).toBe(config);

    expect(withAppDelegate).not.toHaveBeenCalled();
    expect(withInfoPlist).not.toHaveBeenCalled();
    expect(WarningAggregator.addWarningIOS).not.toHaveBeenCalled();
  });

  it('adopts the scene lifecycle in AppDelegate.swift and Info.plist on SDK 57', () => {
    const results = runPlugin({ appDelegate: LEGACY_APP_DELEGATE, enabled: true });

    expect(results.appDelegate).toBe(SCENE_APP_DELEGATE);
    expect(results.infoPlist).toEqual({
      ...BASE_INFO_PLIST,
      UIApplicationSceneManifest: SCENE_MANIFEST,
    });
  });

  it('adopts the scene lifecycle in an AppDelegate without the os() wrapper', () => {
    const enabled = runPlugin({ appDelegate: LEGACY_APP_DELEGATE_UNWRAPPED, enabled: true });
    const disabled = runPlugin({ appDelegate: enabled.appDelegate!, enabled: false });

    expect(disabled.appDelegate).toBe(LEGACY_APP_DELEGATE_UNWRAPPED);
  });

  it.each([
    [
      'before the window assignment',
      LEGACY_APP_DELEGATE.replace(
        WINDOW_ASSIGNMENT,
        `    FirebaseApp.configure()\n${WINDOW_ASSIGNMENT}`
      ),
    ],
    [
      'between window creation and React Native startup',
      LEGACY_APP_DELEGATE.replace(
        START_REACT_NATIVE,
        `    FirebaseApp.configure()\n${START_REACT_NATIVE}`
      ),
    ],
    [
      'after React Native startup',
      LEGACY_APP_DELEGATE.replace(
        `${START_REACT_NATIVE}\n#endif`,
        `${START_REACT_NATIVE}\n    FirebaseApp.configure()\n#endif`
      ),
    ],
  ])('preserves foreign code inserted %s and restores the exact original file', (_, original) => {
    const enabled = runPlugin({ appDelegate: original, enabled: true });

    expect(enabled.appDelegate).toContain('    FirebaseApp.configure()');
    expect(enabled.appDelegate).not.toContain(WINDOW_ASSIGNMENT);
    expect(enabled.appDelegate).not.toContain(START_REACT_NATIVE);

    const disabled = runPlugin({ appDelegate: enabled.appDelegate!, enabled: false });
    expect(disabled.appDelegate).toBe(original);
  });

  it('is idempotent when enabled or disabled repeatedly', () => {
    const firstEnable = runPlugin({ appDelegate: LEGACY_APP_DELEGATE, enabled: true });
    const secondEnable = runPlugin({ appDelegate: firstEnable.appDelegate!, enabled: true });
    expect(secondEnable.appDelegate).toBe(firstEnable.appDelegate);

    const firstDisable = runPlugin({ appDelegate: secondEnable.appDelegate!, enabled: false });
    const secondDisable = runPlugin({ appDelegate: firstDisable.appDelegate!, enabled: false });
    expect(firstDisable.appDelegate).toBe(LEGACY_APP_DELEGATE);
    expect(secondDisable.appDelegate).toBe(LEGACY_APP_DELEGATE);
  });

  it('migrates AppDelegate output generated by the original plugin to reversible markers', () => {
    const originalPluginOutput = LEGACY_APP_DELEGATE.replace(
      'class AppDelegate: ExpoAppDelegate {',
      'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {'
    ).replace(`\n${WRAPPED_STARTUP}`, '');

    const enabled = runPlugin({ appDelegate: originalPluginOutput, enabled: true });
    expect(enabled.appDelegate).toBe(SCENE_APP_DELEGATE);

    const disabled = runPlugin({ appDelegate: enabled.appDelegate!, enabled: false });
    expect(disabled.appDelegate).toBe(LEGACY_APP_DELEGATE);
  });

  it('directly disables AppDelegate output generated by the original plugin', () => {
    const originalPluginOutput = LEGACY_APP_DELEGATE.replace(
      'class AppDelegate: ExpoAppDelegate {',
      'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {'
    ).replace(`\n${WRAPPED_STARTUP}`, '');

    const disabled = runPlugin({ appDelegate: originalPluginOutput, enabled: false });
    expect(disabled.appDelegate).toBe(LEGACY_APP_DELEGATE);
  });

  it('keeps a scene manifest the app owns when set to false', () => {
    const results = runPlugin({
      appDelegate: LEGACY_APP_DELEGATE,
      enabled: false,
      infoPlist: {
        ...BASE_INFO_PLIST,
        UIApplicationSceneManifest: { UIApplicationSupportsMultipleScenes: true },
      },
    });

    expect(results.appDelegate).toBe(LEGACY_APP_DELEGATE);
    expect(results.infoPlist).toEqual({
      ...BASE_INFO_PLIST,
      UIApplicationSceneManifest: { UIApplicationSupportsMultipleScenes: true },
    });
  });

  it('throws when the app already declares its own scene manifest', () => {
    expect(() =>
      runPlugin({
        appDelegate: LEGACY_APP_DELEGATE,
        enabled: true,
        infoPlist: {
          ...BASE_INFO_PLIST,
          UIApplicationSceneManifest: { UIApplicationSupportsMultipleScenes: true },
        },
      })
    ).toThrow(/UIApplicationSceneManifest/);
  });

  it.each([
    ['a custom class declaration', LEGACY_APP_DELEGATE.replace('ExpoAppDelegate', 'UIResponder')],
    ['a missing window assignment', LEGACY_APP_DELEGATE.replace(`${WINDOW_ASSIGNMENT}\n`, '')],
    ['a missing startup call', LEGACY_APP_DELEGATE.replace(`${START_REACT_NATIVE}\n`, '')],
    [
      'executable code after the window assignment',
      LEGACY_APP_DELEGATE.replace(
        WINDOW_ASSIGNMENT,
        `${WINDOW_ASSIGNMENT}; FirebaseApp.configure()`
      ),
    ],
    [
      'a factory assignment with a longer identifier',
      LEGACY_APP_DELEGATE.replace(
        '    reactNativeFactory = factory',
        '    reactNativeFactory = factoryOther'
      ),
    ],
    [
      'an ambiguous window assignment',
      LEGACY_APP_DELEGATE.replace(WINDOW_ASSIGNMENT, `${WINDOW_ASSIGNMENT}\n${WINDOW_ASSIGNMENT}`),
    ],
    [
      'an ambiguous startup call',
      LEGACY_APP_DELEGATE.replace(
        START_REACT_NATIVE,
        `${START_REACT_NATIVE}\n${START_REACT_NATIVE}`
      ),
    ],
    [
      'an ambiguous factory assignment',
      LEGACY_APP_DELEGATE.replace(
        '    reactNativeFactory = factory',
        '    reactNativeFactory = factory\n    reactNativeFactory = factory'
      ),
    ],
  ])('rejects %s', (_, appDelegate) => {
    expect(() => runPlugin({ appDelegate, enabled: true })).toThrow(/Swift AppDelegate/);
  });

  it('rejects missing or ambiguous ownership markers when disabling', () => {
    expect(() =>
      runPlugin({
        appDelegate: SCENE_APP_DELEGATE.replace(`${WINDOW_ASSIGNMENT_MARKER}\n`, ''),
        enabled: false,
      })
    ).toThrow(/Swift AppDelegate/);
    expect(() =>
      runPlugin({
        appDelegate: SCENE_APP_DELEGATE.replace(
          WINDOW_ASSIGNMENT_MARKER,
          `${WINDOW_ASSIGNMENT_MARKER}\n${WINDOW_ASSIGNMENT_MARKER}`
        ),
        enabled: false,
      })
    ).toThrow(/Swift AppDelegate/);
  });

  it('throws when the AppDelegate is not Swift', () => {
    expect(() =>
      runPlugin({ appDelegate: '@implementation AppDelegate', enabled: true, language: 'objcpp' })
    ).toThrow(/Swift AppDelegate/);
  });

  it('throws on SDK 57 patches before the scene runtime backport', () => {
    expect(() =>
      withIosSceneSupport(makeConfig('57.0.22'), { ios: { enableSceneSupport: true } })
    ).toThrow(/57\.0\.23/);
    expect(() =>
      withIosSceneSupport(makeConfig(undefined), { ios: { enableSceneSupport: true } })
    ).toThrow(/57\.0\.23/);
    expect(withAppDelegate).not.toHaveBeenCalled();
  });

  it('reads the installed expo version from the project root', () => {
    (resolveFrom.silent as jest.Mock).mockReturnValueOnce(
      path.join(__dirname, 'fixtures/expo-57.0.23-package.json')
    );
    const results: { appDelegate?: string } = {};
    (withAppDelegate as jest.Mock).mockImplementation((config, action) => {
      const next = action({
        ...config,
        modResults: {
          path: 'ios/HelloWorld/AppDelegate.swift',
          language: 'swift',
          contents: LEGACY_APP_DELEGATE,
        },
      });
      results.appDelegate = next.modResults.contents;
      return next;
    });
    (withInfoPlist as jest.Mock).mockImplementation((config, action) =>
      action({ ...config, modResults: { ...BASE_INFO_PLIST } })
    );

    withIosSceneSupport(
      { ...makeConfig('57.0.0'), _internal: { projectRoot: '/app' } },
      { ios: { enableSceneSupport: true } }
    );

    expect(resolveFrom.silent).toHaveBeenCalledWith('/app', 'expo/package.json');
    expect(results.appDelegate).toBe(SCENE_APP_DELEGATE);
  });

  it('falls back to config.sdkVersion when expo cannot be resolved from the project root', () => {
    (resolveFrom.silent as jest.Mock).mockReturnValueOnce(undefined);

    expect(() =>
      withIosSceneSupport(
        { ...makeConfig('57.0.0'), _internal: { projectRoot: '/app' } },
        { ios: { enableSceneSupport: true } }
      )
    ).toThrow(/57\.0\.23/);
  });

  it('treats SDK 58 prereleases as having native scene support', () => {
    const config = makeConfig('58.0.0-preview.1');

    expect(withIosSceneSupport(config, { ios: { enableSceneSupport: true } })).toBe(config);

    expect(withAppDelegate).not.toHaveBeenCalled();
    expect(WarningAggregator.addWarningIOS).toHaveBeenCalledTimes(1);
  });

  it('warns and does nothing on SDK 58 and newer', () => {
    const config = makeConfig('58.0.0');

    expect(withIosSceneSupport(config, { ios: { enableSceneSupport: true } })).toBe(config);

    expect(withAppDelegate).not.toHaveBeenCalled();
    expect(withInfoPlist).not.toHaveBeenCalled();
    expect(WarningAggregator.addWarningIOS).toHaveBeenCalledWith(
      'ios.enableSceneSupport',
      expect.stringMatching(/no longer required.*can be removed/)
    );
  });
});
