package expo.modules.kotlin.types

import android.os.Bundle
import expo.modules.kotlin.records.Record
import expo.modules.kotlin.records.formatters.FormattedRecord
import io.github.lukmccall.pika.PIntrospectionData
import io.github.lukmccall.pika.introspectionOf
import io.github.lukmccall.pika.isIntrospectable
import kotlin.time.Duration

object ReturnTypeProvider {
  val types = mutableMapOf<Class<*>, ReturnType>()
}

inline fun <reified T> inheritFrom(klass: Class<*>): Boolean {
  return T::class.java.isAssignableFrom(klass)
}

fun getDirectConverter(klass: Class<*>): JSTypeConverter<*>? {
  // Kotlin thinks that Duration is represented as Long and Duration::class.java will return Long::class.java
  // which is already handled. However, it's not 100% true - the value is represented by the Long, but
  // ::class.java will return kotlin.time.Duration. It was verified in the generated bytecode.
  // This warning is likely a bug in the compiler.
  @Suppress("KotlinConstantConditions")
  return when (klass) {
    Unit::class.java -> JSTypeConverter.PassThroughConverter
    Bundle::class.java -> JSTypeConverter.BundleConverter
    IntArray::class.java -> JSTypeConverter.IntArrayConverter
    FloatArray::class.java -> JSTypeConverter.FloatArrayConverter
    DoubleArray::class.java -> JSTypeConverter.DoubleArrayConverter
    BooleanArray::class.java -> JSTypeConverter.BooleanArrayConverter
    ByteArray::class.java -> JSTypeConverter.ByteArrayConverter
    java.net.URI::class.java -> JSTypeConverter.URIConverter
    java.net.URL::class.java -> JSTypeConverter.URLConverter
    android.net.Uri::class.java -> JSTypeConverter.AndroidUriConverter
    java.io.File::class.java -> JSTypeConverter.FileConverter
    Pair::class.java -> JSTypeConverter.PairConverter
    Long::class.java -> JSTypeConverter.LongConverter
    Duration::class.java -> JSTypeConverter.DurationConverter
    Any::class.java -> JSTypeConverter.AnyConverter
    else -> null
  }
}

fun getIndirectConverter(klass: Class<*>, introspectableData: PIntrospectionData<*>?): JSTypeConverter<*> {
  return when {
    inheritFrom<Map<*, *>>(klass) -> JSTypeConverter.MapConverter
    inheritFrom<Enum<*>>(klass) -> JSTypeConverter.EnumConverter
    inheritFrom<Record>(klass) -> {
      if (introspectableData != null) {
        @Suppress("UNCHECKED_CAST")
        JSTypeConverter.IntrospectableRecordConverter(
          introspectableData as PIntrospectionData<Record>
        )
      } else {
        JSTypeConverter.RecordConverter
      }
    }

    inheritFrom<FormattedRecord<*>>(klass) -> JSTypeConverter.FormattedRecordConverter
    inheritFrom<expo.modules.kotlin.typedarray.RawTypedArrayHolder>(klass) -> JSTypeConverter.RawTypedArrayHolderConverter
    inheritFrom<Array<*>>(klass) -> JSTypeConverter.ArrayConverter
    inheritFrom<Collection<*>>(klass) -> JSTypeConverter.CollectionConverter
    else -> JSTypeConverter.PassThroughConverter
  }
}

inline fun <reified T> ReturnTypeProvider.get(): ReturnType {
  val klass = T::class.java
  val cachedType = types[klass]
  if (cachedType != null) {
    return cachedType
  }

  val converter: JSTypeConverter<*> = getDirectConverter(klass) ?: getIndirectConverter(
    klass,
    if (isIntrospectable<T>()) {
      introspectionOf<T>()
    } else {
      null
    }
  )

  return ReturnType(converter).also {
    types[T::class.java] = it
  }
}

inline fun <reified T> toReturnType(): ReturnType {
  return ReturnTypeProvider.get<T>()
}

class ReturnType(
  private val converter: JSTypeConverter<*>
) {
  fun convertToJS(value: Any?): Any? {
    return converter.convertToJS(value)
  }

  val cppType: expo.modules.kotlin.jni.ReturnType
    get() = converter.returnType
}
