package expo.modules.kotlin.types

import android.os.Bundle
import expo.modules.kotlin.records.formatters.FormattedRecord
import kotlin.time.Duration

object ReturnTypeProvider {
  val types = mutableMapOf<Class<*>, ReturnType>()
}

inline fun <reified T> ReturnTypeProvider.get(): ReturnType {
  return types[T::class.java] ?: ReturnType(T::class.java).also {
    types[T::class.java] = it
  }
}

inline fun <reified T> toReturnType(): ReturnType {
  return ReturnTypeProvider.get<T>()
}

class ReturnType(
  private val klass: Class<*>
) {

  private val converter: JSTypeConverter<*> = run {
    // Kotlin thinks that Duration is represented as Long and Duration::class.java will return Long::class.java
    // which is already handled. However, it's not 100% true - the value is represented by the Long, but
    // ::class.java will return kotlin.time.Duration. It was verified in the generated bytecode.
    // This warning is likely a bug in the compiler.
    @Suppress("KotlinConstantConditions")
    val directConverter = when (klass) {
      Unit::class.java -> JSTypeConverter.PassThroughConverter()
      Bundle::class.java -> JSTypeConverter.BundleConverter()
      IntArray::class.java -> JSTypeConverter.IntArrayConverter()
      FloatArray::class.java -> JSTypeConverter.FloatArrayConverter()
      DoubleArray::class.java -> JSTypeConverter.DoubleArrayConverter()
      BooleanArray::class.java -> JSTypeConverter.BooleanArrayConverter()
      ByteArray::class.java -> JSTypeConverter.ByteArrayConverter()
      java.net.URI::class.java -> JSTypeConverter.URIConverter()
      java.net.URL::class.java -> JSTypeConverter.URLConverter()
      android.net.Uri::class.java -> JSTypeConverter.AndroidUriConverter()
      java.io.File::class.java -> JSTypeConverter.FileConverter()
      Pair::class.java -> JSTypeConverter.PairConverter()
      Long::class.java -> JSTypeConverter.LongConverter()
      Duration::class.java -> JSTypeConverter.DurationConverter()
      Any::class.java -> JSTypeConverter.AnyConverter()
      else -> null
    }

    directConverter ?: when {
      inheritFrom<Map<*, *>>() -> JSTypeConverter.MapConverter()
      inheritFrom<Enum<*>>() -> JSTypeConverter.EnumConverter()
      inheritFrom<expo.modules.kotlin.records.Record>() -> JSTypeConverter.RecordConverter()
      inheritFrom<FormattedRecord<*>>() -> JSTypeConverter.FormattedRecordConverter()
      inheritFrom<expo.modules.kotlin.typedarray.RawTypedArrayHolder>() -> JSTypeConverter.RawTypedArrayHolderConverter()
      inheritFrom<Array<*>>() -> JSTypeConverter.ArrayConverter()
      inheritFrom<Collection<*>>() -> JSTypeConverter.CollectionConverter()
      else -> JSTypeConverter.PassThroughConverter()
    }
  }

  fun convertToJS(value: Any?): Any? {
    return converter.convertToJS(value)
  }

  val cppType: expo.modules.kotlin.jni.ReturnType
    get() = converter.returnType

  internal inline fun <reified T> inheritFrom(): Boolean {
    return T::class.java.isAssignableFrom(klass)
  }
}
