/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type ImagePickerOptions = any;

export type Void = any;

export async function getCameraPermissionsAsync(): Promise<any> {}

export async function getMediaLibraryPermissionsAsync(writeOnly: boolean): Promise<any> {}

export async function requestCameraPermissionsAsync(): Promise<any> {}

export async function requestMediaLibraryPermissionsAsync(writeOnly: boolean): Promise<any> {}

export async function launchCameraAsync(options: ImagePickerOptions): Promise<Void> {
  return null; // TODO: Replace with mock for value of type Void.
}

export async function launchImageLibraryAsync(options: ImagePickerOptions): Promise<any> {}
