/**
 * This code was generated by [ABI49_0_0React-native-codegen](https://www.npmjs.com/package/ABI49_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif
#import <Foundation/Foundation.h>
#import <ABI49_0_0RCTRequired/ABI49_0_0RCTRequired.h>
#import <ABI49_0_0RCTTypeSafety/ABI49_0_0RCTConvertHelpers.h>
#import <ABI49_0_0RCTTypeSafety/ABI49_0_0RCTTypedModuleConstants.h>
#import <ABI49_0_0React/ABI49_0_0RCTBridgeModule.h>
#import <ABI49_0_0React/ABI49_0_0RCTCxxConvert.h>
#import <ABI49_0_0React/ABI49_0_0RCTManagedPointer.h>
#import <ABI49_0_0ReactCommon/ABI49_0_0RCTTurboModule.h>
#import <optional>
#import <vector>


@protocol ABI49_0_0NativeAccessibilityInfoSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)isReduceMotionEnabled:(ABI49_0_0RCTResponseSenderBlock)onSuccess;
- (void)isTouchExplorationEnabled:(ABI49_0_0RCTResponseSenderBlock)onSuccess;
- (void)isAccessibilityServiceEnabled:(ABI49_0_0RCTResponseSenderBlock)onSuccess;
- (void)setAccessibilityFocus:(double)ABI49_0_0ReactTag;
- (void)announceForAccessibility:(NSString *)announcement;
- (void)getRecommendedTimeoutMillis:(double)mSec
                          onSuccess:(ABI49_0_0RCTResponseSenderBlock)onSuccess;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAccessibilityInfo'
     */
    class JSI_EXPORT NativeAccessibilityInfoSpecJSI : public ObjCTurboModule {
    public:
      NativeAccessibilityInfoSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeAccessibilityManager {
    struct SpecSetAccessibilityContentSizeMultipliersJSMultipliers {
      std::optional<double> extraSmall() const;
      std::optional<double> small() const;
      std::optional<double> medium() const;
      std::optional<double> large() const;
      std::optional<double> extraLarge() const;
      std::optional<double> extraExtraLarge() const;
      std::optional<double> extraExtraExtraLarge() const;
      std::optional<double> accessibilityMedium() const;
      std::optional<double> accessibilityLarge() const;
      std::optional<double> accessibilityExtraLarge() const;
      std::optional<double> accessibilityExtraExtraLarge() const;
      std::optional<double> accessibilityExtraExtraExtraLarge() const;

      SpecSetAccessibilityContentSizeMultipliersJSMultipliers(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeAccessibilityManager_SpecSetAccessibilityContentSizeMultipliersJSMultipliers)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeAccessibilityManager_SpecSetAccessibilityContentSizeMultipliersJSMultipliers:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativeAccessibilityManager {
    struct SpecAnnounceForAccessibilityWithOptionsOptions {
      std::optional<bool> queue() const;

      SpecAnnounceForAccessibilityWithOptionsOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeAccessibilityManager_SpecAnnounceForAccessibilityWithOptionsOptions)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeAccessibilityManager_SpecAnnounceForAccessibilityWithOptionsOptions:(id)json;
@end
@protocol ABI49_0_0NativeAccessibilityManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getCurrentBoldTextState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                        onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)getCurrentGrayscaleState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                         onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)getCurrentInvertColorsState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                            onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)getCurrentReduceMotionState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                            onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)getCurrentPrefersCrossFadeTransitionsState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                                           onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)getCurrentReduceTransparencyState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                                  onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)getCurrentVoiceOverState:(ABI49_0_0RCTResponseSenderBlock)onSuccess
                         onError:(ABI49_0_0RCTResponseSenderBlock)onError;
- (void)setAccessibilityContentSizeMultipliers:(ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers &)JSMultipliers;
- (void)setAccessibilityFocus:(double)ABI49_0_0ReactTag;
- (void)announceForAccessibility:(NSString *)announcement;
- (void)announceForAccessibilityWithOptions:(NSString *)announcement
                                    options:(ABI49_0_0JS::NativeAccessibilityManager::SpecAnnounceForAccessibilityWithOptionsOptions &)options;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAccessibilityManager'
     */
    class JSI_EXPORT NativeAccessibilityManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeAccessibilityManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeActionSheetManager {
    struct SpecShowActionSheetWithOptionsOptions {
      NSString *title() const;
      NSString *message() const;
      std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *>> options() const;
      std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<double>> destructiveButtonIndices() const;
      std::optional<double> cancelButtonIndex() const;
      std::optional<double> anchor() const;
      std::optional<double> tintColor() const;
      std::optional<double> cancelButtonTintColor() const;
      NSString *userInterfaceStyle() const;
      std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<double>> disabledButtonIndices() const;

      SpecShowActionSheetWithOptionsOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeActionSheetManager_SpecShowActionSheetWithOptionsOptions)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeActionSheetManager_SpecShowActionSheetWithOptionsOptions:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativeActionSheetManager {
    struct SpecShowShareActionSheetWithOptionsOptions {
      NSString *message() const;
      NSString *url() const;
      NSString *subject() const;
      std::optional<double> anchor() const;
      std::optional<double> tintColor() const;
      std::optional<double> cancelButtonTintColor() const;
      std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *>> excludedActivityTypes() const;
      NSString *userInterfaceStyle() const;

      SpecShowShareActionSheetWithOptionsOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeActionSheetManager_SpecShowShareActionSheetWithOptionsOptions)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeActionSheetManager_SpecShowShareActionSheetWithOptionsOptions:(id)json;
@end
@protocol ABI49_0_0NativeActionSheetManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)showActionSheetWithOptions:(ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions &)options
                          callback:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)showShareActionSheetWithOptions:(ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions &)options
                        failureCallback:(ABI49_0_0RCTResponseSenderBlock)failureCallback
                        successCallback:(ABI49_0_0RCTResponseSenderBlock)successCallback;
- (void)dismissActionSheet;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeActionSheetManager'
     */
    class JSI_EXPORT NativeActionSheetManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeActionSheetManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeAlertManager {
    struct Args {
      NSString *title() const;
      NSString *message() const;
      std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<id<NSObject> >> buttons() const;
      NSString *type() const;
      NSString *defaultValue() const;
      NSString *cancelButtonKey() const;
      NSString *destructiveButtonKey() const;
      NSString *preferredButtonKey() const;
      NSString *keyboardType() const;
      NSString *userInterfaceStyle() const;

      Args(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeAlertManager_Args)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeAlertManager_Args:(id)json;
@end
@protocol ABI49_0_0NativeAlertManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)alertWithArgs:(ABI49_0_0JS::NativeAlertManager::Args &)args
             callback:(ABI49_0_0RCTResponseSenderBlock)callback;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAlertManager'
     */
    class JSI_EXPORT NativeAlertManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeAlertManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeAnimatedModule {
    struct EventMapping {
      ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *> nativeEventPath() const;
      std::optional<double> animatedValueTag() const;

      EventMapping(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeAnimatedModule_EventMapping)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeAnimatedModule_EventMapping:(id)json;
@end
@protocol ABI49_0_0NativeAnimatedModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)startOperationBatch;
- (void)finishOperationBatch;
- (void)createAnimatedNode:(double)tag
                    config:(NSDictionary *)config;
- (void)updateAnimatedNodeConfig:(double)tag
                          config:(NSDictionary *)config;
- (void)getValue:(double)tag
saveValueCallback:(ABI49_0_0RCTResponseSenderBlock)saveValueCallback;
- (void)startListeningToAnimatedNodeValue:(double)tag;
- (void)stopListeningToAnimatedNodeValue:(double)tag;
- (void)connectAnimatedNodes:(double)parentTag
                    childTag:(double)childTag;
- (void)disconnectAnimatedNodes:(double)parentTag
                       childTag:(double)childTag;
- (void)startAnimatingNode:(double)animationId
                   nodeTag:(double)nodeTag
                    config:(NSDictionary *)config
               endCallback:(ABI49_0_0RCTResponseSenderBlock)endCallback;
- (void)stopAnimation:(double)animationId;
- (void)setAnimatedNodeValue:(double)nodeTag
                       value:(double)value;
- (void)setAnimatedNodeOffset:(double)nodeTag
                       offset:(double)offset;
- (void)flattenAnimatedNodeOffset:(double)nodeTag;
- (void)extractAnimatedNodeOffset:(double)nodeTag;
- (void)connectAnimatedNodeToView:(double)nodeTag
                          viewTag:(double)viewTag;
- (void)disconnectAnimatedNodeFromView:(double)nodeTag
                               viewTag:(double)viewTag;
- (void)restoreDefaultValues:(double)nodeTag;
- (void)dropAnimatedNode:(double)tag;
- (void)addAnimatedEventToView:(double)viewTag
                     eventName:(NSString *)eventName
                  eventMapping:(ABI49_0_0JS::NativeAnimatedModule::EventMapping &)eventMapping;
- (void)removeAnimatedEventFromView:(double)viewTag
                          eventName:(NSString *)eventName
                    animatedNodeTag:(double)animatedNodeTag;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;
- (void)queueAndExecuteBatchedOperations:(NSArray *)operationsAndArgs;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAnimatedModule'
     */
    class JSI_EXPORT NativeAnimatedModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeAnimatedModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeAnimatedTurboModule {
    struct EventMapping {
      ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *> nativeEventPath() const;
      std::optional<double> animatedValueTag() const;

      EventMapping(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeAnimatedTurboModule_EventMapping)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeAnimatedTurboModule_EventMapping:(id)json;
@end
@protocol ABI49_0_0NativeAnimatedTurboModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)startOperationBatch;
- (void)finishOperationBatch;
- (void)createAnimatedNode:(double)tag
                    config:(NSDictionary *)config;
- (void)updateAnimatedNodeConfig:(double)tag
                          config:(NSDictionary *)config;
- (void)getValue:(double)tag
saveValueCallback:(ABI49_0_0RCTResponseSenderBlock)saveValueCallback;
- (void)startListeningToAnimatedNodeValue:(double)tag;
- (void)stopListeningToAnimatedNodeValue:(double)tag;
- (void)connectAnimatedNodes:(double)parentTag
                    childTag:(double)childTag;
- (void)disconnectAnimatedNodes:(double)parentTag
                       childTag:(double)childTag;
- (void)startAnimatingNode:(double)animationId
                   nodeTag:(double)nodeTag
                    config:(NSDictionary *)config
               endCallback:(ABI49_0_0RCTResponseSenderBlock)endCallback;
- (void)stopAnimation:(double)animationId;
- (void)setAnimatedNodeValue:(double)nodeTag
                       value:(double)value;
- (void)setAnimatedNodeOffset:(double)nodeTag
                       offset:(double)offset;
- (void)flattenAnimatedNodeOffset:(double)nodeTag;
- (void)extractAnimatedNodeOffset:(double)nodeTag;
- (void)connectAnimatedNodeToView:(double)nodeTag
                          viewTag:(double)viewTag;
- (void)disconnectAnimatedNodeFromView:(double)nodeTag
                               viewTag:(double)viewTag;
- (void)restoreDefaultValues:(double)nodeTag;
- (void)dropAnimatedNode:(double)tag;
- (void)addAnimatedEventToView:(double)viewTag
                     eventName:(NSString *)eventName
                  eventMapping:(ABI49_0_0JS::NativeAnimatedTurboModule::EventMapping &)eventMapping;
- (void)removeAnimatedEventFromView:(double)viewTag
                          eventName:(NSString *)eventName
                    animatedNodeTag:(double)animatedNodeTag;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;
- (void)queueAndExecuteBatchedOperations:(NSArray *)operationsAndArgs;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAnimatedTurboModule'
     */
    class JSI_EXPORT NativeAnimatedTurboModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeAnimatedTurboModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeAnimationsDebugModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)startRecordingFps;
- (void)stopRecordingFps:(double)animationStopTimeMs;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAnimationsDebugModule'
     */
    class JSI_EXPORT NativeAnimationsDebugModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeAnimationsDebugModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeAppState {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<NSString *> initialAppState;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeAppStateSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getCurrentAppState:(ABI49_0_0RCTResponseSenderBlock)success
                     error:(ABI49_0_0RCTResponseSenderBlock)error;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeAppState::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeAppState::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAppState'
     */
    class JSI_EXPORT NativeAppStateSpecJSI : public ObjCTurboModule {
    public:
      NativeAppStateSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeAppearanceSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (NSString * _Nullable)getColorScheme;
- (void)setColorScheme:(NSString *)colorScheme;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeAppearance'
     */
    class JSI_EXPORT NativeAppearanceSpecJSI : public ObjCTurboModule {
    public:
      NativeAppearanceSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeBlobModule {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<NSString *> BLOB_URI_SCHEME;
          ABI49_0_0RCTRequired<NSString *> BLOB_URI_HOST;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeBlobModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)addNetworkingHandler;
- (void)addWebSocketHandler:(double)id;
- (void)removeWebSocketHandler:(double)id;
- (void)sendOverSocket:(NSDictionary *)blob
              socketID:(double)socketID;
- (void)createFromParts:(NSArray *)parts
                 withId:(NSString *)withId;
- (void)release:(NSString *)blobId;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeBlobModule::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeBlobModule::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeBlobModule'
     */
    class JSI_EXPORT NativeBlobModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeBlobModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeBugReportingSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)startReportAProblemFlow;
- (void)setExtraData:(NSDictionary *)extraData
          extraFiles:(NSDictionary *)extraFiles;
- (void)setCategoryID:(NSString *)categoryID;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeBugReporting'
     */
    class JSI_EXPORT NativeBugReportingSpecJSI : public ObjCTurboModule {
    public:
      NativeBugReportingSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeClipboardSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getString:(ABI49_0_0RCTPromiseResolveBlock)resolve
           reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)setString:(NSString *)content;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeClipboard'
     */
    class JSI_EXPORT NativeClipboardSpecJSI : public ObjCTurboModule {
    public:
      NativeClipboardSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeDevLoadingViewSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)showMessage:(NSString *)message
          withColor:(NSNumber *)withColor
withBackgroundColor:(NSNumber *)withBackgroundColor;
- (void)hide;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDevLoadingView'
     */
    class JSI_EXPORT NativeDevLoadingViewSpecJSI : public ObjCTurboModule {
    public:
      NativeDevLoadingViewSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeDevMenuSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)show;
- (void)reload;
- (void)debugRemotely:(BOOL)enableDebug;
- (void)setProfilingEnabled:(BOOL)enabled;
- (void)setHotLoadingEnabled:(BOOL)enabled;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDevMenu'
     */
    class JSI_EXPORT NativeDevMenuSpecJSI : public ObjCTurboModule {
    public:
      NativeDevMenuSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeDevSettingsSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)reload;
- (void)reloadWithReason:(NSString *)reason;
- (void)onFastRefresh;
- (void)setHotLoadingEnabled:(BOOL)isHotLoadingEnabled;
- (void)setIsDebuggingRemotely:(BOOL)isDebuggingRemotelyEnabled;
- (void)setProfilingEnabled:(BOOL)isProfilingEnabled;
- (void)toggleElementInspector;
- (void)addMenuItem:(NSString *)title;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;
- (void)setIsShakeToShowDevMenuEnabled:(BOOL)enabled;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDevSettings'
     */
    class JSI_EXPORT NativeDevSettingsSpecJSI : public ObjCTurboModule {
    public:
      NativeDevSettingsSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeDevSplitBundleLoaderSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)loadBundle:(NSString *)bundlePath
           resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
            reject:(ABI49_0_0RCTPromiseRejectBlock)reject;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDevSplitBundleLoader'
     */
    class JSI_EXPORT NativeDevSplitBundleLoaderSpecJSI : public ObjCTurboModule {
    public:
      NativeDevSplitBundleLoaderSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeDevToolsSettingsManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)setConsolePatchSettings:(NSString *)newConsolePatchSettings;
- (NSString * _Nullable)getConsolePatchSettings;
- (void)setProfilingSettings:(NSString *)newProfilingSettings;
- (NSString * _Nullable)getProfilingSettings;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDevToolsSettingsManager'
     */
    class JSI_EXPORT NativeDevToolsSettingsManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeDevToolsSettingsManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeDeviceEventManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)invokeDefaultBackPressHandler;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDeviceEventManager'
     */
    class JSI_EXPORT NativeDeviceEventManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeDeviceEventManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeDeviceInfo {
    struct DisplayMetrics {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<double> width;
          ABI49_0_0RCTRequired<double> height;
          ABI49_0_0RCTRequired<double> scale;
          ABI49_0_0RCTRequired<double> fontScale;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing DisplayMetrics */
        Builder(DisplayMetrics i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static DisplayMetrics fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      DisplayMetrics(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
namespace ABI49_0_0JS {
  namespace NativeDeviceInfo {
    struct DisplayMetricsAndroid {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<double> width;
          ABI49_0_0RCTRequired<double> height;
          ABI49_0_0RCTRequired<double> scale;
          ABI49_0_0RCTRequired<double> fontScale;
          ABI49_0_0RCTRequired<double> densityDpi;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing DisplayMetricsAndroid */
        Builder(DisplayMetricsAndroid i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static DisplayMetricsAndroid fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      DisplayMetricsAndroid(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
namespace ABI49_0_0JS {
  namespace NativeDeviceInfo {
    struct DimensionsPayload {

      struct Builder {
        struct Input {
          std::optional<ABI49_0_0JS::NativeDeviceInfo::DisplayMetrics::Builder> window;
          std::optional<ABI49_0_0JS::NativeDeviceInfo::DisplayMetrics::Builder> screen;
          std::optional<ABI49_0_0JS::NativeDeviceInfo::DisplayMetricsAndroid::Builder> windowPhysicalPixels;
          std::optional<ABI49_0_0JS::NativeDeviceInfo::DisplayMetricsAndroid::Builder> screenPhysicalPixels;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing DimensionsPayload */
        Builder(DimensionsPayload i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static DimensionsPayload fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      DimensionsPayload(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
namespace ABI49_0_0JS {
  namespace NativeDeviceInfo {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<ABI49_0_0JS::NativeDeviceInfo::DimensionsPayload::Builder> Dimensions;
          std::optional<bool> isIPhoneX_deprecated;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeDeviceInfoSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeDeviceInfo::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeDeviceInfo::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeDeviceInfo'
     */
    class JSI_EXPORT NativeDeviceInfoSpecJSI : public ObjCTurboModule {
    public:
      NativeDeviceInfoSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeExceptionsManager {
    struct StackFrame {
      std::optional<double> column() const;
      NSString *file() const;
      std::optional<double> lineNumber() const;
      NSString *methodName() const;
      std::optional<bool> collapse() const;

      StackFrame(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeExceptionsManager_StackFrame)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeExceptionsManager_StackFrame:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativeExceptionsManager {
    struct ExceptionData {
      NSString *message() const;
      NSString *originalMessage() const;
      NSString *name() const;
      NSString *componentStack() const;
      ABI49_0_0facebook::ABI49_0_0React::LazyVector<ABI49_0_0JS::NativeExceptionsManager::StackFrame> stack() const;
      double id_() const;
      bool isFatal() const;
      id<NSObject> _Nullable extraData() const;

      ExceptionData(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeExceptionsManager_ExceptionData)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeExceptionsManager_ExceptionData:(id)json;
@end
@protocol ABI49_0_0NativeExceptionsManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)reportFatalException:(NSString *)message
                       stack:(NSArray *)stack
                 exceptionId:(double)exceptionId;
- (void)reportSoftException:(NSString *)message
                      stack:(NSArray *)stack
                exceptionId:(double)exceptionId;
- (void)reportException:(ABI49_0_0JS::NativeExceptionsManager::ExceptionData &)data;
- (void)updateExceptionMessage:(NSString *)message
                         stack:(NSArray *)stack
                   exceptionId:(double)exceptionId;
- (void)dismissRedbox;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeExceptionsManager'
     */
    class JSI_EXPORT NativeExceptionsManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeExceptionsManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeFileReaderModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)readAsDataURL:(NSDictionary *)data
              resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
               reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)readAsText:(NSDictionary *)data
          encoding:(NSString *)encoding
           resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
            reject:(ABI49_0_0RCTPromiseRejectBlock)reject;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeFileReaderModule'
     */
    class JSI_EXPORT NativeFileReaderModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeFileReaderModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeFrameRateLogger {
    struct SpecSetGlobalOptionsOptions {
      std::optional<bool> debug() const;
      std::optional<bool> reportStackTraces() const;

      SpecSetGlobalOptionsOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeFrameRateLogger_SpecSetGlobalOptionsOptions)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeFrameRateLogger_SpecSetGlobalOptionsOptions:(id)json;
@end
@protocol ABI49_0_0NativeFrameRateLoggerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)setGlobalOptions:(ABI49_0_0JS::NativeFrameRateLogger::SpecSetGlobalOptionsOptions &)options;
- (void)setContext:(NSString *)context;
- (void)beginScroll;
- (void)endScroll;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeFrameRateLogger'
     */
    class JSI_EXPORT NativeFrameRateLoggerSpecJSI : public ObjCTurboModule {
    public:
      NativeFrameRateLoggerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeHeadlessJsTaskSupportSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)notifyTaskFinished:(double)taskId;
- (void)notifyTaskRetry:(double)taskId
                resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
                 reject:(ABI49_0_0RCTPromiseRejectBlock)reject;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeHeadlessJsTaskSupport'
     */
    class JSI_EXPORT NativeHeadlessJsTaskSupportSpecJSI : public ObjCTurboModule {
    public:
      NativeHeadlessJsTaskSupportSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeI18nManager {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<bool> isRTL;
          ABI49_0_0RCTRequired<bool> doLeftAndRightSwapInRTL;
          ABI49_0_0RCTRequired<NSString *> localeIdentifier;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeI18nManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)allowRTL:(BOOL)allowRTL;
- (void)forceRTL:(BOOL)forceRTL;
- (void)swapLeftAndRightInRTL:(BOOL)flipStyles;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeI18nManager::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeI18nManager::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeI18nManager'
     */
    class JSI_EXPORT NativeI18nManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeI18nManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeImageEditor {
    struct OptionsOffset {
      double x() const;
      double y() const;

      OptionsOffset(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeImageEditor_OptionsOffset)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeImageEditor_OptionsOffset:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativeImageEditor {
    struct OptionsSize {
      double width() const;
      double height() const;

      OptionsSize(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeImageEditor_OptionsSize)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeImageEditor_OptionsSize:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativeImageEditor {
    struct OptionsDisplaySize {
      double width() const;
      double height() const;

      OptionsDisplaySize(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeImageEditor_OptionsDisplaySize)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeImageEditor_OptionsDisplaySize:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativeImageEditor {
    struct Options {
      ABI49_0_0JS::NativeImageEditor::OptionsOffset offset() const;
      ABI49_0_0JS::NativeImageEditor::OptionsSize size() const;
      std::optional<ABI49_0_0JS::NativeImageEditor::OptionsDisplaySize> displaySize() const;
      NSString *resizeMode() const;
      std::optional<bool> allowExternalStorage() const;

      Options(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeImageEditor_Options)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeImageEditor_Options:(id)json;
@end
@protocol ABI49_0_0NativeImageEditorSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)cropImage:(NSString *)uri
         cropData:(ABI49_0_0JS::NativeImageEditor::Options &)cropData
  successCallback:(ABI49_0_0RCTResponseSenderBlock)successCallback
    errorCallback:(ABI49_0_0RCTResponseSenderBlock)errorCallback;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeImageEditor'
     */
    class JSI_EXPORT NativeImageEditorSpecJSI : public ObjCTurboModule {
    public:
      NativeImageEditorSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeImageLoaderIOSSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getSize:(NSString *)uri
        resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
         reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)getSizeWithHeaders:(NSString *)uri
                   headers:(NSDictionary *)headers
                   resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
                    reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)prefetchImage:(NSString *)uri
              resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
               reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)prefetchImageWithMetadata:(NSString *)uri
                    queryRootName:(NSString *)queryRootName
                          rootTag:(double)rootTag
                          resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
                           reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)queryCache:(NSArray *)uris
           resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
            reject:(ABI49_0_0RCTPromiseRejectBlock)reject;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeImageLoaderIOS'
     */
    class JSI_EXPORT NativeImageLoaderIOSSpecJSI : public ObjCTurboModule {
    public:
      NativeImageLoaderIOSSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeImageStoreIOSSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getBase64ForTag:(NSString *)uri
        successCallback:(ABI49_0_0RCTResponseSenderBlock)successCallback
          errorCallback:(ABI49_0_0RCTResponseSenderBlock)errorCallback;
- (void)hasImageForTag:(NSString *)uri
              callback:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)removeImageForTag:(NSString *)uri;
- (void)addImageFromBase64:(NSString *)base64ImageData
           successCallback:(ABI49_0_0RCTResponseSenderBlock)successCallback
             errorCallback:(ABI49_0_0RCTResponseSenderBlock)errorCallback;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeImageStoreIOS'
     */
    class JSI_EXPORT NativeImageStoreIOSSpecJSI : public ObjCTurboModule {
    public:
      NativeImageStoreIOSSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeJSCHeapCaptureSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)captureComplete:(NSString *)path
                  error:(NSString * _Nullable)error;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeJSCHeapCapture'
     */
    class JSI_EXPORT NativeJSCHeapCaptureSpecJSI : public ObjCTurboModule {
    public:
      NativeJSCHeapCaptureSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeJSCSamplingProfilerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)operationComplete:(double)token
                   result:(NSString * _Nullable)result
                    error:(NSString * _Nullable)error;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeJSCSamplingProfiler'
     */
    class JSI_EXPORT NativeJSCSamplingProfilerSpecJSI : public ObjCTurboModule {
    public:
      NativeJSCSamplingProfilerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeKeyboardObserverSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeKeyboardObserver'
     */
    class JSI_EXPORT NativeKeyboardObserverSpecJSI : public ObjCTurboModule {
    public:
      NativeKeyboardObserverSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeLinkingManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getInitialURL:(ABI49_0_0RCTPromiseResolveBlock)resolve
               reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)canOpenURL:(NSString *)url
           resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
            reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)openURL:(NSString *)url
        resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
         reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)openSettings:(ABI49_0_0RCTPromiseResolveBlock)resolve
              reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeLinkingManager'
     */
    class JSI_EXPORT NativeLinkingManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeLinkingManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeLogBoxSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)show;
- (void)hide;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeLogBox'
     */
    class JSI_EXPORT NativeLogBoxSpecJSI : public ObjCTurboModule {
    public:
      NativeLogBoxSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeModalManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeModalManager'
     */
    class JSI_EXPORT NativeModalManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeModalManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeNetworkingIOS {
    struct SpecSendRequestQuery {
      NSString *method() const;
      NSString *url() const;
      id<NSObject>  data() const;
      id<NSObject>  headers() const;
      NSString *responseType() const;
      bool incrementalUpdates() const;
      double timeout() const;
      bool withCredentials() const;

      SpecSendRequestQuery(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeNetworkingIOS_SpecSendRequestQuery)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeNetworkingIOS_SpecSendRequestQuery:(id)json;
@end
@protocol ABI49_0_0NativeNetworkingIOSSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)sendRequest:(ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery &)query
           callback:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)abortRequest:(double)requestId;
- (void)clearCookies:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeNetworkingIOS'
     */
    class JSI_EXPORT NativeNetworkingIOSSpecJSI : public ObjCTurboModule {
    public:
      NativeNetworkingIOSSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativePlatformConstantsIOS {
    struct ConstantsreactNativeVersion {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<double> major;
          ABI49_0_0RCTRequired<double> minor;
          ABI49_0_0RCTRequired<double> patch;
          ABI49_0_0RCTRequired<std::optional<double>> prerelease;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing ConstantsreactNativeVersion */
        Builder(ConstantsreactNativeVersion i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static ConstantsreactNativeVersion fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      ConstantsreactNativeVersion(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
namespace ABI49_0_0JS {
  namespace NativePlatformConstantsIOS {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<bool> isTesting;
          ABI49_0_0RCTRequired<ABI49_0_0JS::NativePlatformConstantsIOS::ConstantsreactNativeVersion::Builder> reactNativeVersion;
          ABI49_0_0RCTRequired<bool> forceTouchAvailable;
          ABI49_0_0RCTRequired<NSString *> osVersion;
          ABI49_0_0RCTRequired<NSString *> systemName;
          ABI49_0_0RCTRequired<NSString *> interfaceIdiom;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativePlatformConstantsIOSSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativePlatformConstantsIOS::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativePlatformConstantsIOS::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativePlatformConstantsIOS'
     */
    class JSI_EXPORT NativePlatformConstantsIOSSpecJSI : public ObjCTurboModule {
    public:
      NativePlatformConstantsIOSSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativePushNotificationManagerIOS {
    struct SpecRequestPermissionsPermission {
      bool alert() const;
      bool badge() const;
      bool sound() const;

      SpecRequestPermissionsPermission(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativePushNotificationManagerIOS_SpecRequestPermissionsPermission)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativePushNotificationManagerIOS_SpecRequestPermissionsPermission:(id)json;
@end
namespace ABI49_0_0JS {
  namespace NativePushNotificationManagerIOS {
    struct Notification {
      NSString *alertTitle() const;
      std::optional<double> fireDate() const;
      NSString *alertBody() const;
      NSString *alertAction() const;
      id<NSObject> _Nullable userInfo() const;
      NSString *category() const;
      NSString *repeatInterval() const;
      std::optional<double> applicationIconBadgeNumber() const;
      std::optional<bool> isSilent() const;
      NSString *soundName() const;

      Notification(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativePushNotificationManagerIOS_Notification)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativePushNotificationManagerIOS_Notification:(id)json;
@end
@protocol ABI49_0_0NativePushNotificationManagerIOSSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)onFinishRemoteNotification:(NSString *)notificationId
                       fetchResult:(NSString *)fetchResult;
- (void)setApplicationIconBadgeNumber:(double)num;
- (void)getApplicationIconBadgeNumber:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)requestPermissions:(ABI49_0_0JS::NativePushNotificationManagerIOS::SpecRequestPermissionsPermission &)permission
                   resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
                    reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)abandonPermissions;
- (void)checkPermissions:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)presentLocalNotification:(ABI49_0_0JS::NativePushNotificationManagerIOS::Notification &)notification;
- (void)scheduleLocalNotification:(ABI49_0_0JS::NativePushNotificationManagerIOS::Notification &)notification;
- (void)cancelAllLocalNotifications;
- (void)cancelLocalNotifications:(NSDictionary *)userInfo;
- (void)getInitialNotification:(ABI49_0_0RCTPromiseResolveBlock)resolve
                        reject:(ABI49_0_0RCTPromiseRejectBlock)reject;
- (void)getScheduledLocalNotifications:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)removeAllDeliveredNotifications;
- (void)removeDeliveredNotifications:(NSArray *)identifiers;
- (void)getDeliveredNotifications:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)getAuthorizationStatus:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)addListener:(NSString *)eventType;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativePushNotificationManagerIOS'
     */
    class JSI_EXPORT NativePushNotificationManagerIOSSpecJSI : public ObjCTurboModule {
    public:
      NativePushNotificationManagerIOSSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeRedBoxSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)setExtraData:(NSDictionary *)extraData
       forIdentifier:(NSString *)forIdentifier;
- (void)dismiss;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeRedBox'
     */
    class JSI_EXPORT NativeRedBoxSpecJSI : public ObjCTurboModule {
    public:
      NativeRedBoxSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeSegmentFetcherSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)fetchSegment:(double)segmentId
             options:(NSDictionary *)options
            callback:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)getSegment:(double)segmentId
           options:(NSDictionary *)options
          callback:(ABI49_0_0RCTResponseSenderBlock)callback;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeSegmentFetcher'
     */
    class JSI_EXPORT NativeSegmentFetcherSpecJSI : public ObjCTurboModule {
    public:
      NativeSegmentFetcherSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeSettingsManager {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<id<NSObject> > settings;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeSettingsManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)setValues:(NSDictionary *)values;
- (void)deleteValues:(NSArray *)values;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeSettingsManager::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeSettingsManager::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeSettingsManager'
     */
    class JSI_EXPORT NativeSettingsManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeSettingsManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeShareModule {
    struct SpecShareContent {
      NSString *title() const;
      NSString *message() const;

      SpecShareContent(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeShareModule_SpecShareContent)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeShareModule_SpecShareContent:(id)json;
@end
@protocol ABI49_0_0NativeShareModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)share:(ABI49_0_0JS::NativeShareModule::SpecShareContent &)content
  dialogTitle:(NSString *)dialogTitle
      resolve:(ABI49_0_0RCTPromiseResolveBlock)resolve
       reject:(ABI49_0_0RCTPromiseRejectBlock)reject;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeShareModule'
     */
    class JSI_EXPORT NativeShareModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeShareModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeSoundManagerSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)playTouchSound;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeSoundManager'
     */
    class JSI_EXPORT NativeSoundManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeSoundManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeSourceCode {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<NSString *> scriptURL;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeSourceCodeSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeSourceCode::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeSourceCode::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeSourceCode'
     */
    class JSI_EXPORT NativeSourceCodeSpecJSI : public ObjCTurboModule {
    public:
      NativeSourceCodeSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeStatusBarManagerIOS {
    struct Constants {

      struct Builder {
        struct Input {
          ABI49_0_0RCTRequired<double> HEIGHT;
          std::optional<double> DEFAULT_BACKGROUND_COLOR;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol ABI49_0_0NativeStatusBarManagerIOSSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)getHeight:(ABI49_0_0RCTResponseSenderBlock)callback;
- (void)setNetworkActivityIndicatorVisible:(BOOL)visible;
- (void)addListener:(NSString *)eventType;
- (void)removeListeners:(double)count;
- (void)setStyle:(NSString * _Nullable)statusBarStyle
        animated:(BOOL)animated;
- (void)setHidden:(BOOL)hidden
    withAnimation:(NSString *)withAnimation;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeStatusBarManagerIOS::Constants::Builder>)constantsToExport;
- (ABI49_0_0facebook::ABI49_0_0React::ModuleConstants<ABI49_0_0JS::NativeStatusBarManagerIOS::Constants::Builder>)getConstants;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeStatusBarManagerIOS'
     */
    class JSI_EXPORT NativeStatusBarManagerIOSSpecJSI : public ObjCTurboModule {
    public:
      NativeStatusBarManagerIOSSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeTimingSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)createTimer:(double)callbackID
           duration:(double)duration
   jsSchedulingTime:(double)jsSchedulingTime
            repeats:(BOOL)repeats;
- (void)deleteTimer:(double)timerID;
- (void)setSendIdleEvents:(BOOL)sendIdleEvents;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeTiming'
     */
    class JSI_EXPORT NativeTimingSpecJSI : public ObjCTurboModule {
    public:
      NativeTimingSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

@protocol ABI49_0_0NativeVibrationSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)vibrate:(double)pattern;
- (void)vibrateByPattern:(NSArray *)pattern
                  repeat:(double)repeat;
- (void)cancel;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeVibration'
     */
    class JSI_EXPORT NativeVibrationSpecJSI : public ObjCTurboModule {
    public:
      NativeVibrationSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook
namespace ABI49_0_0JS {
  namespace NativeWebSocketModule {
    struct SpecConnectOptions {
      id<NSObject> _Nullable headers() const;

      SpecConnectOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface ABI49_0_0RCTCxxConvert (NativeWebSocketModule_SpecConnectOptions)
+ (ABI49_0_0RCTManagedPointer *)ABI49_0_0JS_NativeWebSocketModule_SpecConnectOptions:(id)json;
@end
@protocol ABI49_0_0NativeWebSocketModuleSpec <ABI49_0_0RCTBridgeModule, ABI49_0_0RCTTurboModule>

- (void)connect:(NSString *)url
      protocols:(NSArray * _Nullable)protocols
        options:(ABI49_0_0JS::NativeWebSocketModule::SpecConnectOptions &)options
       socketID:(double)socketID;
- (void)send:(NSString *)message
 forSocketID:(double)forSocketID;
- (void)sendBinary:(NSString *)base64String
       forSocketID:(double)forSocketID;
- (void)ping:(double)socketID;
- (void)close:(double)code
       reason:(NSString *)reason
     socketID:(double)socketID;
- (void)addListener:(NSString *)eventName;
- (void)removeListeners:(double)count;

@end
namespace ABI49_0_0facebook {
  namespace ABI49_0_0React {
    /**
     * ObjC++ class for module 'NativeWebSocketModule'
     */
    class JSI_EXPORT NativeWebSocketModuleSpecJSI : public ObjCTurboModule {
    public:
      NativeWebSocketModuleSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook

inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::extraSmall() const
{
  id const p = _v[@"extraSmall"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::small() const
{
  id const p = _v[@"small"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::medium() const
{
  id const p = _v[@"medium"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::large() const
{
  id const p = _v[@"large"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::extraLarge() const
{
  id const p = _v[@"extraLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::extraExtraLarge() const
{
  id const p = _v[@"extraExtraLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::extraExtraExtraLarge() const
{
  id const p = _v[@"extraExtraExtraLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::accessibilityMedium() const
{
  id const p = _v[@"accessibilityMedium"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::accessibilityLarge() const
{
  id const p = _v[@"accessibilityLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::accessibilityExtraLarge() const
{
  id const p = _v[@"accessibilityExtraLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::accessibilityExtraExtraLarge() const
{
  id const p = _v[@"accessibilityExtraExtraLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeAccessibilityManager::SpecSetAccessibilityContentSizeMultipliersJSMultipliers::accessibilityExtraExtraExtraLarge() const
{
  id const p = _v[@"accessibilityExtraExtraExtraLarge"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> ABI49_0_0JS::NativeAccessibilityManager::SpecAnnounceForAccessibilityWithOptionsOptions::queue() const
{
  id const p = _v[@"queue"];
  return ABI49_0_0RCTBridgingToOptionalBool(p);
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::title() const
{
  id const p = _v[@"title"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::message() const
{
  id const p = _v[@"message"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *>> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::options() const
{
  id const p = _v[@"options"];
  return ABI49_0_0RCTBridgingToOptionalVec(p, ^NSString *(id itemValue_0) { return ABI49_0_0RCTBridgingToString(itemValue_0); });
}
inline std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<double>> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::destructiveButtonIndices() const
{
  id const p = _v[@"destructiveButtonIndices"];
  return ABI49_0_0RCTBridgingToOptionalVec(p, ^double(id itemValue_0) { return ABI49_0_0RCTBridgingToDouble(itemValue_0); });
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::cancelButtonIndex() const
{
  id const p = _v[@"cancelButtonIndex"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::anchor() const
{
  id const p = _v[@"anchor"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::tintColor() const
{
  id const p = _v[@"tintColor"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::cancelButtonTintColor() const
{
  id const p = _v[@"cancelButtonTintColor"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::userInterfaceStyle() const
{
  id const p = _v[@"userInterfaceStyle"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<double>> ABI49_0_0JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions::disabledButtonIndices() const
{
  id const p = _v[@"disabledButtonIndices"];
  return ABI49_0_0RCTBridgingToOptionalVec(p, ^double(id itemValue_0) { return ABI49_0_0RCTBridgingToDouble(itemValue_0); });
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::message() const
{
  id const p = _v[@"message"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::url() const
{
  id const p = _v[@"url"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::subject() const
{
  id const p = _v[@"subject"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::anchor() const
{
  id const p = _v[@"anchor"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::tintColor() const
{
  id const p = _v[@"tintColor"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::cancelButtonTintColor() const
{
  id const p = _v[@"cancelButtonTintColor"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *>> ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::excludedActivityTypes() const
{
  id const p = _v[@"excludedActivityTypes"];
  return ABI49_0_0RCTBridgingToOptionalVec(p, ^NSString *(id itemValue_0) { return ABI49_0_0RCTBridgingToString(itemValue_0); });
}
inline NSString *ABI49_0_0JS::NativeActionSheetManager::SpecShowShareActionSheetWithOptionsOptions::userInterfaceStyle() const
{
  id const p = _v[@"userInterfaceStyle"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::title() const
{
  id const p = _v[@"title"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::message() const
{
  id const p = _v[@"message"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<ABI49_0_0facebook::ABI49_0_0React::LazyVector<id<NSObject> >> ABI49_0_0JS::NativeAlertManager::Args::buttons() const
{
  id const p = _v[@"buttons"];
  return ABI49_0_0RCTBridgingToOptionalVec(p, ^id<NSObject> (id itemValue_0) { return itemValue_0; });
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::type() const
{
  id const p = _v[@"type"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::defaultValue() const
{
  id const p = _v[@"defaultValue"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::cancelButtonKey() const
{
  id const p = _v[@"cancelButtonKey"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::destructiveButtonKey() const
{
  id const p = _v[@"destructiveButtonKey"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::preferredButtonKey() const
{
  id const p = _v[@"preferredButtonKey"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::keyboardType() const
{
  id const p = _v[@"keyboardType"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeAlertManager::Args::userInterfaceStyle() const
{
  id const p = _v[@"userInterfaceStyle"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *> ABI49_0_0JS::NativeAnimatedModule::EventMapping::nativeEventPath() const
{
  id const p = _v[@"nativeEventPath"];
  return ABI49_0_0RCTBridgingToVec(p, ^NSString *(id itemValue_0) { return ABI49_0_0RCTBridgingToString(itemValue_0); });
}
inline std::optional<double> ABI49_0_0JS::NativeAnimatedModule::EventMapping::animatedValueTag() const
{
  id const p = _v[@"animatedValueTag"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline ABI49_0_0facebook::ABI49_0_0React::LazyVector<NSString *> ABI49_0_0JS::NativeAnimatedTurboModule::EventMapping::nativeEventPath() const
{
  id const p = _v[@"nativeEventPath"];
  return ABI49_0_0RCTBridgingToVec(p, ^NSString *(id itemValue_0) { return ABI49_0_0RCTBridgingToString(itemValue_0); });
}
inline std::optional<double> ABI49_0_0JS::NativeAnimatedTurboModule::EventMapping::animatedValueTag() const
{
  id const p = _v[@"animatedValueTag"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}

inline ABI49_0_0JS::NativeAppState::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto initialAppState = i.initialAppState.get();
  d[@"initialAppState"] = initialAppState;
  return d;
}) {}
inline ABI49_0_0JS::NativeAppState::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}

inline ABI49_0_0JS::NativeBlobModule::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto BLOB_URI_SCHEME = i.BLOB_URI_SCHEME.get();
  d[@"BLOB_URI_SCHEME"] = BLOB_URI_SCHEME;
  auto BLOB_URI_HOST = i.BLOB_URI_HOST.get();
  d[@"BLOB_URI_HOST"] = BLOB_URI_HOST;
  return d;
}) {}
inline ABI49_0_0JS::NativeBlobModule::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}








inline ABI49_0_0JS::NativeDeviceInfo::DisplayMetrics::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto width = i.width.get();
  d[@"width"] = @(width);
  auto height = i.height.get();
  d[@"height"] = @(height);
  auto scale = i.scale.get();
  d[@"scale"] = @(scale);
  auto fontScale = i.fontScale.get();
  d[@"fontScale"] = @(fontScale);
  return d;
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::DisplayMetrics::Builder::Builder(DisplayMetrics i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::DisplayMetricsAndroid::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto width = i.width.get();
  d[@"width"] = @(width);
  auto height = i.height.get();
  d[@"height"] = @(height);
  auto scale = i.scale.get();
  d[@"scale"] = @(scale);
  auto fontScale = i.fontScale.get();
  d[@"fontScale"] = @(fontScale);
  auto densityDpi = i.densityDpi.get();
  d[@"densityDpi"] = @(densityDpi);
  return d;
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::DisplayMetricsAndroid::Builder::Builder(DisplayMetricsAndroid i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::DimensionsPayload::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto window = i.window;
  d[@"window"] = window.has_value() ? window.value().buildUnsafeRawValue() : nil;
  auto screen = i.screen;
  d[@"screen"] = screen.has_value() ? screen.value().buildUnsafeRawValue() : nil;
  auto windowPhysicalPixels = i.windowPhysicalPixels;
  d[@"windowPhysicalPixels"] = windowPhysicalPixels.has_value() ? windowPhysicalPixels.value().buildUnsafeRawValue() : nil;
  auto screenPhysicalPixels = i.screenPhysicalPixels;
  d[@"screenPhysicalPixels"] = screenPhysicalPixels.has_value() ? screenPhysicalPixels.value().buildUnsafeRawValue() : nil;
  return d;
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::DimensionsPayload::Builder::Builder(DimensionsPayload i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto Dimensions = i.Dimensions.get();
  d[@"Dimensions"] = Dimensions.buildUnsafeRawValue();
  auto isIPhoneX_deprecated = i.isIPhoneX_deprecated;
  d[@"isIPhoneX_deprecated"] = isIPhoneX_deprecated.has_value() ? @((BOOL)isIPhoneX_deprecated.value()) : nil;
  return d;
}) {}
inline ABI49_0_0JS::NativeDeviceInfo::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline std::optional<double> ABI49_0_0JS::NativeExceptionsManager::StackFrame::column() const
{
  id const p = _v[@"column"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline NSString *ABI49_0_0JS::NativeExceptionsManager::StackFrame::file() const
{
  id const p = _v[@"file"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<double> ABI49_0_0JS::NativeExceptionsManager::StackFrame::lineNumber() const
{
  id const p = _v[@"lineNumber"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline NSString *ABI49_0_0JS::NativeExceptionsManager::StackFrame::methodName() const
{
  id const p = _v[@"methodName"];
  return ABI49_0_0RCTBridgingToString(p);
}
inline std::optional<bool> ABI49_0_0JS::NativeExceptionsManager::StackFrame::collapse() const
{
  id const p = _v[@"collapse"];
  return ABI49_0_0RCTBridgingToOptionalBool(p);
}
inline NSString *ABI49_0_0JS::NativeExceptionsManager::ExceptionData::message() const
{
  id const p = _v[@"message"];
  return ABI49_0_0RCTBridgingToString(p);
}
inline NSString *ABI49_0_0JS::NativeExceptionsManager::ExceptionData::originalMessage() const
{
  id const p = _v[@"originalMessage"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeExceptionsManager::ExceptionData::name() const
{
  id const p = _v[@"name"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeExceptionsManager::ExceptionData::componentStack() const
{
  id const p = _v[@"componentStack"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline ABI49_0_0facebook::ABI49_0_0React::LazyVector<ABI49_0_0JS::NativeExceptionsManager::StackFrame> ABI49_0_0JS::NativeExceptionsManager::ExceptionData::stack() const
{
  id const p = _v[@"stack"];
  return ABI49_0_0RCTBridgingToVec(p, ^ABI49_0_0JS::NativeExceptionsManager::StackFrame(id itemValue_0) { return ABI49_0_0JS::NativeExceptionsManager::StackFrame(itemValue_0); });
}
inline double ABI49_0_0JS::NativeExceptionsManager::ExceptionData::id_() const
{
  id const p = _v[@"id"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline bool ABI49_0_0JS::NativeExceptionsManager::ExceptionData::isFatal() const
{
  id const p = _v[@"isFatal"];
  return ABI49_0_0RCTBridgingToBool(p);
}
inline id<NSObject> _Nullable ABI49_0_0JS::NativeExceptionsManager::ExceptionData::extraData() const
{
  id const p = _v[@"extraData"];
  return p;
}

inline std::optional<bool> ABI49_0_0JS::NativeFrameRateLogger::SpecSetGlobalOptionsOptions::debug() const
{
  id const p = _v[@"debug"];
  return ABI49_0_0RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> ABI49_0_0JS::NativeFrameRateLogger::SpecSetGlobalOptionsOptions::reportStackTraces() const
{
  id const p = _v[@"reportStackTraces"];
  return ABI49_0_0RCTBridgingToOptionalBool(p);
}

inline ABI49_0_0JS::NativeI18nManager::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto isRTL = i.isRTL.get();
  d[@"isRTL"] = @(isRTL);
  auto doLeftAndRightSwapInRTL = i.doLeftAndRightSwapInRTL.get();
  d[@"doLeftAndRightSwapInRTL"] = @(doLeftAndRightSwapInRTL);
  auto localeIdentifier = i.localeIdentifier.get();
  d[@"localeIdentifier"] = localeIdentifier;
  return d;
}) {}
inline ABI49_0_0JS::NativeI18nManager::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline double ABI49_0_0JS::NativeImageEditor::OptionsOffset::x() const
{
  id const p = _v[@"x"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline double ABI49_0_0JS::NativeImageEditor::OptionsOffset::y() const
{
  id const p = _v[@"y"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline double ABI49_0_0JS::NativeImageEditor::OptionsSize::width() const
{
  id const p = _v[@"width"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline double ABI49_0_0JS::NativeImageEditor::OptionsSize::height() const
{
  id const p = _v[@"height"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline double ABI49_0_0JS::NativeImageEditor::OptionsDisplaySize::width() const
{
  id const p = _v[@"width"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline double ABI49_0_0JS::NativeImageEditor::OptionsDisplaySize::height() const
{
  id const p = _v[@"height"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline ABI49_0_0JS::NativeImageEditor::OptionsOffset ABI49_0_0JS::NativeImageEditor::Options::offset() const
{
  id const p = _v[@"offset"];
  return ABI49_0_0JS::NativeImageEditor::OptionsOffset(p);
}
inline ABI49_0_0JS::NativeImageEditor::OptionsSize ABI49_0_0JS::NativeImageEditor::Options::size() const
{
  id const p = _v[@"size"];
  return ABI49_0_0JS::NativeImageEditor::OptionsSize(p);
}
inline std::optional<ABI49_0_0JS::NativeImageEditor::OptionsDisplaySize> ABI49_0_0JS::NativeImageEditor::Options::displaySize() const
{
  id const p = _v[@"displaySize"];
  return (p == nil ? std::nullopt : std::make_optional(ABI49_0_0JS::NativeImageEditor::OptionsDisplaySize(p)));
}
inline NSString *ABI49_0_0JS::NativeImageEditor::Options::resizeMode() const
{
  id const p = _v[@"resizeMode"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<bool> ABI49_0_0JS::NativeImageEditor::Options::allowExternalStorage() const
{
  id const p = _v[@"allowExternalStorage"];
  return ABI49_0_0RCTBridgingToOptionalBool(p);
}








inline NSString *ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::method() const
{
  id const p = _v[@"method"];
  return ABI49_0_0RCTBridgingToString(p);
}
inline NSString *ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::url() const
{
  id const p = _v[@"url"];
  return ABI49_0_0RCTBridgingToString(p);
}
inline id<NSObject>  ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::data() const
{
  id const p = _v[@"data"];
  return p;
}
inline id<NSObject>  ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::headers() const
{
  id const p = _v[@"headers"];
  return p;
}
inline NSString *ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::responseType() const
{
  id const p = _v[@"responseType"];
  return ABI49_0_0RCTBridgingToString(p);
}
inline bool ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::incrementalUpdates() const
{
  id const p = _v[@"incrementalUpdates"];
  return ABI49_0_0RCTBridgingToBool(p);
}
inline double ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::timeout() const
{
  id const p = _v[@"timeout"];
  return ABI49_0_0RCTBridgingToDouble(p);
}
inline bool ABI49_0_0JS::NativeNetworkingIOS::SpecSendRequestQuery::withCredentials() const
{
  id const p = _v[@"withCredentials"];
  return ABI49_0_0RCTBridgingToBool(p);
}
inline ABI49_0_0JS::NativePlatformConstantsIOS::ConstantsreactNativeVersion::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto major = i.major.get();
  d[@"major"] = @(major);
  auto minor = i.minor.get();
  d[@"minor"] = @(minor);
  auto patch = i.patch.get();
  d[@"patch"] = @(patch);
  auto prerelease = i.prerelease.get();
  d[@"prerelease"] = prerelease.has_value() ? @((double)prerelease.value()) : nil;
  return d;
}) {}
inline ABI49_0_0JS::NativePlatformConstantsIOS::ConstantsreactNativeVersion::Builder::Builder(ConstantsreactNativeVersion i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline ABI49_0_0JS::NativePlatformConstantsIOS::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto isTesting = i.isTesting.get();
  d[@"isTesting"] = @(isTesting);
  auto reactNativeVersion = i.reactNativeVersion.get();
  d[@"reactNativeVersion"] = reactNativeVersion.buildUnsafeRawValue();
  auto forceTouchAvailable = i.forceTouchAvailable.get();
  d[@"forceTouchAvailable"] = @(forceTouchAvailable);
  auto osVersion = i.osVersion.get();
  d[@"osVersion"] = osVersion;
  auto systemName = i.systemName.get();
  d[@"systemName"] = systemName;
  auto interfaceIdiom = i.interfaceIdiom.get();
  d[@"interfaceIdiom"] = interfaceIdiom;
  return d;
}) {}
inline ABI49_0_0JS::NativePlatformConstantsIOS::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline bool ABI49_0_0JS::NativePushNotificationManagerIOS::SpecRequestPermissionsPermission::alert() const
{
  id const p = _v[@"alert"];
  return ABI49_0_0RCTBridgingToBool(p);
}
inline bool ABI49_0_0JS::NativePushNotificationManagerIOS::SpecRequestPermissionsPermission::badge() const
{
  id const p = _v[@"badge"];
  return ABI49_0_0RCTBridgingToBool(p);
}
inline bool ABI49_0_0JS::NativePushNotificationManagerIOS::SpecRequestPermissionsPermission::sound() const
{
  id const p = _v[@"sound"];
  return ABI49_0_0RCTBridgingToBool(p);
}
inline NSString *ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::alertTitle() const
{
  id const p = _v[@"alertTitle"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<double> ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::fireDate() const
{
  id const p = _v[@"fireDate"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline NSString *ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::alertBody() const
{
  id const p = _v[@"alertBody"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::alertAction() const
{
  id const p = _v[@"alertAction"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline id<NSObject> _Nullable ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::userInfo() const
{
  id const p = _v[@"userInfo"];
  return p;
}
inline NSString *ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::category() const
{
  id const p = _v[@"category"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::repeatInterval() const
{
  id const p = _v[@"repeatInterval"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline std::optional<double> ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::applicationIconBadgeNumber() const
{
  id const p = _v[@"applicationIconBadgeNumber"];
  return ABI49_0_0RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::isSilent() const
{
  id const p = _v[@"isSilent"];
  return ABI49_0_0RCTBridgingToOptionalBool(p);
}
inline NSString *ABI49_0_0JS::NativePushNotificationManagerIOS::Notification::soundName() const
{
  id const p = _v[@"soundName"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}


inline ABI49_0_0JS::NativeSettingsManager::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto settings = i.settings.get();
  d[@"settings"] = settings;
  return d;
}) {}
inline ABI49_0_0JS::NativeSettingsManager::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline NSString *ABI49_0_0JS::NativeShareModule::SpecShareContent::title() const
{
  id const p = _v[@"title"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}
inline NSString *ABI49_0_0JS::NativeShareModule::SpecShareContent::message() const
{
  id const p = _v[@"message"];
  return ABI49_0_0RCTBridgingToOptionalString(p);
}

inline ABI49_0_0JS::NativeSourceCode::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto scriptURL = i.scriptURL.get();
  d[@"scriptURL"] = scriptURL;
  return d;
}) {}
inline ABI49_0_0JS::NativeSourceCode::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
inline ABI49_0_0JS::NativeStatusBarManagerIOS::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto HEIGHT = i.HEIGHT.get();
  d[@"HEIGHT"] = @(HEIGHT);
  auto DEFAULT_BACKGROUND_COLOR = i.DEFAULT_BACKGROUND_COLOR;
  d[@"DEFAULT_BACKGROUND_COLOR"] = DEFAULT_BACKGROUND_COLOR.has_value() ? @((double)DEFAULT_BACKGROUND_COLOR.value()) : nil;
  return d;
}) {}
inline ABI49_0_0JS::NativeStatusBarManagerIOS::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}


inline id<NSObject> _Nullable ABI49_0_0JS::NativeWebSocketModule::SpecConnectOptions::headers() const
{
  id const p = _v[@"headers"];
  return p;
}
