{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-image-manipulator",
    "version": "10.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-image-manipulator-10.3.1.aar",
          "url": "expo-image-manipulator-10.3.1.aar",
          "size": 44246,
          "sha512": "647b63ffcb2f99761977c9dcf3282122d962cd240e805787ff69d8b442ab793df50ab93fedf233a29227089e6cfb1806e10330397a7756fe0aa9fda71555b50d",
          "sha256": "b5695fc18375d46dc007ce6b2210af847d94078a62b974375b6e302e9deea73e",
          "sha1": "f3d4822a4d712229acc26ca52c5190aa76296ce7",
          "md5": "98e5d902573f287ea95097487d40b9a3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-image-manipulator-10.3.1.aar",
          "url": "expo-image-manipulator-10.3.1.aar",
          "size": 44246,
          "sha512": "647b63ffcb2f99761977c9dcf3282122d962cd240e805787ff69d8b442ab793df50ab93fedf233a29227089e6cfb1806e10330397a7756fe0aa9fda71555b50d",
          "sha256": "b5695fc18375d46dc007ce6b2210af847d94078a62b974375b6e302e9deea73e",
          "sha1": "f3d4822a4d712229acc26ca52c5190aa76296ce7",
          "md5": "98e5d902573f287ea95097487d40b9a3"
        }
      ]
    }
  ]
}
