{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-location",
    "version": "14.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "io.nlopez.smartlocation",
          "module": "library",
          "version": {
            "requires": "3.2.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "expo-location-14.2.1.aar",
          "url": "expo-location-14.2.1.aar",
          "size": 56590,
          "sha512": "b9be760eb9b37a66849f0f49ea915d1be241ad47693836b86930fac703fde4b2140ed448ff9dd64508a4bc870ac279b8dd84bd1917578e99a538ab97654b33b6",
          "sha256": "e3ad22a74b03b80596f29c025501fafbd5373a436b3808135242f2ba97414fc8",
          "sha1": "87df375ef62f6237939e9ebc6dc891c10ba3ef77",
          "md5": "642de0744962bf7449a8c20c1ad005fe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "io.nlopez.smartlocation",
          "module": "library",
          "version": {
            "requires": "3.2.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-location-14.2.1.aar",
          "url": "expo-location-14.2.1.aar",
          "size": 56590,
          "sha512": "b9be760eb9b37a66849f0f49ea915d1be241ad47693836b86930fac703fde4b2140ed448ff9dd64508a4bc870ac279b8dd84bd1917578e99a538ab97654b33b6",
          "sha256": "e3ad22a74b03b80596f29c025501fafbd5373a436b3808135242f2ba97414fc8",
          "sha1": "87df375ef62f6237939e9ebc6dc891c10ba3ef77",
          "md5": "642de0744962bf7449a8c20c1ad005fe"
        }
      ]
    }
  ]
}
