// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription
import Foundation

// Resolve PODS_ROOT from the environment. The build is driven from a CocoaPods
// build phase that always sets PODS_ROOT before invoking xcodebuild. If it's
// missing, fall back to a placeholder so `swift package describe` and IDE
// indexing don't crash — actual compilation will fail loudly.
let podsRoot = ProcessInfo.processInfo.environment["PODS_ROOT"] ?? "PODS_ROOT_NOT_SET"

// Header roots needed by ExpoModulesJSI and ExpoModulesJSI-Cxx. The same paths
// exist in both prebuilt and source-built React Native layouts, so we don't
// need to detect the mode.
let publicHeaders = "\(podsRoot)/Headers/Public"
// In source-built RN, third-party deps (folly, boost, etc.) live under
// per-pod dirs like RCT-Folly/folly/. In prebuilt RN they're bundled into
// ReactNativeDependencies. Some pods nest their headers (e.g. RCT-Folly/folly/),
// others place them directly (e.g. boost/preprocessor/), so we include both
// the Headers/Public root and the per-pod dirs for the nested ones.
let headerSearchPaths = [
  publicHeaders,
  "\(publicHeaders)/React-jsi",
  "\(publicHeaders)/hermes-engine",
  "\(publicHeaders)/React-runtimescheduler",
  "\(publicHeaders)/React-rendererconsistency",
  "\(publicHeaders)/React-performancetimeline",
  "\(publicHeaders)/React-timing",
  "\(publicHeaders)/React-debug",
  "\(publicHeaders)/React-callinvoker",
  "\(publicHeaders)/React-runtimeexecutor",
  "\(publicHeaders)/RCT-Folly",
  "\(publicHeaders)/ReactNativeDependencies",
  "\(publicHeaders)/glog",
  "\(publicHeaders)/DoubleConversion",
  "\(publicHeaders)/fmt",
  "\(publicHeaders)/fast_float",
]

// Path to the generated module map for the `jsi` Clang module. The build
// script writes this file at build time so the absolute header path can be
// resolved against the runtime PODS_ROOT. Lives outside `.build/` so the
// build script can wipe SwiftPM state without losing the modulemap.
let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent().path
let generatedModuleMap = "\(packageDir)/.generated/module.modulemap"
let apiNotesPath = "\(packageDir)/APINotes"

let cxxIncludeFlags = headerSearchPaths.map({ "-I\($0)" })
let swiftIncludeFlags = headerSearchPaths.flatMap({ ["-Xcc", "-I\($0)"] })

let package = Package(
  name: "ExpoModulesJSI",
  platforms: [
    .iOS("16.4"),
    .tvOS("16.4"),
    .macOS("13.4"),
  ],
  products: [
    .library(
      name: "ExpoModulesJSI",
      type: .dynamic,
      targets: ["ExpoModulesJSI"],
    ),
  ],
  dependencies: [],
  targets: [
    // Swift target (public)
    .target(
      name: "ExpoModulesJSI",
      dependencies: [
        "ExpoModulesJSI-Cxx",
      ],
      swiftSettings: [
        .interoperabilityMode(.Cxx),

        // Enable some upcoming features that improve ergonomics and reduce executor hoppings
        // https://github.com/swiftlang/swift-evolution/blob/main/proposals/0461-async-function-isolation.md
        .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
        // https://github.com/swiftlang/swift-evolution/blob/main/proposals/0470-isolated-conformances.md
        .enableUpcomingFeature("InferIsolatedConformances"),

        .unsafeFlags([
          "-enable-library-evolution",
          "-emit-module-interface",
          "-no-verify-emitted-module-interface",
          "-Xfrontend",
          "-clang-header-expose-decls=has-expose-attr",

          // Module map for the `jsi` Clang module, generated by build-xcframework.sh
          // before xcodebuild runs.
          "-Xcc", "-fmodule-map-file=\(generatedModuleMap)",

          // API Notes
          "-Xcc", "-iapinotes-modules",
          "-Xcc", apiNotesPath,
        ]),

        .unsafeFlags(swiftIncludeFlags),
      ],
      linkerSettings: [
        // React, ReactCommon, hermes, and JSI symbols are provided by the host
        // app at final link time. Defer their resolution so the xcframework
        // builds without those static libs being available here.
        .unsafeFlags([
          "-Xlinker", "-undefined", "-Xlinker", "dynamic_lookup",
        ]),
      ],
    ),

    // C++ target (internal)
    .target(
      name: "ExpoModulesJSI-Cxx",
      dependencies: [],
      cxxSettings: [
        .unsafeFlags(cxxIncludeFlags),
      ],
    ),

    // Tests
    .testTarget(
      name: "Tests",
      dependencies: ["ExpoModulesJSI"],
    ),
  ],
  swiftLanguageModes: [.v6],
  cxxLanguageStandard: .cxx20
)
