module.exports = {
  EASClient: {
    addListener: { type: 'function' },
    clientID: { type: 'string' },
    removeListeners: { type: 'function' },
  },
  ExpoAppleAuthentication: {
    addListener: { type: 'function' },
    formatFullName: { type: 'function' },
    getCredentialStateAsync: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestAsync: { type: 'function' },
    // view: {
    //   propNames: ['buttonStyle', 'buttonType', 'cornerRadius'],
    // },
  },
  ExpoApplication: {
    addListener: { type: 'function' },
    applicationId: { type: 'string' },
    applicationName: { type: 'string' },
    getApplicationReleaseTypeAsync: { type: 'function' },
    getInstallationTimeAsync: { type: 'function' },
    getIosIdForVendorAsync: { type: 'function' },
    getPushNotificationServiceEnvironmentAsync: { type: 'function' },
    nativeApplicationVersion: { type: 'string' },
    nativeBuildVersion: { type: 'string' },
    removeListeners: { type: 'function' },
  },
  ExpoAsset: {
    addListener: { type: 'function' },
    downloadAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoAudio: {
    addListener: { type: 'function' },
    getRecordingPermissionsAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestRecordingPermissionsAsync: { type: 'function' },
    setAudioModeAsync: { type: 'function' },
    setIsAudioActiveAsync: { type: 'function' },
  },
  ExpoBackgroundFetch: {
    addListener: { type: 'function' },
    getStatusAsync: { type: 'function' },
    registerTaskAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setMinimumIntervalAsync: { type: 'function' },
    unregisterTaskAsync: { type: 'function' },
  },
  ExpoBackgroundNotificationTasksModule: {
    addListener: { type: 'function' },
    registerTaskAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    unregisterTaskAsync: { type: 'function' },
  },
  ExpoBackgroundTask: {
    addListener: { type: 'function' },
    getStatusAsync: { type: 'function' },
    registerTaskAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    triggerTaskWorkerForTestingAsync: { type: 'function' },
    unregisterTaskAsync: { type: 'function' },
  },
  ExpoBadgeModule: {
    addListener: { type: 'function' },
    getBadgeCountAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setBadgeCountAsync: { type: 'function' },
  },
  ExpoBarometer: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setUpdateInterval: { type: 'function' },
  },
  ExpoBattery: {
    addListener: { type: 'function' },
    getBatteryLevelAsync: { type: 'function' },
    getBatteryStateAsync: { type: 'function' },
    isLowPowerModeEnabledAsync: { type: 'function' },
    isSupported: { type: 'boolean', mock: false },
    removeListeners: { type: 'function' },
  },
  ExpoBlurView: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: ['intensity', 'tint'],
    // },
  },
  ExpoBrightness: {
    addListener: { type: 'function' },
    getBrightnessAsync: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    getSystemBrightnessAsync: { type: 'function' },
    getSystemBrightnessModeAsync: { type: 'function' },
    isUsingSystemBrightnessAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
    setBrightnessAsync: { type: 'function' },
    setSystemBrightnessAsync: { type: 'function' },
    setSystemBrightnessModeAsync: { type: 'function' },
    useSystemBrightnessAsync: { type: 'function' },
  },
  ExpoCalendar: {
    addListener: { type: 'function' },
    createEventInCalendarAsync: { type: 'function' },
    deleteCalendarAsync: { type: 'function' },
    deleteEventAsync: { type: 'function' },
    deleteReminderAsync: { type: 'function' },
    editEventInCalendarAsync: { type: 'function' },
    getAttendeesForEventAsync: { type: 'function' },
    getCalendarPermissionsAsync: { type: 'function' },
    getCalendarsAsync: { type: 'function' },
    getDefaultCalendarAsync: { type: 'function' },
    getEventByIdAsync: { type: 'function' },
    getEventsAsync: { type: 'function' },
    getReminderByIdAsync: { type: 'function' },
    getRemindersAsync: { type: 'function' },
    getRemindersPermissionsAsync: { type: 'function' },
    getSourceByIdAsync: { type: 'function' },
    getSourcesAsync: { type: 'function' },
    openEventInCalendarAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestCalendarPermissionsAsync: { type: 'function' },
    requestRemindersPermissionsAsync: { type: 'function' },
    saveCalendarAsync: { type: 'function' },
    saveEventAsync: { type: 'function' },
    saveReminderAsync: { type: 'function' },
  },
  ExpoCamera: {
    addListener: { type: 'function' },
    dismissScanner: { type: 'function' },
    getAvailableVideoCodecsAsync: { type: 'function' },
    getCameraPermissionsAsync: { type: 'function' },
    getMicrophonePermissionsAsync: { type: 'function' },
    isModernBarcodeScannerAvailable: { type: 'property' },
    launchScanner: { type: 'function' },
    removeListeners: { type: 'function' },
    requestCameraPermissionsAsync: { type: 'function' },
    requestMicrophonePermissionsAsync: { type: 'function' },
    scanFromURLAsync: { type: 'function' },
    toggleRecordingAsyncAvailable: { type: 'property' },
    // view: {
    //   propNames: [
    //     'active',
    //     'animateShutter',
    //     'autoFocus',
    //     'barcodeScannerEnabled',
    //     'barcodeScannerSettings',
    //     'enableTorch',
    //     'facing',
    //     'flashMode',
    //     'mirror',
    //     'mode',
    //     'mute',
    //     'pictureSize',
    //     'responsiveOrientationWhenOrientationLocked',
    //     'selectedLens',
    //     'videoBitrate',
    //     'videoQuality',
    //     'zoom',
    //   ],
    // },
  },
  ExpoCellular: {
    addListener: { type: 'function' },
    allowsVoip: { type: 'null' },
    allowsVoipAsync: { type: 'function' },
    carrier: { type: 'null' },
    generation: { type: 'number', mock: 0 },
    getCarrierNameAsync: { type: 'function' },
    getCellularGenerationAsync: { type: 'function' },
    getIsoCountryCodeAsync: { type: 'function' },
    getMobileCountryCodeAsync: { type: 'function' },
    getMobileNetworkCodeAsync: { type: 'function' },
    isoCountryCode: { type: 'null' },
    mobileCountryCode: { type: 'null' },
    mobileNetworkCode: { type: 'null' },
    removeListeners: { type: 'function' },
  },
  ExpoContactAccessButton: {
    addListener: { type: 'function' },
    isAvailable: { type: 'property' },
    removeListeners: { type: 'function' },
  },
  ExpoContacts: {
    addContactAsync: { type: 'function' },
    addExistingContactToGroupAsync: { type: 'function' },
    addExistingGroupToContainerAsync: { type: 'function' },
    addListener: { type: 'function' },
    createGroupAsync: { type: 'function' },
    dismissFormAsync: { type: 'function' },
    getContactsAsync: { type: 'function' },
    getContainersAsync: { type: 'function' },
    getDefaultContainerIdentifierAsync: { type: 'function' },
    getGroupsAsync: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    presentAccessPickerAsync: { type: 'function' },
    presentContactPickerAsync: { type: 'function' },
    presentFormAsync: { type: 'function' },
    removeContactAsync: { type: 'function' },
    removeContactFromGroupAsync: { type: 'function' },
    removeGroupAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
    updateContactAsync: { type: 'function' },
    updateGroupNameAsync: { type: 'function' },
    writeContactToFileAsync: { type: 'function' },
  },
  ExpoDevice: {
    addListener: { type: 'function' },
    brand: { type: 'string' },
    deviceName: { type: 'string' },
    deviceType: { type: 'number', mock: 1 },
    deviceYearClass: { type: 'number', mock: 2025 },
    getDeviceTypeAsync: { type: 'function' },
    getUptimeAsync: { type: 'function' },
    isDevice: { type: 'boolean', mock: false },
    isRootedExperimentalAsync: { type: 'function' },
    manufacturer: { type: 'string' },
    modelId: { type: 'string' },
    modelName: { type: 'string' },
    osBuildId: { type: 'string' },
    osInternalBuildId: { type: 'string' },
    osName: { type: 'string' },
    osVersion: { type: 'string' },
    removeListeners: { type: 'function' },
    supportedCpuArchitectures: { type: 'array' },
    totalMemory: { type: 'unknown' },
  },
  ExpoDocumentPicker: {
    addListener: { type: 'function' },
    getDocumentAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoDomWebViewModule: {
    addListener: { type: 'function' },
    evalJsForWebViewAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: [
    //     'automaticallyAdjustsScrollIndicatorInsets',
    //     'bounces',
    //     'contentInset',
    //     'contentInsetAdjustmentBehavior',
    //     'decelerationRate',
    //     'directionalLockEnabled',
    //     'injectedJavaScriptBeforeContentLoaded',
    //     'pagingEnabled',
    //     'scrollEnabled',
    //     'showsHorizontalScrollIndicator',
    //     'showsVerticalScrollIndicator',
    //     'source',
    //     'webviewDebuggingEnabled',
    //   ],
    // },
  },
  ExpoFetchModule: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoFontLoader: {
    addListener: { type: 'function' },
    getLoadedFonts: { type: 'function' },
    loadAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoFontUtils: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    renderToImageAsync: { type: 'function' },
  },
  ExpoGo: {
    addListener: { type: 'function' },
    expoVersion: { type: 'string' },
    getModulesSchema: { type: 'function' },
    projectConfig: { type: 'object' },
    removeListeners: { type: 'function' },
  },
  ExpoHaptics: {
    addListener: { type: 'function' },
    impactAsync: { type: 'function' },
    notificationAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    selectionAsync: { type: 'function' },
  },
  ExpoHead: {
    activities: { type: 'object' },
    addListener: { type: 'function' },
    clearActivitiesAsync: { type: 'function' },
    createActivity: { type: 'function' },
    getLaunchActivity: { type: 'function' },
    removeListeners: { type: 'function' },
    revokeActivity: { type: 'function' },
    suspendActivity: { type: 'function' },
  },
  ExpoImage: {
    addListener: { type: 'function' },
    clearDiskCache: { type: 'function' },
    clearMemoryCache: { type: 'function' },
    generateBlurhashAsync: { type: 'function' },
    generateThumbhashAsync: { type: 'function' },
    getCachePathAsync: { type: 'function' },
    loadAsync: { type: 'function' },
    prefetch: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: [
    //     'accessibilityLabel',
    //     'accessible',
    //     'allowDownscaling',
    //     'autoplay',
    //     'blurRadius',
    //     'cachePolicy',
    //     'contentFit',
    //     'contentPosition',
    //     'enableLiveTextInteraction',
    //     'enforceEarlyResizing',
    //     'placeholder',
    //     'placeholderContentFit',
    //     'priority',
    //     'recyclingKey',
    //     'source',
    //     'tintColor',
    //     'transition',
    //     'useAppleWebpCodec',
    //   ],
    // },
  },
  ExpoImageManipulator: {
    addListener: { type: 'function' },
    manipulate: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoKeepAwake: {
    activate: { type: 'function' },
    addListener: { type: 'function' },
    deactivate: { type: 'function' },
    isActivated: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoLinearGradient: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: ['colors', 'endPoint', 'locations', 'startPoint'],
    // },
  },
  ExpoGlassEffect: {
    isLiquidGlassAvailable: { type: 'string' },
  },
  ExpoLivePhoto: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: ['contentFit', 'isMuted', 'source', 'useDefaultGestureRecognizer'],
    // },
  },
  ExpoLocalAuthentication: {
    addListener: { type: 'function' },
    authenticateAsync: { type: 'function' },
    getEnrolledLevelAsync: { type: 'function' },
    hasHardwareAsync: { type: 'function' },
    isEnrolledAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    supportedAuthenticationTypesAsync: { type: 'function' },
  },
  ExpoLocation: {
    addListener: { type: 'function' },
    geocodeAsync: { type: 'function' },
    getBackgroundPermissionsAsync: { type: 'function' },
    getCurrentPositionAsync: { type: 'function' },
    getForegroundPermissionsAsync: { type: 'function' },
    getLastKnownPositionAsync: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    getProviderStatusAsync: { type: 'function' },
    hasServicesEnabledAsync: { type: 'function' },
    hasStartedGeofencingAsync: { type: 'function' },
    hasStartedLocationUpdatesAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    removeWatchAsync: { type: 'function' },
    requestBackgroundPermissionsAsync: { type: 'function' },
    requestForegroundPermissionsAsync: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
    reverseGeocodeAsync: { type: 'function' },
    startGeofencingAsync: { type: 'function' },
    startLocationUpdatesAsync: { type: 'function' },
    stopGeofencingAsync: { type: 'function' },
    stopLocationUpdatesAsync: { type: 'function' },
    watchDeviceHeading: { type: 'function' },
    watchPositionImplAsync: { type: 'function' },
  },
  ExpoMailComposer: {
    addListener: { type: 'function' },
    composeAsync: { type: 'function' },
    getClients: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoMediaLibrary: {
    addAssetsToAlbumAsync: { type: 'function' },
    addListener: { type: 'function' },
    CHANGE_LISTENER_NAME: { type: 'string' },
    createAlbumAsync: { type: 'function' },
    createAssetAsync: { type: 'function' },
    deleteAlbumsAsync: { type: 'function' },
    deleteAssetsAsync: { type: 'function' },
    getAlbumAsync: { type: 'function' },
    getAlbumsAsync: { type: 'function' },
    getAssetInfoAsync: { type: 'function' },
    getAssetsAsync: { type: 'function' },
    getMomentsAsync: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    MediaType: { type: 'object' },
    presentPermissionsPickerAsync: { type: 'function' },
    removeAssetsFromAlbumAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
    saveToLibraryAsync: { type: 'function' },
    SortBy: { type: 'object' },
  },
  ExpoMeshGradient: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExponentAccelerometer: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setUpdateInterval: { type: 'function' },
  },
  ExponentConstants: {
    addListener: { type: 'function' },
    appOwnership: { type: 'string' },
    debugMode: { type: 'boolean', mock: true },
    deviceName: { type: 'string' },
    executionEnvironment: { type: 'string' },
    experienceUrl: { type: 'string' },
    expoRuntimeVersion: { type: 'string' },
    expoVersion: { type: 'string' },
    getWebViewUserAgentAsync: { type: 'function' },
    isDetached: { type: 'boolean', mock: false },
    isHeadless: { type: 'boolean', mock: false },
    linkingUri: { type: 'string' },
    manifest: { type: 'object' },
    platform: { type: 'object' },
    removeListeners: { type: 'function' },
    sessionId: { type: 'string' },
    statusBarHeight: { type: 'number', mock: 54 },
    supportedExpoSdks: { type: 'array' },
    systemFonts: { type: 'array' },
  },
  ExponentDeviceMotion: {
    addListener: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    Gravity: { type: 'number', mock: 9.80665 },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
    setUpdateInterval: { type: 'function' },
  },
  ExponentFileSystem: {
    addListener: { type: 'function' },
    bundleDirectory: { type: 'string' },
    cacheDirectory: { type: 'string' },
    copyAsync: { type: 'function' },
    deleteAsync: { type: 'function' },
    documentDirectory: { type: 'string' },
    downloadAsync: { type: 'function' },
    downloadResumablePauseAsync: { type: 'function' },
    downloadResumableStartAsync: { type: 'function' },
    getFreeDiskStorageAsync: { type: 'function' },
    getInfoAsync: { type: 'function' },
    getTotalDiskCapacityAsync: { type: 'function' },
    makeDirectoryAsync: { type: 'function' },
    moveAsync: { type: 'function' },
    networkTaskCancelAsync: { type: 'function' },
    readAsStringAsync: { type: 'function' },
    readDirectoryAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    uploadAsync: { type: 'function' },
    uploadTaskStartAsync: { type: 'function' },
    writeAsStringAsync: { type: 'function' },
  },
  ExpoGL: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: ['enableExperimentalWorkletSupport', 'msaaSamples'],
    // },
  },
  ExponentGyroscope: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setUpdateInterval: { type: 'function' },
  },
  ExponentImagePicker: {
    addListener: { type: 'function' },
    getCameraPermissionsAsync: { type: 'function' },
    getMediaLibraryPermissionsAsync: { type: 'function' },
    launchCameraAsync: { type: 'function' },
    launchImageLibraryAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestCameraPermissionsAsync: { type: 'function' },
    requestMediaLibraryPermissionsAsync: { type: 'function' },
  },
  ExponentMagnetometer: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setUpdateInterval: { type: 'function' },
  },
  ExponentMagnetometerUncalibrated: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setUpdateInterval: { type: 'function' },
  },
  ExponentPedometer: {
    addListener: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    getStepCountAsync: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
  },
  ExpoNetwork: {
    addListener: { type: 'function' },
    getIpAddressAsync: { type: 'function' },
    getNetworkStateAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoNotificationCategoriesModule: {
    addListener: { type: 'function' },
    deleteNotificationCategoryAsync: { type: 'function' },
    getNotificationCategoriesAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setNotificationCategoryAsync: { type: 'function' },
  },
  ExpoNotificationPermissionsModule: {
    addListener: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
  },
  ExpoNotificationPresenter: {
    addListener: { type: 'function' },
    dismissAllNotificationsAsync: { type: 'function' },
    dismissNotificationAsync: { type: 'function' },
    getPresentedNotificationsAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoNotificationScheduler: {
    addListener: { type: 'function' },
    cancelAllScheduledNotificationsAsync: { type: 'function' },
    cancelScheduledNotificationAsync: { type: 'function' },
    getAllScheduledNotificationsAsync: { type: 'function' },
    getNextTriggerDateAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    scheduleNotificationAsync: { type: 'function' },
  },
  ExpoNotificationsEmitter: {
    addListener: { type: 'function' },
    clearLastNotificationResponse: { type: 'function' },
    getLastNotificationResponse: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoNotificationsHandlerModule: {
    addListener: { type: 'function' },
    handleNotificationAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoPrint: {
    addListener: { type: 'function' },
    Orientation: { type: 'object' },
    print: { type: 'function' },
    printToFileAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    selectPrinter: { type: 'function' },
  },
  ExpoPushTokenManager: {
    addListener: { type: 'function' },
    getDevicePushTokenAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    unregisterForNotificationsAsync: { type: 'function' },
  },
  ExpoRouter: {
    Material3Color: { type: 'function' },
    Material3DynamicColor: { type: 'function' },
  },
  ExpoRouterNativeLinkPreview: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: [
    //     'destructive',
    //     'disabled',
    //     'displayAsPalette',
    //     'displayInline',
    //     'icon',
    //     'isOn',
    //     'keepPresented',
    //     'nextScreenId',
    //     'preferredContentSize',
    //     'singleSelection',
    //     'tabPath',
    //     'title',
    //   ],
    // },
  },
  ExpoScreenCapture: {
    addListener: { type: 'function' },
    allowScreenCapture: { type: 'function' },
    disableAppSwitcherProtection: { type: 'function' },
    enableAppSwitcherProtection: { type: 'function' },
    preventScreenCapture: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoScreenOrientation: {
    addListener: { type: 'function' },
    getOrientationAsync: { type: 'function' },
    getOrientationLockAsync: { type: 'function' },
    getPlatformOrientationLockAsync: { type: 'function' },
    lockAsync: { type: 'function' },
    lockPlatformAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    supportsOrientationLockAsync: { type: 'function' },
  },
  ExpoSecureStore: {
    addListener: { type: 'function' },
    AFTER_FIRST_UNLOCK: { type: 'number', mock: 0 },
    AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY: { type: 'number', mock: 1 },
    ALWAYS: { type: 'number', mock: 2 },
    ALWAYS_THIS_DEVICE_ONLY: { type: 'number', mock: 4 },
    canUseBiometricAuthentication: { type: 'function' },
    deleteValueWithKeyAsync: { type: 'function' },
    getValueWithKeyAsync: { type: 'function' },
    getValueWithKeySync: { type: 'function' },
    removeListeners: { type: 'function' },
    setValueWithKeyAsync: { type: 'function' },
    setValueWithKeySync: { type: 'function' },
    WHEN_PASSCODE_SET_THIS_DEVICE_ONLY: { type: 'number', mock: 3 },
    WHEN_UNLOCKED: { type: 'number', mock: 5 },
    WHEN_UNLOCKED_THIS_DEVICE_ONLY: { type: 'number', mock: 6 },
  },
  ExpoSharing: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    shareAsync: { type: 'function' },
  },
  ExpoSMS: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    sendSMSAsync: { type: 'function' },
  },
  ExpoSpeech: {
    addListener: { type: 'function' },
    getVoices: { type: 'function' },
    isSpeaking: { type: 'function' },
    pause: { type: 'function' },
    removeListeners: { type: 'function' },
    resume: { type: 'function' },
    speak: { type: 'function' },
    stop: { type: 'function' },
  },
  ExpoSQLite: {
    addListener: { type: 'function' },
    backupDatabaseAsync: { type: 'function' },
    backupDatabaseSync: { type: 'function' },
    defaultDatabaseDirectory: { type: 'string' },
    deleteDatabaseAsync: { type: 'function' },
    deleteDatabaseSync: { type: 'function' },
    ensureDatabasePathExistsAsync: { type: 'function' },
    ensureDatabasePathExistsSync: { type: 'function' },
    importAssetDatabaseAsync: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoStoreReview: {
    addListener: { type: 'function' },
    isAvailableAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestReview: { type: 'function' },
  },
  ExpoSystemUI: {
    addListener: { type: 'function' },
    getBackgroundColorAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setBackgroundColorAsync: { type: 'function' },
  },
  ExpoTrackingTransparency: {
    addListener: { type: 'function' },
    getAdvertisingId: { type: 'function' },
    getPermissionsAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    requestPermissionsAsync: { type: 'function' },
  },
  ExpoUpdates: {
    addListener: { type: 'function' },
    channel: { type: 'string' },
    checkAutomatically: { type: 'string' },
    checkForUpdateAsync: { type: 'function' },
    clearLogEntriesAsync: { type: 'function' },
    emergencyLaunchReason: { type: 'null' },
    fetchUpdateAsync: { type: 'function' },
    getExtraParamsAsync: { type: 'function' },
    initialContext: { type: 'object' },
    isEmbeddedLaunch: { type: 'boolean', mock: false },
    isEmergencyLaunch: { type: 'boolean', mock: false },
    isEnabled: { type: 'boolean', mock: true },
    isUsingEmbeddedAssets: { type: 'boolean', mock: false },
    launchDuration: { type: 'number', mock: 455.30903339385986 },
    readLogEntriesAsync: { type: 'function' },
    reload: { type: 'function' },
    removeListeners: { type: 'function' },
    runtimeVersion: { type: 'string' },
    setExtraParamAsync: { type: 'function' },
    shouldDeferToNativeForAPIMethodAvailabilityInDevelopment: { type: 'boolean', mock: true },
  },
  ExpoVideo: {
    addListener: { type: 'function' },
    clearVideoCacheAsync: { type: 'function' },
    getCurrentVideoCacheSize: { type: 'function' },
    isPictureInPictureSupported: { type: 'function' },
    removeListeners: { type: 'function' },
    setVideoCacheSizeAsync: { type: 'function' },
    // view: {
    //   propNames: [
    //     'activeTint',
    //     'allowsFullscreen',
    //     'allowsPictureInPicture',
    //     'allowsVideoFrameAnalysis',
    //     'contentFit',
    //     'contentPosition',
    //     'fullscreenOptions',
    //     'nativeControls',
    //     'player',
    //     'prioritizeVideoDevices',
    //     'requiresLinearPlayback',
    //     'showsTimecodes',
    //     'startsPictureInPictureAutomatically',
    //     'tint',
    //   ],
    // },
  },
  ExpoVideoThumbnails: {
    addListener: { type: 'function' },
    getThumbnail: { type: 'function' },
    removeListeners: { type: 'function' },
  },
  ExpoVideoView: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    ScaleAspectFill: { type: 'unknown' },
    ScaleAspectFit: { type: 'unknown' },
    ScaleNone: { type: 'unknown' },
    ScaleToFill: { type: 'unknown' },
    setFullscreen: { type: 'function' },
  },
  ExpoWebBrowser: {
    addListener: { type: 'function' },
    coolDownAsync: { type: 'function' },
    dismissAuthSession: { type: 'function' },
    dismissBrowser: { type: 'function' },
    getCustomTabsSupportingBrowsers: { type: 'function' },
    mayInitWithUrlAsync: { type: 'function' },
    openAuthSessionAsync: { type: 'function' },
    openBrowserAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    warmUpAsync: { type: 'function' },
  },
  FileSystem: {
    addListener: { type: 'function' },
    appleSharedContainers: { type: 'object' },
    availableDiskSpace: { type: 'property' },
    bundleDirectory: { type: 'string' },
    cacheDirectory: { type: 'string' },
    documentDirectory: { type: 'string' },
    downloadFileAsync: { type: 'function' },
    info: { type: 'function' },
    removeListeners: { type: 'function' },
    totalDiskSpace: { type: 'property' },
  },
  NotificationsServerRegistrationModule: {
    addListener: { type: 'function' },
    getInstallationIdAsync: { type: 'function' },
    getRegistrationInfoAsync: { type: 'function' },
    removeListeners: { type: 'function' },
    setRegistrationInfoAsync: { type: 'function' },
  },
  SymbolModule: {
    addListener: { type: 'function' },
    removeListeners: { type: 'function' },
    // view: {
    //   propNames: [
    //     'animated',
    //     'animationSpec',
    //     'colors',
    //     'name',
    //     'resizeMode',
    //     'scale',
    //     'tintColor',
    //     'type',
    //     'weight',
    //   ],
    // },
  },
};
