// getPropertyDataForDeviceAsync
// isBootAnimationCompleteAsync
// adbReverseRemoveAsync
// adbReverseAsync
// getAbdNameForEmulatorIdAsync
// getAttachedDevicesAsync
// openUrlAsync
// openAppIdAsync
// launchActivityAsync
// isPackageInstalledAsync
// ADBServer
