module.exports = {
  AIRGoogleMapCalloutManager: {},
  AIRGoogleMapCalloutSubviewManager: {},
  AIRGoogleMapCircleManager: {},
  AIRGoogleMapHeatmapManager: {},
  AIRGoogleMapManager: {
    animateCamera: { type: 'function', functionType: 'async' },
    animateToRegion: { type: 'function', functionType: 'async' },
    coordinateForPoint: { type: 'function', functionType: 'promise' },
    fitToCoordinates: { type: 'function', functionType: 'async' },
    fitToElements: { type: 'function', functionType: 'async' },
    fitToSuppliedMarkers: { type: 'function', functionType: 'async' },
    getCamera: { type: 'function', functionType: 'promise' },
    getConstants: { type: 'function' },
    getMapBoundaries: { type: 'function', functionType: 'promise' },
    getMarkersFrames: { type: 'function', functionType: 'promise' },
    legalNotice: { type: 'string' },
    pointForCoordinate: { type: 'function', functionType: 'promise' },
    setCamera: { type: 'function', functionType: 'async' },
    setIndoorActiveLevelIndex: { type: 'function', functionType: 'async' },
    setMapBoundaries: { type: 'function', functionType: 'async' },
    takeSnapshot: { type: 'function', functionType: 'async' },
  },
  AIRGoogleMapMarkerManager: {
    getConstants: { type: 'function' },
    hideCallout: { type: 'function', functionType: 'async' },
    redraw: { type: 'function', functionType: 'async' },
    redrawCallout: { type: 'function', functionType: 'async' },
    showCallout: { type: 'function', functionType: 'async' },
  },
  AIRGoogleMapOverlayManager: {},
  AIRGoogleMapPolygonManager: {},
  AIRGoogleMapPolylineManager: {},
  AIRGoogleMapUrlTileManager: {},
  AIRGoogleMapWMSTileManager: {},
  AIRMapCalloutManager: {},
  AIRMapCalloutSubviewManager: {},
  AIRMapCircleManager: {},
  AIRMapLocalTileManager: {},
  AIRMapManager: {
    animateCamera: { type: 'function', functionType: 'async' },
    animateToRegion: { type: 'function', functionType: 'async' },
    coordinateForPoint: { type: 'function', functionType: 'promise' },
    fitToCoordinates: { type: 'function', functionType: 'async' },
    fitToElements: { type: 'function', functionType: 'async' },
    fitToSuppliedMarkers: { type: 'function', functionType: 'async' },
    getAddressFromCoordinates: { type: 'function', functionType: 'promise' },
    getCamera: { type: 'function', functionType: 'promise' },
    getConstants: { type: 'function' },
    getMapBoundaries: { type: 'function', functionType: 'promise' },
    getMarkersFrames: { type: 'function', functionType: 'promise' },
    pointForCoordinate: { type: 'function', functionType: 'promise' },
    setCamera: { type: 'function', functionType: 'async' },
    takeSnapshot: { type: 'function', functionType: 'async' },
  },
  AIRMapMarkerManager: {
    getConstants: { type: 'function' },
    hideCallout: { type: 'function', functionType: 'async' },
    redrawCallout: { type: 'function', functionType: 'async' },
    showCallout: { type: 'function', functionType: 'async' },
  },
  AIRMapOverlayManager: {},
  AIRMapPolygonManager: {},
  AIRMapPolylineManager: {},
  AIRMapUrlTileManager: {},
  AIRMapWMSTileManager: {},
  ExpoBridgeModule: {},
  'ExpoModulesCore.ViewModuleWrapper': {},
  ExpoNativeModuleIntrospection: {
    getConstants: { type: 'function' },
    getNativeModuleNamesAsync: { type: 'function', functionType: 'promise' },
    introspectNativeModuleAsync: { type: 'function', functionType: 'promise' },
  },
  ExponentNotifications: {
    cancelAllScheduledNotificationsAsync: { type: 'function', functionType: 'promise' },
    cancelScheduledNotificationAsync: { type: 'function', functionType: 'promise' },
    createCategoryAsync: { type: 'function', functionType: 'promise' },
    deleteCategoryAsync: { type: 'function', functionType: 'promise' },
    getBadgeNumberAsync: { type: 'function', functionType: 'promise' },
    getConstants: { type: 'function' },
    getDevicePushTokenAsync: { type: 'function', functionType: 'promise' },
    getExponentPushTokenAsync: { type: 'function', functionType: 'promise' },
    legacyScheduleLocalRepeatingNotification: { type: 'function', functionType: 'promise' },
    presentLocalNotification: { type: 'function', functionType: 'promise' },
    scheduleLocalNotification: { type: 'function', functionType: 'promise' },
    scheduleNotificationWithCalendar: { type: 'function', functionType: 'promise' },
    scheduleNotificationWithTimer: { type: 'function', functionType: 'promise' },
    setBadgeNumberAsync: { type: 'function', functionType: 'promise' },
  },
  ExponentScopedModuleRegistry: {},
  ExponentTest: {
    action: { type: 'function', functionType: 'promise' },
    completed: { type: 'function', functionType: 'async' },
    getConstants: { type: 'function' },
    isInCI: { type: 'number', mock: 0 },
    log: { type: 'function', functionType: 'async' },
    shouldSkipTestsRequiringPermissionsAsync: { type: 'function', functionType: 'promise' },
  },
  ExponentUtil: {},
  LottieAnimationView: {
    VERSION: { type: 'number', mock: 1 },
    getConstants: { type: 'function' },
    pause: { type: 'function', functionType: 'async' },
    play: { type: 'function', functionType: 'async' },
    reset: { type: 'function', functionType: 'async' },
    resume: { type: 'function', functionType: 'async' },
  },
  NativeUnimoduleProxy: {
    callMethod: { type: 'function', functionType: 'promise' },
    exportedMethods: {
      type: 'object',
      mock: {
        '': [],
        EASClient: [],
        ExpoAppleAuthentication: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'requestAsync', argumentsCount: 1, key: 1 },
          { name: 'getCredentialStateAsync', argumentsCount: 1, key: 2 },
        ],
        ExpoAppleAuthenticationButtonContinueBlack: [],
        ExpoAppleAuthenticationButtonContinueWhite: [],
        ExpoAppleAuthenticationButtonContinueWhiteOutline: [],
        ExpoAppleAuthenticationButtonSignInBlack: [],
        ExpoAppleAuthenticationButtonSignInWhite: [],
        ExpoAppleAuthenticationButtonSignInWhiteOutline: [],
        ExpoAppleAuthenticationButtonSignUpBlack: [],
        ExpoAppleAuthenticationButtonSignUpWhite: [],
        ExpoAppleAuthenticationButtonSignUpWhiteOutline: [],
        ExpoApplication: [
          { name: 'getIosIdForVendorAsync', argumentsCount: 0, key: 0 },
          { name: 'getPushNotificationServiceEnvironmentAsync', argumentsCount: 0, key: 1 },
          { name: 'getApplicationReleaseTypeAsync', argumentsCount: 0, key: 2 },
          { name: 'getInstallationTimeAsync', argumentsCount: 0, key: 3 },
        ],
        ExpoBackgroundFetch: [
          { name: 'unregisterTaskAsync', argumentsCount: 1, key: 0 },
          { name: 'setMinimumIntervalAsync', argumentsCount: 1, key: 1 },
          { name: 'getStatusAsync', argumentsCount: 0, key: 2 },
          { name: 'registerTaskAsync', argumentsCount: 2, key: 3 },
        ],
        ExpoBackgroundNotificationTasksModule: [
          { name: 'unregisterTaskAsync', argumentsCount: 1, key: 0 },
          { name: 'registerTaskAsync', argumentsCount: 1, key: 1 },
        ],
        ExpoBadgeModule: [
          { name: 'setBadgeCountAsync', argumentsCount: 1, key: 0 },
          { name: 'getBadgeCountAsync', argumentsCount: 0, key: 1 },
        ],
        ExpoBarCodeScanner: [
          { key: 'requestPermissionsAsync', name: 'requestPermissionsAsync', argumentsCount: 0 },
          { argumentsCount: 0, key: 'getPermissionsAsync', name: 'getPermissionsAsync' },
          { name: 'scanFromURLAsync', argumentsCount: 2, key: 'scanFromURLAsync' },
        ],
        ExpoBarometer: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'setUpdateInterval', argumentsCount: 1, key: 1 },
        ],
        ExpoBattery: [
          { key: 'stopObserving', name: 'stopObserving', argumentsCount: 0 },
          {
            key: 'isLowPowerModeEnabledAsync',
            argumentsCount: 0,
            name: 'isLowPowerModeEnabledAsync',
          },
          { argumentsCount: 0, key: 'startObserving', name: 'startObserving' },
          { argumentsCount: 0, key: 'getBatteryLevelAsync', name: 'getBatteryLevelAsync' },
          { argumentsCount: 0, name: 'getBatteryStateAsync', key: 'getBatteryStateAsync' },
        ],
        ExpoBlurView: [{ argumentsCount: 2, key: 'setNativeProps', name: 'setNativeProps' }],
        ExpoBrightness: [
          {
            key: 'isUsingSystemBrightnessAsync',
            name: 'isUsingSystemBrightnessAsync',
            argumentsCount: 0,
          },
          { name: 'startObserving', argumentsCount: 0, key: 'startObserving' },
          { key: 'useSystemBrightnessAsync', argumentsCount: 0, name: 'useSystemBrightnessAsync' },
          {
            argumentsCount: 0,
            key: 'getSystemBrightnessModeAsync',
            name: 'getSystemBrightnessModeAsync',
          },
          {
            key: 'setSystemBrightnessModeAsync',
            name: 'setSystemBrightnessModeAsync',
            argumentsCount: 0,
          },
          { argumentsCount: 0, key: 'setSystemBrightnessAsync', name: 'setSystemBrightnessAsync' },
          { name: 'getSystemBrightnessAsync', key: 'getSystemBrightnessAsync', argumentsCount: 0 },
          { name: 'setBrightnessAsync', argumentsCount: 1, key: 'setBrightnessAsync' },
          { name: 'getPermissionsAsync', argumentsCount: 0, key: 'getPermissionsAsync' },
          { name: 'requestPermissionsAsync', key: 'requestPermissionsAsync', argumentsCount: 0 },
          { name: 'stopObserving', argumentsCount: 0, key: 'stopObserving' },
          { key: 'getBrightnessAsync', argumentsCount: 0, name: 'getBrightnessAsync' },
        ],
        ExpoCalendar: [
          { name: 'deleteCalendarAsync', argumentsCount: 1, key: 0 },
          { name: 'deleteReminderAsync', argumentsCount: 1, key: 1 },
          { name: 'getCalendarPermissionsAsync', argumentsCount: 0, key: 2 },
          { name: 'deleteEventAsync', argumentsCount: 2, key: 3 },
          { name: 'requestRemindersPermissionsAsync', argumentsCount: 0, key: 4 },
          { name: 'getEventsAsync', argumentsCount: 3, key: 5 },
          { name: 'getSourcesAsync', argumentsCount: 0, key: 6 },
          { name: 'getReminderByIdAsync', argumentsCount: 1, key: 7 },
          { name: 'requestCalendarPermissionsAsync', argumentsCount: 0, key: 8 },
          { name: 'getAttendeesForEventAsync', argumentsCount: 1, key: 9 },
          { name: 'getRemindersAsync', argumentsCount: 4, key: 10 },
          { name: 'getRemindersPermissionsAsync', argumentsCount: 0, key: 11 },
          { name: 'saveEventAsync', argumentsCount: 2, key: 12 },
          { name: 'getCalendarsAsync', argumentsCount: 1, key: 13 },
          { name: 'getEventByIdAsync', argumentsCount: 2, key: 14 },
          { name: 'getDefaultCalendarAsync', argumentsCount: 0, key: 15 },
          { name: 'saveCalendarAsync', argumentsCount: 1, key: 16 },
          { name: 'saveReminderAsync', argumentsCount: 1, key: 17 },
          { name: 'getSourceByIdAsync', argumentsCount: 1, key: 18 },
        ],
        ExpoCellular: [
          {
            key: 'getCellularGenerationAsync',
            name: 'getCellularGenerationAsync',
            argumentsCount: 0,
          },
          {
            name: 'getMobileCountryCodeAsync',
            argumentsCount: 0,
            key: 'getMobileCountryCodeAsync',
          },
          {
            name: 'getMobileNetworkCodeAsync',
            key: 'getMobileNetworkCodeAsync',
            argumentsCount: 0,
          },
          { argumentsCount: 0, key: 'getCarrierNameAsync', name: 'getCarrierNameAsync' },
          { key: 'getIsoCountryCodeAsync', argumentsCount: 0, name: 'getIsoCountryCodeAsync' },
          { name: 'allowsVoipAsync', argumentsCount: 0, key: 'allowsVoipAsync' },
        ],
        ExpoClipboard: [
          { name: 'setStringAsync', key: 'setStringAsync', argumentsCount: 2 },
          { argumentsCount: 1, name: 'getImageAsync', key: 'getImageAsync' },
          { name: 'getUrlAsync', key: 'getUrlAsync', argumentsCount: 0 },
          { argumentsCount: 0, name: 'hasUrlAsync', key: 'hasUrlAsync' },
          { name: 'setImageAsync', argumentsCount: 1, key: 'setImageAsync' },
          { key: 'hasStringAsync', argumentsCount: 0, name: 'hasStringAsync' },
          { name: 'getStringAsync', argumentsCount: 1, key: 'getStringAsync' },
          { argumentsCount: 0, name: 'hasImageAsync', key: 'hasImageAsync' },
          { key: 'setUrlAsync', name: 'setUrlAsync', argumentsCount: 1 },
          { name: 'stopObserving', key: 'stopObserving', argumentsCount: 0 },
          { key: 'startObserving', argumentsCount: 0, name: 'startObserving' },
        ],
        ExpoContacts: [
          { name: 'getDefaultContainerIdentifierAsync', argumentsCount: 0, key: 0 },
          { name: 'addExistingGroupToContainerAsync', argumentsCount: 2, key: 1 },
          { name: 'createGroupAsync', argumentsCount: 2, key: 2 },
          { name: 'addContactAsync', argumentsCount: 2, key: 3 },
          { name: 'removeGroupAsync', argumentsCount: 1, key: 4 },
          { name: 'removeContactFromGroupAsync', argumentsCount: 2, key: 5 },
          { name: 'removeContactAsync', argumentsCount: 1, key: 6 },
          { name: 'getPermissionsAsync', argumentsCount: 0, key: 7 },
          { name: 'updateContactAsync', argumentsCount: 1, key: 8 },
          { name: 'getGroupsAsync', argumentsCount: 1, key: 9 },
          { name: 'addExistingContactToGroupAsync', argumentsCount: 2, key: 10 },
          { name: 'getContainersAsync', argumentsCount: 1, key: 11 },
          { name: 'requestPermissionsAsync', argumentsCount: 0, key: 12 },
          { name: 'updateGroupNameAsync', argumentsCount: 2, key: 13 },
          { name: 'getContactsAsync', argumentsCount: 1, key: 14 },
          { name: 'presentFormAsync', argumentsCount: 3, key: 15 },
          { name: 'writeContactToFileAsync', argumentsCount: 1, key: 16 },
          { name: 'dismissFormAsync', argumentsCount: 0, key: 17 },
        ],
        ExpoCrypto: [
          {
            name: 'getRandomBase64StringAsync',
            argumentsCount: 1,
            key: 'getRandomBase64StringAsync',
          },
          { argumentsCount: 3, key: 'digestString', name: 'digestString' },
          { argumentsCount: 1, key: 'getRandomBase64String', name: 'getRandomBase64String' },
          { argumentsCount: 1, key: 'getRandomValues', name: 'getRandomValues' },
          { name: 'randomUUID', argumentsCount: 0, key: 'randomUUID' },
          { key: 'digestStringAsync', name: 'digestStringAsync', argumentsCount: 3 },
        ],
        ExpoDevice: [
          {
            key: 'isRootedExperimentalAsync',
            argumentsCount: 0,
            name: 'isRootedExperimentalAsync',
          },
          { key: 'getDeviceTypeAsync', name: 'getDeviceTypeAsync', argumentsCount: 0 },
          { argumentsCount: 0, key: 'getUptimeAsync', name: 'getUptimeAsync' },
        ],
        ExpoDocumentPicker: [{ name: 'getDocumentAsync', argumentsCount: 1, key: 0 }],
        ExpoErrorRecovery: [{ name: 'saveRecoveryProps', argumentsCount: 1, key: 0 }],
        ExpoFaceDetector: [{ name: 'detectFaces', argumentsCount: 1, key: 0 }],
        ExpoFirebaseAnalytics: [
          { name: 'logEvent', argumentsCount: 2, key: 0 },
          { name: 'setUserId', argumentsCount: 1, key: 1 },
          { name: 'setUserProperties', argumentsCount: 1, key: 2 },
          { name: 'resetAnalyticsData', argumentsCount: 0, key: 3 },
          { name: 'setSessionTimeoutDuration', argumentsCount: 1, key: 4 },
          { name: 'setAnalyticsCollectionEnabled', argumentsCount: 1, key: 5 },
        ],
        ExpoFirebaseCore: [],
        ExpoFontLoader: [{ name: 'loadAsync', argumentsCount: 2, key: 0 }],
        ExpoHaptics: [
          { name: 'selectionAsync', argumentsCount: 0, key: 'selectionAsync' },
          { argumentsCount: 1, key: 'notificationAsync', name: 'notificationAsync' },
          { name: 'impactAsync', argumentsCount: 1, key: 'impactAsync' },
        ],
        ExpoImageManipulator: [
          { name: 'manipulateAsync', argumentsCount: 3, key: 'manipulateAsync' },
        ],
        ExpoKeepAwake: [
          { name: 'activate', argumentsCount: 1, key: 'activate' },
          { name: 'deactivate', argumentsCount: 1, key: 'deactivate' },
          { name: 'isActivated', argumentsCount: 0, key: 'isActivated' },
        ],
        ExpoLinearGradient: [],
        ExpoLocalAuthentication: [
          {
            argumentsCount: 0,
            key: 'supportedAuthenticationTypesAsync',
            name: 'supportedAuthenticationTypesAsync',
          },
          { argumentsCount: 0, key: 'getEnrolledLevelAsync', name: 'getEnrolledLevelAsync' },
          { key: 'isEnrolledAsync', name: 'isEnrolledAsync', argumentsCount: 0 },
          { name: 'hasHardwareAsync', key: 'hasHardwareAsync', argumentsCount: 0 },
          { key: 'authenticateAsync', argumentsCount: 1, name: 'authenticateAsync' },
        ],
        ExpoLocalization: [
          { name: 'getCalendars', argumentsCount: 0, key: 'getCalendars' },
          { name: 'getLocales', argumentsCount: 0, key: 'getLocales' },
          { key: 'getLocalizationAsync', argumentsCount: 0, name: 'getLocalizationAsync' },
        ],
        ExpoLocation: [
          { name: 'watchPositionImplAsync', argumentsCount: 2, key: 0 },
          { name: 'watchDeviceHeading', argumentsCount: 1, key: 1 },
          { name: 'requestForegroundPermissionsAsync', argumentsCount: 0, key: 2 },
          { name: 'hasServicesEnabledAsync', argumentsCount: 0, key: 3 },
          { name: 'removeWatchAsync', argumentsCount: 1, key: 4 },
          { name: 'requestPermissionsAsync', argumentsCount: 0, key: 5 },
          { name: 'reverseGeocodeAsync', argumentsCount: 1, key: 6 },
          { name: 'hasStartedGeofencingAsync', argumentsCount: 1, key: 7 },
          { name: 'startLocationUpdatesAsync', argumentsCount: 2, key: 8 },
          { name: 'getPermissionsAsync', argumentsCount: 0, key: 9 },
          { name: 'stopGeofencingAsync', argumentsCount: 1, key: 10 },
          { name: 'hasStartedLocationUpdatesAsync', argumentsCount: 1, key: 11 },
          { name: 'getProviderStatusAsync', argumentsCount: 0, key: 12 },
          { name: 'getBackgroundPermissionsAsync', argumentsCount: 0, key: 13 },
          { name: 'geocodeAsync', argumentsCount: 1, key: 14 },
          { name: 'stopLocationUpdatesAsync', argumentsCount: 1, key: 15 },
          { name: 'getLastKnownPositionAsync', argumentsCount: 1, key: 16 },
          { name: 'getForegroundPermissionsAsync', argumentsCount: 0, key: 17 },
          { name: 'getCurrentPositionAsync', argumentsCount: 1, key: 18 },
          { name: 'startGeofencingAsync', argumentsCount: 2, key: 19 },
          { name: 'requestBackgroundPermissionsAsync', argumentsCount: 0, key: 20 },
        ],
        ExpoMailComposer: [
          { argumentsCount: 0, name: 'isAvailableAsync', key: 'isAvailableAsync' },
          { argumentsCount: 1, name: 'composeAsync', key: 'composeAsync' },
        ],
        ExpoMediaLibrary: [
          { name: 'createAssetAsync', argumentsCount: 1, key: 0 },
          { name: 'deleteAssetsAsync', argumentsCount: 1, key: 1 },
          { name: 'getPermissionsAsync', argumentsCount: 1, key: 2 },
          { name: 'removeAssetsFromAlbumAsync', argumentsCount: 2, key: 3 },
          { name: 'saveToLibraryAsync', argumentsCount: 1, key: 4 },
          { name: 'requestPermissionsAsync', argumentsCount: 1, key: 5 },
          { name: 'getAlbumsAsync', argumentsCount: 1, key: 6 },
          { name: 'getAssetsAsync', argumentsCount: 1, key: 7 },
          { name: 'createAlbumAsync', argumentsCount: 2, key: 8 },
          { name: 'deleteAlbumsAsync', argumentsCount: 2, key: 9 },
          { name: 'getMomentsAsync', argumentsCount: 0, key: 10 },
          { name: 'presentPermissionsPickerAsync', argumentsCount: 0, key: 11 },
          { name: 'addAssetsToAlbumAsync', argumentsCount: 2, key: 12 },
          { name: 'getAssetInfoAsync', argumentsCount: 2, key: 13 },
          { name: 'getAlbumAsync', argumentsCount: 1, key: 14 },
        ],
        ExpoNetwork: [
          { argumentsCount: 0, name: 'getNetworkStateAsync', key: 'getNetworkStateAsync' },
          { key: 'getIpAddressAsync', name: 'getIpAddressAsync', argumentsCount: 0 },
        ],
        ExpoNotificationCategoriesModule: [
          { name: 'deleteNotificationCategoryAsync', argumentsCount: 1, key: 0 },
          { name: 'getNotificationCategoriesAsync', argumentsCount: 0, key: 1 },
          { name: 'setNotificationCategoryAsync', argumentsCount: 3, key: 2 },
        ],
        ExpoNotificationPermissionsModule: [
          { name: 'getPermissionsAsync', argumentsCount: 0, key: 0 },
          { name: 'requestPermissionsAsync', argumentsCount: 1, key: 1 },
        ],
        ExpoNotificationPresenter: [
          { name: 'presentNotificationAsync', argumentsCount: 2, key: 0 },
          { name: 'dismissNotificationAsync', argumentsCount: 1, key: 1 },
          { name: 'getPresentedNotificationsAsync', argumentsCount: 0, key: 2 },
          { name: 'dismissAllNotificationsAsync', argumentsCount: 0, key: 3 },
        ],
        ExpoNotificationScheduler: [
          { name: 'cancelAllScheduledNotificationsAsync', argumentsCount: 0, key: 0 },
          { name: 'getNextTriggerDateAsync', argumentsCount: 1, key: 1 },
          { name: 'getAllScheduledNotificationsAsync', argumentsCount: 0, key: 2 },
          { name: 'scheduleNotificationAsync', argumentsCount: 3, key: 3 },
          { name: 'cancelScheduledNotificationAsync', argumentsCount: 1, key: 4 },
        ],
        ExpoNotificationsEmitter: [
          { name: 'getLastNotificationResponseAsync', argumentsCount: 0, key: 0 },
        ],
        ExpoNotificationsHandlerModule: [
          { name: 'handleNotificationAsync', argumentsCount: 2, key: 0 },
        ],
        ExpoPermissions: [
          { name: 'getAsync', argumentsCount: 1, key: 0 },
          { name: 'askAsync', argumentsCount: 1, key: 1 },
        ],
        ExpoPushTokenManager: [
          { name: 'getDevicePushTokenAsync', argumentsCount: 0, key: 0 },
          { name: 'unregisterForNotificationsAsync', argumentsCount: 0, key: 1 },
        ],
        ExpoRandom: [
          { argumentsCount: 1, name: 'getRandomBase64String', key: 'getRandomBase64String' },
          {
            name: 'getRandomBase64StringAsync',
            key: 'getRandomBase64StringAsync',
            argumentsCount: 1,
          },
        ],
        ExpoSMS: [
          { name: 'sendSMSAsync', key: 'sendSMSAsync', argumentsCount: 3 },
          { argumentsCount: 0, name: 'isAvailableAsync', key: 'isAvailableAsync' },
        ],
        ExpoScreenCapture: [
          { name: 'preventScreenCapture', argumentsCount: 0, key: 0 },
          { name: 'allowScreenCapture', argumentsCount: 0, key: 1 },
        ],
        ExpoScreenOrientation: [
          { name: 'lockAsync', argumentsCount: 1, key: 0 },
          { name: 'supportsOrientationLockAsync', argumentsCount: 1, key: 1 },
          { name: 'getOrientationAsync', argumentsCount: 0, key: 2 },
          { name: 'lockPlatformAsync', argumentsCount: 1, key: 3 },
          { name: 'getOrientationLockAsync', argumentsCount: 0, key: 4 },
          { name: 'getPlatformOrientationLockAsync', argumentsCount: 0, key: 5 },
        ],
        ExpoSecureStore: [
          { name: 'getValueWithKeyAsync', argumentsCount: 2, key: 0 },
          { name: 'deleteValueWithKeyAsync', argumentsCount: 2, key: 1 },
          { name: 'setValueWithKeyAsync', argumentsCount: 3, key: 2 },
        ],
        ExpoSharing: [{ name: 'shareAsync', argumentsCount: 2, key: 0 }],
        ExpoSplashScreen: [
          { name: 'hideAsync', argumentsCount: 0, key: 0 },
          { name: 'preventAutoHideAsync', argumentsCount: 0, key: 1 },
        ],
        ExpoStoreReview: [
          { argumentsCount: 0, name: 'requestReview', key: 'requestReview' },
          { key: 'isAvailableAsync', name: 'isAvailableAsync', argumentsCount: 0 },
        ],
        ExpoSystemUI: [
          { name: 'setBackgroundColorAsync', key: 'setBackgroundColorAsync', argumentsCount: 1 },
          { name: 'getBackgroundColorAsync', key: 'getBackgroundColorAsync', argumentsCount: 0 },
        ],
        ExpoTaskManager: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'notifyTaskFinishedAsync', argumentsCount: 2, key: 1 },
          { name: 'unregisterTaskAsync', argumentsCount: 1, key: 2 },
          { name: 'getTaskOptionsAsync', argumentsCount: 1, key: 3 },
          { name: 'unregisterAllTasksAsync', argumentsCount: 0, key: 4 },
          { name: 'isTaskRegisteredAsync', argumentsCount: 1, key: 5 },
          { name: 'getRegisteredTasksAsync', argumentsCount: 0, key: 6 },
        ],
        ExpoTrackingTransparency: [
          { name: 'requestPermissionsAsync', key: 'requestPermissionsAsync', argumentsCount: 0 },
          { name: 'getPermissionsAsync', key: 'getPermissionsAsync', argumentsCount: 0 },
        ],
        ExpoUpdates: [
          { name: 'readLogEntriesAsync', argumentsCount: 1, key: 0 },
          { name: 'fetchUpdateAsync', argumentsCount: 0, key: 1 },
          { name: 'checkForUpdateAsync', argumentsCount: 0, key: 2 },
          { name: 'clearLogEntriesAsync', argumentsCount: 0, key: 3 },
          { name: 'reload', argumentsCount: 0, key: 4 },
        ],
        ExpoVideoThumbnails: [{ key: 'getThumbnail', name: 'getThumbnail', argumentsCount: 2 }],
        ExpoVideoView: [{ name: 'setFullscreen', key: 'setFullscreen', argumentsCount: 2 }],
        ExpoWebBrowser: [
          { name: 'openAuthSessionAsync', key: 'openAuthSessionAsync', argumentsCount: 3 },
          { key: 'warmUpAsync', name: 'warmUpAsync', argumentsCount: 0 },
          { argumentsCount: 0, name: 'dismissBrowser', key: 'dismissBrowser' },
          { argumentsCount: 0, key: 'mayInitWithUrlAsync', name: 'mayInitWithUrlAsync' },
          {
            name: 'getCustomTabsSupportingBrowsers',
            argumentsCount: 0,
            key: 'getCustomTabsSupportingBrowsers',
          },
          { name: 'openBrowserAsync', argumentsCount: 2, key: 'openBrowserAsync' },
          { name: 'dismissAuthSession', argumentsCount: 0, key: 'dismissAuthSession' },
          { name: 'coolDownAsync', key: 'coolDownAsync', argumentsCount: 0 },
        ],
        ExponentAV: [
          { name: 'getStatusForVideo', argumentsCount: 1, key: 0 },
          { name: 'setAudioMode', argumentsCount: 1, key: 1 },
          { name: 'unloadAudioRecorder', argumentsCount: 0, key: 2 },
          { name: 'stopAudioRecording', argumentsCount: 0, key: 3 },
          { name: 'requestPermissionsAsync', argumentsCount: 0, key: 4 },
          { name: 'setInput', argumentsCount: 1, key: 5 },
          { name: 'loadForVideo', argumentsCount: 3, key: 6 },
          { name: 'setAudioIsEnabled', argumentsCount: 1, key: 7 },
          { name: 'prepareAudioRecorder', argumentsCount: 1, key: 8 },
          { name: 'replayVideo', argumentsCount: 2, key: 9 },
          { name: 'getPermissionsAsync', argumentsCount: 0, key: 10 },
          { name: 'unloadForSound', argumentsCount: 1, key: 11 },
          { name: 'setStatusForSound', argumentsCount: 2, key: 12 },
          { name: 'unloadForVideo', argumentsCount: 1, key: 13 },
          { name: 'replaySound', argumentsCount: 2, key: 14 },
          { name: 'getAvailableInputs', argumentsCount: 0, key: 15 },
          { name: 'getAudioRecordingStatus', argumentsCount: 0, key: 16 },
          { name: 'setStatusForVideo', argumentsCount: 2, key: 17 },
          { name: 'loadForSound', argumentsCount: 2, key: 18 },
          { name: 'pauseAudioRecording', argumentsCount: 0, key: 19 },
          { name: 'getStatusForSound', argumentsCount: 1, key: 20 },
          { name: 'getCurrentInput', argumentsCount: 0, key: 21 },
          { name: 'startAudioRecording', argumentsCount: 0, key: 22 },
        ],
        ExponentAccelerometer: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'setUpdateInterval', argumentsCount: 1, key: 1 },
        ],
        ExponentCamera: [
          { name: 'requestPermissionsAsync', argumentsCount: 0, key: 'requestPermissionsAsync' },
          {
            name: 'requestCameraPermissionsAsync',
            argumentsCount: 0,
            key: 'requestCameraPermissionsAsync',
          },
          { key: 'getPermissionsAsync', argumentsCount: 0, name: 'getPermissionsAsync' },
          {
            key: 'requestMicrophonePermissionsAsync',
            argumentsCount: 0,
            name: 'requestMicrophonePermissionsAsync',
          },
          { argumentsCount: 1, name: 'stopRecording', key: 'stopRecording' },
          {
            key: 'getAvailableVideoCodecsAsync',
            argumentsCount: 0,
            name: 'getAvailableVideoCodecsAsync',
          },
          { key: 'resumePreview', argumentsCount: 1, name: 'resumePreview' },
          { argumentsCount: 2, key: 'takePicture', name: 'takePicture' },
          { key: 'getAvailablePictureSizes', name: 'getAvailablePictureSizes', argumentsCount: 2 },
          { name: 'pausePreview', key: 'pausePreview', argumentsCount: 1 },
          {
            name: 'getCameraPermissionsAsync',
            argumentsCount: 0,
            key: 'getCameraPermissionsAsync',
          },
          {
            key: 'getMicrophonePermissionsAsync',
            name: 'getMicrophonePermissionsAsync',
            argumentsCount: 0,
          },
          { argumentsCount: 2, key: 'record', name: 'record' },
        ],
        ExponentConstants: [
          { name: 'getWebViewUserAgentAsync', key: 'getWebViewUserAgentAsync', argumentsCount: 0 },
        ],
        ExponentDeviceMotion: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'setUpdateInterval', argumentsCount: 1, key: 1 },
        ],
        ExponentFileSystem: [
          { name: 'uploadAsync', argumentsCount: 3, key: 0 },
          { name: 'readDirectoryAsync', argumentsCount: 2, key: 1 },
          { name: 'getTotalDiskCapacityAsync', argumentsCount: 0, key: 2 },
          { name: 'getInfoAsync', argumentsCount: 2, key: 3 },
          { name: 'downloadAsync', argumentsCount: 3, key: 4 },
          { name: 'writeAsStringAsync', argumentsCount: 3, key: 5 },
          { name: 'deleteAsync', argumentsCount: 2, key: 6 },
          { name: 'moveAsync', argumentsCount: 1, key: 7 },
          { name: 'getFreeDiskStorageAsync', argumentsCount: 0, key: 8 },
          { name: 'readAsStringAsync', argumentsCount: 2, key: 9 },
          { name: 'downloadResumableStartAsync', argumentsCount: 5, key: 10 },
          { name: 'makeDirectoryAsync', argumentsCount: 2, key: 11 },
          { name: 'uploadTaskStartAsync', argumentsCount: 4, key: 12 },
          { name: 'copyAsync', argumentsCount: 1, key: 13 },
          { name: 'networkTaskCancelAsync', argumentsCount: 1, key: 14 },
          { name: 'downloadResumablePauseAsync', argumentsCount: 1, key: 15 },
        ],
        ExponentGLObjectManager: [
          { name: 'createContextAsync', argumentsCount: 0, key: 0 },
          { name: 'destroyContextAsync', argumentsCount: 1, key: 1 },
          { name: 'destroyObjectAsync', argumentsCount: 1, key: 2 },
          { name: 'createCameraTextureAsync', argumentsCount: 2, key: 3 },
          { name: 'takeSnapshotAsync', argumentsCount: 2, key: 4 },
        ],
        ExponentGLView: [],
        ExponentGyroscope: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'setUpdateInterval', argumentsCount: 1, key: 1 },
        ],
        ExponentImagePicker: [
          {
            argumentsCount: 1,
            key: 'requestMediaLibraryPermissionsAsync',
            name: 'requestMediaLibraryPermissionsAsync',
          },
          {
            argumentsCount: 0,
            key: 'getCameraPermissionsAsync',
            name: 'getCameraPermissionsAsync',
          },
          {
            argumentsCount: 0,
            name: 'requestCameraPermissionsAsync',
            key: 'requestCameraPermissionsAsync',
          },
          { name: 'launchCameraAsync', argumentsCount: 1, key: 'launchCameraAsync' },
          { name: 'launchImageLibraryAsync', argumentsCount: 1, key: 'launchImageLibraryAsync' },
          {
            name: 'getMediaLibraryPermissionsAsync',
            argumentsCount: 1,
            key: 'getMediaLibraryPermissionsAsync',
          },
        ],
        ExponentMagnetometer: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'setUpdateInterval', argumentsCount: 1, key: 1 },
        ],
        ExponentMagnetometerUncalibrated: [
          { name: 'isAvailableAsync', argumentsCount: 0, key: 0 },
          { name: 'setUpdateInterval', argumentsCount: 1, key: 1 },
        ],
        ExponentPedometer: [
          { name: 'requestPermissionsAsync', argumentsCount: 0, key: 0 },
          { name: 'getPermissionsAsync', argumentsCount: 0, key: 1 },
          { name: 'isAvailableAsync', argumentsCount: 0, key: 2 },
          { name: 'getStepCountAsync', argumentsCount: 2, key: 3 },
        ],
        ExponentPrint: [
          { name: 'print', argumentsCount: 1, key: 0 },
          { name: 'selectPrinter', argumentsCount: 0, key: 1 },
          { name: 'printToFileAsync', argumentsCount: 1, key: 2 },
        ],
        ExponentSQLite: [
          { name: 'close', argumentsCount: 1, key: 0 },
          { name: 'exec', argumentsCount: 3, key: 1 },
          { name: 'deleteAsync', argumentsCount: 1, key: 2 },
        ],
        ExponentSpeech: [
          { name: 'speak', argumentsCount: 3, key: 0 },
          { name: 'stop', argumentsCount: 0, key: 1 },
          { name: 'pause', argumentsCount: 0, key: 2 },
          { name: 'resume', argumentsCount: 0, key: 3 },
          { name: 'isSpeaking', argumentsCount: 0, key: 4 },
          { name: 'getVoices', argumentsCount: 0, key: 5 },
        ],
        NativeModulesProxy: [{ name: 'callMethod', argumentsCount: 3, key: 'callMethod' }],
        NotificationsServerRegistrationModule: [
          { name: 'getRegistrationInfoAsync', argumentsCount: 0, key: 0 },
          { name: 'setRegistrationInfoAsync', argumentsCount: 1, key: 1 },
          { name: 'getInstallationIdAsync', argumentsCount: 0, key: 2 },
        ],
      },
    },
    getConstants: { type: 'function' },
    modulesConstants: {
      type: 'mock',
      mockDefinition: {
        EASClient: {
          addListener: { type: 'function' },
          clientID: { type: 'string' },
          removeListeners: { type: 'function' },
        },
        ExpoApplication: {
          addListener: { type: 'function' },
          applicationId: { type: 'string' },
          applicationName: { type: 'string' },
          getApplicationReleaseTypeAsync: { type: 'function' },
          getInstallationTimeAsync: { type: 'function' },
          getIosIdForVendorAsync: { type: 'function' },
          getPushNotificationServiceEnvironmentAsync: { type: 'function' },
          nativeApplicationVersion: { type: 'string' },
          nativeBuildVersion: { type: 'string' },
          removeListeners: { type: 'function' },
        },
        ExpoBarCodeScanner: {
          BarCodeType: { type: 'object' },
          Type: { type: 'object' },
          addListener: { type: 'function' },
          getPermissionsAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          requestPermissionsAsync: { type: 'function' },
          scanFromURLAsync: { type: 'function' },
        },
        ExpoBattery: {
          addListener: { type: 'function' },
          getBatteryLevelAsync: { type: 'function' },
          getBatteryStateAsync: { type: 'function' },
          isLowPowerModeEnabledAsync: { type: 'function' },
          isSupported: { type: 'boolean', mock: false },
          removeListeners: { type: 'function' },
          startObserving: { type: 'function' },
          stopObserving: { type: 'function' },
        },
        ExpoBlurView: {
          addListener: { type: 'function' },
          removeListeners: { type: 'function' },
          setNativeProps: { type: 'function' },
        },
        ExpoBrightness: {
          addListener: { type: 'function' },
          getBrightnessAsync: { type: 'function' },
          getPermissionsAsync: { type: 'function' },
          getSystemBrightnessAsync: { type: 'function' },
          getSystemBrightnessModeAsync: { type: 'function' },
          isUsingSystemBrightnessAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          requestPermissionsAsync: { type: 'function' },
          setBrightnessAsync: { type: 'function' },
          setSystemBrightnessAsync: { type: 'function' },
          setSystemBrightnessModeAsync: { type: 'function' },
          startObserving: { type: 'function' },
          stopObserving: { type: 'function' },
          useSystemBrightnessAsync: { type: 'function' },
        },
        ExpoCellular: {
          addListener: { type: 'function' },
          allowsVoip: { type: 'object', mock: null },
          allowsVoipAsync: { type: 'function' },
          carrier: { type: 'object', mock: null },
          generation: { type: 'number', mock: 0 },
          getCarrierNameAsync: { type: 'function' },
          getCellularGenerationAsync: { type: 'function' },
          getIsoCountryCodeAsync: { type: 'function' },
          getMobileCountryCodeAsync: { type: 'function' },
          getMobileNetworkCodeAsync: { type: 'function' },
          isoCountryCode: { type: 'object', mock: null },
          mobileCountryCode: { type: 'object', mock: null },
          mobileNetworkCode: { type: 'object', mock: null },
          removeListeners: { type: 'function' },
        },
        ExpoClipboard: {
          addListener: { type: 'function' },
          getImageAsync: { type: 'function' },
          getStringAsync: { type: 'function' },
          getUrlAsync: { type: 'function' },
          hasImageAsync: { type: 'function' },
          hasStringAsync: { type: 'function' },
          hasUrlAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          setImageAsync: { type: 'function' },
          setStringAsync: { type: 'function' },
          setUrlAsync: { type: 'function' },
          startObserving: { type: 'function' },
          stopObserving: { type: 'function' },
        },
        ExpoCrypto: {
          addListener: { type: 'function' },
          digestString: { type: 'function' },
          digestStringAsync: { type: 'function' },
          getRandomBase64String: { type: 'function' },
          getRandomBase64StringAsync: { type: 'function' },
          getRandomValues: { type: 'function' },
          randomUUID: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoDevice: {
          addListener: { type: 'function' },
          brand: { type: 'string' },
          deviceName: { type: 'string' },
          deviceYearClass: { type: 'number', mock: 2022 },
          getDeviceTypeAsync: { type: 'function' },
          getUptimeAsync: { type: 'function' },
          isDevice: { type: 'boolean', mock: false },
          isRootedExperimentalAsync: { type: 'function' },
          manufacturer: { type: 'string' },
          modelId: { type: 'string' },
          modelName: { type: 'string' },
          osBuildId: { type: 'string' },
          osInternalBuildId: { type: 'string' },
          osName: { type: 'string' },
          osVersion: { type: 'string' },
          removeListeners: { type: 'function' },
          supportedCpuArchitectures: { type: 'array' },
          totalMemory: { type: 'number', mock: 8589934592 },
        },
        ExpoErrorRecovery: {
          addListener: { type: 'function' },
          recoveredProps: { type: 'object', mock: null },
          removeListeners: { type: 'function' },
          saveRecoveryProps: { type: 'function' },
        },
        ExpoFaceDetector: {
          Classifications: { type: 'object' },
          Landmarks: { type: 'object' },
          Mode: { type: 'object' },
          addListener: { type: 'function' },
          detectFaces: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoFirebaseCore: {
          DEFAULT_APP_NAME: { type: 'string' },
          addListener: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoHaptics: {
          addListener: { type: 'function' },
          impactAsync: { type: 'function' },
          notificationAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          selectionAsync: { type: 'function' },
        },
        ExpoImageManipulator: {
          addListener: { type: 'function' },
          manipulateAsync: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoKeepAwake: {
          activate: { type: 'function' },
          addListener: { type: 'function' },
          deactivate: { type: 'function' },
          isActivated: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoLinearGradient: {
          addListener: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoLocalAuthentication: {
          addListener: { type: 'function' },
          authenticateAsync: { type: 'function' },
          getEnrolledLevelAsync: { type: 'function' },
          hasHardwareAsync: { type: 'function' },
          isEnrolledAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          supportedAuthenticationTypesAsync: { type: 'function' },
        },
        ExpoLocalization: {
          addListener: { type: 'function' },
          currency: { type: 'string' },
          decimalSeparator: { type: 'string' },
          digitGroupingSeparator: { type: 'string' },
          getCalendars: { type: 'function' },
          getLocales: { type: 'function' },
          getLocalizationAsync: { type: 'function' },
          isMetric: { type: 'boolean', mock: false },
          isRTL: { type: 'boolean', mock: false },
          isoCurrencyCodes: { type: 'array' },
          locale: { type: 'string' },
          locales: { type: 'array' },
          region: { type: 'string' },
          removeListeners: { type: 'function' },
          timezone: { type: 'string' },
        },
        ExpoMailComposer: {
          addListener: { type: 'function' },
          composeAsync: { type: 'function' },
          isAvailableAsync: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoMediaLibrary: {
          CHANGE_LISTENER_NAME: { type: 'string' },
          MediaType: { type: 'object' },
          SortBy: { type: 'object' },
          addAssetsToAlbumAsync: { type: 'function' },
          addListener: { type: 'function' },
          createAlbumAsync: { type: 'function' },
          createAssetAsync: { type: 'function' },
          deleteAlbumsAsync: { type: 'function' },
          deleteAssetsAsync: { type: 'function' },
          getAlbumAsync: { type: 'function' },
          getAlbumsAsync: { type: 'function' },
          getAssetInfoAsync: { type: 'function' },
          getAssetsAsync: { type: 'function' },
          getMomentsAsync: { type: 'function' },
          getPermissionsAsync: { type: 'function' },
          presentPermissionsPickerAsync: { type: 'function' },
          removeAssetsFromAlbumAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          requestPermissionsAsync: { type: 'function' },
          saveToLibraryAsync: { type: 'function' },
        },
        ExpoNetwork: {
          addListener: { type: 'function' },
          getIpAddressAsync: { type: 'function' },
          getNetworkStateAsync: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoRandom: {
          addListener: { type: 'function' },
          getRandomBase64String: { type: 'function' },
          getRandomBase64StringAsync: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoSMS: {
          addListener: { type: 'function' },
          isAvailableAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          sendSMSAsync: { type: 'function' },
        },
        ExpoSecureStore: {
          AFTER_FIRST_UNLOCK: { type: 'number', mock: 0 },
          AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY: { type: 'number', mock: 1 },
          ALWAYS: { type: 'number', mock: 2 },
          ALWAYS_THIS_DEVICE_ONLY: { type: 'number', mock: 4 },
          WHEN_PASSCODE_SET_THIS_DEVICE_ONLY: { type: 'number', mock: 3 },
          WHEN_UNLOCKED: { type: 'number', mock: 5 },
          WHEN_UNLOCKED_THIS_DEVICE_ONLY: { type: 'number', mock: 6 },
          addListener: { type: 'function' },
          deleteValueWithKeyAsync: { type: 'function' },
          getValueWithKeyAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          setValueWithKeyAsync: { type: 'function' },
        },
        ExpoStoreReview: {
          addListener: { type: 'function' },
          isAvailableAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          requestReview: { type: 'function' },
        },
        ExpoSystemUI: {
          addListener: { type: 'function' },
          getBackgroundColorAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          setBackgroundColorAsync: { type: 'function' },
        },
        ExpoTaskManager: {
          EVENT_NAME: { type: 'string' },
          addListener: { type: 'function' },
          getRegisteredTasksAsync: { type: 'function' },
          getTaskOptionsAsync: { type: 'function' },
          isAvailableAsync: { type: 'function' },
          isTaskRegisteredAsync: { type: 'function' },
          notifyTaskFinishedAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          unregisterAllTasksAsync: { type: 'function' },
          unregisterTaskAsync: { type: 'function' },
        },
        ExpoTrackingTransparency: {
          addListener: { type: 'function' },
          getPermissionsAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          requestPermissionsAsync: { type: 'function' },
        },
        ExpoUpdates: {
          addListener: { type: 'function' },
          channel: { type: 'string' },
          checkForUpdateAsync: { type: 'function' },
          clearLogEntriesAsync: { type: 'function' },
          fetchUpdateAsync: { type: 'function' },
          isEmbeddedLaunch: { type: 'boolean', mock: false },
          isEnabled: { type: 'boolean', mock: false },
          isMissingRuntimeVersion: { type: 'boolean', mock: false },
          readLogEntriesAsync: { type: 'function' },
          releaseChannel: { type: 'string' },
          reload: { type: 'function' },
          removeListeners: { type: 'function' },
          runtimeVersion: { type: 'string' },
        },
        ExpoVideoThumbnails: {
          addListener: { type: 'function' },
          getThumbnail: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExpoVideoView: {
          ScaleAspectFill: { type: 'string' },
          ScaleAspectFit: { type: 'string' },
          ScaleNone: { type: 'string' },
          ScaleToFill: { type: 'string' },
          addListener: { type: 'function' },
          removeListeners: { type: 'function' },
          setFullscreen: { type: 'function' },
        },
        ExpoWebBrowser: {
          addListener: { type: 'function' },
          coolDownAsync: { type: 'function' },
          dismissAuthSession: { type: 'function' },
          dismissBrowser: { type: 'function' },
          getCustomTabsSupportingBrowsers: { type: 'function' },
          mayInitWithUrlAsync: { type: 'function' },
          openAuthSessionAsync: { type: 'function' },
          openBrowserAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          warmUpAsync: { type: 'function' },
        },
        ExponentAV: {
          Qualities: { type: 'object' },
          addListener: { type: 'function' },
          getAudioRecordingStatus: { type: 'function' },
          getAvailableInputs: { type: 'function' },
          getCurrentInput: { type: 'function' },
          getPermissionsAsync: { type: 'function' },
          getStatusForSound: { type: 'function' },
          getStatusForVideo: { type: 'function' },
          loadForSound: { type: 'function' },
          loadForVideo: { type: 'function' },
          pauseAudioRecording: { type: 'function' },
          prepareAudioRecorder: { type: 'function' },
          removeListeners: { type: 'function' },
          replaySound: { type: 'function' },
          replayVideo: { type: 'function' },
          requestPermissionsAsync: { type: 'function' },
          setAudioIsEnabled: { type: 'function' },
          setAudioMode: { type: 'function' },
          setInput: { type: 'function' },
          setStatusForSound: { type: 'function' },
          setStatusForVideo: { type: 'function' },
          startAudioRecording: { type: 'function' },
          stopAudioRecording: { type: 'function' },
          unloadAudioRecorder: { type: 'function' },
          unloadForSound: { type: 'function' },
          unloadForVideo: { type: 'function' },
        },
        ExponentCamera: {
          AutoFocus: { type: 'object' },
          FlashMode: { type: 'object' },
          Type: { type: 'object' },
          VideoCodec: { type: 'object' },
          VideoQuality: { type: 'object' },
          VideoStabilization: { type: 'object' },
          WhiteBalance: { type: 'object' },
          addListener: { type: 'function' },
          getAvailablePictureSizes: { type: 'function' },
          getAvailableVideoCodecsAsync: { type: 'function' },
          getCameraPermissionsAsync: { type: 'function' },
          getMicrophonePermissionsAsync: { type: 'function' },
          getPermissionsAsync: { type: 'function' },
          pausePreview: { type: 'function' },
          record: { type: 'function' },
          removeListeners: { type: 'function' },
          requestCameraPermissionsAsync: { type: 'function' },
          requestMicrophonePermissionsAsync: { type: 'function' },
          requestPermissionsAsync: { type: 'function' },
          resumePreview: { type: 'function' },
          stopRecording: { type: 'function' },
          takePicture: { type: 'function' },
        },
        ExponentConstants: {
          addListener: { type: 'function' },
          appOwnership: { type: 'string' },
          debugMode: { type: 'boolean', mock: true },
          deviceName: { type: 'string' },
          deviceYearClass: { type: 'number', mock: 2022 },
          executionEnvironment: { type: 'string' },
          experienceUrl: { type: 'string' },
          expoRuntimeVersion: { type: 'string' },
          expoVersion: { type: 'string' },
          getWebViewUserAgentAsync: { type: 'function' },
          installationId: { type: 'string' },
          isDetached: { type: 'boolean', mock: false },
          isDevice: { type: 'boolean', mock: false },
          isHeadless: { type: 'boolean', mock: false },
          linkingUri: { type: 'string' },
          manifest: { type: 'object' },
          nativeAppVersion: { type: 'string' },
          nativeBuildVersion: { type: 'string' },
          platform: { type: 'object' },
          removeListeners: { type: 'function' },
          sessionId: { type: 'string' },
          statusBarHeight: { type: 'number', mock: 54 },
          supportedExpoSdks: { type: 'array' },
          systemFonts: { type: 'array' },
        },
        ExponentDeviceMotion: {
          Gravity: { type: 'number', mock: 9.8100004196167 },
          addListener: { type: 'function' },
          isAvailableAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          setUpdateInterval: { type: 'function' },
        },
        ExponentFileSystem: {
          addListener: { type: 'function' },
          bundleDirectory: { type: 'object', mock: null },
          bundledAssets: { type: 'object', mock: null },
          cacheDirectory: { type: 'string' },
          copyAsync: { type: 'function' },
          deleteAsync: { type: 'function' },
          documentDirectory: { type: 'string' },
          downloadAsync: { type: 'function' },
          downloadResumablePauseAsync: { type: 'function' },
          downloadResumableStartAsync: { type: 'function' },
          getFreeDiskStorageAsync: { type: 'function' },
          getInfoAsync: { type: 'function' },
          getTotalDiskCapacityAsync: { type: 'function' },
          makeDirectoryAsync: { type: 'function' },
          moveAsync: { type: 'function' },
          networkTaskCancelAsync: { type: 'function' },
          readAsStringAsync: { type: 'function' },
          readDirectoryAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          uploadAsync: { type: 'function' },
          uploadTaskStartAsync: { type: 'function' },
          writeAsStringAsync: { type: 'function' },
        },
        ExponentGLView: {
          addListener: { type: 'function' },
          removeListeners: { type: 'function' },
        },
        ExponentImagePicker: {
          addListener: { type: 'function' },
          getCameraPermissionsAsync: { type: 'function' },
          getMediaLibraryPermissionsAsync: { type: 'function' },
          launchCameraAsync: { type: 'function' },
          launchImageLibraryAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          requestCameraPermissionsAsync: { type: 'function' },
          requestMediaLibraryPermissionsAsync: { type: 'function' },
        },
        ExponentPrint: {
          Orientation: { type: 'object' },
          addListener: { type: 'function' },
          print: { type: 'function' },
          printToFileAsync: { type: 'function' },
          removeListeners: { type: 'function' },
          selectPrinter: { type: 'function' },
        },
      },
    },
    viewManagersMetadata: {
      type: 'object',
      mock: {
        ExpoBlurView: { propsNames: ['tint', 'intensity'] },
        ExpoBarCodeScanner: { propsNames: ['type', 'barCodeTypes'] },
        ExpoAppleAuthenticationButtonContinueWhite: { propsNames: ['cornerRadius'] },
        ExpoLinearGradient: { propsNames: ['colors', 'startPoint', 'endPoint', 'locations'] },
        ExpoAppleAuthenticationButtonContinueWhiteOutline: { propsNames: ['cornerRadius'] },
        ExpoAppleAuthenticationButtonContinueBlack: { propsNames: ['cornerRadius'] },
        ExpoAppleAuthenticationButtonSignUpWhiteOutline: { propsNames: ['cornerRadius'] },
        ExpoAppleAuthenticationButtonSignUpBlack: { propsNames: ['cornerRadius'] },
        ExpoVideoView: { propsNames: ['status', 'useNativeControls', 'source', 'resizeMode'] },
        ExponentGLView: { propsNames: ['msaaSamples'] },
        ExpoAppleAuthenticationButtonSignInWhiteOutline: { propsNames: ['cornerRadius'] },
        ExpoAppleAuthenticationButtonSignInWhite: { propsNames: ['cornerRadius'] },
        ExpoAppleAuthenticationButtonSignUpWhite: { propsNames: ['cornerRadius'] },
        ExpoAppleAuthenticationButtonSignInBlack: { propsNames: ['cornerRadius'] },
        ExponentCamera: {
          propsNames: [
            'type',
            'flashMode',
            'faceDetectorSettings',
            'barCodeScannerSettings',
            'autoFocus',
            'focusDepth',
            'zoom',
            'whiteBalance',
            'pictureSize',
            'faceDetectorEnabled',
            'barCodeScannerEnabled',
          ],
        },
      },
    },
  },
  RNAWSCognito: {
    computeModPow: { type: 'function', functionType: 'async' },
    computeS: { type: 'function', functionType: 'async' },
    getConstants: { type: 'function' },
    getRandomBase64: { type: 'function', functionType: 'sync' },
  },
  RNBranch: {
    INIT_SESSION_ERROR: { type: 'string' },
    INIT_SESSION_START: { type: 'string' },
    INIT_SESSION_SUCCESS: { type: 'string' },
    STANDARD_EVENT_ACHIEVE_LEVEL: { type: 'string' },
    STANDARD_EVENT_ADD_PAYMENT_INFO: { type: 'string' },
    STANDARD_EVENT_ADD_TO_CART: { type: 'string' },
    STANDARD_EVENT_ADD_TO_WISHLIST: { type: 'string' },
    STANDARD_EVENT_CLICK_AD: { type: 'string' },
    STANDARD_EVENT_COMPLETE_REGISTRATION: { type: 'string' },
    STANDARD_EVENT_COMPLETE_TUTORIAL: { type: 'string' },
    STANDARD_EVENT_INITIATE_PURCHASE: { type: 'string' },
    STANDARD_EVENT_INVITE: { type: 'string' },
    STANDARD_EVENT_LOGIN: { type: 'string' },
    STANDARD_EVENT_PURCHASE: { type: 'string' },
    STANDARD_EVENT_RATE: { type: 'string' },
    STANDARD_EVENT_RESERVE: { type: 'string' },
    STANDARD_EVENT_SEARCH: { type: 'string' },
    STANDARD_EVENT_SHARE: { type: 'string' },
    STANDARD_EVENT_SPEND_CREDITS: { type: 'string' },
    STANDARD_EVENT_START_TRIAL: { type: 'string' },
    STANDARD_EVENT_SUBSCRIBE: { type: 'string' },
    STANDARD_EVENT_UNLOCK_ACHIEVEMENT: { type: 'string' },
    STANDARD_EVENT_VIEW_AD: { type: 'string' },
    STANDARD_EVENT_VIEW_CART: { type: 'string' },
    STANDARD_EVENT_VIEW_ITEM: { type: 'string' },
    STANDARD_EVENT_VIEW_ITEMS: { type: 'string' },
    createUniversalObject: { type: 'function', functionType: 'promise' },
    disableTracking: { type: 'function', functionType: 'async' },
    generateShortUrl: { type: 'function', functionType: 'promise' },
    getConstants: { type: 'function' },
    getCreditHistory: { type: 'function', functionType: 'promise' },
    getFirstReferringParams: { type: 'function', functionType: 'promise' },
    getLatestReferringParams: { type: 'function', functionType: 'promise' },
    getShortUrl: { type: 'function', functionType: 'promise' },
    initializeBranch: { type: 'function', functionType: 'promise' },
    isTrackingDisabled: { type: 'function', functionType: 'promise' },
    listOnSpotlight: { type: 'function', functionType: 'promise' },
    loadRewards: { type: 'function', functionType: 'promise' },
    logEvent: { type: 'function', functionType: 'promise' },
    logout: { type: 'function', functionType: 'async' },
    openURL: { type: 'function', functionType: 'async' },
    redeemInitSessionResult: { type: 'function', functionType: 'promise' },
    redeemRewards: { type: 'function', functionType: 'promise' },
    registerView: { type: 'function', functionType: 'promise' },
    releaseUniversalObject: { type: 'function', functionType: 'async' },
    sendCommerceEvent: { type: 'function', functionType: 'promise' },
    setIdentity: { type: 'function', functionType: 'async' },
    setRequestMetadataKey: { type: 'function', functionType: 'async' },
    showShareSheet: { type: 'function', functionType: 'promise' },
    userCompletedAction: { type: 'function', functionType: 'async' },
    userCompletedActionOnUniversalObject: { type: 'function', functionType: 'promise' },
  },
  RNBranchEventEmitter: {
    addListener: { type: 'function', functionType: 'async' },
    getConstants: { type: 'function' },
    removeListeners: { type: 'function', functionType: 'async' },
  },
  RNCMaskedViewManager: {},
  RNCNetInfo: {
    addListener: { type: 'function', functionType: 'async' },
    configure: { type: 'function', functionType: 'async' },
    getConstants: { type: 'function' },
    getCurrentState: { type: 'function', functionType: 'promise' },
    removeListeners: { type: 'function', functionType: 'async' },
  },
  RNCPickerManager: {},
  RNCSafeAreaContext: {
    getConstants: { type: 'function' },
    initialWindowMetrics: { type: 'object' },
  },
  RNCSafeAreaProvider: {},
  RNCSafeAreaView: {},
  RNCSegmentedControlManager: {},
  RNCSliderManager: {},
  RNCViewPager: {
    getConstants: { type: 'function' },
    setPage: { type: 'function', functionType: 'async' },
    setPageWithoutAnimation: { type: 'function', functionType: 'async' },
    setScrollEnabled: { type: 'function', functionType: 'async' },
  },
  RNCWebViewManager: {
    getConstants: { type: 'function' },
    goBack: { type: 'function', functionType: 'async' },
    goForward: { type: 'function', functionType: 'async' },
    injectJavaScript: { type: 'function', functionType: 'async' },
    postMessage: { type: 'function', functionType: 'async' },
    reload: { type: 'function', functionType: 'async' },
    requestFocus: { type: 'function', functionType: 'async' },
    startLoadWithResult: { type: 'function', functionType: 'async' },
    stopLoading: { type: 'function', functionType: 'async' },
  },
  RNDateTimePickerManager: {},
  RNGestureHandlerButton: {},
  RNGestureHandlerModule: {
    Direction: { type: 'object' },
    State: { type: 'object' },
    addListener: { type: 'function', functionType: 'async' },
    attachGestureHandler: { type: 'function', functionType: 'async' },
    createGestureHandler: { type: 'function', functionType: 'async' },
    dropGestureHandler: { type: 'function', functionType: 'async' },
    flushOperations: { type: 'function', functionType: 'async' },
    getConstants: { type: 'function' },
    handleClearJSResponder: { type: 'function', functionType: 'async' },
    handleSetJSResponder: { type: 'function', functionType: 'async' },
    removeListeners: { type: 'function', functionType: 'async' },
    updateGestureHandler: { type: 'function', functionType: 'async' },
  },
  RNSFullWindowOverlayManager: {},
  RNSScreenContainerManager: {},
  RNSScreenManager: {},
  RNSScreenNavigationContainerManager: {},
  RNSScreenStackHeaderConfigManager: {},
  RNSScreenStackHeaderSubviewManager: {},
  RNSScreenStackManager: {},
  RNSSearchBarManager: {},
  RNSVGCircleManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGClipPathManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGDefsManager: {},
  RNSVGEllipseManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGForeignObjectManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGGroupManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGImageManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGLineManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGLinearGradientManager: {},
  RNSVGMarkerManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGMaskManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGNodeManager: {},
  RNSVGPathManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGPatternManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGRadialGradientManager: {},
  RNSVGRectManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGRenderableManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGSvgViewManager: {
    getConstants: { type: 'function' },
    toDataURL: { type: 'function', functionType: 'async' },
  },
  RNSVGSymbolManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGTSpanManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGTextManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGTextPathManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSVGUseManager: {
    getBBox: { type: 'function', functionType: 'sync' },
    getCTM: { type: 'function', functionType: 'sync' },
    getConstants: { type: 'function' },
    getPointAtLength: { type: 'function', functionType: 'sync' },
    getScreenCTM: { type: 'function', functionType: 'sync' },
    getTotalLength: { type: 'function', functionType: 'sync' },
    isPointInFill: { type: 'function', functionType: 'sync' },
    isPointInStroke: { type: 'function', functionType: 'sync' },
  },
  RNSharedElementTransition: {
    configure: { type: 'function', functionType: 'promise' },
    getConstants: { type: 'function' },
  },
  RNSkia: {
    getConstants: { type: 'function' },
    install: { type: 'function', functionType: 'sync' },
  },
  RNViewShot: {
    captureRef: { type: 'function', functionType: 'promise' },
    captureScreen: { type: 'function', functionType: 'promise' },
    getConstants: { type: 'function' },
    releaseCapture: { type: 'function', functionType: 'async' },
  },
  ReanimatedModule: {
    addListener: { type: 'function', functionType: 'async' },
    animateNextTransition: { type: 'function', functionType: 'async' },
    attachEvent: { type: 'function', functionType: 'async' },
    connectNodeToView: { type: 'function', functionType: 'async' },
    connectNodes: { type: 'function', functionType: 'async' },
    createNode: { type: 'function', functionType: 'async' },
    detachEvent: { type: 'function', functionType: 'async' },
    disconnectNodeFromView: { type: 'function', functionType: 'async' },
    disconnectNodes: { type: 'function', functionType: 'async' },
    dropNode: { type: 'function', functionType: 'async' },
    getConstants: { type: 'function' },
    getValue: { type: 'function', functionType: 'async' },
    installTurboModule: { type: 'function', functionType: 'async' },
    removeListeners: { type: 'function', functionType: 'async' },
    setValue: { type: 'function', functionType: 'async' },
    triggerRender: { type: 'function', functionType: 'async' },
  },
};
