import 'react';
import 'react/jsx-dev-runtime';
import 'url';
import 'whatwg-fetch';
import 'react-devtools-core';
import 'base64-js';
import 'buffer';
import 'punycode';
import 'whatwg-url-without-unicode';
import 'pretty-format';
import 'event-target-shim';
import 'invariant';
import 'regenerator-runtime/runtime';
import 'react-refresh/runtime';
import 'react-native/Libraries/ReactNative/RendererProxy';
import '@react-native/normalize-colors';
import 'anser';
import "react-native/src/private/setup/setUpDOM"
// import '@react-native/virtualized-lists';
