/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function setFullscreen(viewTag: number, value: boolean): Promise<any> {}

export type ViewProps = {
  status: {
    [key: string]: any;
  };
  useNativeControls: boolean;
  source: {
    [key: string]: any;
  };
  resizeMode: string;
  onStatusUpdate: (event: any) => void;
  onLoadStart: (event: any) => void;
  onLoad: (event: any) => void;
  onError: (event: any) => void;
  onReadyForDisplay: (event: any) => void;
  onFullscreenUpdate: (event: any) => void;
};

export function View(props: ViewProps) {}
