#!/bin/bash


# iOS

npx react-native bundle \
    --platform ios \
    --dev false \
    --entry-file index.js \
    --bundle-output bundle/devlauncher.ios.bundle 

tee > ios/EXDevLauncherBundle.cpp <<EOF
// NOTE: Autogenerated using 'yarn bundle' in 'expo-dev-launcher' package

#include "EXDevLauncherBundle.h"
const unsigned int EXDevLauncherBundleLength = $(wc -c < bundle/devlauncher.ios.bundle) + 2;
const char *EXDevLauncherBundle = R"DELIM(
$(cat bundle/devlauncher.ios.bundle)





)DELIM";
EOF

rm bundle/devlauncher.ios.bundle


# Android

npx react-native bundle \
    --platform android \
    --dev false \
    --entry-file index.js \
    --bundle-output android/src/main/res/raw/expo_dev_launcher_android.bundle



