{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-permissions",
    "version": "13.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-permissions-13.2.0.aar",
          "url": "expo-permissions-13.2.0.aar",
          "size": 37863,
          "sha512": "463ae3eed10f79ea5b8f4a7098b9bb57db511d0d6d99e75bf36bb5bc84ea49d7903cd363b9751e9e6455abb057761af36f20add76752eab9c7cff8deca81f7fd",
          "sha256": "bf1b23469cece755a548ee49bd088f6338be08a7e529d4f241c619b231f70d5a",
          "sha1": "6764b3cf4b1cf048e61ac4cee1780ab217815805",
          "md5": "813cd3b3d16eae6e044a6ee2c7b0ed18"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-permissions-13.2.0.aar",
          "url": "expo-permissions-13.2.0.aar",
          "size": 37863,
          "sha512": "463ae3eed10f79ea5b8f4a7098b9bb57db511d0d6d99e75bf36bb5bc84ea49d7903cd363b9751e9e6455abb057761af36f20add76752eab9c7cff8deca81f7fd",
          "sha256": "bf1b23469cece755a548ee49bd088f6338be08a7e529d4f241c619b231f70d5a",
          "sha1": "6764b3cf4b1cf048e61ac4cee1780ab217815805",
          "md5": "813cd3b3d16eae6e044a6ee2c7b0ed18"
        }
      ]
    }
  ]
}
