name: "\U0001F64B Feature Request"
description: 'Want us to add something to Expo?'
labels: ['invalid issue: feature request']
body:
  - type: markdown
    attributes:
      value: Thanks for helping us make Expo even better! We track our feature requests on https://expo.canny.io, so that we can focus on bug reports on GitHub issues. Please post your feature request there instead.
  - type: dropdown
    attributes:
      label: Do you understand that any feature requests opened in the core Expo repository will be closed?
      options:
        - 'Yes'
    validations:
      required: true
