name: "\U0001F41B CLI Bug Report"
description: 'Report a reproducible bug in the versioned Expo CLI (npx expo)'
labels: ['needs validation', 'CLI']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: |
        If you leave out sections there is a high likelihood your issue will be closed.
        If you have a question or you think your issue might be caused by your application code, you can get help from the community on the [forums](https://forums.expo.dev/) or on [Discord](https://chat.expo.dev).
  - type: textarea
    attributes:
      label: Summary
      description: |
        Clearly describe what the expected behavior is vs. what is actually happening. This should be as short as possible, while still communicating all the necessary information.
        If your summary is simply, for example: "My device cannot connect to Wi-Fi.", then you will need to [continue debugging on your own](https://expo.fyi/manual-debugging) to more precisely define your issue before proceeding.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: false
  - type: input
    attributes:
      label: SDK Version
      description: What version of the Expo SDK are you using?
  - type: textarea
    attributes:
      label: Environment
      description: Run the `npx expo-env-info` command and paste its output in the field below.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproducible example
      description: |
        A link to a GitHub repository containing a minimal reproducible example. This repository should include as little code as possible and not include extraneous dependencies. The most effective reproducible examples are created by starting a new project from scratch and adding in only the necessary pieces to reproduce the issue. Do not share your entire project.
        List the steps you took to generate the reproducible example within that repository in the README or the summary field below along with any instructions needed to run the project.
        You must also test your issue against the latest CLI version to ensure that it hasn't already been resolved.
        If a reproducible example is not provided, your issue will be closed.
        [Learn more about creating a minimal reproducible example](https://stackoverflow.com/help/mcve).
    validations:
      required: true
  - type: markdown
    attributes:
      value: Please make sure contributors can run your code and follow the steps your provided in order to reproduce the bug.
  - type: markdown
    attributes:
      value: |
        **Realize that it is up to you to debug your code and be as certain as possible that the bug is with Expo, not with your own app.**
        [Here's an excellent guide to debugging you can follow](https://gist.github.com/brentvatne/5ac00cba0c70b7a06b89a56787d6bc4a).
