name: "\U0001F41B SDK Bug Report"
description: 'Report a reproducible bug in the Expo SDK'
labels: ['needs validation']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! If you are convinced that you have found a bug in Expo tools, this is the right place. Please fill out this entire form. The most important piece is a minimal reproducible example.
  - type: markdown
    attributes:
      value: If you have a question or you think your issue might be caused by your application code, you can get help from the community on the [forums](https://forums.expo.dev/) or on [Discord](https://chat.expo.dev).
  - type: input
    attributes:
      label: Minimal reproducible example
      description: |
        A link to a GitHub repository containing a minimal reproducible example. This repository should include as little code as possible and not include extraneous dependencies. The most effective reproducible examples are created by starting a new project from scratch and adding in only the necessary pieces to reproduce the issue. Do not share your entire project.
        List the steps you took to generate the reproducible example within that repository in the README or the summary field below along with any instructions needed to run the project.
        You should also test your issue against the latest SDK version to ensure that it hasn't already been resolved.
        If a reproducible example is not provided, your issue will be closed.
        [Learn more about creating a minimal reproducible example](https://stackoverflow.com/help/mcve).
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Where did you reproduce the issue?
      multiple: true
      options:
        - in a development build
        - in Expo Go
        - in a standalone app
        - on web
      description: |
        If you are reporting an issue within your standalone app that is not reproducible in Expo Go, you should test your code in a [development build](https://docs.expo.dev/develop/development-builds/introduction/) before submitting an issue. A development build is a much more accurate representation of how your standalone app will work, and many such issues can be resolved by troubleshooting with a development build.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Realize that it is up to you to debug your code and be as certain as possible that the bug is with Expo, not with your own app.**
        [Here's an excellent guide to debugging you can follow](https://gist.github.com/brentvatne/5ac00cba0c70b7a06b89a56787d6bc4a).
  - type: textarea
    attributes:
      label: Summary
      description: |
        Clearly describe what the expected behavior is and what instead is actually happening. Be concise and precise in your description. Include any affected platforms (iOS, Android, web).
        Ex: if you report that "X library/method isn't working", then you will need to [continue debugging on your own](https://expo.fyi/manual-debugging) to more precisely define your issue before proceeding.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: Run the `npx expo-env-info` command and paste its output in the field below.
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expo Doctor Diagnostics
      description: Run the `npx expo-doctor@latest` command on your minimal reproduction and paste its output in the field below. If Doctor reports any errors, fix them before submitting the issue.
      render: text
    validations:
      required: true
