name: "\U0001F41B SDK Bug Report"
description: 'Report a reproducible bug in the Expo SDK'
labels: 'needs review'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! If you are convinced that you have found a bug in Expo tools, this is the right place. Please fill out this entire form.
  - type: markdown
    attributes:
      value: If you have a question or you think your issue might be caused by your application code, you can get help from the community on the [forums](https://forums.expo.dev/) or on [Discord](https://chat.expo.dev).
  - type: textarea
    attributes:
      label: Summary
      description: Describe the issue
      placeholder: Clearly describe what the expected behavior is vs. what is actually happening. Try to be concise and precise. If all you have to report is that 'X library/method isn't working', then will need to [continue debugging on your own](https://expo.fyi/manual-debugging) to more precisely articulate your issue before proceeding.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Not Applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: Run `npx expo-env-info` and paste the output here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproducible example
      description: 'This should include as little code as possible, and no extraneous dependencies. Do not share your entire project. Sharing a link to a [Snack](https://snack.expo.dev/) is often the best approach, but in some cases a GitHub repository is required. If a reproducible demo is not provided, your issue will be closed. You must also test your issue against the latest SDK version to ensure that it hasn't already been resolved. [Learn more about creating a minimal reproducible example](https://stackoverflow.com/help/mcve).'
    validations:
      required: true
  - type: markdown
    attributes:
`     value: Please make sure contributors can run your Snack or repository, and you explain how to reproduce the issue once the example is running.