name: "\U0001F6E0 Development Client Bug Report"
description: 'Report a reproducible issue with a Custom Development Client'
labels: ['Custom Client', 'needs review']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible so we have the information we need to help.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood your issue will be closed. If you have a question, not a bug report, please post it on our [forums](https://forums.expo.dev/) instead.
  - type: markdown
    attributes:
      value: 'IMPORTANT: Before filling out this template further, ensure you have the latest version of the `expo-dev-client` package, `expo-cli`, and (if applicable) `eas-cli`. If not, try upgrading first and see if that fixes your issue.'
  - type: textarea
    attributes:
      label: Summary
      description: Describe the issue in 1 or 2 sentences
      placeholder: Clearly describe what the expected behavior is vs. what is actually happening. This should be as short as possible, while still communicating all the necessary information. If your summary is just 'X library/method isn't working', then you need to continue debugging yourself and provide more information.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!
      options:
        - managed
        - bare
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: textarea
    attributes:
      label: Package versions
      description: 'List the package versions of `expo-dev-client`, `expo-updates`, and any other relevant libraries in your project.'
  - type: textarea
    attributes:
      label: Environment
      placeholder: Run `expo diagnostics` and paste the output here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducible demo or steps to reproduce from a blank project
      description: 'This should include as little code as possible, do not simply link your entire project. If a reproducible demo, or a complete list of steps from blank project to bug, is not provided, it is very likely your issue will be closed. If you link to a project that contains multiple non-Expo-core modules, it is unlikely to help us narrow down the cause of your issue more quickly. Read more guidance [here](https://stackoverflow.com/help/mcve).'
    validations:
      required: true
  - type: markdown
    attributes:
      value: Please make sure contributors can follow the steps you provided in order to reproduce the bug.
  - type: textarea
    attributes:
      label: Stacktrace (if a crash is involved)
      description: 'If your issue involves a crash, please provide the native stacktrace if you are able.'
  - type: markdown
    attributes:
      value: "**Realize that it is up to you to debug your code and be as certain as possible that the bug is with Expo, not with your own app.** [Here's an excellent guide to debugging you can follow](https://gist.github.com/brentvatne/5ac00cba0c70b7a06b89a56787d6bc4a)."
