name: "\U0001F4C3 Documentation Bug"
description: 'You want to report something that is wrong or missing from the documentation.'
title: '[docs] '
labels: ['docs']
body:
  - type: markdown
    attributes:
      value: Thanks for helping us make Expo even better! We want our docs to be an amazing resource, and that requires your feedback!
  - type: textarea
    attributes:
      label: Summary
      description: Clearly describe what is wrong or missing from the docs.
    validations:
      required: true
  - type: input
    attributes:
      label: Link to the related docs page
    validations:
      required: true
  - type: markdown
    attributes:
      value: If this is a typo, or something you feel up to fixing, please do so! You can edit any page in our docs by scrolling to the bottom and selecting `Edit this page`.
  - type: textarea
    attributes:
      label: Anything else?
