name: "\U0001F64B Feature Request"
about: 'Want us to add something to Expo?'
issue_body: false
inputs:
  - type: description
    attributes:
      value: Thanks for helping us make Expo even better! 😀 Unfortunately, this is not the right place for feature requests. Please find and upvote your feature (or create a new one) at https://expo.canny.io instead.
  - type: description
    attributes:
      value: Feature requests opened in the core Expo repository will be closed.
