export { default as Accelerometer } from './Accelerometer';
export { default as Barometer, BarometerMeasurement } from './Barometer';
export { default as DeviceMotion, DeviceMotionMeasurement } from './DeviceMotion';
export { default as Gyroscope } from './Gyroscope';
export { default as Magnetometer } from './Magnetometer';
export { default as MagnetometerUncalibrated } from './MagnetometerUncalibrated';
export { ThreeAxisMeasurement } from './ThreeAxisSensor';
import * as Pedometer from './Pedometer';
export { Pedometer };
export { default as DeviceSensor } from './DeviceSensor';
