[versions]
# Android versions
minSdk = "21"
targetSdk = "34"
compileSdk = "34"
buildTools = "34.0.0"
# Dependencies versions
agp = "8.1.1"
fresco = "3.1.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
fresco-middleware = { module = "com.facebook.fresco:middleware", version.ref = "fresco" }
fresco-animated-gif  = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
fresco-animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
fresco-webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }

