module.exports = {
  name: 'expo/eslint/base',
  languageOptions: {
    ecmaVersion: 2022,
    sourceType: 'module',
    parser: require('@babel/eslint-parser'),
    globals: {
      console: 'readonly',
      exports: 'readonly',
      global: 'readonly',
      module: 'readonly',
      require: 'readonly',
    },
  },
  rules: {
    eqeqeq: ['warn', 'smart'],
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty-character-class': 'warn',
    'no-empty-pattern': 'warn',
    'no-extend-native': 'warn',
    'no-extra-bind': 'warn',
    'no-redeclare': 'warn',
    'no-undef': 'error',
    'no-unreachable': 'warn',
    'no-unsafe-negation': 'warn',
    'no-unused-expressions': ['warn', { allowShortCircuit: true, enforceForJSX: true }],
    'no-unused-labels': 'warn',
    'no-unused-vars': [
      'warn',
      { vars: 'all', args: 'none', ignoreRestSiblings: true, caughtErrors: 'all', caughtErrorsIgnorePattern: '^_' },
    ],
    'no-with': 'warn',
    'unicode-bom': ['warn', 'never'],
    'use-isnan': 'error',
    'valid-typeof': 'error',
  },
};
