/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type ViewProps = {
  msaaSamples: number;
  enableExperimentalWorkletSupport: boolean;
  onSurfaceCreate: (event: any) => void;
};

export function View(props: ViewProps) {}
