/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type DocumentPickerOptions = any;

export async function getDocumentAsync(options: DocumentPickerOptions): Promise<any> {}
