/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifdef ABI37_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// FB Internal: Plugins.h is autogenerated by the build system.
#import "ABI37_0_0Plugins.h"

#else

// OSS-compatibility layer

#import <Foundation/Foundation.h>

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"

#ifdef __cplusplus
extern "C" {
#endif

// ABI37_0_0RCTTurboModuleManagerDelegate should call this to resolve module classes.
Class ABI37_0_0RCTCoreModulesClassProvider(const char *name);

// Lookup functions
Class ABI37_0_0RCTExceptionsManagerCls(void);
Class ABI37_0_0RCTImageLoaderCls(void);
Class ABI37_0_0RCTPlatformCls(void);

#ifdef __cplusplus
}
#endif

#pragma GCC diagnostic pop

#endif // ABI37_0_0RN_DISABLE_OSS_PLUGIN_HEADER
