{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-in-app-purchases",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-in-app-purchases-13.0.0.aar",
          "url": "expo-in-app-purchases-13.0.0.aar",
          "size": 39430,
          "sha512": "de0e5a71deb6e2cf196617df70c15b1e691b1d1b65598ffb36c8d01269528babd61bbc5f1d110e3bbbe402dba988c9b9a49439fa6e60f7f00e11980ad6cac97d",
          "sha256": "57dcc80de0b30107f7f7d205271756112e7f428c236456666c1df6af491f3376",
          "sha1": "94a9b0a11c8619a65d56c521745abc641a1d9c02",
          "md5": "bba9dd2f521015453a42a73a18d83081"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-in-app-purchases-13.0.0.aar",
          "url": "expo-in-app-purchases-13.0.0.aar",
          "size": 39430,
          "sha512": "de0e5a71deb6e2cf196617df70c15b1e691b1d1b65598ffb36c8d01269528babd61bbc5f1d110e3bbbe402dba988c9b9a49439fa6e60f7f00e11980ad6cac97d",
          "sha256": "57dcc80de0b30107f7f7d205271756112e7f428c236456666c1df6af491f3376",
          "sha1": "94a9b0a11c8619a65d56c521745abc641a1d9c02",
          "md5": "bba9dd2f521015453a42a73a18d83081"
        }
      ]
    }
  ]
}
