{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-image-picker",
    "version": "13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "expo-image-picker-13.0.1.aar",
          "url": "expo-image-picker-13.0.1.aar",
          "size": 83353,
          "sha512": "147b16e6d893e663d6145a97fecd74c2354b14007f206bb5fa56b4f1b08f6b4e0a1866c5a6e059cb66677cdc26d18db90dff71dad19ea68c3c2019ecd0a24f2b",
          "sha256": "30cd2993f67ea1c32c06b6759a8dcfdcafed135a71f61d39a5efceb991b79d34",
          "sha1": "299676f8f89f3c618555031323674d4edb0962f4",
          "md5": "5b90d92298ef282545579b7276830d87"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.github.CanHub",
          "module": "Android-Image-Cropper",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "expo-image-picker-13.0.1.aar",
          "url": "expo-image-picker-13.0.1.aar",
          "size": 83353,
          "sha512": "147b16e6d893e663d6145a97fecd74c2354b14007f206bb5fa56b4f1b08f6b4e0a1866c5a6e059cb66677cdc26d18db90dff71dad19ea68c3c2019ecd0a24f2b",
          "sha256": "30cd2993f67ea1c32c06b6759a8dcfdcafed135a71f61d39a5efceb991b79d34",
          "sha1": "299676f8f89f3c618555031323674d4edb0962f4",
          "md5": "5b90d92298ef282545579b7276830d87"
        }
      ]
    }
  ]
}
