export default {
  light: {
    tint: '#4630eb',
    text: '#000020',
    secondaryText: '#555',
    grayText: '#a7aab0',
    background: '#f5f5f7',
    secondaryBackground: '#fff',
    border: '#ebebed',
    menuItemText: '#000020',
    appIconPlaceholderBackground: '#f5f5f5',
    appIconPlaceholderBorder: '#c5c5c5',
  },
  dark: {
    tint: '#aca2f6',
    text: '#fff',
    secondaryText: '#ccc',
    grayText: '#a7aab0',
    background: '#000',
    secondaryBackground: '#1c1c1e',
    border: '#303033',
    menuItemText: '#fff',
    appIconPlaceholderBackground: '#333',
    appIconPlaceholderBorder: '#555',
  },
};
