export default {
  light: {
    tint: '#4630eb',
    text: '#000020',
    secondaryText: '#555',
    grayText: '#a7aab0',
    disabledTest: '#a7aab0',
    background: '#f5f5f7',
    secondaryBackground: '#fff',
    border: '#ebebed',
    menuItemText: '#000020',
    appIconPlaceholderBackground: '#f5f5f5',
    appIconPlaceholderBorder: '#c5c5c5',
    warningBackground: '#fef6d0',
    warningColor: '#886636',
    warningBorders: '#fceca8',
    error: '#dc3545',
  },
  dark: {
    tint: '#aca2f6',
    text: '#fff',
    secondaryText: '#ccc',
    grayText: '#a7aab0',
    disabledTest: '#5e6063',
    background: '#000',
    secondaryBackground: '#1c1c1e',
    border: '#303033',
    menuItemText: '#ddd',
    appIconPlaceholderBackground: '#333',
    appIconPlaceholderBorder: '#555',
    warningBackground: '#feffb0',
    warningColor: '#886636',
    warningBorders: '#fceca8',
    error: '#dc3545',
  },
};
