const expose = (name, getter) => __native__d((_, __, ___, ____, module) => {module.exports=getter()}, `native:${name}`);

__native__d((_, __, ___, ____, module) => {module.exports=require('react')}, 'native:react');
__native__d((_, __, ___, ____, module) => {module.exports=require('react/jsx-dev-runtime')}, 'native:react/jsx-dev-runtime');
__native__d((_, __, ___, ____, module) => {module.exports=require('react/jsx-runtime')}, 'native:react/jsx-runtime');
__native__d((_, __, ___, ____, module) => {module.exports=require('url')}, 'native:url');
__native__d((_, __, ___, ____, module) => {module.exports=require('whatwg-fetch')}, 'native:whatwg-fetch');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-devtools-core')}, 'native:react-devtools-core');
__native__d((_, __, ___, ____, module) => {module.exports=require('base64-js')}, 'native:base64-js');
__native__d((_, __, ___, ____, module) => {module.exports=require('buffer')}, 'native:buffer');
__native__d((_, __, ___, ____, module) => {module.exports=require('punycode')}, 'native:punycode');
__native__d((_, __, ___, ____, module) => {module.exports=require('whatwg-url-without-unicode')}, 'native:whatwg-url-without-unicode');
__native__d((_, __, ___, ____, module) => {module.exports=require('pretty-format')}, 'native:pretty-format');
__native__d((_, __, ___, ____, module) => {module.exports=require('event-target-shim')}, 'native:event-target-shim');
__native__d((_, __, ___, ____, module) => {module.exports=require('invariant')}, 'native:invariant');
__native__d((_, __, ___, ____, module) => {module.exports=require('scheduler')}, 'native:scheduler');
__native__d((_, __, ___, ____, module) => {module.exports=require('regenerator-runtime/runtime')}, 'native:regenerator-runtime/runtime');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-refresh/runtime')}, 'native:react-refresh/runtime');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-native/normalize-colors')},'native:@react-native/normalize-colors');
__native__d((_, __, ___, ____, module) => {module.exports=require('anser')}, 'native:anser');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native')}, 'native:react-native');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/src/private/setup/setUpDOM')},'native:react-native/src/private/setup/setUpDOM');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/src/private/featureflags/ReactNativeFeatureFlags')},'native:react-native/src/private/featureflags/ReactNativeFeatureFlags');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/NativeComponent/NativeComponentRegistry')},'native:react-native/Libraries/NativeComponent/NativeComponentRegistry');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/Utilities/PolyfillFunctions')},'native:react-native/Libraries/Utilities/PolyfillFunctions');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/ReactPrivate/ReactNativePrivateInterface')},'native:react-native/Libraries/ReactPrivate/ReactNativePrivateInterface');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/Image/resolveAssetSource')},'native:react-native/Libraries/Image/resolveAssetSource');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/StyleSheet/processColor')},'native:react-native/Libraries/StyleSheet/processColor');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/NativeComponent/ViewConfigIgnore')},'native:react-native/Libraries/NativeComponent/ViewConfigIgnore');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/StyleSheet/processColorArray')},'native:react-native/Libraries/StyleSheet/processColorArray');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/NativeModules/specs/NativeSourceCode')},'native:react-native/Libraries/NativeModules/specs/NativeSourceCode');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/Image/AssetSourceResolver')},'native:react-native/Libraries/Image/AssetSourceResolver');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore')},'native:react-native/Libraries/ReactPrivate/ReactNativePrivateInitializeCore');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-modules-core')}, 'native:expo-modules-core');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-modules-core/src/LegacyEventEmitter')},'native:expo-modules-core/src/LegacyEventEmitter');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo')}, 'native:expo');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo/dom')}, 'native:expo/dom');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo/dom/global')}, 'native:expo/dom/global');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-asset')}, 'native:expo-asset');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-constants')}, 'native:expo-constants');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-keep-awake')}, 'native:expo-keep-awake');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-status-bar')}, 'native:expo-status-bar');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-blur')}, 'native:expo-blur');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-font')}, 'native:expo-font');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-haptics')}, 'native:expo-haptics');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-image')}, 'native:expo-image');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-linking')}, 'native:expo-linking');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-splash-screen')}, 'native:expo-splash-screen');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-symbols')}, 'native:expo-symbols');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-system-ui')}, 'native:expo-system-ui');
__native__d((_, __, ___, ____, module) => {module.exports=require('expo-web-browser')}, 'native:expo-web-browser');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native-gesture-handler')}, 'native:react-native-gesture-handler');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native-reanimated')}, 'native:react-native-reanimated');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native-safe-area-context')},'native:react-native-safe-area-context');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native-screens')}, 'native:react-native-screens');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native-webview')}, 'native:react-native-webview');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-native-masked-view/masked-view')},'native:@react-native-masked-view/masked-view');
__native__d((_, __, ___, ____, module) => {module.exports=require('color')}, 'native:color');
__native__d((_, __, ___, ____, module) => {module.exports=require('color-string')}, 'native:color-string');
__native__d((_, __, ___, ____, module) => {module.exports=require('color-name')}, 'native:color-name');
__native__d((_, __, ___, ____, module) => {module.exports=require('@radix-ui/react-compose-refs')}, 'native:@radix-ui/react-compose-refs');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-navigation/routers')}, 'native:@react-navigation/routers');
__native__d((_, __, ___, ____, module) => {module.exports=require('nanoid/non-secure')}, 'native:nanoid/non-secure');
__native__d((_, __, ___, ____, module) => {module.exports=require('use-latest-callback')}, 'native:use-latest-callback');
__native__d((_, __, ___, ____, module) => {module.exports=require('query-string')}, 'native:query-string');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-is')}, 'native:react-is');
__native__d((_, __, ___, ____, module) => {module.exports=require('use-sync-external-store')}, 'native:use-sync-external-store');
__native__d((_, __, ___, ____, module) => {module.exports=require('use-sync-external-store/with-selector')},'native:use-sync-external-store/with-selector');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-navigation/core')}, 'native:@react-navigation/core');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-navigation/native')}, 'native:@react-navigation/native');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-navigation/elements')}, 'native:@react-navigation/elements');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-navigation/native-stack')},'native:@react-navigation/native-stack');
__native__d((_, __, ___, ____, module) => {module.exports=require('@react-navigation/bottom-tabs')}, 'native:@react-navigation/bottom-tabs');
__native__d((_, __, ___, ____, module) => {module.exports=require('@radix-ui/react-slot')}, 'native:@radix-ui/react-slot');
__native__d((_, __, ___, ____, module) => {module.exports=require('react-native-is-edge-to-edge')}, 'native:react-native-is-edge-to-edge');
__native__d((_, __, ___, ____, module) => {module.exports=require('stacktrace-parser')}, 'native:stacktrace-parser');

// // TODO: Full metro-runtime will likely not work with native embedding.
// // import "@expo/metro-runtime";
