{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-calendar",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-calendar-10.2.0.aar",
          "url": "expo-calendar-10.2.0.aar",
          "size": 82066,
          "sha512": "00e9a89d2ce1948b1f2e1c7a1e41d1c5ab5967506ffe3c7436a0f28b26ccf78db5da64004b1f38b4f0f052a4b17fb4bf5120372ba67ed7e68d82201604ea32b7",
          "sha256": "a25acc204014d41e0235fd05d3504002534b2844ff9eff0bb22501fbe8c50272",
          "sha1": "25f30ffcb8fa378372692e89087d6a1a5fc1f773",
          "md5": "e0d01842d0943fca238055f87fa659e4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "expo-calendar-10.2.0.aar",
          "url": "expo-calendar-10.2.0.aar",
          "size": 82066,
          "sha512": "00e9a89d2ce1948b1f2e1c7a1e41d1c5ab5967506ffe3c7436a0f28b26ccf78db5da64004b1f38b4f0f052a4b17fb4bf5120372ba67ed7e68d82201604ea32b7",
          "sha256": "a25acc204014d41e0235fd05d3504002534b2844ff9eff0bb22501fbe8c50272",
          "sha1": "25f30ffcb8fa378372692e89087d6a1a5fc1f773",
          "md5": "e0d01842d0943fca238055f87fa659e4"
        }
      ]
    }
  ]
}
