{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-face-detector",
    "version": "11.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-face-detector-11.2.0.aar",
          "url": "expo-face-detector-11.2.0.aar",
          "size": 39963,
          "sha512": "f684b8f127a50b5e824e6cc2fa73345bd2c6c4dfe928eb44814a2e3de07824ae70754a57e5f61a54132d63b5b181bd6714bc44cf06d35e0a46fef90c4e735e96",
          "sha256": "127f809b32dddcc83f8cfaac7ad9ecc919dbcf62a15751ca72113c71c800fa95",
          "sha1": "419cd549481ff2f91fa66208547902ad78130e86",
          "md5": "b19bef19fb98f844833746a40b76b214"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-face-detector-11.2.0.aar",
          "url": "expo-face-detector-11.2.0.aar",
          "size": 39963,
          "sha512": "f684b8f127a50b5e824e6cc2fa73345bd2c6c4dfe928eb44814a2e3de07824ae70754a57e5f61a54132d63b5b181bd6714bc44cf06d35e0a46fef90c4e735e96",
          "sha256": "127f809b32dddcc83f8cfaac7ad9ecc919dbcf62a15751ca72113c71c800fa95",
          "sha1": "419cd549481ff2f91fa66208547902ad78130e86",
          "md5": "b19bef19fb98f844833746a40b76b214"
        }
      ]
    }
  ]
}
