/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifndef ABI46_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// OSS-compatibility layer

#import "ABI46_0_0CoreModulesPlugins.h"

#import <string>
#import <unordered_map>

Class ABI46_0_0RCTCoreModulesClassProvider(const char *name) {
  // Intentionally leak to avoid crashing after static destructors are run.
  static const auto sCoreModuleClassMap = new const std::unordered_map<std::string, Class (*)(void)>{
    {"AccessibilityManager", ABI46_0_0RCTAccessibilityManagerCls},
    {"Appearance", ABI46_0_0RCTAppearanceCls},
    {"DeviceInfo", ABI46_0_0RCTDeviceInfoCls},
    {"ExceptionsManager", ABI46_0_0RCTExceptionsManagerCls},
    {"PlatformConstants", ABI46_0_0RCTPlatformCls},
    {"Clipboard", ABI46_0_0RCTClipboardCls},
    {"I18nManager", ABI46_0_0RCTI18nManagerCls},
    {"SourceCode", ABI46_0_0RCTSourceCodeCls},
    {"ActionSheetManager", ABI46_0_0RCTActionSheetManagerCls},
    {"AlertManager", ABI46_0_0RCTAlertManagerCls},
    {"AsyncLocalStorage", ABI46_0_0RCTAsyncLocalStorageCls},
    {"Timing", ABI46_0_0RCTTimingCls},
    {"StatusBarManager", ABI46_0_0RCTStatusBarManagerCls},
    {"KeyboardObserver", ABI46_0_0RCTKeyboardObserverCls},
    {"AppState", ABI46_0_0RCTAppStateCls},
    {"PerfMonitor", ABI46_0_0RCTPerfMonitorCls},
    {"DevMenu", ABI46_0_0RCTDevMenuCls},
    {"DevSettings", ABI46_0_0RCTDevSettingsCls},
    {"RedBox", ABI46_0_0RCTRedBoxCls},
    {"LogBox", ABI46_0_0RCTLogBoxCls},
    {"WebSocketExecutor", ABI46_0_0RCTWebSocketExecutorCls},
    {"WebSocketModule", ABI46_0_0RCTWebSocketModuleCls},
    {"DevLoadingView", ABI46_0_0RCTDevLoadingViewCls},
    {"DevSplitBundleLoader", ABI46_0_0RCTDevSplitBundleLoaderCls},
    {"EventDispatcher", ABI46_0_0RCTEventDispatcherCls},
  };

  auto p = sCoreModuleClassMap->find(name);
  if (p != sCoreModuleClassMap->end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return nil;
}

#endif // ABI46_0_0RN_DISABLE_OSS_PLUGIN_HEADER
