/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package abi48_0_0.host.exp.exponent.modules.api.safeareacontext;

import android.view.View;
import androidx.annotation.Nullable;
import abi48_0_0.com.facebook.react.uimanager.BaseViewManagerDelegate;
import abi48_0_0.com.facebook.react.uimanager.BaseViewManagerInterface;

public class RNCSafeAreaProviderManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & RNCSafeAreaProviderManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public RNCSafeAreaProviderManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    super.setProperty(view, propName, value);
  }
}
