/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package abi48_0_0.host.exp.exponent.modules.api.safeareacontext;

import android.view.View;
import androidx.annotation.Nullable;
import abi48_0_0.com.facebook.react.bridge.ReadableArray;

public interface RNCSafeAreaViewManagerInterface<T extends View> {
  void setMode(T view, @Nullable String value);
  void setEdges(T view, @Nullable ReadableArray value);
}
