{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-camera",
    "version": "12.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "cameraview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-camera-12.2.0.aar",
          "url": "expo-camera-12.2.0.aar",
          "size": 99884,
          "sha512": "a6f104190413e461033172f27fba7cfeff95d1bfab36e8c031aa174070f28f62ce5586ea6fdcb52604d07ab9f2da91931c7a766f81a7acdd7efe19c76bcdcde3",
          "sha256": "65503c5d3ed14021679bd2f56740b0c012a1c37d8a7284ccacf0e397ae58fa71",
          "sha1": "1d37ffa36fbc67918e4f5ebad83b0fc32ece71e3",
          "md5": "c4770c6dcd6e92916d130543f0241da4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "cameraview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-camera-12.2.0.aar",
          "url": "expo-camera-12.2.0.aar",
          "size": 99884,
          "sha512": "a6f104190413e461033172f27fba7cfeff95d1bfab36e8c031aa174070f28f62ce5586ea6fdcb52604d07ab9f2da91931c7a766f81a7acdd7efe19c76bcdcde3",
          "sha256": "65503c5d3ed14021679bd2f56740b0c012a1c37d8a7284ccacf0e397ae58fa71",
          "sha1": "1d37ffa36fbc67918e4f5ebad83b0fc32ece71e3",
          "md5": "c4770c6dcd6e92916d130543f0241da4"
        }
      ]
    }
  ]
}
