{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-image-loader",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-image-loader-3.2.0.aar",
          "url": "expo-image-loader-3.2.0.aar",
          "size": 24192,
          "sha512": "c60b79eea59705591b832bbac9ba84583dadfddb0c656073af1daf70674f84fb95ab9edfd664869b7b3972cc6dcb1e8cfd1fe13531087756aaa7e7a3387ffcdc",
          "sha256": "80d645dea5a33241528e77a2b1cdc51da2cb7193e3094e8d4b5da01e66e6ffc8",
          "sha1": "8cd8bff38802b94c926b9d82dbefc6c9d291ab86",
          "md5": "6ddf43761948b728673eda91a416942c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-image-loader-3.2.0.aar",
          "url": "expo-image-loader-3.2.0.aar",
          "size": 24192,
          "sha512": "c60b79eea59705591b832bbac9ba84583dadfddb0c656073af1daf70674f84fb95ab9edfd664869b7b3972cc6dcb1e8cfd1fe13531087756aaa7e7a3387ffcdc",
          "sha256": "80d645dea5a33241528e77a2b1cdc51da2cb7193e3094e8d4b5da01e66e6ffc8",
          "sha1": "8cd8bff38802b94c926b9d82dbefc6c9d291ab86",
          "md5": "6ddf43761948b728673eda91a416942c"
        }
      ]
    }
  ]
}
