{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-speech",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-speech-10.2.0.aar",
          "url": "expo-speech-10.2.0.aar",
          "size": 37759,
          "sha512": "85e56b6f6a37cf286a9fc0a5f32b24420862c5deb9dc3909a75b41334eecc0b31eecedee022095331409935ae32d14195f282027c0224e655957333d05a13e29",
          "sha256": "895a71767a6dd03565c3029dca51009211f4ab1ccc6ceff830a643ad27869ffb",
          "sha1": "9706f7826dabeb2f913e2d8ee0b2e4eaa76979f6",
          "md5": "18ae1a43423dc15038c05fcc5499acdd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-speech-10.2.0.aar",
          "url": "expo-speech-10.2.0.aar",
          "size": 37759,
          "sha512": "85e56b6f6a37cf286a9fc0a5f32b24420862c5deb9dc3909a75b41334eecc0b31eecedee022095331409935ae32d14195f282027c0224e655957333d05a13e29",
          "sha256": "895a71767a6dd03565c3029dca51009211f4ab1ccc6ceff830a643ad27869ffb",
          "sha1": "9706f7826dabeb2f913e2d8ee0b2e4eaa76979f6",
          "md5": "18ae1a43423dc15038c05fcc5499acdd"
        }
      ]
    }
  ]
}
