# @generated by expotools

require './versioned-react-native/ABI37_0_0/ReactNative/autolink-ios.rb'

use_react_native_ABI37_0_0! path: './versioned-react-native/ABI37_0_0/ReactNative'

pod 'ABI37_0_0ExpoKit',
  :path => './versioned-react-native/ABI37_0_0/Expo/ExpoKit',
  :project_name => 'ABI37_0_0',
  :subspecs => ['Expo', 'ExpoOptional']

pod 'ABI37_0_0UMCore',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMCore',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMReactNativeAdapter',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMReactNativeAdapter',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXAdsAdMob',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXAdsAdMob',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXAdsFacebook',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXAdsFacebook',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXAmplitude',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXAmplitude',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSegment',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSegment',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXAppAuth',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXAppAuth',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXAppleAuthentication',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXAppleAuthentication',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXApplication',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXApplication',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXAV',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXAV',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXBackgroundFetch',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXBackgroundFetch',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXBarCodeScanner',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXBarCodeScanner',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXBattery',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXBattery',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXBluetooth',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXBluetooth',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXBlur',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXBlur',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXBrightness',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXBrightness',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXCalendar',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXCalendar',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXCamera',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXCamera',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXCellular',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXCellular',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXConstants',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXConstants',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXContacts',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXContacts',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXCrypto',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXCrypto',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXDevice',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXDevice',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXDocumentPicker',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXDocumentPicker',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXErrorRecovery',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXErrorRecovery',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXFaceDetector',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXFaceDetector',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXFacebook',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXFacebook',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXFileSystem',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXFileSystem',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXFirebaseAnalytics',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXFirebaseAnalytics',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXFirebaseCore',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXFirebaseCore',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXFont',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXFont',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXGL',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXGL',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXGoogleSignIn',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXGoogleSignIn',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXHaptics',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXHaptics',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXImageLoader',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXImageLoader',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXImageManipulator',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXImageManipulator',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXImagePicker',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXImagePicker',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXInAppPurchases',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXInAppPurchases',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXKeepAwake',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXKeepAwake',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXLinearGradient',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXLinearGradient',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXLocalAuthentication',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXLocalAuthentication',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXLocalization',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXLocalization',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXLocation',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXLocation',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXMailComposer',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXMailComposer',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXMediaLibrary',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXMediaLibrary',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXModuleTemplate',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXModuleTemplate',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXNetwork',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXNetwork',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXPermissions',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXPermissions',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXPrint',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXPrint',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXRandom',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXRandom',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXScreenOrientation',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXScreenOrientation',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSecureStore',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSecureStore',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSensors',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSensors',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSharing',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSharing',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSMS',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSMS',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSpeech',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSpeech',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXSQLite',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXSQLite',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXStoreReview',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXStoreReview',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXTaskManager',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXTaskManager',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXVideoThumbnails',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXVideoThumbnails',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0EXWebBrowser',
  :path => './versioned-react-native/ABI37_0_0/Expo/EXWebBrowser',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMAppLoader',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMAppLoader',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMBarCodeScannerInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMBarCodeScannerInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMCameraInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMCameraInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMConstantsInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMConstantsInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMFaceDetectorInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMFaceDetectorInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMFileSystemInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMFileSystemInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMFontInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMFontInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMImageLoaderInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMImageLoaderInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMPermissionsInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMPermissionsInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMSensorsInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMSensorsInterface',
  :project_name => 'ABI37_0_0'
pod 'ABI37_0_0UMTaskManagerInterface',
  :path => './versioned-react-native/ABI37_0_0/Expo/UMTaskManagerInterface',
  :project_name => 'ABI37_0_0'
