/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifndef ABI47_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// OSS-compatibility layer

#import "ABI47_0_0RCTFabricComponentsPlugins.h"

#import <string>
#import <unordered_map>

Class<ABI47_0_0RCTComponentViewProtocol> ABI47_0_0RCTFabricComponentsProvider(const char *name) {
  static std::unordered_map<std::string, Class (*)(void)> sFabricComponentsClassMap = {
    {"SafeAreaView", ABI47_0_0RCTSafeAreaViewCls},
    {"ScrollView", ABI47_0_0RCTScrollViewCls},
    {"PullToRefreshView", ABI47_0_0RCTPullToRefreshViewCls},
    {"ActivityIndicatorView", ABI47_0_0RCTActivityIndicatorViewCls},
    {"Slider", ABI47_0_0RCTSliderCls},
    {"Switch", ABI47_0_0RCTSwitchCls},
    {"UnimplementedNativeView", ABI47_0_0RCTUnimplementedNativeViewCls},
    {"Paragraph", ABI47_0_0RCTParagraphCls},
    {"TextInput", ABI47_0_0RCTTextInputCls},
    {"InputAccessoryView", ABI47_0_0RCTInputAccessoryCls},
    {"View", ABI47_0_0RCTViewCls},
    {"Image", ABI47_0_0RCTImageCls},
  };

  auto p = sFabricComponentsClassMap.find(name);
  if (p != sFabricComponentsClassMap.end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return ABI47_0_0RCTThirdPartyFabricComponentsProvider(name);
}

#endif // ABI47_0_0RN_DISABLE_OSS_PLUGIN_HEADER
