namespace ReactNativeWebView {
[webhosthidden]
[default_interface] 
runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider {
  ReactPackageProvider();
};
} // namespace ReactNativeWebView
