// @ref llp/0006-agent-native-cli-surface.rfc.md §Surface improvements
// The body of the managed block: the project facts an agent would otherwise guess at, and the
// commands that answer in a shape it can parse. Pure text generation — no I/O, no timestamps, so
// the same project always produces the same block and a rerun rewrites nothing.
import { PROGRAM_PREFIX } from '../programName';
import type { ProjectState } from '../project/types';

export interface AgentsMdContext {
  /** The probed project state, from `probeProjectStateAsync`. */
  state: ProjectState;
  /** `name` of the project's `package.json`, or null when it has none. */
  projectName: string | null;
  /** Project-relative skills directories of the targeted agents, e.g. `[".claude/skills"]`. */
  skillsDirs: string[];
}

/**
 * One line of a value the project supplied.
 *
 * `package.json` `name` and the installed SDK version are read from files this CLI does not own,
 * and they land inside a block a coding agent reads as instructions. A newline in one of them
 * would add lines of the project's choosing, so every run of whitespace collapses to one space.
 */
function oneLine(value: string | null | undefined): string | null {
  if (value == null) {
    return null;
  }
  const collapsed = value.replace(/\s+/g, ' ').trim();
  return collapsed.length > 0 ? collapsed : null;
}

/** Render the body of the managed block, without the markers around it. */
export function generateAgentsMdBlock({ state, projectName, skillsDirs }: AgentsMdContext): string {
  return [
    `<!-- Generated by \`${PROGRAM_PREFIX} agents:setup\`. Everything inside the markers is overwritten on the next run. -->`,
    '',
    '## Expo project',
    '',
    `- Project: ${oneLine(projectName) ?? 'unnamed (no name in package.json)'}`,
    `- SDK: ${oneLine(state.sdkVersion) ?? 'unknown (the `expo` package is not installed)'}`,
    `- Native: ${nativeLine(state)}`,
    `- Expo Go: ${expoGoLine(state)}`,
    `- Dev client: \`expo-dev-client\` is ${state.usesDevClient ? 'installed' : 'not installed'}`,
    '',
    '## Commands',
    '',
    'Prefer these over the raw `expo` commands: they answer in a shape an agent can parse, and most of them take `--json` for the machine-readable form.',
    '',
    `- \`${PROGRAM_PREFIX} status\` — where the project is right now, and what would happen next`,
    `- \`${PROGRAM_PREFIX} status --json\` — the same report as one object, with the raw project probe under \`probe\``,
    `- \`${PROGRAM_PREFIX} status --explain\` — the deep dive: which sources changed, whether an update can ship over the air, and whether EAS already has a build for this fingerprint`,
    `- \`${PROGRAM_PREFIX} status --assert js-only\` — a gate on what a change costs: exit 20 when it costs more than the class named, 22 when nothing could be measured, 0 otherwise`,
    `- \`${PROGRAM_PREFIX} dev\` — get the app onto a device: it prints the plan, then runs it; \`${PROGRAM_PREFIX} dev --plan\` prints the steps without running them`,
    `- \`${PROGRAM_PREFIX} start\` — \`expo start\` and nothing else: a dev server no planning may touch`,
    `- \`${PROGRAM_PREFIX} install <pkg>\` — install a package and report what it changes natively`,
    `- \`${PROGRAM_PREFIX} typecheck\` — run the TypeScript compiler of this project as a gate: exit 20 with the diagnostics, exit 0 when there are none. A bundle that builds and an app that does not throw do not cover this.`,
    `- \`${PROGRAM_PREFIX} runtime:eval <js>\` — evaluate JavaScript in the running app`,
    `- \`${PROGRAM_PREFIX} runtime:errors\` — collect the runtime errors of the running app`,
    `- \`${PROGRAM_PREFIX} navigate <route>\` — open a route as a deep link on a device`,
    `- \`${PROGRAM_PREFIX} runtime:tree\` — what is on the screen of the running app, by testID`,
    `- \`${PROGRAM_PREFIX} runtime:tap <testID>\` — tap an element; \`--verify\` reports what changed`,
    `- \`${PROGRAM_PREFIX} runtime:type <text> --testID <id>\` — type into an input`,
    `- \`${PROGRAM_PREFIX} skills:list\` — the agent skills the installed packages ship`,
    `- \`${PROGRAM_PREFIX} new <dir>\` / \`${PROGRAM_PREFIX} deploy\` — create a project headlessly / deploy web and native`,
    `- \`${PROGRAM_PREFIX} smoke\` — the whole gate in one command: the dev server bundles, the app is up, and nothing threw`,
    '',
    skillsLine(skillsDirs),
  ].join('\n');
}

function nativeLine(state: ProjectState): string {
  const checkedIn = [state.nativeDirs.ios && 'ios', state.nativeDirs.android && 'android'].filter(
    Boolean
  );
  if (checkedIn.length) {
    return `bare (${checkedIn.join(', ')} checked into the repo, so they are the source of truth)`;
  }
  return 'CNG (no native directories; they are generated by `npx expo prebuild`)';
}

function expoGoLine(state: ProjectState): string {
  if (state.expoGo.compatible) {
    return 'compatible (Expo Go can run this project)';
  }
  const count = state.expoGo.reasons.length;
  return `not compatible (${count} reason${count === 1 ? '' : 's'}; needs a development build, run \`${PROGRAM_PREFIX} status --json\` for the details)`;
}

function skillsLine(skillsDirs: string[]): string {
  if (!skillsDirs.length) {
    return `No agent skills are linked yet. Run \`${PROGRAM_PREFIX} agents:setup --agent <agent>\` to link the skills the installed packages ship.`;
  }
  return `Agent skills of the installed packages are linked into ${skillsDirs
    .map((dir) => `\`${dir}\``)
    .join(', ')}. Rerun \`${PROGRAM_PREFIX} agents:setup\` after installing a package.

Commands end with a \`Suggested next:\` section — suggested follow-up commands, not required steps. Run one only when it serves your current goal.`;
}
