/**
 * This code was generated by [ABI49_0_0React-native-codegen](https://www.npmjs.com/package/ABI49_0_0React-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

#ifdef ANDROID
#include <folly/dynamic.h>
#include <ABI49_0_0React/renderer/mapbuffer/ABI49_0_0MapBuffer.h>
#include <ABI49_0_0React/renderer/mapbuffer/ABI49_0_0MapBufferBuilder.h>
#endif

namespace ABI49_0_0facebook {
namespace ABI49_0_0React {

class AndroidHorizontalScrollContentViewState {
public:
  AndroidHorizontalScrollContentViewState() = default;

#ifdef ANDROID
  AndroidHorizontalScrollContentViewState(AndroidHorizontalScrollContentViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class AndroidSwipeRefreshLayoutState {
public:
  AndroidSwipeRefreshLayoutState() = default;

#ifdef ANDROID
  AndroidSwipeRefreshLayoutState(AndroidSwipeRefreshLayoutState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class PullToRefreshViewState {
public:
  PullToRefreshViewState() = default;

#ifdef ANDROID
  PullToRefreshViewState(PullToRefreshViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class AndroidDrawerLayoutState {
public:
  AndroidDrawerLayoutState() = default;

#ifdef ANDROID
  AndroidDrawerLayoutState(AndroidDrawerLayoutState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class ActivityIndicatorViewState {
public:
  ActivityIndicatorViewState() = default;

#ifdef ANDROID
  ActivityIndicatorViewState(ActivityIndicatorViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class UnimplementedNativeViewState {
public:
  UnimplementedNativeViewState() = default;

#ifdef ANDROID
  UnimplementedNativeViewState(UnimplementedNativeViewState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class SwitchState {
public:
  SwitchState() = default;

#ifdef ANDROID
  SwitchState(SwitchState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

class TraceUpdateOverlayState {
public:
  TraceUpdateOverlayState() = default;

#ifdef ANDROID
  TraceUpdateOverlayState(TraceUpdateOverlayState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
  MapBuffer getMapBuffer() const {
    return MapBufferBuilder::EMPTY();
  };
#endif
};

} // namespace ABI49_0_0React
} // namespace ABI49_0_0facebook