ROOT = ../

build-archive:
	gtar -C ${ROOT} \
		-zcf ${OUTPUT} \
		package.json \
		template-files \
		exponent-view-template \
		shellAppBase-builds \
		ios \
		tools-public \
		tools


.PHONY: build-archive
