source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

EXPO_CPP_HEADER_DIR = 'ExponentCPP'

target 'Exponent' do
  pod 'Amplitude-iOS', '~> 3.8', :inhibit_warnings => true
  pod 'Analytics', '~> 3.5', :inhibit_warnings => true
  pod 'AppAuth', '~> 0.4', :inhibit_warnings => true
  pod 'CocoaLumberjack', '~> 3.2.1', :inhibit_warnings => true
  pod 'Crashlytics', '~> 3.8', :inhibit_warnings => true
  pod 'FBAudienceNetwork', '~> 4.24', :inhibit_warnings => true
  pod 'FBSDKCoreKit', '~> 4.28', :inhibit_warnings => true
  pod 'FBSDKLoginKit', '~> 4.28', :inhibit_warnings => true
  pod 'FBSDKShareKit', '~> 4.28', :inhibit_warnings => true
  pod 'Fabric', '~> 1.6', :inhibit_warnings => true
  pod 'GoogleSignIn', '~> 3.0', :inhibit_warnings => true
  pod 'GoogleMaps', '~> 2.5.0', :inhibit_warnings => true
  pod 'Google-Maps-iOS-Utils', '~> 2.1.0', :inhibit_warnings => true
  pod 'lottie-ios', '~> 2.5.0', :inhibit_warnings => true
  pod 'GPUImage', '~> 0.1.7', :inhibit_warnings => true
  pod 'JKBigInteger2', '0.0.5', :inhibit_warnings => true
  pod 'Branch', '~> 0.24.2', :inhibit_warnings => true
  pod 'Google-Mobile-Ads-SDK', '~> 7.22.0', :inhibit_warnings => true

  # Local CocoaPods
  pod 'ExponentCPP', :path => '../cpp'
  pod 'GoogleMobileVision/FaceDetector', '~> 1.1.0'
  pod 'GoogleMobileVision/MVDataOutput', '~> 1.1.0'

  pod 'React',
    :path => "../js/node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../js/node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../js/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../js/node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../js/node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


    # Generated dependency: ReactABI22_0_0
    pod 'ReactABI22_0_0', :inhibit_warnings => true, :path => './versioned-react-native/ABI22_0_0', :subspecs => [
      'Core',
      'ART',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'Expo', 'ExpoOptional'
    ]
    pod 'yogaABI22_0_0', :path => './versioned-react-native/ABI22_0_0/ReactCommon/ABI22_0_0yoga'
    # End generated dependency


    # Generated dependency: ReactABI23_0_0
    pod 'ReactABI23_0_0', :inhibit_warnings => true, :path => './versioned-react-native/ABI23_0_0', :subspecs => [
      'Core',
      'ART',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'Expo', 'ExpoOptional'
    ]
    pod 'yogaABI23_0_0', :path => './versioned-react-native/ABI23_0_0/ReactCommon/ABI23_0_0yoga'
    # End generated dependency


    # Generated dependency: ReactABI24_0_0
    pod 'ReactABI24_0_0', :inhibit_warnings => true, :path => './versioned-react-native/ABI24_0_0', :subspecs => [
      'Core',
      'ART',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'Expo', 'ExpoOptional'
    ]
    pod 'yogaABI24_0_0', :path => './versioned-react-native/ABI24_0_0/ReactCommon/ABI24_0_0yoga'
    # End generated dependency


    # Generated dependency: ReactABI25_0_0
    pod 'ReactABI25_0_0', :inhibit_warnings => true, :path => './versioned-react-native/ABI25_0_0', :subspecs => [
      'Core',
      'ART',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'Expo', 'ExpoOptional'
    ]
    pod 'yogaABI25_0_0', :path => './versioned-react-native/ABI25_0_0/ReactCommon/ABI25_0_0yoga'
    # End generated dependency


    # Generated dependency: ReactABI26_0_0
    pod 'ReactABI26_0_0', :inhibit_warnings => true, :path => './versioned-react-native/ABI26_0_0', :subspecs => [
      'Core',
      'ART',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'Expo', 'ExpoOptional'
    ]
    pod 'yogaABI26_0_0', :path => './versioned-react-native/ABI26_0_0/ReactCommon/ABI26_0_0yoga'
    # End generated dependency


    # Generated dependency: ReactABI27_0_0
    pod 'ReactABI27_0_0', :inhibit_warnings => true, :path => './versioned-react-native/ABI27_0_0', :subspecs => [
      'Core',
      'ART',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge',
      'Expo', 'ExpoOptional'
    ]
    pod 'yogaABI27_0_0', :path => './versioned-react-native/ABI27_0_0/ReactCommon/ABI27_0_0yoga'
    # End generated dependency


    # Build React Native with RCT_DEV enabled
  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    # Generated postinstall: ReactABI22_0_0
    if target.pod_name == 'ReactABI22_0_0'
      target.native_target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = ['-DkNeverRequested=ReactABI22_0_0kNeverRequested','-DkNeverProgressed=ReactABI22_0_0kNeverProgressed','-DkSMCalloutViewRepositionDelayForUIScrollView=ReactABI22_0_0kSMCalloutViewRepositionDelayForUIScrollView','-DregionAsJSON=ReactABI22_0_0regionAsJSON','-DunionRect=ReactABI22_0_0unionRect','-DJSNoBytecodeFileFormatVersion=ReactABI22_0_0JSNoBytecodeFileFormatVersion','-DJSSamplingProfilerEnabled=ReactABI22_0_0JSSamplingProfilerEnabled','-DRECONNECT_DELAY_MS=ReactABI22_0_0RECONNECT_DELAY_MS','-DgCurrentGenerationCount=ReactABI22_0_0gCurrentGenerationCount','-DgPrintSkips=ReactABI22_0_0gPrintSkips','-DgPrintChanges=ReactABI22_0_0gPrintChanges','-DlayoutNodeInternal=ReactABI22_0_0layoutNodeInternal','-DgDepth=ReactABI22_0_0gDepth','-DgPrintTree=ReactABI22_0_0gPrintTree','-DisUndefined=ReactABI22_0_0isUndefined','-DgNodeInstanceCount=ReactABI22_0_0gNodeInstanceCount','-DMAX_DELTA_TIME=ReactABI22_0_0MAX_DELTA_TIME']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI22_0_0RCT_DEV=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end
    # End generated postinstall


    # Generated postinstall: ReactABI23_0_0
    if target.pod_name == 'ReactABI23_0_0'
      target.native_target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = ['-DkNeverRequested=ReactABI23_0_0kNeverRequested','-DkNeverProgressed=ReactABI23_0_0kNeverProgressed','-DkSMCalloutViewRepositionDelayForUIScrollView=ReactABI23_0_0kSMCalloutViewRepositionDelayForUIScrollView','-DregionAsJSON=ReactABI23_0_0regionAsJSON','-DunionRect=ReactABI23_0_0unionRect','-DJSNoBytecodeFileFormatVersion=ReactABI23_0_0JSNoBytecodeFileFormatVersion','-DJSSamplingProfilerEnabled=ReactABI23_0_0JSSamplingProfilerEnabled','-DRECONNECT_DELAY_MS=ReactABI23_0_0RECONNECT_DELAY_MS','-DMAX_DELTA_TIME=ReactABI23_0_0MAX_DELTA_TIME','-DgCurrentGenerationCount=ReactABI23_0_0gCurrentGenerationCount','-DgPrintSkips=ReactABI23_0_0gPrintSkips','-DgPrintChanges=ReactABI23_0_0gPrintChanges','-DlayoutNodeInternal=ReactABI23_0_0layoutNodeInternal','-DgDepth=ReactABI23_0_0gDepth','-DgPrintTree=ReactABI23_0_0gPrintTree','-DisUndefined=ReactABI23_0_0isUndefined','-DgNodeInstanceCount=ReactABI23_0_0gNodeInstanceCount']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI23_0_0RCT_DEV=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end
    # End generated postinstall


    # Generated postinstall: ReactABI24_0_0
    if target.pod_name == 'ReactABI24_0_0'
      target.native_target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = ['-DkNeverRequested=ReactABI24_0_0kNeverRequested','-DkNeverProgressed=ReactABI24_0_0kNeverProgressed','-DkSMCalloutViewRepositionDelayForUIScrollView=ReactABI24_0_0kSMCalloutViewRepositionDelayForUIScrollView','-DregionAsJSON=ReactABI24_0_0regionAsJSON','-DunionRect=ReactABI24_0_0unionRect','-DJSNoBytecodeFileFormatVersion=ReactABI24_0_0JSNoBytecodeFileFormatVersion','-DJSSamplingProfilerEnabled=ReactABI24_0_0JSSamplingProfilerEnabled','-DRECONNECT_DELAY_MS=ReactABI24_0_0RECONNECT_DELAY_MS','-DMAX_DELTA_TIME=ReactABI24_0_0MAX_DELTA_TIME','-DgCurrentGenerationCount=ReactABI24_0_0gCurrentGenerationCount','-DgPrintSkips=ReactABI24_0_0gPrintSkips','-DgPrintChanges=ReactABI24_0_0gPrintChanges','-DlayoutNodeInternal=ReactABI24_0_0layoutNodeInternal','-DgDepth=ReactABI24_0_0gDepth','-DgPrintTree=ReactABI24_0_0gPrintTree','-DisUndefined=ReactABI24_0_0isUndefined','-DgNodeInstanceCount=ReactABI24_0_0gNodeInstanceCount']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI24_0_0RCT_DEV=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end
    # End generated postinstall


    # Generated postinstall: ReactABI25_0_0
    if target.pod_name == 'ReactABI25_0_0'
      target.native_target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = ['-DkNeverRequested=ReactABI25_0_0kNeverRequested','-DkNeverProgressed=ReactABI25_0_0kNeverProgressed','-DkSMCalloutViewRepositionDelayForUIScrollView=ReactABI25_0_0kSMCalloutViewRepositionDelayForUIScrollView','-DregionAsJSON=ReactABI25_0_0regionAsJSON','-DunionRect=ReactABI25_0_0unionRect','-DJSNoBytecodeFileFormatVersion=ReactABI25_0_0JSNoBytecodeFileFormatVersion','-DJSSamplingProfilerEnabled=ReactABI25_0_0JSSamplingProfilerEnabled','-DRECONNECT_DELAY_MS=ReactABI25_0_0RECONNECT_DELAY_MS','-DMAX_DELTA_TIME=ReactABI25_0_0MAX_DELTA_TIME','-DgCurrentGenerationCount=ReactABI25_0_0gCurrentGenerationCount','-DgPrintSkips=ReactABI25_0_0gPrintSkips','-DgPrintChanges=ReactABI25_0_0gPrintChanges','-DlayoutNodeInternal=ReactABI25_0_0layoutNodeInternal','-DgDepth=ReactABI25_0_0gDepth','-DgPrintTree=ReactABI25_0_0gPrintTree','-DisUndefined=ReactABI25_0_0isUndefined','-DgNodeInstanceCount=ReactABI25_0_0gNodeInstanceCount']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI25_0_0RCT_DEV=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end
    # End generated postinstall


    # Generated postinstall: ReactABI26_0_0
    if target.pod_name == 'ReactABI26_0_0'
      target.native_target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = ['-DkNeverRequested=ReactABI26_0_0kNeverRequested','-DkNeverProgressed=ReactABI26_0_0kNeverProgressed','-DkSMCalloutViewRepositionDelayForUIScrollView=ReactABI26_0_0kSMCalloutViewRepositionDelayForUIScrollView','-DregionAsJSON=ReactABI26_0_0regionAsJSON','-DunionRect=ReactABI26_0_0unionRect','-DJSNoBytecodeFileFormatVersion=ReactABI26_0_0JSNoBytecodeFileFormatVersion','-DJSSamplingProfilerEnabled=ReactABI26_0_0JSSamplingProfilerEnabled','-DRECONNECT_DELAY_MS=ReactABI26_0_0RECONNECT_DELAY_MS','-DMAX_DELTA_TIME=ReactABI26_0_0MAX_DELTA_TIME','-DgCurrentGenerationCount=ReactABI26_0_0gCurrentGenerationCount','-DgPrintSkips=ReactABI26_0_0gPrintSkips','-DgPrintChanges=ReactABI26_0_0gPrintChanges','-DlayoutNodeInternal=ReactABI26_0_0layoutNodeInternal','-DgDepth=ReactABI26_0_0gDepth','-DgPrintTree=ReactABI26_0_0gPrintTree','-DisUndefined=ReactABI26_0_0isUndefined','-DgNodeInstanceCount=ReactABI26_0_0gNodeInstanceCount']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI26_0_0RCT_DEV=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end
    # End generated postinstall


    # Generated postinstall: ReactABI27_0_0
    if target.pod_name == 'ReactABI27_0_0'
      target.native_target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = ['-DkNeverRequested=ReactABI27_0_0kNeverRequested','-DkNeverProgressed=ReactABI27_0_0kNeverProgressed','-DkSMCalloutViewRepositionDelayForUIScrollView=ReactABI27_0_0kSMCalloutViewRepositionDelayForUIScrollView','-DregionAsJSON=ReactABI27_0_0regionAsJSON','-DunionRect=ReactABI27_0_0unionRect','-DJSNoBytecodeFileFormatVersion=ReactABI27_0_0JSNoBytecodeFileFormatVersion','-DJSSamplingProfilerEnabled=ReactABI27_0_0JSSamplingProfilerEnabled','-DRECONNECT_DELAY_MS=ReactABI27_0_0RECONNECT_DELAY_MS','-DMAX_DELTA_TIME=ReactABI27_0_0MAX_DELTA_TIME','-DgCurrentGenerationCount=ReactABI27_0_0gCurrentGenerationCount','-DgPrintSkips=ReactABI27_0_0gPrintSkips','-DgPrintChanges=ReactABI27_0_0gPrintChanges','-DlayoutNodeInternal=ReactABI27_0_0layoutNodeInternal','-DgDepth=ReactABI27_0_0gDepth','-DgPrintTree=ReactABI27_0_0gPrintTree','-DisUndefined=ReactABI27_0_0isUndefined','-DgNodeInstanceCount=ReactABI27_0_0gNodeInstanceCount']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI27_0_0RCT_DEV=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end
    # End generated postinstall


    if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? target.pod_name
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    # Can't specify this in the React podspec because we need
    # to use those podspecs for detached projects which don't reference ExponentCPP.
    if target.pod_name.start_with?('React')
      target.native_target.build_configurations.each do |config|
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << "${PODS_ROOT}/Headers/Public/#{EXPO_CPP_HEADER_DIR}"
      end
    end
    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end


  target 'ExponentIntegrationTests' do
    inherit! :search_paths
  end

end
