require_relative './podfile_helpers.rb'
require_relative '../packages/react-native-unimodules/cocoapods.rb'

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true
platform :ios, '10.0'
inhibit_all_warnings!

target 'Exponent' do
  # Expo Client dependencies
  pod 'Amplitude-iOS'
  pod 'CocoaLumberjack', '~> 3.5.3'
  pod 'Crashlytics', '~> 3.13.4'
  pod 'Fabric', '~> 1.10.2'
  pod 'GoogleMaps', '~> 3.3'
  pod 'Google-Maps-iOS-Utils', '~> 2.1.0'
  pod 'lottie-ios', '~> 2.5.0'
  pod 'JKBigInteger2', '0.0.5'

  # Unimodules
  use_unimodules!({
    modules_paths: ['../packages'],
    exclude: [
      'expo-module-template',
      'expo-bluetooth',
      'expo-in-app-purchases',
      'expo-payments-stripe',
      'expo-updates',
    ],
    flags: {
      :inhibit_warnings => false
    }
  })

  # Unversioned React Native
  pod 'React',
    :path => "../react-native-lab/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../react-native-lab/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../react-native-lab/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly',
    :podspec => "../react-native-lab/react-native/third-party-podspecs/Folly.podspec"
  pod 'glog',
    :podspec => "../react-native-lab/react-native/third-party-podspecs/glog.podspec"

  # Evaluate all files matching `versioned-react-native/ABI*/dependencies.rb` glob pattern
  # and install ReactABIXX_0_0 pods with all versioned unimodules.
  use_versioned_abis!

  # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
  # RCT_ENABLE_PACKAGER_CONNECTION disabled
  post_install do |installer|
    # Disabled as of CocoaPods 1.8.0.beta1 since pods_project seems to be nil
    # installer.pods_project.main_group.tab_width = '2';
    # installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      # Run postinstalls actions for versioned dependencies.
      # These actions are specified in `versioned-react-native/ABI*/postinstalls.rb` files.
      run_versioned_postinstalls!(pod_name, target_installation_result)

      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name == 'React'
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
    end
  end

  # Test targets
  target 'ExponentIntegrationTests' do
    inherit! :search_paths
  end

  target 'Tests' do
    inherit! :search_paths
  end
end
