import { expect, jest, test } from '@jest/globals';

import { CommonActions } from '../../react-navigation/routers';
import { StackRouter } from '../stack-router';

jest.mock('nanoid/non-secure', () => ({ nanoid: () => 'test' }));

const options = {
  routeNames: ['first', 'second'],
  routeGetIdList: {},
};

test.each([CommonActions.navigate('second'), CommonActions.preload('second')])(
  'Expo stack override stamps seeded state for $type',
  (action) => {
    const result = StackRouter({}).getStateForAction(
      {
        stale: false,
        key: 'stack',
        index: 0,
        routeNames: options.routeNames,
        routes: [{ key: 'first-key', name: 'first' }],
      },
      action,
      options
    );

    expect(result?.state.type).toBe('stack');
  }
);

test('reports the key generated by the Expo stack override', () => {
  const result = StackRouter({}).getStateForAction(
    {
      stale: false,
      type: 'stack',
      key: 'stack',
      index: 0,
      routeNames: options.routeNames,
      routes: [{ key: 'first-key', name: 'first' }],
    },
    CommonActions.navigate('second'),
    options
  );

  expect(result?.affectedRouteKey).toBe('second-test');
  expect(result?.state.routes[result.state.index ?? -1]?.key).toBe('second-test');
});

test('attaches trusted state in the Expo stack override', () => {
  const childState = { routes: [{ name: 'child' }], __internal__routerActionState: true as const };
  const result = StackRouter({}).getStateForAction(
    {
      stale: false,
      type: 'stack',
      key: 'stack',
      index: 0,
      routeNames: options.routeNames,
      routes: [{ key: 'first-key', name: 'first' }],
    },
    {
      type: 'NAVIGATE',
      payload: { name: 'second', state: childState },
    },
    options
  );

  expect(result?.state.routes[result.state.index ?? -1]?.state).toBe(childState);
});

test('reports the key of a route preloaded by the Expo stack override', () => {
  const result = StackRouter({}).getStateForAction(
    {
      stale: false,
      type: 'stack',
      key: 'stack',
      index: 0,
      routeNames: options.routeNames,
      routes: [{ key: 'first-key', name: 'first' }],
    },
    CommonActions.preload('second'),
    options
  );

  expect(result?.affectedRouteKey).toBe('second-test');
  expect(result?.state.routes[result.state.index ?? -1]?.key).toBe('first-key');
});

test('attaches trusted state to an unfocused route preloaded by the Expo stack override', () => {
  const childState = { routes: [{ name: 'child' }], __internal__routerActionState: true as const };
  const result = StackRouter({}).getStateForAction(
    {
      stale: false,
      type: 'stack',
      key: 'stack',
      index: 0,
      routeNames: options.routeNames,
      routes: [{ key: 'first-key', name: 'first' }],
    },
    {
      type: 'PRELOAD',
      payload: { name: 'second', state: childState },
    },
    options
  );

  expect(result?.state.routes[result.state.index ?? -1]?.key).toBe('first-key');
  expect(result?.state.routes.find((route) => route.name === 'second')?.state).toBe(childState);
});
