{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-sensors",
    "version": "11.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-sensors-11.2.0.aar",
          "url": "expo-sensors-11.2.0.aar",
          "size": 54656,
          "sha512": "fd772e5146bd9b634532034dc922bf3371940ef7c33af056bcdaeba78ed48e2ef3449ce922fe75da6297d121a4a0782bc27dfd2d8bf55a98dab9cf9079f56180",
          "sha256": "947377c4b78ba38dfd13f4856a79de0094a2fe05f72cd9cb7500f851b63802bd",
          "sha1": "d0ac5633b9f3a6b8dd8a5c8f3c18a65f6c389eee",
          "md5": "417ac0c099deaad2b1af5d1cb2006741"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-sensors-11.2.0.aar",
          "url": "expo-sensors-11.2.0.aar",
          "size": 54656,
          "sha512": "fd772e5146bd9b634532034dc922bf3371940ef7c33af056bcdaeba78ed48e2ef3449ce922fe75da6297d121a4a0782bc27dfd2d8bf55a98dab9cf9079f56180",
          "sha256": "947377c4b78ba38dfd13f4856a79de0094a2fe05f72cd9cb7500f851b63802bd",
          "sha1": "d0ac5633b9f3a6b8dd8a5c8f3c18a65f6c389eee",
          "md5": "417ac0c099deaad2b1af5d1cb2006741"
        }
      ]
    }
  ]
}
