package expo.modules.crypto.aes.records

import android.util.Base64
import expo.modules.crypto.aes.AesConfig.DEFAULT_IV_SIZE
import expo.modules.crypto.aes.AesConfig.DEFAULT_TAG_SIZE
import expo.modules.crypto.aes.BinaryInput
import expo.modules.kotlin.apifeatures.EitherType
import expo.modules.kotlin.records.Field
import expo.modules.kotlin.records.Record
import expo.modules.kotlin.types.Either
import expo.modules.kotlin.types.EitherOfThree
import java.security.SecureRandom
import javax.crypto.spec.GCMParameterSpec

@OptIn(EitherType::class)
class EncryptOptions: Record {
  @Field val nonce: EitherOfThree<String, ByteArray, Int>? = null
  @Field val tagLength: Int? = null
  @Field val additionalData: BinaryInput? = null

  internal fun gcmParameterSpec(random: SecureRandom): GCMParameterSpec? {
    // a default will be generated by Cipher
    if (nonce == null && tagLength == null) {
      return null
    }

    val iv = if (nonce == null) {
      ByteArray(DEFAULT_IV_SIZE).also { random.nextBytes(it) }
    } else if (nonce.`is`(Int::class)) {
      ByteArray(nonce.get(Int::class)).also { random.nextBytes(it) }
    } else if (nonce.`is`(String::class)) {
      Base64.decode(nonce.get(String::class), Base64.NO_WRAP)
    } else {
      nonce.get(ByteArray::class)
    }

    val tagByteLength = tagLength ?: DEFAULT_TAG_SIZE
    return GCMParameterSpec(tagByteLength * 8, iv)
  }
}
