// TODO:
// applyEnvironmentVariables
// startAsync
// broadcastMessage
// loadConfigAsync
// clearWebProjectCacheAsync
// createNativeDevServerMiddleware
// attachNativeDevServerMiddlewareToDevServer
// getAvailablePortAsync
// isTargetingNative
