{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-sms",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-sms-10.2.0.aar",
          "url": "expo-sms-10.2.0.aar",
          "size": 19759,
          "sha512": "0bdcdad58ec20e4649b134ade916c2f9baf5ed2e8a69484c5d800301dfee9cc4d518c128af4d793596331226054aad99444ba0a928dd5489dd57526af8da536e",
          "sha256": "d6d4ca9051057af801d53493a10d545546bacf01a402fc508a627738f5742e39",
          "sha1": "c707df6457444f069eb208a0553cc2d1f0d7d615",
          "md5": "08eecf06b649bc1ccd846c9d0aa95783"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-sms-10.2.0.aar",
          "url": "expo-sms-10.2.0.aar",
          "size": 19759,
          "sha512": "0bdcdad58ec20e4649b134ade916c2f9baf5ed2e8a69484c5d800301dfee9cc4d518c128af4d793596331226054aad99444ba0a928dd5489dd57526af8da536e",
          "sha256": "d6d4ca9051057af801d53493a10d545546bacf01a402fc508a627738f5742e39",
          "sha1": "c707df6457444f069eb208a0553cc2d1f0d7d615",
          "md5": "08eecf06b649bc1ccd846c9d0aa95783"
        }
      ]
    }
  ]
}
