/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function activate(tag: string): Promise<boolean> {
  return false;
}

export async function deactivate(tag: string): Promise<boolean> {
  return false;
}

export async function isActivated(): Promise<boolean> {
  return false;
}
