// Copyright 2016-present 650 Industries. All rights reserved.
// @generated by tools/generate-dynamic-macros.js

#define BUILD_MACHINE_IP_ADDRESS @"192.168.2.14"
#define BUILD_MACHINE_LOCAL_HOSTNAME @"Janics-MacBook-Pro.local"
#define BUILD_MACHINE_KERNEL_NGROK_URL @""
#define TEMPORARY_SDK_VERSION @"7.0.0"
#define INITIAL_URL nil
