POST https://o.expo.dev/5310c5f2-8ab4-4d5e-8f53-a5c90aa9594a
Content-Type: application/json

{
  "eas_client_id": "7d6c5c81-244d-4929-89ae-2bc5dcb28c92",
  "events": [
    {
      "metadata": {
        "app_name": "observability",
        "app_identifier": "dev.expo.observability",
        "app_version": "1.0.0",
        "app_build_number": "1",
        "language_tag": "en-US",
        "device_os": "Android",
        "device_os_version": "16",
        "device_model": "sdk_gphone64_arm64",
        "device_name": "emu64a",
        "expo_sdk_version": "50.0.0",
        "react_native_version": "0.73.0"
      },
      "metrics": [
        {
          "session_id": "14fb5ca3-c54d-4714-8d6b-cfeba3a77283",
          "parent_session_id": null,
          "metric_timestamp": "2025-11-13T11:44:13.477Z",
          "metric_category": "app_startup",
          "metric_name": "launchTime",
          "metric_value": 1.0
        }
      ]
    }
  ]
}