export default {
  AdMob: require('../assets/icons/api/AdMob.png'),
  BarCodeScanner: require('../assets/icons/api/BarCodeScanner.png'),
  BlurView: require('../assets/icons/api/BlurView.png'),
  Calendars: require('../assets/icons/api/Calendars.png'),
  Contacts: require('../assets/icons/api/Contacts.png'),
  DocumentPicker: require('../assets/icons/api/DocumentPicker.png'),
  FacebookAds: require('../assets/icons/api/FacebookAds.png'),
  FacebookLogin: require('../assets/icons/api/FacebookLogin.png'),
  FileSystem: require('../assets/icons/api/FileSystem.png'),
  Fingerprint: require('../assets/icons/api/Fingerprint.png'),
  Geocoding: require('../assets/icons/api/Geocoding.png'),
  GL: require('../assets/icons/api/GL.png'),
  GoogleLogin: require('../assets/icons/api/GoogleLogin.png'),
  Haptic: require('../assets/icons/api/Haptic.png'),
  ImagePicker: require('../assets/icons/api/ImagePicker.png'),
  KeepAwake: require('../assets/icons/api/KeepAwake.png'),
  LinearGradient: require('../assets/icons/api/LinearGradient.png'),
  Location: require('../assets/icons/api/Location.png'),
  Lottie: require('../assets/icons/api/Lottie.png'),
  Maps: require('../assets/icons/api/Maps.png'),
  MediaLibrary: require('../assets/icons/api/FileSystem.png'),
  Notification: require('../assets/icons/api/Notification.png'),
  Pedometer: require('../assets/icons/api/Pedometer.png'),
  Print: require('../assets/icons/api/Print.png'),
  PhotoLibrary: require('../assets/icons/api/FileSystem.png'),
  ScreenOrientation: require('../assets/icons/api/ScreenOrientation.png'),
  SecureStore: require('../assets/icons/api/SecureStore.png'),
  Sensor: require('../assets/icons/api/Sensor.png'),
  TextToSpeech: require('../assets/icons/api/Speech.png'),
  Video: require('../assets/icons/api/Video.png'),
  WebBrowser: require('../assets/icons/api/WebBrowser.png'),

  Default: require('../assets/icons/api/Placeholder.png'),
};
