{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-localization",
    "version": "13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-localization-13.0.0.aar",
          "url": "expo-localization-13.0.0.aar",
          "size": 22986,
          "sha512": "22f076d36bbac7ec3c0fb92660cc44b7818b53a03a38f9e4b64848c8b7edf62858192eb758ec38fcb9b7186250d724d674e100be60d33ff279a6a9e35977aa8d",
          "sha256": "6af79b13e6d85d7970fbec01b6ba7bb27b2ecc5c6076189cf4c7ca9e08c30d3b",
          "sha1": "3d45b44e395f7aefe39c0ce67c942301e73069d2",
          "md5": "564d19c363a97df7bcab1b98ae4f68fa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-localization-13.0.0.aar",
          "url": "expo-localization-13.0.0.aar",
          "size": 22986,
          "sha512": "22f076d36bbac7ec3c0fb92660cc44b7818b53a03a38f9e4b64848c8b7edf62858192eb758ec38fcb9b7186250d724d674e100be60d33ff279a6a9e35977aa8d",
          "sha256": "6af79b13e6d85d7970fbec01b6ba7bb27b2ecc5c6076189cf4c7ca9e08c30d3b",
          "sha1": "3d45b44e395f7aefe39c0ce67c942301e73069d2",
          "md5": "564d19c363a97df7bcab1b98ae4f68fa"
        }
      ]
    }
  ]
}
