install! 'cocoapods',
         generate_multiple_pod_projects: true,
         incremental_installation: true
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'
inhibit_all_warnings!

# Import the auto-linking packages
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../../../packages/@unimodules/react-native-adapter/scripts/autolinking'

abstract_target 'BareExpoMain' do
  use_expo_modules!

  config = use_native_modules!

  use_react_native!(path: config['reactNativePath'])

  # Fix Google Sign-in and Flipper
  post_install do |installer|
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

        if (pod_name == 'Flipper') || (pod_name == 'Flipper-Folly') || (pod_name == 'Flipper-RSocket')
          # Fix `Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')`
          # See https://github.com/react-native-community/upgrade-support/issues/91 and https://github.com/facebook/flipper/issues/834
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        else
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
  end

  target 'BareExpo' do
    # Enables Flipper.
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
    # Note that we don't call `flipper_post_install`.
    # It causes problems with cocoapods. We add the FB_SONARKIT_ENABLED manually instead.
  end

  target 'BareExpoDetox' do
  end

  target 'BareExpoTests' do
    inherit! :search_paths
  end
end
