require 'json'

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
inhibit_all_warnings!

# Get the package.json for the excluded modules
package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))

# [Custom] Add target the root modules in the workspace
modules_path = '../../../node_modules'
# [Custom] Don't try to use the symlinked copy from the postinstall script it won't work as
# expected (you may get `'React/<File>.h' file not found` when building)
rnPrefix = '../../../react-native-lab/react-native'

# Import the auto-linking packages
require_relative "#{modules_path}/react-native-unimodules/cocoapods.rb"
require_relative "#{modules_path}/@react-native-community/cli-platform-ios/native_modules"
require_relative "#{rnPrefix}/scripts/react_native_pods"

target 'BareExpo' do

  # react-native-cli auto-linking
  config = use_native_modules!

  use_react_native!(:path => rnPrefix)

  # Auto-linking
  use_unimodules!(
    {
      modules_paths: %w[../../../packages], # [Custom] Prevent the bundling of template code and stripe
      exclude: package['excludedUnimodules'],
      flags: { inhibit_warnings: false }
    }
  )

  pod 'EXDevMenuInterface', path: '../../../packages/expo-dev-menu-interface'
  pod 'EXDevMenu', path: '../../../packages/expo-dev-menu', :configurations => :debug
  pod 'expo-image', path: '../../../packages/expo-image'
  pod 'EXRandom', path: '../../../packages/expo-random/ios'
  pod 'expo-development-client', path: '../../../packages/expo-development-client'

  # Fix Google Sign-in
  post_install do |installer|
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end

  target 'BareExpoTests' do
    inherit! :search_paths
  end
end
