{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-print",
    "version": "11.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-print-11.2.0.aar",
          "url": "expo-print-11.2.0.aar",
          "size": 38302,
          "sha512": "94b7ce2628ee275c5311538876a746d787f777a58332109f0792cc3d04d817e4d898eb75420b05b3f1c2491c4707447954f8484bb321ed1fef81b18de448d5fc",
          "sha256": "598328ab3b51cd556a3fc3f63dbff926b3f16fe19be324b2a39dfb937ff40a95",
          "sha1": "b3864825ab96ba5903d8889570329fd0ca62ba99",
          "md5": "a63b88e0c542c49ca37885c9296d7d25"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-print-11.2.0.aar",
          "url": "expo-print-11.2.0.aar",
          "size": 38302,
          "sha512": "94b7ce2628ee275c5311538876a746d787f777a58332109f0792cc3d04d817e4d898eb75420b05b3f1c2491c4707447954f8484bb321ed1fef81b18de448d5fc",
          "sha256": "598328ab3b51cd556a3fc3f63dbff926b3f16fe19be324b2a39dfb937ff40a95",
          "sha1": "b3864825ab96ba5903d8889570329fd0ca62ba99",
          "md5": "a63b88e0c542c49ca37885c9296d7d25"
        }
      ]
    }
  ]
}
