{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-clipboard",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-clipboard-3.0.1.aar",
          "url": "expo-clipboard-3.0.1.aar",
          "size": 91362,
          "sha512": "df206d4495c265109b038a0593f2bde7220a09c6fc4f1d9d78a229be353eacbaab75f997e9eab4e9aea1e1f8cb63721137e8d9692df04d38d72495dca28c59ae",
          "sha256": "bce5cb2b2662a6c1bb23072c94436939e62beb29e09db16fc0047a109e342c15",
          "sha1": "f33af7cdf6140d5267be9adfa13763666e2dfb60",
          "md5": "664231aba32f59483cd2b0a07ecdefd8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "expo-clipboard-3.0.1.aar",
          "url": "expo-clipboard-3.0.1.aar",
          "size": 91362,
          "sha512": "df206d4495c265109b038a0593f2bde7220a09c6fc4f1d9d78a229be353eacbaab75f997e9eab4e9aea1e1f8cb63721137e8d9692df04d38d72495dca28c59ae",
          "sha256": "bce5cb2b2662a6c1bb23072c94436939e62beb29e09db16fc0047a109e342c15",
          "sha1": "f33af7cdf6140d5267be9adfa13763666e2dfb60",
          "md5": "664231aba32f59483cd2b0a07ecdefd8"
        }
      ]
    }
  ]
}
