source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target '${TARGET_NAME}' do
${EXPONENT_CLIENT_DEPS}

  # Local CocoaPods
  pod 'ExponentCPP', :path => '../cpp'
  pod 'GoogleMobileVision/FaceDetector', '~> 1.1.0'
  pod 'GoogleMobileVision/MVDataOutput', '~> 1.1.0'
${PODFILE_UNVERSIONED_RN_DEPENDENCY}
${PODFILE_VERSIONED_RN_DEPENDENCIES}

    # Build React Native with RCT_DEV enabled
  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|
      # Can't specify this in the React podspec because we need
      # to use those podspecs for detached projects which don't reference ExponentCPP.
      if target.pod_name.start_with?('React')
        target.native_target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['HEADER_SEARCH_PATHS'] << '${PODS_ROOT}/Headers/Public/ExponentCPP'
        end
      end
${PODFILE_VERSIONED_POSTINSTALLS}
${PODFILE_UNVERSIONED_POSTINSTALL}
    end
  end

${PODFILE_TEST_TARGET}
end
