source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target '${TARGET_NAME}' do
${EXPONENT_CLIENT_DEPS}

  # Universal modules
  require_relative '../node_modules/@unimodules/core/cocoapods.rb'
  use_unimodules!({
    modules_paths: ['../packages'],
    exclude: [
      'expo-firebase-analytics',
      'expo-firebase-app',
      'expo-firebase-auth',
      'expo-firebase-crashlytics',
      'expo-firebase-database',
      'expo-firebase-firestore',
      'expo-firebase-functions',
      'expo-firebase-instance-id',
      'expo-firebase-invites',
      'expo-firebase-links',
      'expo-firebase-messaging',
      'expo-firebase-notifications',
      'expo-firebase-performance',
      'expo-firebase-remote-config',
      'expo-firebase-storage',
      'expo-payments-stripe',
    ]
  })

${PODFILE_UNVERSIONED_RN_DEPENDENCY}
${PODFILE_VERSIONED_RN_DEPENDENCIES}

  # Build React Native with RCT_DEV enabled and ENABLE_PACKAGER_CONNECTION disabled
  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|
${PODFILE_VERSIONED_POSTINSTALLS}
${PODFILE_UNVERSIONED_POSTINSTALL}
    end
  end

${PODFILE_TEST_TARGET}
end
