export const FirebaseNamespaces = {
  // admob: 'admob',
  analytics: 'analytics',
  auth: 'auth',
  config: 'config',
  crash: 'crash',
  crashlytics: 'crashlytics',
  database: 'database',
  firestore: 'firestore',
  functions: 'functions',
  iid: 'iid',
  invites: 'invites',
  links: 'links',
  messaging: 'messaging',
  notifications: 'notifications',
  perf: 'perf',
  storage: 'storage',
  utils: 'utils',
  // vision: 'vision',
};

export const FirebaseModuleNames = {
  ExpoFirebaseAdMob: 'ExpoFirebaseAdMob',
  ExpoFirebaseAnalytics: 'ExpoFirebaseAnalytics',
  ExpoFirebaseAuth: 'ExpoFirebaseAuth',
  ExpoFirebaseRemoteConfig: 'ExpoFirebaseRemoteConfig',
  ExpoFirebaseCrash: 'ExpoFirebaseCrash',
  ExpoFirebaseCrashlytics: 'ExpoFirebaseCrashlytics',
  ExpoFirebaseDatabase: 'ExpoFirebaseDatabase',
  ExpoFirebaseFirestore: 'ExpoFirebaseFirestore',
  ExpoFirebaseFunctions: 'ExpoFirebaseFunctions',
  ExpoFirebaseInstanceId: 'ExpoFirebaseInstanceId',
  ExpoFirebaseInvites: 'ExpoFirebaseInvites',
  ExpoFirebaseLinks: 'ExpoFirebaseLinks',
  ExpoFirebaseMessaging: 'ExpoFirebaseMessaging',
  ExpoFirebaseNotifications: 'ExpoFirebaseNotifications',
  ExpoFirebasePerformance: 'ExpoFirebasePerformance',
  ExpoFirebaseStorage: 'ExpoFirebaseStorage',
  ExpoFirebaseUtils: 'ExpoFirebaseUtils',
  ExpoFirebaseVision: 'ExpoFirebaseVision',
};

export const DEFAULT_APP_NAME = '[DEFAULT]';
