###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md

app_identifier "host.exp.Exponent"

screenshots_path "./fastlane/screenshots"
