# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
])

languages([
  'en-US',
])

# Where should the resulting screenshots be stored?
screenshots_path "./screenshots"

clear_previous_screenshots # remove the '#'' to clear all previously generated screenshots before creating new ones

# JavaScript UIAutomation file
js_file './scripts/snapshot.js'

project_path '../Exponent.xcworkspace'
scheme 'Exponent'
custom_build_args "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1'"

# Custom Callbacks

# setup_for_device_change do |device, udid, language|
#   puts "Running #{language} on #{device}"
#   system("./populateDatabase.sh")
# end

# teardown_device do |language, device|
#   puts "Finished with #{language} on #{device}"
#   system("./cleanup.sh")
# end
