{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-modules-core",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-modules-core-0.9.0.aar",
          "url": "expo-modules-core-0.9.0.aar",
          "size": 474741,
          "sha512": "4ad6cb4079a327602350b9b4f53da468eada0f7278508cdfe3d8936abe73d4491e12d75fd617935ff97f5f5619c4bd309457c4f17c6046e3eeba6ac95a48f5d0",
          "sha256": "da0a84a24a2f366e328770e1f85a3e2368e6aae576e5720d5b426bcd1d3c3720",
          "sha1": "2df50795b764210ff6668a33dc81b567a4abb594",
          "md5": "095f841c0e4f7faf9e6320f439af6259"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-native",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "expo-modules-core-0.9.0.aar",
          "url": "expo-modules-core-0.9.0.aar",
          "size": 474741,
          "sha512": "4ad6cb4079a327602350b9b4f53da468eada0f7278508cdfe3d8936abe73d4491e12d75fd617935ff97f5f5619c4bd309457c4f17c6046e3eeba6ac95a48f5d0",
          "sha256": "da0a84a24a2f366e328770e1f85a3e2368e6aae576e5720d5b426bcd1d3c3720",
          "sha1": "2df50795b764210ff6668a33dc81b567a4abb594",
          "md5": "095f841c0e4f7faf9e6320f439af6259"
        }
      ]
    }
  ]
}
