import spawnAsync from '@expo/spawn-async';
import fs from 'fs/promises';
import path from 'path';

import * as env from './env';

export async function initializeGitRepoAsync(repoRoot: string) {
  try {
    await fs.rm(path.join(repoRoot, '.git'), { recursive: true, force: true });
  } catch {}
  await runGitAsync(['init'], { cwd: repoRoot });
  await generateDefaultGitignoreAsync(repoRoot);
}

export async function addAllToGitIndexAsync(repoRoot: string) {
  await runGitAsync(['add', '-A'], { cwd: repoRoot });
}

export async function commitAsync(repoRoot: string, message: string) {
  await runGitAsync(['commit', '-m', message], {
    cwd: repoRoot,
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: 'expo-cng',
      GIT_COMMITTER_NAME: 'expo-cng',
      GIT_AUTHOR_EMAIL: 'noreply@expo.dev',
      GIT_COMMITTER_EMAIL: 'noreply@expo.dev',
    },
  });
}

export async function diffAsync(
  repoRoot: string,
  outputPatchFilePath: string,
  options: string[]
): Promise<void> {
  await runGitAsync(
    [
      'diff',
      '--no-color',
      '--ignore-space-at-eol',
      '--no-ext-diff',
      '--src-prefix=a/',
      '--dst-prefix=b/',
      ...options,
      '--output',
      outputPatchFilePath,
    ],
    {
      cwd: repoRoot,
    }
  );
}

export async function applyPatchAsync(projectRoot: string, patchFilePath: string) {
  const pathArgs = await getPatchPathArgsAsync(projectRoot);
  return await runGitAsync(['apply', '--ignore-whitespace', ...pathArgs, patchFilePath], {
    cwd: projectRoot,
  });
}

/**
 * Returns the extra `git apply` arguments that make patch paths resolve relative to
 * `projectRoot`.
 *
 * Patches are generated in a standalone repository whose root is the native project, so their
 * paths are project relative. `git apply` however resolves paths from the root of the enclosing
 * repository, and ignores paths that fall outside the current directory. In a monorepo where the
 * project lives in a subdirectory, that combination makes every hunk target the wrong location and
 * the patch is skipped without an error. `--directory` restores the missing prefix.
 */
async function getPatchPathArgsAsync(projectRoot: string): Promise<string[]> {
  try {
    // Empty when `projectRoot` is the repository root, `apps/mobile/` when it is nested.
    const prefix = await runGitAsync(['rev-parse', '--show-prefix'], { cwd: projectRoot });
    return prefix ? [`--directory=${prefix}`] : [];
  } catch (e: any) {
    if (e.code === 'ENOENT') {
      throw e;
    }
    // Not inside a repository at all — `git apply` then resolves paths from the current
    // directory, which is already `projectRoot`.
    return [];
  }
}

export async function isPatchAppliedAsync(
  projectRoot: string,
  patchFilePath: string
): Promise<boolean> {
  try {
    const pathArgs = await getPatchPathArgsAsync(projectRoot);
    await runGitAsync(
      ['apply', '--reverse', '--check', '--ignore-whitespace', ...pathArgs, patchFilePath],
      { cwd: projectRoot }
    );
    return true;
  } catch (e: any) {
    if (e.code === 'ENOENT') {
      throw e;
    }
    return false;
  }
}

export async function getPatchChangedLinesAsync(
  projectRoot: string,
  patchFilePath: string
): Promise<number> {
  const pathArgs = await getPatchPathArgsAsync(projectRoot);
  const stdout = await runGitAsync(['apply', '--numstat', ...pathArgs, patchFilePath], {
    cwd: projectRoot,
  });
  const lines = stdout.split(/\r?\n/);
  let changedLines = 0;
  for (const line of lines) {
    if (line === '') {
      continue;
    }
    const [added, deleted] = line.split('\t', 2);
    changedLines += Number(added) + Number(deleted);
  }
  return changedLines;
}

async function runGitAsync(args: string[], options?: spawnAsync.SpawnOptions): Promise<string> {
  try {
    const { stdout, stderr } = await spawnAsync('git', args, options);
    if (env.EXPO_DEBUG) {
      console.log(`Running \`git ${args}\` outputs:\nstdout:\n${stdout}\nstderr:\n${stderr}`);
    }
    return stdout.trim();
  } catch (e: any) {
    if (e.code === 'ENOENT') {
      e.message += `\nGit is required to apply patches. Install Git and try again.`;
    } else if (e.stderr) {
      e.message += `\nstderr:\n${e.stderr}`;
    }
    throw e;
  }
}

async function generateDefaultGitignoreAsync(repoRoot: string) {
  const contents = `\
# These files are generated by pod install and should not be included in patch files.
Podfile.lock
contents.xcworkspacedata
`;
  await fs.writeFile(path.join(repoRoot, '.gitignore'), contents, 'utf8');
}
