package expo.modules.processor

import expo.modules.processor.OptimizedFunctionProcessor.FunctionMetadata

object KotlinRegistryGenerator {

    fun generate(moduleName: String, packageName: String, functions: List<FunctionMetadata>): String {
        // Generate external function declarations
        val externalFunctions = functions.joinToString("\n\n") { function ->
            val methodName = "get${function.functionName.capitalize()}FunctionPointer"
            "    @JvmStatic\n    private external fun $methodName(): Long"
        }

        // Generate registration calls
        val registrationCalls = functions.joinToString("\n") { function ->
            val methodName = "get${function.functionName.capitalize()}FunctionPointer"
            val jsName = function.functionName
            "        decorator.registerOptimizedSyncFunction(\n" +
            "            \"$jsName\",\n" +
            "            moduleInstance,\n" +
            "            $methodName()\n" +
            "        )"
        }

        return """
// Generated by OptimizedFunctionProcessor
// DO NOT EDIT - This file is auto-generated

package $packageName

import expo.modules.kotlin.jni.decorators.JSDecoratorsBridgingObject

@Suppress("unused")
internal object ${moduleName}_OptimizedRegistry {

$externalFunctions

    @JvmStatic
    fun registerOptimizedFunctions(
        decorator: JSDecoratorsBridgingObject,
        moduleInstance: $moduleName
    ) {
$registrationCalls
    }

    init {
        // TODO
        System.loadLibrary("benchmarking-module")
    }
}
""".trimIndent()
    }

    private fun String.capitalize(): String {
        return this.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
    }
}
