/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

#pragma once
#include "ABI48_0_0YGMacros.h"

// clang-format off


ABI48_0_0YG_EXTERN_C_BEGIN

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGAlign,
    ABI48_0_0YGAlignAuto,
    ABI48_0_0YGAlignFlexStart,
    ABI48_0_0YGAlignCenter,
    ABI48_0_0YGAlignFlexEnd,
    ABI48_0_0YGAlignStretch,
    ABI48_0_0YGAlignBaseline,
    ABI48_0_0YGAlignSpaceBetween,
    ABI48_0_0YGAlignSpaceAround)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGDimension,
    ABI48_0_0YGDimensionWidth,
    ABI48_0_0YGDimensionHeight)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGDirection,
    ABI48_0_0YGDirectionInherit,
    ABI48_0_0YGDirectionLTR,
    ABI48_0_0YGDirectionRTL)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGDisplay,
    ABI48_0_0YGDisplayFlex,
    ABI48_0_0YGDisplayNone)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGEdge,
    ABI48_0_0YGEdgeLeft,
    ABI48_0_0YGEdgeTop,
    ABI48_0_0YGEdgeRight,
    ABI48_0_0YGEdgeBottom,
    ABI48_0_0YGEdgeStart,
    ABI48_0_0YGEdgeEnd,
    ABI48_0_0YGEdgeHorizontal,
    ABI48_0_0YGEdgeVertical,
    ABI48_0_0YGEdgeAll)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGExperimentalFeature,
    ABI48_0_0YGExperimentalFeatureWebFlexBasis)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGFlexDirection,
    ABI48_0_0YGFlexDirectionColumn,
    ABI48_0_0YGFlexDirectionColumnReverse,
    ABI48_0_0YGFlexDirectionRow,
    ABI48_0_0YGFlexDirectionRowReverse)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGGutter,
    ABI48_0_0YGGutterColumn,
    ABI48_0_0YGGutterRow,
    ABI48_0_0YGGutterAll)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGJustify,
    ABI48_0_0YGJustifyFlexStart,
    ABI48_0_0YGJustifyCenter,
    ABI48_0_0YGJustifyFlexEnd,
    ABI48_0_0YGJustifySpaceBetween,
    ABI48_0_0YGJustifySpaceAround,
    ABI48_0_0YGJustifySpaceEvenly)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGLogLevel,
    ABI48_0_0YGLogLevelError,
    ABI48_0_0YGLogLevelWarn,
    ABI48_0_0YGLogLevelInfo,
    ABI48_0_0YGLogLevelDebug,
    ABI48_0_0YGLogLevelVerbose,
    ABI48_0_0YGLogLevelFatal)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGMeasureMode,
    ABI48_0_0YGMeasureModeUndefined,
    ABI48_0_0YGMeasureModeExactly,
    ABI48_0_0YGMeasureModeAtMost)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGNodeType,
    ABI48_0_0YGNodeTypeDefault,
    ABI48_0_0YGNodeTypeText)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGOverflow,
    ABI48_0_0YGOverflowVisible,
    ABI48_0_0YGOverflowHidden,
    ABI48_0_0YGOverflowScroll)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGPositionType,
    ABI48_0_0YGPositionTypeStatic,
    ABI48_0_0YGPositionTypeRelative,
    ABI48_0_0YGPositionTypeAbsolute)

ABI48_0_0YG_ENUM_DECL(
    ABI48_0_0YGPrintOptions,
    ABI48_0_0YGPrintOptionsLayout = 1,
    ABI48_0_0YGPrintOptionsStyle = 2,
    ABI48_0_0YGPrintOptionsChildren = 4)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGUnit,
    ABI48_0_0YGUnitUndefined,
    ABI48_0_0YGUnitPoint,
    ABI48_0_0YGUnitPercent,
    ABI48_0_0YGUnitAuto)

ABI48_0_0YG_ENUM_SEQ_DECL(
    ABI48_0_0YGWrap,
    ABI48_0_0YGWrapNoWrap,
    ABI48_0_0YGWrapWrap,
    ABI48_0_0YGWrapWrapReverse)

ABI48_0_0YG_EXTERN_C_END
