// @ref llp/0006-agent-native-cli-surface.rfc.md — `context`: the machine-readable project brief.
import chalk from 'chalk';

import * as Log from '../log';
import { probeProjectStateAsync } from '../project/probe';
import type { ProjectState } from '../project/types';

/** Width of the label column of the human readable summary. */
const LABEL_WIDTH = 12;

/**
 * Print the project state, either as the brief an agent parses (`--json`) or as a summary a
 * developer reads.
 */
export async function printProjectContextAsync(
  projectRoot: string,
  options: { json?: boolean }
): Promise<void> {
  const state = await probeProjectStateAsync(projectRoot);

  if (options.json) {
    Log.log(JSON.stringify(state, null, 2));
    return;
  }

  for (const line of summaryLines(state)) {
    Log.log(line);
  }
}

function summaryLines(state: ProjectState): string[] {
  const lines: string[] = [];
  const row = (label: string, value: string) =>
    lines.push(`${chalk.dim(label.padEnd(LABEL_WIDTH))}${value}`);
  const detail = (value: string) => lines.push(`${' '.repeat(LABEL_WIDTH)}${value}`);

  const nativeDirs = [state.nativeDirs.ios && 'ios', state.nativeDirs.android && 'android'].filter(
    Boolean
  );

  row('Project', state.projectRoot);
  row('SDK', state.sdkVersion ?? chalk.yellow('unknown (expo is not installed)'));
  row(
    'Native',
    nativeDirs.length
      ? `bare (${nativeDirs.join(', ')} checked in)`
      : 'managed (native projects generated by prebuild)'
  );
  row('Dev client', state.usesDevClient ? 'yes' : 'no');
  row('Web', state.hasWeb ? 'yes' : 'no');
  row(
    'Expo Go',
    state.expoGo.compatible
      ? chalk.green('compatible')
      : chalk.yellow(`not compatible (${state.expoGo.reasons.length} reason(s))`)
  );
  for (const reason of state.expoGo.reasons) {
    const target = reason.packageName ? ` ${chalk.bold(reason.packageName)}` : '';
    detail(`${chalk.yellow(reason.kind)}${target}: ${reason.detail}`);
  }
  row(
    'Fingerprint',
    state.fingerprint.hash ?? chalk.yellow(`unavailable: ${state.fingerprint.error}`)
  );

  return lines;
}
