// @ref llp/0006-agent-native-cli-surface.rfc.md — `context`: the machine-readable project brief.
import chalk from 'chalk';

import { buildContextFollowUps, followUpsEnabled, reportFollowUps } from '../followups';
import * as Log from '../log';
import { probeProjectStateAsync } from '../project/probe';
import type { ProjectState } from '../project/types';

/** Width of the label column of the human readable summary. */
const LABEL_WIDTH = 12;

export interface ProjectContextOptions {
  /** Print the project brief as one JSON object instead of a summary. */
  json?: boolean;
  /** Attach the state-aware next actions to the output, cleared by `--no-followups`. */
  followups?: boolean;
}

/**
 * Print the project state, either as the brief an agent parses (`--json`) or as a summary a
 * developer reads.
 */
export async function printProjectContextAsync(
  projectRoot: string,
  options: ProjectContextOptions
): Promise<void> {
  const state = await probeProjectStateAsync(projectRoot);
  // @ref llp/0009-smart-followups.rfc.md §Design — the brief says what the project is, so the
  // follow-ups are the commands that answer what is true now and what would happen next.
  const followups = followUpsEnabled(options.followups) ? buildContextFollowUps(state) : [];

  if (options.json) {
    Log.log(JSON.stringify({ ...state, followups }, null, 2));
  } else {
    for (const line of summaryLines(state)) {
      Log.log(line);
    }
  }

  reportFollowUps('context', followups, { json: options.json });
}

function summaryLines(state: ProjectState): string[] {
  const lines: string[] = [];
  const row = (label: string, value: string) =>
    lines.push(`${chalk.dim(label.padEnd(LABEL_WIDTH))}${value}`);
  const detail = (value: string) => lines.push(`${' '.repeat(LABEL_WIDTH)}${value}`);

  const nativeDirs = [state.nativeDirs.ios && 'ios', state.nativeDirs.android && 'android'].filter(
    Boolean
  );

  row('Project', state.projectRoot);
  row('SDK', state.sdkVersion ?? chalk.yellow('unknown (expo is not installed)'));
  row(
    'Native',
    nativeDirs.length
      ? `bare (${nativeDirs.join(', ')} checked in)`
      : 'managed (native projects generated by prebuild)'
  );
  row('Dev client', state.usesDevClient ? 'yes' : 'no');
  row('Web', state.hasWeb ? 'yes' : 'no');
  row(
    'Expo Go',
    state.expoGo.compatible
      ? chalk.green('compatible')
      : chalk.yellow(`not compatible (${state.expoGo.reasons.length} reason(s))`)
  );
  for (const reason of state.expoGo.reasons) {
    const target = reason.packageName ? ` ${chalk.bold(reason.packageName)}` : '';
    detail(`${chalk.yellow(reason.kind)}${target}: ${reason.detail}`);
  }
  row(
    'Fingerprint',
    state.fingerprint.hash ?? chalk.yellow(`unavailable: ${state.fingerprint.error}`)
  );

  return lines;
}
