import { microBundle } from './mini-metro';

const fs = {
  'index.js': `
    import { foo } from './foo';
    console.log(foo);
  `,
  'foo.js': `
    export const foo = 'foo';
  `,
};

it(`can create a micro Metro graph fixture`, async () => {
  expect(await microBundle({ fs })).toMatchInlineSnapshot(`
    [
      "/app/index.js",
      [],
      {
        "dependencies": Map {
          "/app/index.js" => {
            "dependencies": Map {
              "w3xsnP8GGa/kB56APw6c+VOi8X0=" => {
                "absolutePath": "/app/foo.js",
                "data": {
                  "data": {
                    "asyncType": null,
                    "exportNames": [
                      "*",
                    ],
                    "imports": 1,
                    "isESMImport": true,
                    "key": "w3xsnP8GGa/kB56APw6c+VOi8X0=",
                    "locs": [
                      SourceLocation {
                        "end": Position {
                          "column": 32,
                          "index": 33,
                          "line": 2,
                        },
                        "filename": undefined,
                        "identifierName": undefined,
                        "start": Position {
                          "column": 4,
                          "index": 5,
                          "line": 2,
                        },
                      },
                    ],
                  },
                  "name": "./foo",
                },
              },
            },
            "getSource": [Function],
            "inverseDependencies": [],
            "output": [
              {
                "data": {
                  "code": "__d(function (global, _$$_REQUIRE, _$$_IMPORT_DEFAULT, _$$_IMPORT_ALL, module, exports, _dependencyMap) {
      "use strict";

      var _foo = _$$_REQUIRE(_dependencyMap[0], "./foo");
      console.log(_foo.foo);
    });",
                  "expoDomComponentReference": undefined,
                  "functionMap": {
                    "mappings": "AAA",
                    "names": [
                      "<global>",
                    ],
                  },
                  "hasCjsExports": false,
                  "lineCount": 6,
                  "loaderReference": undefined,
                  "map": {
                    "__count": 18,
                    "__names": [
                      "_foo",
                      "_$$_REQUIRE",
                      "_dependencyMap",
                      "console",
                      "log",
                      "foo",
                    ],
                    "__packed": [
                      4,
                      2,
                      2,
                      4,
                      -1,
                      4,
                      6,
                      2,
                      4,
                      0,
                      4,
                      10,
                      2,
                      4,
                      -1,
                      4,
                      13,
                      2,
                      4,
                      1,
                      4,
                      24,
                      2,
                      4,
                      -1,
                      4,
                      25,
                      2,
                      4,
                      2,
                      4,
                      39,
                      2,
                      4,
                      -1,
                      5,
                      2,
                      3,
                      4,
                      3,
                      5,
                      9,
                      3,
                      11,
                      -1,
                      5,
                      10,
                      3,
                      12,
                      4,
                      5,
                      13,
                      3,
                      15,
                      -1,
                      5,
                      14,
                      3,
                      16,
                      5,
                      5,
                      18,
                      3,
                      19,
                      -1,
                      5,
                      19,
                      3,
                      19,
                      5,
                      5,
                      22,
                      3,
                      19,
                      -1,
                      5,
                      23,
                      3,
                      20,
                      -1,
                      6,
                      0,
                      3,
                      21,
                      -1,
                      6,
                      3,
                      -1,
                      -1,
                      -1,
                    ],
                    "__version": 1,
                  },
                  "reactClientReference": undefined,
                  "reactServerReference": undefined,
                },
                "type": "js/module",
              },
            ],
            "path": "/app/index.js",
          },
          "/app/foo.js" => {
            "dependencies": Map {},
            "getSource": [Function],
            "inverseDependencies": [
              "/app/index.js",
            ],
            "output": [
              {
                "data": {
                  "code": "__d(function (global, _$$_REQUIRE, _$$_IMPORT_DEFAULT, _$$_IMPORT_ALL, module, exports, _dependencyMap) {
      "use strict";

      Object.defineProperty(exports, '__esModule', {
        value: true
      });
      Object.defineProperty(exports, "foo", {
        enumerable: true,
        get: function () {
          return foo;
        }
      });
      const foo = 'foo';
    });",
                  "expoDomComponentReference": undefined,
                  "functionMap": {
                    "mappings": "AAA",
                    "names": [
                      "<global>",
                    ],
                  },
                  "hasCjsExports": false,
                  "lineCount": 14,
                  "loaderReference": undefined,
                  "map": {
                    "__count": 24,
                    "__names": [
                      "Object",
                      "defineProperty",
                      "exports",
                      "enumerable",
                      "get",
                      "foo",
                    ],
                    "__packed": [
                      7,
                      2,
                      2,
                      4,
                      0,
                      7,
                      8,
                      2,
                      4,
                      -1,
                      7,
                      9,
                      2,
                      4,
                      1,
                      7,
                      23,
                      2,
                      4,
                      -1,
                      7,
                      24,
                      2,
                      4,
                      2,
                      7,
                      31,
                      2,
                      4,
                      -1,
                      8,
                      4,
                      2,
                      4,
                      3,
                      8,
                      14,
                      2,
                      4,
                      -1,
                      9,
                      4,
                      2,
                      4,
                      4,
                      9,
                      7,
                      2,
                      4,
                      -1,
                      9,
                      18,
                      2,
                      4,
                      4,
                      9,
                      19,
                      2,
                      4,
                      -1,
                      10,
                      6,
                      2,
                      4,
                      -1,
                      10,
                      13,
                      2,
                      4,
                      5,
                      10,
                      16,
                      2,
                      4,
                      -1,
                      11,
                      4,
                      2,
                      4,
                      -1,
                      12,
                      2,
                      2,
                      4,
                      -1,
                      13,
                      2,
                      2,
                      11,
                      -1,
                      13,
                      8,
                      2,
                      17,
                      5,
                      13,
                      11,
                      2,
                      20,
                      -1,
                      13,
                      14,
                      2,
                      23,
                      -1,
                      13,
                      19,
                      2,
                      28,
                      -1,
                      14,
                      0,
                      2,
                      29,
                      -1,
                      14,
                      3,
                      -1,
                      -1,
                      -1,
                    ],
                    "__version": 1,
                  },
                  "reactClientReference": undefined,
                  "reactServerReference": undefined,
                },
                "type": "js/module",
              },
            ],
            "path": "/app/foo.js",
          },
        },
        "entryPoints": Set {
          "/app/index.js",
        },
        "transformOptions": {
          "customTransformOptions": {
            "baseUrl": undefined,
            "bytecode": undefined,
            "engine": undefined,
            "environment": undefined,
            "optimize": undefined,
            "reactCompiler": undefined,
          },
          "dev": true,
          "experimentalImportSupport": true,
          "inlineRequires": false,
          "minify": false,
          "platform": "web",
          "type": "module",
          "unstable_transformProfile": "default",
        },
      },
      {
        "_test_getPackageJson": [Function],
        "asyncRequireModulePath": "expo-mock/async-require",
        "createModuleId": [Function],
        "dev": true,
        "getRunModuleStatement": [Function],
        "includeAsyncPaths": true,
        "inlineSourceMap": undefined,
        "modulesOnly": false,
        "processModuleFilter": [Function],
        "projectRoot": "/app",
        "runBeforeMainModule": [],
        "runModule": true,
        "serializerOptions": undefined,
        "serverRoot": "/app",
        "shouldAddToIgnoreList": [Function],
        "sourceMapUrl": undefined,
        "sourceUrl": undefined,
      },
    ]
  `);
});
