{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-structured-headers",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-structured-headers-2.2.1.aar",
          "url": "expo-structured-headers-2.2.1.aar",
          "size": 40759,
          "sha512": "0d4b3a94198c6b1bbd669a61f2f4563d947a89836049ab6d31623ecc77008ec83fa28499023abc77b37ffa9a5adc1cff3831b880b88916ed839562d15864c990",
          "sha256": "3a804f62dd7922ca4a4ff56a37de92f12586085e4b2a1a450820367be9332308",
          "sha1": "c03380b235fc82c0c4f4da75f4e8a1b8a38d2203",
          "md5": "0c5ba8d9ae20fe6cae6995905e9e9203"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-structured-headers-2.2.1.aar",
          "url": "expo-structured-headers-2.2.1.aar",
          "size": 40759,
          "sha512": "0d4b3a94198c6b1bbd669a61f2f4563d947a89836049ab6d31623ecc77008ec83fa28499023abc77b37ffa9a5adc1cff3831b880b88916ed839562d15864c990",
          "sha256": "3a804f62dd7922ca4a4ff56a37de92f12586085e4b2a1a450820367be9332308",
          "sha1": "c03380b235fc82c0c4f4da75f4e8a1b8a38d2203",
          "md5": "0c5ba8d9ae20fe6cae6995905e9e9203"
        }
      ]
    }
  ]
}
