export {
  getPosition,
  hasLocationServicesEnabled,
  enableLocationServices,
  useLocationServices,
  getForegroundPermissionsAsync,
  requestForegroundPermissionsAsync,
  getBackgroundPermissionsAsync,
  requestBackgroundPermissionsAsync,
  useForegroundPermissions,
  useBackgroundPermissions,
  PositionWatchHandle,
  watchPosition,
  useWatchPosition,
  LocationProvider,
  setLocationProvider,
  getSelectedLocationProviderName,
  LocationUpdatesHandle,
  defineLocationTask,
  type UseWatchPositionOptions,
  type UseWatchPositionResult,
} from './js';

export {
  LocationProfile,
  LocationAccuracy,
  LocationScope,
  RequestPermissionsAccuracyOption,
  type Coordinates,
  type Position,
  type PositionUpdate,
  type WatchPositionParams,
  type GetPositionOptions,
  type LocationPermissionResponse,
  type RequestPermissionsOptions,
  type LocationProviderRefType,
} from './types';
