export {
  getPosition,
  watchPosition,
  hasLocationServicesEnabled,
  enableLocationServices,
  getForegroundPermissions,
  requestForegroundPermissions,
  getBackgroundPermissions,
  requestBackgroundPermissions,
  getNotificationPermissions,
  requestNotificationPermissions,
  setLocationProvider,
  getSelectedLocationProviderName,
  ensureBackgroundSessionStarted,
  stopBackgroundSession,
  getBackgroundSessionStatus,
} from './js';
