export {
  getPosition,
  watchPosition,
  hasLocationServicesEnabled,
  enableLocationServices,
  getForegroundPermissions,
  requestForegroundPermissions,
  getBackgroundPermissions,
  requestBackgroundPermissions,
  setLocationProvider,
  getSelectedLocationProviderName,
  defineLocationTask,
  useForegroundPermissions,
  useBackgroundPermissions,
  useLocationServices,
  useUserLocation,
} from './js';
