source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'NCL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Camersja
  rn_path = "../node_modules/react-native"
  # Cocoapods ~> 1.5.0 does not support including local pods for which path
  # is a symlink. See PR https://github.com/CocoaPods/CocoaPods/pull/7781.
  pod 'React', path: rn_path, subspecs: [
    "Core",
    "ART",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTCameraRoll",
    "RCTGeolocation",
    "RCTImage",
    "RCTNetwork",
    "RCTLinkingIOS",
    "RCTText",
    "RCTVibration",
    "RCTWebSocket",
    "DevSupport",
    "CxxBridge"
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'Folly',
    :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true

  pod 'EXCore', path: '../node_modules/expo-core/ios'
  pod 'EXReactNativeAdapter', path: '../node_modules/expo-react-native-adapter/ios'

  pod 'EXConstantsInterface', path: '../node_modules/expo-constants-interface/ios'
  pod 'EXConstants', path: '../node_modules/expo-constants/ios'

  pod 'EXSensorsInterface', path: '../node_modules/expo-sensors-interface/ios'
  pod 'EXSensors', path: '../node_modules/expo-sensors/ios'

  pod 'EXFileSystemInterface', path: '../node_modules/expo-file-system-interface/ios'
  pod 'EXFileSystem', path: '../node_modules/expo-file-system/ios'

  pod 'EXGL', path: '../node_modules/expo-gl/ios'
  pod 'EXGL-CPP', path: '../node_modules/expo-gl-cpp/cpp'

  pod 'EXCameraInterface', path: '../node_modules/expo-camera-interface/ios'
  pod 'EXCamera', path: '../node_modules/expo-camera/ios'
  pod 'EXFaceDetectorInterface', path: '../node_modules/expo-face-detector-interface/ios'

  pod 'EXPermissionsInterface', path: '../node_modules/expo-permissions-interface/ios'
  pod 'EXPermissions', path: '../node_modules/expo-permissions/ios'
end
