{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-local-authentication",
    "version": "12.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-local-authentication-12.2.0.aar",
          "url": "expo-local-authentication-12.2.0.aar",
          "size": 27486,
          "sha512": "f95dfc816ba85ba8179567d3db7709aeab05211a1f111bcc03019c4cbc53f73eb6b0d7b03103fe0ec0ad1638fd93be08f2fcd50f18574a780375f5be9f199a59",
          "sha256": "6e5eedc5122fe12d48e9e6ebdd7c014aa133aa34b13b8b9412bdf30cafeff7d8",
          "sha1": "97726b62303c9486a3eb607b9e587421f21b0b0e",
          "md5": "629802b87f93830f3789789f171225ce"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-local-authentication-12.2.0.aar",
          "url": "expo-local-authentication-12.2.0.aar",
          "size": 27486,
          "sha512": "f95dfc816ba85ba8179567d3db7709aeab05211a1f111bcc03019c4cbc53f73eb6b0d7b03103fe0ec0ad1638fd93be08f2fcd50f18574a780375f5be9f199a59",
          "sha256": "6e5eedc5122fe12d48e9e6ebdd7c014aa133aa34b13b8b9412bdf30cafeff7d8",
          "sha1": "97726b62303c9486a3eb607b9e587421f21b0b0e",
          "md5": "629802b87f93830f3789789f171225ce"
        }
      ]
    }
  ]
}
