'use strict';

const {
  parseDumpedManifest,
  renderPrecompiledManifest,
  renderSourceManifest,
  renderPureSwiftManifest,
} = require('../manifests');

describe('parseDumpedManifest', () => {
  const dumped = JSON.stringify({
    name: 'expo-file-system',
    products: [
      { name: 'ExpoFileSystem', type: { library: ['automatic'] }, targets: ['ExpoFileSystem', 'ExpoFileSystemObjC'] },
      { name: 'ExpoFileSystemExecutable', type: { executable: [] }, targets: ['CLI'] },
    ],
    targets: [
      {
        name: 'ExpoFileSystem',
        type: 'regular',
        path: 'ios/ExpoFileSystem',
        dependencies: [{ byName: ['ExpoFileSystemObjC', null] }],
      },
      { name: 'ExpoFileSystemObjC', type: 'regular', path: 'ios/ExpoFileSystemObjC', publicHeadersPath: 'include', dependencies: [] },
      { name: 'ExpoFileSystemTests', type: 'test', path: 'ios/Tests', dependencies: [] },
    ],
  });

  it('keeps only regular targets, records path/publicHeadersPath, resolves sibling deps', () => {
    const { name, targets } = parseDumpedManifest(dumped);
    expect(name).toBe('expo-file-system');
    expect(targets).toEqual([
      { name: 'ExpoFileSystem', path: 'ios/ExpoFileSystem', publicHeadersPath: null, siblingDeps: ['ExpoFileSystemObjC'] },
      { name: 'ExpoFileSystemObjC', path: 'ios/ExpoFileSystemObjC', publicHeadersPath: 'include', siblingDeps: [] },
    ]);
  });

  it('keeps only library products and drops product targets not present as regular targets', () => {
    const { products } = parseDumpedManifest(dumped);
    expect(products).toEqual([
      { name: 'ExpoFileSystem', targets: ['ExpoFileSystem', 'ExpoFileSystemObjC'] },
    ]);
  });
});

describe('renderPrecompiledManifest', () => {
  it('exposes the xcframework as a binaryTarget (exact bytes)', () => {
    expect(renderPrecompiledManifest('ExpoModulesCore', '../../rel/ExpoModulesCore.xcframework')).toBe(
      `// swift-tools-version: 6.0
// AUTO-GENERATED by expo/scripts/spm/plugin.js — do not edit.
// Consumption package for the precompiled ExpoModulesCore.xcframework.
import PackageDescription

let package = Package(
    name: "ExpoModulesCore",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ExpoModulesCore", targets: ["ExpoModulesCore"]),
    ],
    targets: [
        .binaryTarget(name: "ExpoModulesCore", path: "../../rel/ExpoModulesCore.xcframework"),
    ]
)
`
    );
  });
});

describe('renderSourceManifest', () => {
  const manifest = {
    name: 'expo-file-system',
    products: [{ name: 'ExpoFileSystem', targets: ['ExpoFileSystem', 'ExpoFileSystemObjC'] }],
    targets: [
      { name: 'ExpoFileSystem', path: 'ios/ExpoFileSystem', publicHeadersPath: null, siblingDeps: ['ExpoFileSystemObjC'] },
      { name: 'ExpoFileSystemObjC', path: 'ios/ExpoFileSystemObjC', publicHeadersPath: 'include', siblingDeps: [] },
    ],
  };
  const out = renderSourceManifest(
    manifest,
    ['.package(name: "ExpoModulesCore", path: "/abs/emc")'],
    ['.product(name: "ExpoModulesCore", package: "ExpoModulesCore")']
  );

  it('mirrors targets with sibling deps first, then injected deps', () => {
    expect(out).toContain('name: "ExpoFileSystem"');
    expect(out).toContain('"ExpoFileSystemObjC",\n                .product(name: "ExpoModulesCore", package: "ExpoModulesCore")');
    expect(out).toContain('path: "root/ios/ExpoFileSystem"');
  });

  it('emits publicHeadersPath only for targets that declare it', () => {
    expect(out).toContain('path: "root/ios/ExpoFileSystemObjC",\n            publicHeadersPath: "include",');
    // the Swift target has no publicHeadersPath line
    expect(out).not.toContain('path: "root/ios/ExpoFileSystem",\n            publicHeadersPath:');
  });

  it('always emits the Swift-5 language mode + C++20 tail (folly needs C++17+)', () => {
    expect(out).toContain('swiftLanguageModes: [.v5],\n    cxxLanguageStandard: .cxx20');
  });
});

describe('renderPureSwiftManifest', () => {
  const out = renderPureSwiftManifest(
    'ExpoAsset',
    'ios',
    ['.package(name: "ExpoModulesCore", path: "/abs/emc")'],
    ['.product(name: "ExpoModulesCore", package: "ExpoModulesCore")']
  );

  it('emits a single target over the source dir with the given deps', () => {
    expect(out).toContain('.library(name: "ExpoAsset", targets: ["ExpoAsset"])');
    expect(out).toContain('path: "root/ios"');
    expect(out).toContain('.product(name: "ExpoModulesCore", package: "ExpoModulesCore")');
    expect(out).toContain('swiftLanguageModes: [.v5],\n    cxxLanguageStandard: .cxx20');
  });
});
