# @generated by expotools
      
if pod_name.start_with?('ABI36_0_0React') || pod_name == 'ABI36_0_0ExpoKit'
  target_installation_result.native_target.build_configurations.each do |config|
    config.build_settings['OTHER_CFLAGS'] = %w[
      -DkNeverRequested=ABI36_0_0ReactkNeverRequested
      -DkNeverProgressed=ABI36_0_0ReactkNeverProgressed
      -DkSMCalloutViewRepositionDelayForUIScrollView=ABI36_0_0ReactkSMCalloutViewRepositionDelayForUIScrollView
      -DregionAsJSON=ABI36_0_0ReactregionAsJSON
      -DunionRect=ABI36_0_0ReactunionRect
      -DJSNoBytecodeFileFormatVersion=ABI36_0_0ReactJSNoBytecodeFileFormatVersion
      -DJSSamplingProfilerEnabled=ABI36_0_0ReactJSSamplingProfilerEnabled
      -DRECONNECT_DELAY_MS=ABI36_0_0ReactRECONNECT_DELAY_MS
      -DMAX_DELTA_TIME=ABI36_0_0ReactMAX_DELTA_TIME
      -DgCurrentGenerationCount=ABI36_0_0ReactgCurrentGenerationCount
      -DgPrintSkips=ABI36_0_0ReactgPrintSkips
      -DgPrintChanges=ABI36_0_0ReactgPrintChanges
      -DlayoutNodeInternal=ABI36_0_0ReactlayoutNodeInternal
      -DgDepth=ABI36_0_0ReactgDepth
      -DgPrintTree=ABI36_0_0ReactgPrintTree
      -DisUndefined=ABI36_0_0ReactisUndefined
      -DgNodeInstanceCount=ABI36_0_0ReactgNodeInstanceCount
    ]
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI36_0_0RCT_DEV=1'
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI36_0_0RCT_ENABLE_INSPECTOR=0'
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI36_0_0ENABLE_PACKAGER_CONNECTION=0'
    # Enable Google Maps support
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI36_0_0HAVE_GOOGLE_MAPS=1'
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABI36_0_0HAVE_GOOGLE_MAPS_UTILS=1'
  end
end
