/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */
import type { AgeRangeRequest, AgeRangeResponse, RegulatoryFeature } from '../src/index';

export async function requestAgeRangeAsync(opts: AgeRangeRequest): Promise<AgeRangeResponse> {
  return {
    installId: 'some-id',
    userStatus: 'VERIFIED',
    lowerBound: 18,
    upperBound: null,
    activeParentalControls: [],
  };
}

export async function isEligibleForAgeFeaturesAsync(): Promise<boolean | null> {
  return null;
}

export async function showSignificantUpdateAcknowledgmentAsync(
  _updateDescription: string
): Promise<void> {}

export async function getRequiredRegulatoryFeaturesAsync(): Promise<RegulatoryFeature[] | null> {
  return null;
}
