/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by an internal plugin build system
 */

#ifndef ABI43_0_0RN_DISABLE_OSS_PLUGIN_HEADER

// OSS-compatibility layer

#import "ABI43_0_0CoreModulesPlugins.h"

#import <string>
#import <unordered_map>

Class ABI43_0_0RCTCoreModulesClassProvider(const char *name) {
  static std::unordered_map<std::string, Class (*)(void)> sCoreModuleClassMap = {
    {"AccessibilityManager", ABI43_0_0RCTAccessibilityManagerCls},
    {"Appearance", ABI43_0_0RCTAppearanceCls},
    {"DeviceInfo", ABI43_0_0RCTDeviceInfoCls},
    {"ExceptionsManager", ABI43_0_0RCTExceptionsManagerCls},
    {"PlatformConstants", ABI43_0_0RCTPlatformCls},
    {"Clipboard", ABI43_0_0RCTClipboardCls},
    {"I18nManager", ABI43_0_0RCTI18nManagerCls},
    {"SourceCode", ABI43_0_0RCTSourceCodeCls},
    {"ActionSheetManager", ABI43_0_0RCTActionSheetManagerCls},
    {"AlertManager", ABI43_0_0RCTAlertManagerCls},
    {"AsyncLocalStorage", ABI43_0_0RCTAsyncLocalStorageCls},
    {"Timing", ABI43_0_0RCTTimingCls},
    {"StatusBarManager", ABI43_0_0RCTStatusBarManagerCls},
    {"KeyboardObserver", ABI43_0_0RCTKeyboardObserverCls},
    {"AppState", ABI43_0_0RCTAppStateCls},
    {"PerfMonitor", ABI43_0_0RCTPerfMonitorCls},
    {"DevMenu", ABI43_0_0RCTDevMenuCls},
    {"DevSettings", ABI43_0_0RCTDevSettingsCls},
    {"RedBox", ABI43_0_0RCTRedBoxCls},
    {"LogBox", ABI43_0_0RCTLogBoxCls},
    {"WebSocketExecutor", ABI43_0_0RCTWebSocketExecutorCls},
    {"WebSocketModule", ABI43_0_0RCTWebSocketModuleCls},
    {"DevLoadingView", ABI43_0_0RCTDevLoadingViewCls},
    {"DevSplitBundleLoader", ABI43_0_0RCTDevSplitBundleLoaderCls},
    {"EventDispatcher", ABI43_0_0RCTEventDispatcherCls},
  };

  auto p = sCoreModuleClassMap.find(name);
  if (p != sCoreModuleClassMap.end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return nil;
}

#endif // ABI43_0_0RN_DISABLE_OSS_PLUGIN_HEADER
