/**
 * Automatically generated by expo-modules-autolinking.
 *
 * This autogenerated class provides a list of classes of native Expo modules,
 * but only these that are written in Swift and use the new API for creating Expo modules.
 */

import ABI45_0_0ExpoModulesCore
import ABI45_0_0ExpoCellular
import ABI45_0_0ExpoClipboard
import ABI45_0_0ExpoCrypto
import ABI45_0_0EASClient
import ABI45_0_0ExpoHaptics
import ABI45_0_0ExpoImageManipulator
import ABI45_0_0ExpoImagePicker
import ABI45_0_0ExpoKeepAwake
import ABI45_0_0ExpoLinearGradient
import ABI45_0_0ExpoLocalization
import ABI45_0_0ExpoRandom
import ABI45_0_0EXScreenOrientation
import ABI45_0_0ExpoSystemUI
import ABI45_0_0EXTrackingTransparency
import ABI45_0_0EXUpdates
import ABI45_0_0ExpoWebBrowser

@objc(ABI45_0_0ExpoModulesProvider)
public class ExpoModulesProvider: ModulesProvider {
  public override func getModuleClasses() -> [AnyModule.Type] {
    return [
      CellularModule.self,
      ClipboardModule.self,
      CryptoModule.self,
      EASClientModule.self,
      HapticsModule.self,
      ImageManipulatorModule.self,
      ImagePickerModule.self,
      KeepAwakeModule.self,
      LinearGradientModule.self,
      LocalizationModule.self,
      RandomModule.self,
      ExpoSystemUIModule.self,
      TrackingTransparencyModule.self,
      WebBrowserModule.self
    ]
  }

  public override func getAppDelegateSubscribers() -> [ExpoAppDelegateSubscriber.Type] {
    return [
      ScreenOrientationAppDelegate.self,
      ExpoUpdatesAppDelegateSubscriber.self
    ]
  }

  public override func getReactDelegateHandlers() -> [ExpoReactDelegateHandlerTupleType] {
    return [
      (packageName: "expo-screen-orientation", handler: ScreenOrientationReactDelegateHandler.self),
      (packageName: "expo-updates", handler: ExpoUpdatesReactDelegateHandler.self)
    ]
  }
}
