/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type PrintOptions = any;

export async function print(options: PrintOptions): Promise<any> {}

export async function selectPrinter(): Promise<any> {}

export async function printToFileAsync(options: PrintOptions): Promise<any> {}
