/**
 * @generated by scripts/bump-oss-version.js
 *
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "ABI30_0_0RCTVersion.h"

NSString* const ABI30_0_0RCTVersionMajor = @"major";
NSString* const ABI30_0_0RCTVersionMinor = @"minor";
NSString* const ABI30_0_0RCTVersionPatch = @"patch";
NSString* const ABI30_0_0RCTVersionPrerelease = @"prerelease";

static NSDictionary* __rnVersion;

__attribute__((constructor))
static void __makeVersion()
{
  __rnVersion = @{
                  ABI30_0_0RCTVersionMajor: @(0),
                  ABI30_0_0RCTVersionMinor: @(55),
                  ABI30_0_0RCTVersionPatch: @(4),
                  ABI30_0_0RCTVersionPrerelease: [NSNull null],
                  };
}

NSDictionary* ABI30_0_0RCTGetreactNativeVersion(void)
{
  return __rnVersion;
}
