module.exports = {
  SimpleLineIcons: true,
  AntDesign: true,
  createIconSet: true,
  createIconSetFromFontAwesome5: true,
  createIconSetFromFontello: true,
  createIconSetFromIcoMoon: true,
  createMultiStyleIconSet: true,
  Entypo: true,
  EvilIcons: true,
  Feather: true,
  FontAwesome: true,
  FontAwesome5: true,
  Foundation: true,
  iconFontSources: true,
  Icons: true,
  Ionicons: true,
  MaterialCommunityIcons: true,
  MaterialIcons: true,
  Octicons: true,
  Zocial: true,
};
