{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-web-browser",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-web-browser-10.2.0.aar",
          "url": "expo-web-browser-10.2.0.aar",
          "size": 26500,
          "sha512": "aa9e1c1afbdeccbd33328e6946846e6fb552a7a45b16dc96e90d487c30dadbc21e68b79e264cb7d57bfe88e44c6cc50e459b5711d70117cc8911fcf155c6fa19",
          "sha256": "e5a06b7c19807e1c98167512371c9eb9b24de9307ac3dc4b84410294c644fbf2",
          "sha1": "2d8f7ad79917941ac2207bc07bcde5934cec1f2e",
          "md5": "78f0319708dce5ffa9d030e97d4dd0b0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-web-browser-10.2.0.aar",
          "url": "expo-web-browser-10.2.0.aar",
          "size": 26500,
          "sha512": "aa9e1c1afbdeccbd33328e6946846e6fb552a7a45b16dc96e90d487c30dadbc21e68b79e264cb7d57bfe88e44c6cc50e459b5711d70117cc8911fcf155c6fa19",
          "sha256": "e5a06b7c19807e1c98167512371c9eb9b24de9307ac3dc4b84410294c644fbf2",
          "sha1": "2d8f7ad79917941ac2207bc07bcde5934cec1f2e",
          "md5": "78f0319708dce5ffa9d030e97d4dd0b0"
        }
      ]
    }
  ]
}
