# @generated by expotools

require './versioned-react-native/ABI46_0_0/ReactNative/scripts/react_native_pods.rb'

use_react_native_ABI46_0_0!(
  :path => './versioned-react-native/ABI46_0_0/ReactNative',
  :hermes_enabled => true,
  :fabric_enabled => false,
)

pod 'ABI46_0_0ExpoKit',
  :path => './versioned-react-native/ABI46_0_0/Expo/ExpoKit',
  :project_name => 'ABI46_0_0',
  :subspecs => ['Expo', 'ExpoOptional']

use_pods! '{versioned,vendored}/sdk46/**/*.podspec.json', 'ABI46_0_0'
