{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-intent-launcher",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-intent-launcher-10.2.0.aar",
          "url": "expo-intent-launcher-10.2.0.aar",
          "size": 23762,
          "sha512": "f50140bb085be9bd324ea15600644338f524224a4323957158da54342ceb2de920d30e63c9244e8fd3d88180527f165671a1220bf921d760d6a5c451aa096dc0",
          "sha256": "42904cf7fd2dcbb88844587319927913e007ed489b2b66e3c89f0a390f241803",
          "sha1": "35823e2018c93ddd2d677b5a864f78519c158c68",
          "md5": "0d51b84002daf80415f4e7b2f977aebe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-intent-launcher-10.2.0.aar",
          "url": "expo-intent-launcher-10.2.0.aar",
          "size": 23762,
          "sha512": "f50140bb085be9bd324ea15600644338f524224a4323957158da54342ceb2de920d30e63c9244e8fd3d88180527f165671a1220bf921d760d6a5c451aa096dc0",
          "sha256": "42904cf7fd2dcbb88844587319927913e007ed489b2b66e3c89f0a390f241803",
          "sha1": "35823e2018c93ddd2d677b5a864f78519c158c68",
          "md5": "0d51b84002daf80415f4e7b2f977aebe"
        }
      ]
    }
  ]
}
