{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-store-review",
    "version": "5.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-store-review-5.2.0.aar",
          "url": "expo-store-review-5.2.0.aar",
          "size": 19041,
          "sha512": "830901cd6783653202b5fbd62776554b960c2d426b14a716c4399fc3366dcc4afc613340b00aa2d1eaf6310778c94ef793f926d4f35d7b4da1ef4d94b2ac16d1",
          "sha256": "f02f6afdad2eb6007cea87fb600580d5d5545b43214326f7ed43992c6a17a959",
          "sha1": "46ba5c6e4ed474f008048c5f28e5fe2f45ba6924",
          "md5": "85304ef111e79be07f33956064d0efd3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-store-review-5.2.0.aar",
          "url": "expo-store-review-5.2.0.aar",
          "size": 19041,
          "sha512": "830901cd6783653202b5fbd62776554b960c2d426b14a716c4399fc3366dcc4afc613340b00aa2d1eaf6310778c94ef793f926d4f35d7b4da1ef4d94b2ac16d1",
          "sha256": "f02f6afdad2eb6007cea87fb600580d5d5545b43214326f7ed43992c6a17a959",
          "sha1": "46ba5c6e4ed474f008048c5f28e5fe2f45ba6924",
          "md5": "85304ef111e79be07f33956064d0efd3"
        }
      ]
    }
  ]
}
