/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package abi47_0_0.host.exp.exponent.modules.api.safeareacontext;

import android.view.View;

public interface RNCSafeAreaProviderManagerInterface<T extends View> {
  // No props
}
