import ExpoBluetooth from './ExpoBluetooth';

export const {
  BLUETOOTH_EVENT,
  UUID,
  TYPES,
  /* iOS */
  CONNECT_PERIPHERAL_OPTIONS,
  /* Android */
  PRIORITY,
} = ExpoBluetooth;

export const DELIMINATOR = '|';

export const SCAN_OPTIONS: {
  /** CBCentralManagerScanOptionAllowDuplicatesKey */
  ALLOW_DUPLICATES: string;
  /** CBCentralManagerScanOptionSolicitedServiceUUIDsKey */
  SOLICITED_SERVICE_UUIDS: string;
} = ExpoBluetooth.SCAN_OPTIONS;

/** iOS only */
export const CENTRAL_OPTIONS: {
  /** CBCentralManagerOptionShowPowerAlertKey  */
  SHOW_POWER_ALERT: string;
  /** CBCentralManagerOptionRestoreIdentifierKey */
  RESTORE_IDENTIFIER: string;
} = ExpoBluetooth.CENTRAL_OPTIONS;

export const EVENTS: {
  UPDATE_STATE: 'UPDATE_STATE';
  SYSTEM_ENABLED_STATE_CHANGED?: 'SYSTEM_ENABLED_STATE_CHANGED';
  CENTRAL_DISCOVERED_PERIPHERAL: 'CENTRAL_DISCOVERED_PERIPHERAL';
  CENTRAL_STATE_CHANGED: 'CENTRAL_STATE_CHANGED';
  PERIPHERAL_CONNECTED: 'PERIPHERAL_CONNECTED';
  PERIPHERAL_DISCONNECTED: 'PERIPHERAL_DISCONNECTED';
  PERIPHERAL_DISCOVERED_SERVICES: 'PERIPHERAL_DISCOVERED_SERVICES';
  PERIPHERAL_BONDED?: 'PERIPHERAL_BONDED';
  PERIPHERAL_UNBONDED?: 'PERIPHERAL_UNBONDED';
  SERVICE_DISCOVERED_CHARACTERISTICS: 'SERVICE_DISCOVERED_CHARACTERISTICS';
  SERVICE_DISCOVERED_INCLUDED_SERVICES: 'SERVICE_DISCOVERED_INCLUDED_SERVICES';
  CHARACTERISTIC_DID_NOTIFY: 'CHARACTERISTIC_DID_NOTIFY';
  CHARACTERISTIC_DID_READ: 'CHARACTERISTIC_DID_READ';
  CHARACTERISTIC_DID_WRITE: 'CHARACTERISTIC_DID_WRITE';
  CHARACTERISTIC_DISCOVERED_DESCRIPTORS: 'CHARACTERISTIC_DISCOVERED_DESCRIPTORS';
  DESCRIPTOR_DID_READ: 'DESCRIPTOR_DID_READ';
  DESCRIPTOR_DID_WRITE: 'DESCRIPTOR_DID_WRITE';
} = ExpoBluetooth.EVENTS;
