{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-eas-client",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-eas-client-0.2.1.aar",
          "url": "expo-eas-client-0.2.1.aar",
          "size": 19420,
          "sha512": "09d4fd595cdf46cd534bf650a0bfb334737d30ad5414a09781f5a31320312deb10ffa03f5e5c6d88613d7168d54bcb017e3581ca78a638505aea0711eecefcc4",
          "sha256": "2690c44d110fee66e48b114697c675dc74ebc121098f3a01b3a9d7d47b3a2dc4",
          "sha1": "b1e37509493f28e97b93aa508f8e321083c9cc2d",
          "md5": "c0b4b96baffcdf9fd21c226caa5a1802"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-eas-client-0.2.1.aar",
          "url": "expo-eas-client-0.2.1.aar",
          "size": 19420,
          "sha512": "09d4fd595cdf46cd534bf650a0bfb334737d30ad5414a09781f5a31320312deb10ffa03f5e5c6d88613d7168d54bcb017e3581ca78a638505aea0711eecefcc4",
          "sha256": "2690c44d110fee66e48b114697c675dc74ebc121098f3a01b3a9d7d47b3a2dc4",
          "sha1": "b1e37509493f28e97b93aa508f8e321083c9cc2d",
          "md5": "c0b4b96baffcdf9fd21c226caa5a1802"
        }
      ]
    }
  ]
}
