{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-navigation-bar",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-navigation-bar-1.2.0.aar",
          "url": "expo-navigation-bar-1.2.0.aar",
          "size": 61521,
          "sha512": "70f7847c92c9b5d4abef3bcbef01fc8e51c9f2e690c455f394a8fda4d38ada62cc30bca49f64866fa042cf0fb63fa01494a2247871c8d64bf74f5c5897e17383",
          "sha256": "2c1ea09bea566cdf176a49c3352201bad85fd9419968da370c7bcf259de53a2e",
          "sha1": "76be4a708448ff0ff6dca50b9ff796c5a23c2548",
          "md5": "6012d9da81908c02617ffb612ecbd7ca"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-navigation-bar-1.2.0.aar",
          "url": "expo-navigation-bar-1.2.0.aar",
          "size": 61521,
          "sha512": "70f7847c92c9b5d4abef3bcbef01fc8e51c9f2e690c455f394a8fda4d38ada62cc30bca49f64866fa042cf0fb63fa01494a2247871c8d64bf74f5c5897e17383",
          "sha256": "2c1ea09bea566cdf176a49c3352201bad85fd9419968da370c7bcf259de53a2e",
          "sha1": "76be4a708448ff0ff6dca50b9ff796c5a23c2548",
          "md5": "6012d9da81908c02617ffb612ecbd7ca"
        }
      ]
    }
  ]
}
