type Compatibility = {
  native: boolean;
  web: boolean;
  notes?: string;
};

const webOnly: Compatibility = {
  native: false,
  web: true,
};

const rawData: Record<string, Record<string, Record<string, Compatibility | true>>> = {
  Layout: {
    'Aspect Ratio': {
      'aspect-auto': {
        native: true,
        web: true,
      },
      'aspect-video': true,
      'aspect-square': true,
    },
    Container: {
      container: true,
    },
    Columns: {
      'columns-{n}': webOnly,
      'columns-[n]': webOnly,
      'columns-auto': webOnly,
    },
    'Break After': {
      'break-after-auto': webOnly,
      'break-after-avoid': webOnly,
      'break-after-all': webOnly,
      'break-after-avoid-page': webOnly,
      'break-after-page': webOnly,
      'break-after-left': webOnly,
      'break-after-right': webOnly,
      'break-after-column': webOnly,
    },
    'Break Before': {
      'break-before-auto': webOnly,
      'break-before-avoid': webOnly,
      'break-before-all': webOnly,
      'break-before-avoid-page': webOnly,
      'break-before-page': webOnly,
      'break-before-left': webOnly,
      'break-before-right': webOnly,
      'break-before-column': webOnly,
    },
    'Break Inside': {
      'break-inside-auto': webOnly,
      'break-inside-avoid': webOnly,
      'break-inside-avoid-page': webOnly,
      'break-inside-avoid-column': webOnly,
    },
    'Box Decoration Break': {
      'box-decoration-clone': webOnly,
      'box-decoration-slice': webOnly,
    },
    'Box Sizing': {
      'box-border': webOnly,
      'box-content': webOnly,
    },
    Display: {
      flex: true,
      hidden: true,
      block: webOnly,
      'inline-block': webOnly,
      inline: webOnly,
      'inline-flex': webOnly,
      table: webOnly,
      'inline-table': webOnly,
      'table-caption': webOnly,
      'table-column': webOnly,
      'table-column-group': webOnly,
      'table-footer-group': webOnly,
      'table-header-group': webOnly,
      'table-row-group': webOnly,
      'table-row': webOnly,
      'table-root': webOnly,
      grid: webOnly,
      'inline-grid': webOnly,
      contents: webOnly,
      'list-item': webOnly,
    },
    Floats: {
      'float-right': webOnly,
      'float-left': webOnly,
      'float-none': webOnly,
    },
    Clear: {
      'clear-right': webOnly,
      'clear-left': webOnly,
      'clear-both': webOnly,
      'clear-none': webOnly,
    },
    Isolation: {
      isolate: webOnly,
      'isolate-auto': webOnly,
    },
    'Object Fit': {
      'object-contain': webOnly,
      'object-cover': webOnly,
      'object-fill': webOnly,
      'object-none': webOnly,
      'object-scale-down': webOnly,
    },
    'Object Position': {
      'object-bottom': webOnly,
      'object-center': webOnly,
      'object-left': webOnly,
      'object-left-bottom': webOnly,
      'object-left-top': webOnly,
      'object-right': webOnly,
      'object-right-bottom': webOnly,
      'object-right-top': webOnly,
      'object-top': webOnly,
    },
    Overflow: {
      visible: true,
      hidden: true,
      scroll: true,
      'overflow-auto': webOnly,
      'overflow-clip': webOnly,
      'overflow-x-auto': webOnly,
      'overflow-y-auto': webOnly,
      'overflow-x-hidden': webOnly,
      'overflow-y-hidden': webOnly,
      'overflow-x-clip': webOnly,
      'overflow-y-clip': webOnly,
      'overflow-x-visible': webOnly,
      'overflow-y-visible': webOnly,
      'overflow-x-scroll ': webOnly,
      'overflow-y-scroll ': webOnly,
    },
    'Overscroll Behavior': {
      'overscroll-auto': webOnly,
      'overscroll-contain': webOnly,
      'overscroll-none': webOnly,
      'overscroll-y-auto': webOnly,
      'overscroll-y-contain': webOnly,
      'overscroll-y-none': webOnly,
      'overscroll-x-auto': webOnly,
      'overscroll-x-contain': webOnly,
      'overscroll-x-none': webOnly,
    },
    Position: {
      absolute: true,
      relative: true,
      fixed: webOnly,
      sticky: webOnly,
    },
    'Top/Right/Bottom/Left': {
      'inset-{n}': true,
      'inset-[n]': true,
      'inset-x-{n}': true,
      'inset-y-[n]': true,
      'top-{n}': true,
      'top-[n]': true,
      'bottom-{n}': true,
      'bottom-[n]': true,
      'left-{n}': true,
      'left-[n]': true,
      'right-{n}': true,
      'right-[n]': true,
      'inset-auto': webOnly,
      'inset-x-auto': webOnly,
      'inset-y-auto': webOnly,
      'top-auto': webOnly,
      'bottom-auto': webOnly,
      'left-auto': webOnly,
      'right-auto': webOnly,
    },
    'Z-Index': {
      'z-{n}': true,
      'z-[n]': true,
      'z-auto': webOnly,
    },
  },
  Flexbox: {
    Flex: {
      'flex-1': {
        native: true,
        web: true,
        notes:
          'Flexbox behaves differently between Native and Web. You can normalise this behaviour by setting flex-1',
      },
      'flex-auto': true,
      'flex-initial': true,
      'flex-none': webOnly,
    },
    'Flex Basis': {
      'basis-{n}': true,
      'basis-[n]': true,
      'basis-auto': webOnly,
    },
    'Flex Direction': {
      'flex-row': true,
      'flex-row-reverse': true,
      'flex-col': true,
      'flex-col-reverse': true,
    },
    'Flex Wrap': {
      'flex-wrap': true,
      'flex-wrap-reverse': true,
      'flex-nowrap': true,
    },
    'Flex Grow': {
      grow: true,
      'grow-0': true,
    },
    'Flex Shrink': {
      shrink: true,
      'shrink-0': true,
    },
    Order: {
      'order-{n}': webOnly,
      'order-[n]': webOnly,
      'order-first': webOnly,
      'order-last': webOnly,
      'order-none': webOnly,
    },
    'Grid Template Columns': {
      'grid-cols-{n}': webOnly,
      'grid-cols-[n]': webOnly,
      'grid-cols-none': webOnly,
    },
    'Grid Column Start / End': {
      'col-span-{n}': webOnly,
      'col-span-[n]': webOnly,
      'col-span-auto': webOnly,
    },
    'Grid Template Rows': {
      'grid-rows-{n}': webOnly,
      'grid-rows-[n]': webOnly,
      'grid-rows-none': webOnly,
    },
    'Grid Row Start / End': {
      'row-span-{n}': webOnly,
      'row-span-[n]': webOnly,
      'row-span-auto': webOnly,
    },
    'Grid Auto Flow': {
      'grid-flow-row': webOnly,
      'grid-flow-col': webOnly,
      'grid-flow-dense': webOnly,
      'grid-flow-row-dense': webOnly,
      'grid-flow-col-dense': webOnly,
    },
    'Grid Auto Columns': {
      'auto-cols-auto': webOnly,
      'auto-cols-min': webOnly,
      'auto-cols-max': webOnly,
      'auto-cols-fr': webOnly,
    },
    'Grid Auto Rows': {
      'auto-rows-auto': webOnly,
      'auto-rows-min': webOnly,
      'auto-rows-max': webOnly,
      'auto-rows-fr': webOnly,
    },
    Gap: {
      'gap-{n}': true,
      'gap-[n]': true,
      'gap-x-{n}': true,
      'gap-x-[n]': true,
      'gap-y-{n}': true,
      'gap-y-[n]': true,
    },
    'Justify Content': {
      'justify-start': true,
      'justify-end': true,
      'justify-center': true,
      'justify-between': true,
      'justify-around': true,
      'justify-evenly': true,
    },
    'Justify Items': {
      'justify-items-start': webOnly,
      'justify-items-end': webOnly,
      'justify-items-center': webOnly,
      'justify-items-stretch': webOnly,
    },
    'Justify Self': {
      'justify-self-auto': webOnly,
      'justify-self-start': webOnly,
      'justify-self-end': webOnly,
      'justify-self-center': webOnly,
      'justify-self-stretch': webOnly,
    },
    'Align Content': {
      'content-center': true,
      'content-start': true,
      'content-end': true,
      'content-between': true,
      'content-around': true,
      'content-evenly': true,
    },
    'Align Items': {
      'items-start': true,
      'items-end': true,
      'items-center': true,
      'items-baseline': true,
      'items-stretch': true,
    },
    'Align Self': {
      'self-auto': true,
      'self-start': true,
      'self-end': true,
      'self-center': true,
      'self-stretch': true,
      'self-baseline': true,
    },
    'Place Content': {
      'place-content-center': webOnly,
      'place-content-start': webOnly,
      'place-content-end': webOnly,
      'place-content-between': webOnly,
      'place-content-around': webOnly,
      'place-content-evenly': webOnly,
      'place-content-baseline': webOnly,
      'place-content-stretch': webOnly,
    },
    'Place Items': {
      'place-items-start': webOnly,
      'place-items-end': webOnly,
      'place-items-center': webOnly,
      'place-items-baseline': webOnly,
      'place-items-stretch': webOnly,
    },
    'Place Self': {
      'place-self-start': webOnly,
      'place-self-end': webOnly,
      'place-self-center': webOnly,
      'place-self-baseline': webOnly,
      'place-self-stretch': webOnly,
    },
  },
  Spacing: {
    Padding: {
      'p-{n}	': true,
      'p-[n]	': true,
      'px-{n}	': true,
      'px-[n]	': true,
      'py-{n}	': true,
      'py-[n]	': true,
      'pt-{n}	': true,
      'pt-[n]	': true,
      'pr-{n}	': true,
      'pr-[n]	': true,
      'pb-{n}	': true,
      'pb-[n]	': true,
      'pl-{n}	': true,
      'pl-[n]	': true,
      'p-auto': webOnly,
      'px-auto': webOnly,
      'py-auto': webOnly,
      'pt-auto': webOnly,
      'pr-auto': webOnly,
      'pb-auto': webOnly,
      'pl-auto': webOnly,
    },
    Margin: {
      'm-{n}	': true,
      'm-[n]	': true,
      'mx-{n}	': true,
      'mx-[n]	': true,
      'my-{n}	': true,
      'my-[n]	': true,
      'mt-{n}	': true,
      'mt-[n]	': true,
      'mr-{n}	': true,
      'mr-[n]	': true,
      'mb-{n}	': true,
      'mb-[n]	': true,
      'ml-{n}	': true,
      'ml-[n]	': true,
      'm-auto	': true,
      'mx-auto	': true,
      'my-auto	': true,
      'mt-auto	': true,
      'mr-auto	': true,
      'mb-auto	': true,
      'ml-auto	': true,
    },
    'Space Between': {
      'space-{n}	': webOnly,
      'space-[n]	': webOnly,
      'space-x-{n}	': webOnly,
      'space-x-[n]	': webOnly,
      'space-y-{n}	': webOnly,
      'space-y-[n]	': webOnly,
      'space-x-reverse': webOnly,
      'space-y-reverse': webOnly,
    },
  },
  Sizing: {
    Width: {
      'w-{n}	': true,
      'w-[n]	': true,
      'w-full	': true,
      'w-screen	': true,
      'w-auto': webOnly,
      'w-min': webOnly,
      'w-max': webOnly,
      'w-fit': webOnly,
    },
    'Min-Width': {
      'min-w-0	': true,
      'min-w-[n]	': true,
      'min-w-full	': true,
      'min-w-min': webOnly,
      'min-w-max': webOnly,
      'min-w-fit': webOnly,
    },
    'Max-Width': {
      'max-w-0	': true,
      'max-w-[n]	': true,
      'max-w-{n}	': true,
      'max-w-full	': true,
      'max-w-screen-sm	': true,
      'max-w-screen-md	': true,
      'max-w-screen-lg	': true,
      'max-w-screen-xl	': true,
      'max-w-screen-2xl	': true,
      'max-w-min': webOnly,
      'max-w-max': webOnly,
      'max-w-fit': webOnly,
      'max-w-prose': webOnly,
    },
    Height: {
      'h-{n}	': true,
      'h-[n]	': true,
      'h-full	': true,
      'h-screen	': true,
      'h-auto': webOnly,
      'h-min': webOnly,
      'h-max': webOnly,
      'h-fit': webOnly,
    },
    'Min-Height': {
      'min-h-0	': true,
      'min-h-[n]	': true,
      'min-h-full	': true,
      'min-h-min': webOnly,
      'min-h-max': webOnly,
      'min-h-fit': webOnly,
    },
    'Max-Height': {
      'max-h-0	': true,
      'max-h-[n]	': true,
      'max-h-{n}	': true,
      'max-h-full	': true,
      'max-h-screen	': true,
      'max-h-min': webOnly,
      'max-h-max': webOnly,
      'max-h-fit': webOnly,
    },
  },
  Typography: {
    'Font Family': {
      'font-[n]	': true,
      'font-{n}	': true,
      'font-sans': webOnly,
      'font-serif': webOnly,
      'font-mono': webOnly,
    },
    'Font Size': {
      'text-{n}	': true,
      'text-[n]	': true,
      'text-base	': true,
    },
    'Font Smoothing': {
      antialiased: webOnly,
      'subpixel-antialiased': webOnly,
    },
    'Font Style': {
      'italic	': true,
      'not-italic	': true,
    },
    'Font Weight': {
      'font-thin	': true,
      'font-extralight	': true,
      'font-light	': true,
      'font-normal	': true,
      'font-medium	': true,
      'font-semibold	': true,
      'font-bold	': true,
      'font-extrabold	': true,
      'font-black	': true,
    },
    'Font Variant Numeric': {
      'normal-nums': webOnly,
      ordinal: webOnly,
      'slashed-zero': webOnly,
      'lining-nums': webOnly,
      'oldstyle-nums': webOnly,
      'proportional-nums': webOnly,
      'tabular-nums': webOnly,
      'diagonal-fractions': webOnly,
      'stacked-fractions': webOnly,
    },
    'Letter Spacing': {
      'tracking-tighter	': true,
      'tracking-tight	': true,
      'tracking-normal	': true,
      'tracking-wide	': true,
      'tracking-wider	': true,
      'tracking-widest	': true,
    },
    'Line Clamp': {
      'line-clamp-[n]': webOnly,
      'line-clamp-{n}': webOnly,
      'line-clamp-none': webOnly,
    },
    'Line Height': {
      'leading-{n}	': true,
      'leading-[n]	': true,
      'leading-none': webOnly,
      'leading-tight': webOnly,
      'leading-snug': webOnly,
      'leading-normal': webOnly,
      'leading-relaxed': webOnly,
      'leading-loose': webOnly,
    },
    'List Style Image': {
      'list-image-none': webOnly,
    },
    'List Style Position': {
      'list-inside': webOnly,
      'list-outside': webOnly,
    },
    'List Style Type': {
      'list-none': webOnly,
      'list-disc': webOnly,
      'list-decimal': webOnly,
    },
    'Text Align': {
      'text-left': true,
      'text-center': true,
      'text-right': true,
      'text-justify': true,
      'text-start': webOnly,
      'text-end': webOnly,
    },
    'Text Color': {
      'text-{n}	': true,
      'text-[n]	': true,
      'text-inherit': webOnly,
      'text-current': webOnly,
    },
    'Text Decoration': {
      'underline	': true,
      'line-through	': true,
      'no-underline	': true,
      overline: webOnly,
    },
    'Text Decoration Color': {
      'decoration-{n}	': true,
      'decoration-[n]	': true,
      'decoration-inherit': webOnly,
      'decoration-current': webOnly,
    },
    'Text Decoration Style': {
      'decoration-solid	': true,
      'decoration-double	': true,
      'decoration-dotted	': true,
      'decoration-dashed	': true,
      'decoration-wavy': webOnly,
    },
    'Text Decoration Thickness': {
      'decoration-auto': webOnly,
      'decoration-from-font': webOnly,
      'decoration-0': webOnly,
      'decoration-1': webOnly,
      'decoration-2': webOnly,
      'decoration-4': webOnly,
      'decoration-8': webOnly,
    },
    'Text Underline Offset': {
      'underline-offset-auto': webOnly,
      'underline-offset-0': webOnly,
      'underline-offset-1': webOnly,
      'underline-offset-2': webOnly,
      'underline-offset-4': webOnly,
      'underline-offset-8': webOnly,
    },
    'Text Transform': {
      uppercase: true,
      lowercase: true,
      capitalize: true,
      'normal-case': true,
    },
    'Text Overflow': {
      truncate: webOnly,
      'text-ellipsis': webOnly,
      'text-clip': webOnly,
    },
    'Text Indent': {
      'indent-{n}	': true,
      'indent-[n]	': true,
    },
    'Vertical Align': {
      'align-baseline': webOnly,
      'align-top': true,
      'align-middle': true,
      'align-bottom': true,
      'align-text-top': webOnly,
      'align-text-bottom': webOnly,
      'align-sub': webOnly,
      'align-super': webOnly,
    },
    Whitespace: {
      'whitespace-normal': webOnly,
      'whitespace-nowrap': webOnly,
      'whitespace-pre': webOnly,
      'whitespace-pre-line': webOnly,
      'whitespace-pre-wrap': webOnly,
      'whitespace-break-spaces': webOnly,
    },
    'Word Break': {
      'break-normal': webOnly,
      'break-words': webOnly,
      'break-all': webOnly,
      'break-keep': webOnly,
    },
    Hyphens: {
      'hyphens-none': webOnly,
      'hyphens-manual': webOnly,
      'hyphens-auto': webOnly,
    },
    Content: {
      'content-none': webOnly,
    },
  },
  Backgrounds: {
    'Background Attachment': {
      'bg-fixed': webOnly,
      'bg-local': webOnly,
      'bg-scroll': webOnly,
    },
    'Background Clip': {
      'bg-clip-border': webOnly,
      'bg-clip-padding': webOnly,
      'bg-clip-content': webOnly,
      'bg-clip-text': webOnly,
    },
    'Background Color': {
      'bg-{n}	': true,
      'bg-[n]	': true,
      'bg-inherit': webOnly,
      'bg-current': webOnly,
    },
    'Background Origin': {
      'bg-origin-border': webOnly,
      'bg-origin-padding': webOnly,
      'bg-origin-content': webOnly,
    },
    'Background Position': {
      'bg-bottom': webOnly,
      'bg-center': webOnly,
      'bg-left': webOnly,
      'bg-left-bottom': webOnly,
      'bg-left-top': webOnly,
      'bg-right': webOnly,
      'bg-right-bottom': webOnly,
      'bg-right-top': webOnly,
      'bg-top': webOnly,
    },
    'Background Repeat': {
      'bg-repeat': webOnly,
      'bg-no-repeat': webOnly,
      'bg-repeat-x': webOnly,
      'bg-repeat-y': webOnly,
      'bg-repeat-round': webOnly,
      'bg-repeat-space': webOnly,
    },
    'Background Size': {
      'bg-auto': webOnly,
      'bg-cover': webOnly,
      'bg-contain': webOnly,
    },
    'Background Image': {
      'bg-none': webOnly,
      'bg-gradient-to-t': webOnly,
      'bg-gradient-to-tr': webOnly,
      'bg-gradient-to-r': webOnly,
      'bg-gradient-to-br': webOnly,
      'bg-gradient-to-b': webOnly,
      'bg-gradient-to-bl': webOnly,
      'bg-gradient-to-l': webOnly,
      'bg-gradient-to-tl': webOnly,
    },
    'Gradient Color Stops': {
      'from-[n]': webOnly,
      'from-{n}': webOnly,
      'from-[n]%': webOnly,
      'from-{n}%': webOnly,
      'to-[n]': webOnly,
      'to-{n}': webOnly,
      'to-[n]%': webOnly,
      'to-{n}%': webOnly,
    },
  },
  Borders: {
    'Border Radius': {
      'rounded-none	': true,
      'rounded	': true,
      'rounded-{n}	': true,
      'rounded-[n]	': true,
      'rounded-full	': true,
      'rounded-t-none	': true,
      'rounded-t-{n}	': true,
      'rounded-t-[n]	': true,
      'rounded-t-full	': true,
      'rounded-r-none	': true,
      'rounded-r-{n}	': true,
      'rounded-r-[n]	': true,
      'rounded-r-full	': true,
      'rounded-b-none	': true,
      'rounded-b-{n}	': true,
      'rounded-b-[n]	': true,
      'rounded-b-full	': true,
      'rounded-l-none	': true,
      'rounded-l-{n}	': true,
      'rounded-l-[n]	': true,
      'rounded-l-full	': true,
      'rounded-tl-none	': true,
      'rounded-tl-{n}	': true,
      'rounded-tl-[n]	': true,
      'rounded-tl-full	': true,
      'rounded-tr-none	': true,
      'rounded-tr-{n}	': true,
      'rounded-tr-[n]	': true,
      'rounded-tr-full	': true,
      'rounded-br-none	': true,
      'rounded-br-{n}	': true,
      'rounded-br-[n]	': true,
      'rounded-br-full	': true,
      'rounded-bl-none	': true,
      'rounded-bl-{n}	': true,
      'rounded-bl-[n]	': true,
      'rounded-bl-full	': true,
      'border-inherit': webOnly,
      'border-current': webOnly,
    },
    'Border Width': {
      'border	': true,
      'border-{n}	': true,
      'border-[n]	': true,
      'border-x	': true,
      'border-x-{n}	': true,
      'border-x-[n]	': true,
      'border-y	': true,
      'border-y-{n}	': true,
      'border-y-[n]	': true,
      'border-t	': true,
      'border-t-{n}	': true,
      'border-t-[n]	': true,
      'border-r	': true,
      'border-r-{n}	': true,
      'border-r-[n]	': true,
      'border-b	': true,
      'border-b-{n}	': true,
      'border-b-[n]	': true,
      'border-l	': true,
      'border-l-{n}	': true,
      'border-l-[n]	': true,
    },
    'Border Color': {
      'border-{n}	': true,
      'border-[n]	': true,
      'border-inherit': webOnly,
      'border-current': webOnly,
    },
    'Border Style': {
      'border-solid	': true,
      'border-dashed	': true,
      'border-dotted	': true,
      'border-none': webOnly,
      'border-double': webOnly,
      'border-hidden': webOnly,
    },
    'Divide Width': {
      'divide-x-{n}	': webOnly,
      'divide-x-[n]	': webOnly,
      'divide-y-{n}	': webOnly,
      'divide-y-[n]	': webOnly,
    },
    'Divide Color': {
      'divide-{n}	': webOnly,
      'divide-[n]	': webOnly,
      'divide-inherit': webOnly,
      'divide-current': webOnly,
    },
    'Divide Style': {
      'divide-solid': webOnly,
      'divide-dashed': webOnly,
      'divide-dotted': webOnly,
      'divide-double': webOnly,
      'divide-none': webOnly,
    },
    'Outline Width': {
      'outline-0': webOnly,
      'outline-1': webOnly,
      'outline-2': webOnly,
      'outline-4': webOnly,
      'outline-8': webOnly,
    },
    'Outline Color': {
      'outline-[n]': webOnly,
      'outline-{n}': webOnly,
      'outline-inherit': webOnly,
      'outline-current': webOnly,
      'outline-transparent': webOnly,
    },
    'Outline Style': {
      'outline-none': webOnly,
      outline: webOnly,
      'outline-dashed': webOnly,
      'outline-dotted': webOnly,
      'outline-double': webOnly,
    },
    'Outline Offset': {
      'outline-offset-0': webOnly,
      'outline-offset-1': webOnly,
      'outline-offset-2': webOnly,
      'outline-offset-4': webOnly,
      'outline-offset-8': webOnly,
    },
    'Ring Width': {
      'ring-0': webOnly,
      'ring-1': webOnly,
      'ring-2': webOnly,
      ring: webOnly,
      'ring-4': webOnly,
      'ring-8': webOnly,
      'ring-inset': webOnly,
    },
    'Ring Color': {
      'ring-[n]': webOnly,
      'ring-{n}': webOnly,
      'ring-inherit': webOnly,
      'ring-current': webOnly,
      'ring-transparent': webOnly,
    },
    'Ring Offset Width': {
      'ring-offset-0': webOnly,
      'ring-offset-2': webOnly,
      'ring-offset-4': webOnly,
      'ring-offset-8': webOnly,
    },
    'Ring Offset Color': {
      'ring-offset-[n]': webOnly,
      'ring-offset-{n}': webOnly,
      'ring-offset-inherit': webOnly,
      'ring-offset-current': webOnly,
      'ring-offset-transparent': webOnly,
    },
  },
  Effects: {
    'Box Shadow': {
      'shadow-sm': webOnly,
      shadow: webOnly,
      'shadow-md': webOnly,
      'shadow-lg': webOnly,
      'shadow-xl': webOnly,
      'shadow-2xl': webOnly,
      'shadow-inner': webOnly,
      'shadow-none': webOnly,
    },
    'Box Shadow Color': {
      'shadow-[n]': webOnly,
      'shadow-{n}': webOnly,
      'shadow-inherit': webOnly,
      'shadow-current': webOnly,
      'shadow-transparent': webOnly,
    },
    Opacity: {
      'opacity-{n}	': true,
      'opacity-[n]	': true,
    },
    'Mix Blend Mode': {
      'mix-blend-normal': webOnly,
      'mix-blend-multiply': webOnly,
      'mix-blend-screen': webOnly,
      'mix-blend-overlay': webOnly,
      'mix-blend-darken': webOnly,
      'mix-blend-lighten': webOnly,
      'mix-blend-color-dodge': webOnly,
      'mix-blend-color-burn': webOnly,
      'mix-blend-hard-light': webOnly,
      'mix-blend-soft-light': webOnly,
      'mix-blend-difference': webOnly,
      'mix-blend-exclusion': webOnly,
      'mix-blend-hue': webOnly,
      'mix-blend-saturation': webOnly,
      'mix-blend-color': webOnly,
      'mix-blend-luminosity': webOnly,
      'mix-blend-plus-lighter': webOnly,
    },
    'Background Blend Mode': {
      'bg-blend-normal': webOnly,
      'bg-blend-multiply': webOnly,
      'bg-blend-screen': webOnly,
      'bg-blend-overlay': webOnly,
      'bg-blend-darken': webOnly,
      'bg-blend-lighten': webOnly,
      'bg-blend-color-dodge': webOnly,
      'bg-blend-color-burn': webOnly,
      'bg-blend-hard-light': webOnly,
      'bg-blend-soft-light': webOnly,
      'bg-blend-difference': webOnly,
      'bg-blend-exclusion': webOnly,
      'bg-blend-hue': webOnly,
      'bg-blend-saturation': webOnly,
      'bg-blend-color': webOnly,
      'bg-blend-luminosity': webOnly,
    },
  },
  Filters: {
    Blur: {
      'blur-none': webOnly,
      'blur-sm': webOnly,
      blur: webOnly,
      'blur-md': webOnly,
      'blur-lg': webOnly,
      'blur-xl': webOnly,
      'blur-2xl': webOnly,
      'blur-3xl': webOnly,
    },
    Brightness: {
      'brightness-0': webOnly,
      'brightness-50': webOnly,
      'brightness-75': webOnly,
      'brightness-90': webOnly,
      'brightness-95': webOnly,
      'brightness-100': webOnly,
      'brightness-105': webOnly,
      'brightness-110': webOnly,
      'brightness-125': webOnly,
      'brightness-150': webOnly,
      'brightness-200': webOnly,
    },
    Contrast: {
      'contrast-0': webOnly,
      'contrast-50': webOnly,
      'contrast-75': webOnly,
      'contrast-100': webOnly,
      'contrast-125': webOnly,
      'contrast-150': webOnly,
      'contrast-200': webOnly,
    },
    'Drop Shadow': {
      'drop-shadow-sm': webOnly,
      'drop-shadow': webOnly,
      'drop-shadow-md': webOnly,
      'drop-shadow-lg': webOnly,
      'drop-shadow-xl': webOnly,
      'drop-shadow-2xl': webOnly,
      'drop-shadow-none': webOnly,
    },
    Grayscale: {
      'grayscale-0': webOnly,
      grayscale: webOnly,
    },
    'Hue Rotate': {
      'hue-rotate-0': webOnly,
      'hue-rotate-15': webOnly,
      'hue-rotate-30': webOnly,
      'hue-rotate-60': webOnly,
      'hue-rotate-90': webOnly,
      'hue-rotate-180': webOnly,
    },
    Invert: {
      'invert-0': webOnly,
      invert: webOnly,
    },
    Saturate: {
      'saturate-0': webOnly,
      'saturate-50': webOnly,
      'saturate-100': webOnly,
      'saturate-150': webOnly,
      'saturate-200': webOnly,
    },
    Sepia: {
      'sepia-0': webOnly,
      sepia: webOnly,
    },
    'Backdrop Blur': {
      'backdrop-blur-none': webOnly,
      'backdrop-blur-sm': webOnly,
      'backdrop-blur': webOnly,
      'backdrop-blur-md': webOnly,
      'backdrop-blur-lg': webOnly,
      'backdrop-blur-xl': webOnly,
      'backdrop-blur-2xl': webOnly,
      'backdrop-blur-3xl': webOnly,
    },
    'Backdrop Brightness': {
      'backdrop-brightness-0': webOnly,
      'backdrop-brightness-50': webOnly,
      'backdrop-brightness-75': webOnly,
      'backdrop-brightness-90': webOnly,
      'backdrop-brightness-95': webOnly,
      'backdrop-brightness-100': webOnly,
      'backdrop-brightness-105': webOnly,
      'backdrop-brightness-110': webOnly,
      'backdrop-brightness-125': webOnly,
      'backdrop-brightness-150': webOnly,
      'backdrop-brightness-200': webOnly,
    },
    'Backdrop Contrast': {
      'backdrop-contrast-0': webOnly,
      'backdrop-contrast-50': webOnly,
      'backdrop-contrast-75': webOnly,
      'backdrop-contrast-100': webOnly,
      'backdrop-contrast-125': webOnly,
      'backdrop-contrast-150': webOnly,
      'backdrop-contrast-200': webOnly,
    },
    'Backdrop Grayscale': {
      'backdrop-grayscale-0': webOnly,
      'backdrop-grayscale': webOnly,
    },
    'Backdrop Hue Rotate': {
      'backdrop-hue-rotate-0': webOnly,
      'backdrop-hue-rotate-15': webOnly,
      'backdrop-hue-rotate-30': webOnly,
      'backdrop-hue-rotate-60': webOnly,
      'backdrop-hue-rotate-90': webOnly,
      'backdrop-hue-rotate-180': webOnly,
    },
    'Backdrop Invert': {
      'backdrop-invert-0': webOnly,
      'backdrop-invert': webOnly,
    },
    'Backdrop Opacity': {
      'backdrop-opacity-0': webOnly,
      'backdrop-opacity-5': webOnly,
      'backdrop-opacity-10': webOnly,
      'backdrop-opacity-20': webOnly,
      'backdrop-opacity-25': webOnly,
      'backdrop-opacity-30': webOnly,
      'backdrop-opacity-40': webOnly,
      'backdrop-opacity-50': webOnly,
      'backdrop-opacity-60': webOnly,
      'backdrop-opacity-70': webOnly,
      'backdrop-opacity-75': webOnly,
      'backdrop-opacity-80': webOnly,
      'backdrop-opacity-90': webOnly,
      'backdrop-opacity-95': webOnly,
      'backdrop-opacity-100': webOnly,
    },
    'Backdrop Saturate': {
      'backdrop-saturate-0': webOnly,
      'backdrop-saturate-50': webOnly,
      'backdrop-saturate-100': webOnly,
      'backdrop-saturate-150': webOnly,
      'backdrop-saturate-200': webOnly,
    },
    'Backdrop Sepia': {
      'backdrop-sepia-0': webOnly,
      'backdrop-sepia': webOnly,
    },
  },
  Tables: {
    'Border Collapse': {
      'border-collapse': webOnly,
      'border-separate': webOnly,
    },
    'Border Spacing': {
      'border-spacing-[n]': webOnly,
      'border-spacing-{n}': webOnly,
      'border-spacing-x-[n]': webOnly,
      'border-spacing-x-{n}': webOnly,
      'border-spacing-y-[n]': webOnly,
      'border-spacing-y-{n}': webOnly,
    },
    'Table Layout': {
      'table-auto': webOnly,
      'table-fixed': webOnly,
    },
    'Caption Side': {
      'caption-top': webOnly,
      'caption-bottom': webOnly,
    },
  },
  'Transitions & Animation': {
    'Transition Property': {
      'transition-none': true,
      'transition-[n]': true,
      'transition-{n}': true,
      'transition-all': webOnly,
      transition: true,
      'transition-colors': true,
      'transition-opacity': true,
      'transition-shadow': true,
      'transition-transform': true,
    },
    'Transition Duration': {
      'duration-0': true,
      'duration-75': true,
      'duration-100': true,
      'duration-150': true,
      'duration-200': true,
      'duration-300': true,
      'duration-500': true,
      'duration-700': true,
      'duration-1000': true,
    },
    'Transition Timing Function': {
      'ease-linear': true,
      'ease-in': true,
      'ease-out': true,
      'ease-in-out': true,
    },
    'Transition Delay': {
      'delay-0': true,
      'delay-75': true,
      'delay-100': true,
      'delay-150': true,
      'delay-200': true,
      'delay-300': true,
      'delay-500': true,
      'delay-700': true,
      'delay-1000': true,
    },
    Animation: {
      'animate-[n]': true,
      'animate-{n}': true,
      'animate-none': true,
      'animate-spin': true,
      'animate-ping': true,
      'animate-pulse': true,
      'animate-bounce': true,
    },
  },
  Transforms: {
    Scale: {
      'scale-{n}	': true,
      'scale-[n]	': true,
      'scale-x-{n}	': true,
      'scale-x-[n]	': true,
      'scale-y-{n}	': true,
      'scale-y-[n]	': true,
    },
    Rotate: {
      'rotate-{n}	': true,
      'rotate-[n]	': true,
    },
    Translate: {
      'translate-x-{n}	': true,
      'translate-x-[n]	': true,
      'translate-y-{n}	': true,
      'translate-y-[n]	': true,
    },
    Skew: {
      'skew-x-{n}	': true,
      'skew-x-[n]	': true,
      'skew-y-{n}	': true,
      'skew-y-[n]	': true,
    },
    'Transform Origin': {
      'origin-center': webOnly,
      'origin-top': webOnly,
      'origin-top-right': webOnly,
      'origin-right': webOnly,
      'origin-bottom-right': webOnly,
      'origin-bottom': webOnly,
      'origin-bottom-left': webOnly,
      'origin-left': webOnly,
      'origin-top-left': webOnly,
    },
  },
  Interactivity: {
    'Accent Color': {
      'accent-{n}	': true,
      'accent-[n]	': true,
      'accent-inherit': webOnly,
      'accent-current': webOnly,
    },
    Appearance: {
      'appearance-none': webOnly,
    },
    Cursor: {
      'cursor-auto': webOnly,
      'cursor-default': webOnly,
      'cursor-pointer': webOnly,
      'cursor-wait': webOnly,
      'cursor-text': webOnly,
      'cursor-move': webOnly,
      'cursor-help': webOnly,
      'cursor-not-allowed': webOnly,
      'cursor-progress': webOnly,
      'cursor-cell': webOnly,
      'cursor-crosshair': webOnly,
      'cursor-vertical-text': webOnly,
      'cursor-alias': webOnly,
      'cursor-copy': webOnly,
      'cursor-no-drop': webOnly,
      'cursor-grab': webOnly,
      'cursor-grabbing': webOnly,
      'cursor-all-scroll': webOnly,
      'cursor-col-resize': webOnly,
      'cursor-row-resize': webOnly,
      'cursor-n-resize': webOnly,
      'cursor-e-resize': webOnly,
      'cursor-s-resize': webOnly,
      'cursor-w-resize': webOnly,
      'cursor-ne-resize': webOnly,
      'cursor-nw-resize': webOnly,
      'cursor-se-resize': webOnly,
      'cursor-sw-resize': webOnly,
      'cursor-ew-resize': webOnly,
      'cursor-ns-resize': webOnly,
      'cursor-nesw-resize': webOnly,
      'cursor-nwse-resize': webOnly,
      'cursor-zoom-in': webOnly,
      'cursor-zoom-out': webOnly,
    },
    'Caret Color': {
      'caret-{n}	': webOnly,
      'caret-[n]	': webOnly,
      'caret-inherit': webOnly,
      'caret-current': webOnly,
    },
    'Pointer Events': {
      'pointer-events-none': webOnly,
      'pointer-events-auto': webOnly,
    },
    Resize: {
      'resize-none': webOnly,
      'resize-y': webOnly,
      'resize-x': webOnly,
      resize: webOnly,
    },
    'Scroll Behavior': {
      'scroll-auto': webOnly,
      'scroll-smooth': webOnly,
    },
    'Scroll Margin': {
      'scroll-m-{n}	': webOnly,
      'scroll-m-[n]	': webOnly,
      'scroll-mx-{n}	': webOnly,
      'scroll-mx-[n]	': webOnly,
      'scroll-my-{n}	': webOnly,
      'scroll-my-[n]	': webOnly,
      'scroll-ms-{n}	': webOnly,
      'scroll-ms-[n]	': webOnly,
      'scroll-me-{n}	': webOnly,
      'scroll-me-[n]	': webOnly,
      'scroll-mt-{n}	': webOnly,
      'scroll-mt-[n]	': webOnly,
      'scroll-mr-{n}	': webOnly,
      'scroll-mr-[n]	': webOnly,
      'scroll-ml-{n}	': webOnly,
      'scroll-ml-[n]	': webOnly,
    },
    'Scroll Padding': {
      'scroll-p-{n}	': webOnly,
      'scroll-p-[n]	': webOnly,
      'scroll-px-{n}	': webOnly,
      'scroll-px-[n]	': webOnly,
      'scroll-py-{n}	': webOnly,
      'scroll-py-[n]	': webOnly,
      'scroll-ps-{n}	': webOnly,
      'scroll-ps-[n]	': webOnly,
      'scroll-pe-{n}	': webOnly,
      'scroll-pe-[n]	': webOnly,
      'scroll-pt-{n}	': webOnly,
      'scroll-pt-[n]	': webOnly,
      'scroll-pr-{n}	': webOnly,
      'scroll-pr-[n]	': webOnly,
      'scroll-pl-{n}	': webOnly,
      'scroll-pl-[n]	': webOnly,
    },
    'Scroll Snap Align': {
      'snap-start': webOnly,
      'snap-end': webOnly,
      'snap-center': webOnly,
      'snap-align-none': webOnly,
    },
    'Scroll Snap Stop': {
      'snap-normal': webOnly,
      'snap-always': webOnly,
    },
    'Scroll Snap Type': {
      'snap-none': webOnly,
      'snap-x': webOnly,
      'snap-y': webOnly,
      'snap-both': webOnly,
      'snap-mandatory': webOnly,
      'snap-proximity': webOnly,
    },
    'Touch Action': {
      'touch-auto': webOnly,
      'touch-none': webOnly,
      'touch-pan-x': webOnly,
      'touch-pan-left': webOnly,
      'touch-pan-right': webOnly,
      'touch-pan-y': webOnly,
      'touch-pan-up': webOnly,
      'touch-pan-down': webOnly,
      'touch-pinch-zoom': webOnly,
      'touch-manipulation': webOnly,
    },
    'User Select': {
      'select-none': webOnly,
      'select-text': webOnly,
      'select-all': webOnly,
      'select-auto': webOnly,
    },
    'Will Change': {
      'will-change-auto': webOnly,
      'will-change-scroll': webOnly,
      'will-change-contents': webOnly,
      'will-change-transform': webOnly,
    },
  },
  SVG: {
    Fill: {
      'fill-{n}	': webOnly,
      'fill-[n]	': webOnly,
      'fill-inherit': webOnly,
      'fill-current': webOnly,
    },
    Stroke: {
      'stroke-{n}	': webOnly,
      'stroke-[n]	': webOnly,
      'stroke-inherit': webOnly,
      'stroke-current': webOnly,
    },
    'Stroke Width': {
      'stroke-0': webOnly,
      'stroke-1': webOnly,
      'stroke-2': webOnly,
    },
  },
  Accessibility: {
    'Screen Readers': {
      'sr-only': webOnly,
      'not-sr-only': webOnly,
    },
  },
  Plugins: {
    Official: {
      '@tailwindcss/typography': webOnly,
      '@tailwindcss/forms': webOnly,
      '@tailwindcss/aspect-ratio': webOnly,
      '@tailwindcss/container-queries': true,
    },
  },
};

export const data = Object.entries(rawData).flatMap(([category, subCategories]) => {
  return Object.entries(subCategories).flatMap(([subcategory, items]) => {
    return Object.entries(items).flatMap(([name, value]) => {
      if (value === true) {
        return {
          category,
          subcategory,
          name,
          native: true,
          web: true,
        };
      }

      return {
        category,
        subcategory,
        name,
        ...value,
      };
    });
  });
});
