{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-crypto",
    "version": "10.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo-crypto-10.2.0.aar",
          "url": "expo-crypto-10.2.0.aar",
          "size": 18351,
          "sha512": "7b82d44b653751cbb447536d56d336bd0b35ef6bfdb36f1376a6713e03abf9319c0c7408b629c1c7baeed57f3b440513b3225dea17a1eb2cb12cf9f5c53ef947",
          "sha256": "bb84faa6c4d0e498fabc22878d0c546fc6485bd71ed63ff60712c70b8d7649b1",
          "sha1": "66d8b9a2cf87c225d60bc3ed0d3de00c11b7a202",
          "md5": "e914b86faa93ae1a1876baa78703b772"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-crypto-10.2.0.aar",
          "url": "expo-crypto-10.2.0.aar",
          "size": 18351,
          "sha512": "7b82d44b653751cbb447536d56d336bd0b35ef6bfdb36f1376a6713e03abf9319c0c7408b629c1c7baeed57f3b440513b3225dea17a1eb2cb12cf9f5c53ef947",
          "sha256": "bb84faa6c4d0e498fabc22878d0c546fc6485bd71ed63ff60712c70b8d7649b1",
          "sha1": "66d8b9a2cf87c225d60bc3ed0d3de00c11b7a202",
          "md5": "e914b86faa93ae1a1876baa78703b772"
        }
      ]
    }
  ]
}
