{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-video-thumbnails",
    "version": "6.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-video-thumbnails-6.3.0.aar",
          "url": "expo-video-thumbnails-6.3.0.aar",
          "size": 19695,
          "sha512": "aa60130b9c9a6b4ffe411ea5783f12e149da99354294707efc923bf2a7707666a3bd0263f3f514f88f2b57efad5ee0185cd730d81f3f9eaca3a04ffcfd16e8c3",
          "sha256": "5f993e0b3ec25a2751693a5ec022e91c036b7851ee1d6c9447250259706b1fcf",
          "sha1": "e81e4d18ef7b0cc6ad76612e65833196ec6a49ee",
          "md5": "b6876e289f05fea61d40445d8df26f90"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-video-thumbnails-6.3.0.aar",
          "url": "expo-video-thumbnails-6.3.0.aar",
          "size": 19695,
          "sha512": "aa60130b9c9a6b4ffe411ea5783f12e149da99354294707efc923bf2a7707666a3bd0263f3f514f88f2b57efad5ee0185cd730d81f3f9eaca3a04ffcfd16e8c3",
          "sha256": "5f993e0b3ec25a2751693a5ec022e91c036b7851ee1d6c9447250259706b1fcf",
          "sha1": "e81e4d18ef7b0cc6ad76612e65833196ec6a49ee",
          "md5": "b6876e289f05fea61d40445d8df26f90"
        }
      ]
    }
  ]
}
