{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo-constants",
    "version": "13.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.device.yearclass",
          "module": "yearclass",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo-constants-13.1.0.aar",
          "url": "expo-constants-13.1.0.aar",
          "size": 31753,
          "sha512": "09cc0e90d6597cd3e1ec18fb948954f5ab544a451262d311e753df63202e61d11ff2bfd37b6c0f697659494dafccb5899793d3daeb52f35f48c2ee60861557a8",
          "sha256": "92a38422ec4657ac99a56b7cbad1a8b55f57fa359c2fdf6ed2868578bfbedc86",
          "sha1": "df0b58de606c271f5662c17f5a80f603f265b23e",
          "md5": "7932bebb920af34b4a1f827500913ce5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.device.yearclass",
          "module": "yearclass",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "host.exp.exponent",
          "module": "expo-modules-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "expo-constants-13.1.0.aar",
          "url": "expo-constants-13.1.0.aar",
          "size": 31753,
          "sha512": "09cc0e90d6597cd3e1ec18fb948954f5ab544a451262d311e753df63202e61d11ff2bfd37b6c0f697659494dafccb5899793d3daeb52f35f48c2ee60861557a8",
          "sha256": "92a38422ec4657ac99a56b7cbad1a8b55f57fa359c2fdf6ed2868578bfbedc86",
          "sha1": "df0b58de606c271f5662c17f5a80f603f265b23e",
          "md5": "7932bebb920af34b4a1f827500913ce5"
        }
      ]
    }
  ]
}
