name: Android Unit Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - .github/workflows/android-unit-tests.yml
      - fastlane/**
      - packages/**/android/**
      - tools/**
      - pnpm-lock.yaml
      - '!packages/@expo/cli/**'
      - '!tools/src/commands/GenerateDocsAPIData.ts'
  pull_request:
    paths:
      - .github/workflows/android-unit-tests.yml
      - fastlane/**
      - packages/**/android/**
      - tools/**
      - pnpm-lock.yaml
      - '!packages/@expo/cli/**'
      - '!tools/src/commands/GenerateDocsAPIData.ts'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 100
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m
    steps:
      - name: 👀 Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10
      - name: ⬢ Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'
      - name: 🧹 Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: 🔨 Use JDK 17
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          react-native-gradle-downloads: 'true'
          gradle: 'true'
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: expo
      - name: 💅 Run Spotless lint check
        working-directory: apps/bare-expo/android
        run: ./gradlew spotlessCheck || { echo '::error Spotless lint failed. Run `./gradlew spotlessApply` from `apps/bare-expo/android` to automatically fix formatting.' && exit 1; }
      - name: 🎸 Run native Android unit tests
        if: always()
        timeout-minutes: 30
        run: pnpm expotools native-unit-tests --platform android
      - name: 💾 Save test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results
          path: packages/*/android/build/test-results/**/*xml
