name: Check Template Bare Minimum Diffs

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bare-diffs:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: ⬢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-docs: 'true'
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🧐 Check diffs
        run: |
          echo "Checking that expo-template-bare-minimum diffs are updated"
          pnpm expotools generate-bare-diffs --check
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && github.event.ref == 'refs/heads/main'
        with:
          webhook: ${{ secrets.slack_webhook_docs }}
          author_name: Check for Changes in Bare Diffs
      - name: 💾 Store artifacts of diff failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: template-bare-minimum-bare-diff-failure
          path: docs/public/static/diffs/template-bare-minimum/raw
