name: Check Template Bare Minimum Diffs

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bare-diffs:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10
      - name: ⬢ Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          pnpm-docs: 'true'
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🛠 Build expotools
        run: pnpm turbo build --filter expotools...
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: expo
      - name: 🧐 Check diffs
        run: |
          echo "Checking that expo-template-bare-minimum diffs are updated"
          pnpm expotools generate-bare-diffs --check
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && github.event.ref == 'refs/heads/main' && github.repository == 'expo/expo'
        with:
          webhook: ${{ secrets.slack_webhook_docs }}
          author_name: Check for Changes in Bare Diffs
      - name: 💾 Store artifacts of diff failures
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: template-bare-minimum-bare-diff-failure
          path: docs/public/static/diffs/template-bare-minimum/raw
