name: Create Expo App

on:
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/create-expo-app.yml
      - packages/create-expo/**
      - pnpm-lock.yaml
  pull_request:
    paths:
      - .github/workflows/create-expo-app.yml
      - packages/create-expo/**
      - pnpm-lock.yaml
  schedule:
    - cron: 0 14 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 100
      - name: ⬇️ Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      - name: 🏗️ Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: 1.x
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: 📦 Install node modules in root dir
        run: pnpm install --frozen-lockfile
      - name: 🛠 Build create-expo
        run: pnpm run prepublishOnly
        working-directory: packages/create-expo
      - name: E2E Test create-expo
        run: pnpm test:e2e
        working-directory: packages/create-expo
