name: Development Client latest e2e

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * SUN' # 0:00 AM UTC time every Sunday

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detox_latest_e2e:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [36]
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🍺 Install required tools
        run: |
          brew tap wix/brew
          brew install applesimutils
          brew install watchman
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      - name: 💎 Install cocoapods
        run: sudo gem install cocoapods
      - name: 🔨 Use JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: 'true'
      - name: 🤖 Set up android emulator
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: 🧶 Install `expo-test-runner`
        run: |
          pnpm add -g expo-test-runner@$(cat package.json | grep '"expo-test-runner": "[0-9]*\.[0-9]*\.[0-9]*' | head -n 1 | awk '{print $2}' | sed 's/"//g; s/,//g')
        working-directory: packages/expo-dev-client
      - name: 🧪 Run tests
        run: |
          pnpm latest-e2e
        working-directory: packages/expo-dev-client
      - name: 💾 Store artifacts of build failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: expo-dev-client-latest-e2e-artifacts
          path: packages/expo-dev-client/artifacts
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure()
        with:
          webhook: ${{ secrets.slack_webhook_dev_client }}
          channel: '#dev-clients'
          author_name: Dev Client e2e
