name: Development Client

on:
  workflow_dispatch: {}
  # This task will fail due to migration to `expo-modules-core`.
  # We temporary disable it.
  # pull_request:
  #   paths:
  #     - .github/workflows/development-client.yml
  #     - packages/expo-dev-*/**
  # push:
  #   branches: [main]
  #   paths:
  #     - .github/workflows/development-client.yml
  #     - packages/expo-dev-*/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ndk-version: [21.4.7075529]
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          ndk: 'true'
          ndk-version: ${{ matrix.ndk-version }}
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: Init new expo app
        working-directory: ../
        run: pnpm create expo-app ./development-client-android-test --yes
      - name: Make Yarn resolve expo-dev-client dependencies locally
        working-directory: ../development-client-android-test
        run: |
          node -e " \
            const pkg = require('./package.json'); \
            pkg.resolutions = { \
              ...pkg.resolutions, \
              'expo-dev-menu': 'file:../expo/packages/expo-dev-menu', \
              'expo-dev-menu-interface': 'file:../expo/packages/expo-dev-menu-interface', \
              'expo-dev-launcher': 'file:../expo/packages/expo-dev-launcher', \
              'expo-updates-interface': 'file:../expo/packages/expo-updates-interface', \
              'expo-updates': 'file:../expo/packages/expo-updates', \
              'expo-manifests': 'file:../expo/packages/expo-manifests', \
              'expo-json-utils': 'file:../expo/packages/expo-json-utils', \
            }; \
            fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');"
      - name: Add dependencies
        working-directory: ../development-client-android-test
        run: pnpm add file:../expo/packages/expo-dev-client
      - name: Setup app.config.json
        working-directory: ../development-client-android-test
        run: echo "{\"name\":\"development-client-android-test\",\"plugins\":[\"expo-dev-client\"],\"android\":{\"package\":\"com.devclient.test\"},\"ios\":{\"bundleIdentifier\":\"com.devclient.test\"}}" > app.config.json
      - name: Prebuild Android
        working-directory: ../development-client-android-test
        run: pnpm expo prebuild --platform android
      - name: Bump `build tools`
        working-directory: ../development-client-android-test
        run: sed -i -e 's/buildToolsVersion\ =\ \"29\..\..\"/buildToolsVersion\ = \"30\.0\.3\"/' ./android/build.gradle
      - name: Bump `android build tools`
        working-directory: ../development-client-android-test
        run: sed -i -e 's/com\.android\.tools\.build:gradle:3\..\../com\.android\.tools\.build:gradle:3\.5\.4/' ./android/build.gradle
      - name: 🏗️ Build debug version
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/${{ matrix.ndk-version }}/
        working-directory: ../development-client-android-test/android
        run: ./gradlew assembleDebug

  ios:
    runs-on: macos-15
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: Init new expo app
        working-directory: ../
        run: pnpm create expo-app ./development-client-ios-test --yes
      - name: Make Yarn resolve expo-dev-client dependencies locally
        working-directory: ../development-client-ios-test
        run: |
          node -e " \
            const pkg = require('./package.json'); \
            pkg.resolutions = { \
              ...pkg.resolutions, \
              'expo-dev-menu': 'file:../expo/packages/expo-dev-menu', \
              'expo-dev-menu-interface': 'file:../expo/packages/expo-dev-menu-interface', \
              'expo-dev-launcher': 'file:../expo/packages/expo-dev-launcher', \
              'expo-updates-interface': 'file:../expo/packages/expo-updates-interface', \
              'expo-updates': 'file:../expo/packages/expo-updates', \
              'expo-manifests': 'file:../expo/packages/expo-manifests', \
              'expo-json-utils': 'file:../expo/packages/expo-json-utils', \
            }; \
            fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');"
      - name: Add dependencies
        working-directory: ../development-client-ios-test
        run: pnpm add file:../expo/packages/expo-dev-client
      - name: Setup app.config.json
        working-directory: ../development-client-ios-test
        run: echo "{\"name\":\"development-client-ios-test\",\"plugins\":[\"expo-dev-client\"],\"android\":{\"package\":\"com.devclient.test\"},\"ios\":{\"bundleIdentifier\":\"com.devclient.test\"}}" > app.config.json
      - name: Prebuild iOS
        working-directory: ../development-client-ios-test
        run: pnpm expo prebuild --platform ios
      - name: 🏗️ Build debug version
        working-directory: ../development-client-ios-test
        run: xcodebuild -workspace ios/developmentclientiostest.xcworkspace -scheme developmentclientiostest -configuration debug -sdk iphonesimulator -arch x86_64
