name: Expotools

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/expotools.yml
      - tools/**
  pull_request:
    paths:
      - .github/workflows/expotools.yml
      - tools/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
      - name: 🛠 Compile TypeScript sources
        run: pnpm build
        working-directory: tools
      - name: 🛠 Typecheck sources
        run: pnpm tsc --noEmit
        working-directory: tools
      - name: 🚨 Lint TypeScript sources
        run: pnpm lint --max-warnings 0
        working-directory: tools
