name: Expotools

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/expotools.yml
      - tools/**
  pull_request:
    paths:
      - .github/workflows/expotools.yml
      - tools/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
      - name: 🛠 Compile TypeScript sources
        run: pnpm turbo build --filter expotools...
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: expo
      - name: 🛠 Typecheck sources
        run: pnpm tsc --noEmit
        working-directory: tools
      - name: 🚨 Lint TypeScript sources
        run: pnpm lint --max-warnings 0
        working-directory: tools
      - name: 🧪 Test sources
        run: pnpm test
        working-directory: tools
