name: Fingerprint

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/fingerprint.yml
      - packages/@expo/fingerprint/**
      - packages/create-expo/**
      - pnpm-lock.yaml
  pull_request:
    paths:
      - .github/workflows/fingerprint.yml
      - packages/@expo/fingerprint/**
      - packages/create-expo/**
      - pnpm-lock.yaml
  schedule:
    - cron: 0 14 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 100
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: ⬢ Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 🚀 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      - name: ⬇️ Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'main' }}:${{ github.event.before || github.base_ref || 'main' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: E2E Test @expo/fingerprint
        run: |
          pnpm tsc
          pnpm jest --config e2e/jest.config.js --ci --runInBand
        working-directory: packages/@expo/fingerprint
      - name: ⚙️  Create temp project
        run: |
          cd ..
          bunx create-expo-app -t blank@sdk-52 my-app
      - name: 💾 Create fingerprint from the temp project
        if: ${{ startsWith(matrix.os, 'windows') == false }}
        env:
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
        run: |
          cd ../my-app

          # Add dependencies with native binaries
          bun add -D sharp
          cat > fingerprint.config.js <<EOF
          /** @type {import('expo/fingerprint').Config} */
          const config = {
            extraSources: [
              {
                type: 'dir',
                filePath: 'node_modules/@img',
              },
              {
                type: 'dir',
                filePath: 'node_modules/sharp',
              },
            ],
          };
          module.exports = config;
          EOF

          if [[ "${{ env.ACTIONS_STEP_DEBUG }}" == "true" ]]; then
            ../expo/packages/@expo/fingerprint/bin/cli.js fingerprint:generate --debug > ../expo/fingerprint-${{ matrix.os }}.json
          else
            ../expo/packages/@expo/fingerprint/bin/cli.js fingerprint:generate > ../expo/fingerprint-${{ matrix.os }}.json
          fi
      - name: 💾 Create fingerprint from the temp project (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        env:
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
        shell: pwsh
        run: |
          cd ../my-app

          # Add dependencies with native binaries
          bun add -D sharp
          @"
          /** @type {import('expo/fingerprint').Config} */
          const config = {
            extraSources: [
              {
                type: 'dir',
                filePath: 'node_modules/@img',
              },
              {
                type: 'dir',
                filePath: 'node_modules/sharp',
              },
            ],
          };
          module.exports = config;
          "@ | Set-Content fingerprint.config.js

          if ($env:ACTIONS_STEP_DEBUG -eq "true") {
            node ../expo/packages/@expo/fingerprint/bin/cli.js fingerprint:generate --debug > ../expo/fingerprint-${{ matrix.os }}.json
          } else {
            node ../expo/packages/@expo/fingerprint/bin/cli.js fingerprint:generate > ../expo/fingerprint-${{ matrix.os }}.json
          }
      - name: 📤 Upload fingerprint
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: fingerprint-${{ matrix.os }}
          path: fingerprint-${{ matrix.os }}.json

  cross-platform-checks:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download fingerprint (macos)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: fingerprint-macos-latest

      - name: 📥 Download fingerprint (ubuntu)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: fingerprint-ubuntu-latest

      - name: 📥 Download fingerprint (windows)
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: fingerprint-windows-latest

      - name: 👀 Check fingerprint consistency
        shell: bash
        run: |
          hash_macos=$(jq -r '.hash' fingerprint-macos-latest.json)
          hash_ubuntu=$(jq -r '.hash' fingerprint-ubuntu-latest.json)
          hash_windows=$(jq -r '.hash' fingerprint-windows-latest.json)

          echo "Hash from fingerprint-macos-latest.json: $hash_macos"
          echo "Hash from fingerprint-ubuntu-latest.json: $hash_ubuntu"
          echo "Hash from fingerprint-windows-latest.json: $hash_windows"

          if [[ "$hash_macos" != "$hash_ubuntu" || "$hash_ubuntu" != "$hash_windows" ]]; then
            echo "Hashes do not match!"
            exit 1
          else
            echo "All hashes match!"
          fi
