name: Process when issue is closed

on:
  issues:
    types: [closed]

jobs:
  run-on-issue-accepted:
    runs-on: ubuntu-24.04
    if: contains(github.event.issue.labels.*.name, 'Issue accepted')
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
      - name: 🔎 Close Linear issue
        # accepted issues should have a corresponding Linear issue (from issue-triage.yml)
        # if not, we don't want to fail the workflow
        continue-on-error: true
        run: pnpm expotools close-linear-issue-from-github --issue "${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.EXPO_BOT_GITHUB_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
