name: Issue needs attention

on:
  issues:
    types: [opened]

jobs:
  issue:
    runs-on: ubuntu-20.04
    steps:
      - uses: 8398a7/action-slack@v3.8.0
        if: ${{ contains( env.TRUSTED_USERS, github.event.issue.user.login ) }}
        env:
          TRUSTED_USERS: 'RodolfoGS awinograd hesyifei LinusU SimenB actuallymentor derekstavis wscotten wcandillon tevonsb MaRaSu devashishsethia'
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_expo_support }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          status: ${{ job.status }}
          channel: '#support'
          text: 'This issue should be triaged ASAP: ${{ github.event.issue.html_url }}'
          author_name: ${{ github.event.issue.user.login }}
          fields: repo
