name: Sync App Template Repository

on:
  workflow_dispatch: {}
  push:
    branches: [sdk-54]
    paths:
      - .github/workflows/sync-template.yml
      - templates/expo-template-default/**

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: 🚚 Rename .gitignore
        run: mv ./templates/expo-template-default/gitignore ./templates/expo-template-default/.gitignore
      - name: 🚀 Push changes to the template repository
        uses: cpina/github-action-push-to-another-repository@55306faa4ed53b815ae49e564af8cfb359d32ae2 # main
        env:
          API_TOKEN_GITHUB: ${{ secrets.EXPO_BOT_GITHUB_TOKEN }}
        with:
          source-directory: 'templates/expo-template-default'
          destination-github-username: 'expo'
          destination-repository-name: 'expo-template-default'
          user-name: Expo Bot
          user-email: expo-bot@users.noreply.github.com
          target-branch: main
          commit-message: Sync the default project template from ORIGIN_COMMIT
