name: E2E Test Suite for Expo Brownfield

on:
  workflow_dispatch: {}
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/test-suite-brownfield-isolated.yml
      - apps/brownfield-tester/expo-app/**
      - packages/expo-brownfield/**
      - '!**.md'
      - '!**/__tests__/**'
      - '!**/__mocks__/**'
  pull_request:
    paths:
      - .github/workflows/test-suite-brownfield-isolated.yml
      - apps/brownfield-tester/expo-app/**
      - packages/expo-brownfield/**
      - '!**.md'
      - '!**/__tests__/**'
      - '!**/__mocks__/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-platform-for-e2e:
    runs-on: ubuntu-24.04
    outputs:
      should_run_ios: ${{ steps.changes.outputs.should_run_ios }}
      should_run_android: ${{ steps.changes.outputs.should_run_android }}
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v5
      - name: 🧐 Detect platform change
        id: changes
        uses: ./.github/actions/detect-platform-change
        with:
          android-paths: >-
            "packages/expo-brownfield/android/**",
            "packages/expo-brownfield/gradle-plugins/**"

          ios-paths: >-
            "packages/expo-brownfield/ios/**"

          common-paths: >-
            .github/workflows/test-suite-brownfield-isolated.yml,
            "apps/brownfield-tester/expo-app/**",
            "packages/expo-brownfield/cli/**",
            "packages/expo-brownfield/plugin/**",
            "packages/expo-brownfield/src/**",
            "packages/expo-brownfield/e2e/maestro/**"

  android-build:
    runs-on: ubuntu-24.04
    needs: detect-platform-for-e2e
    if: needs.detect-platform-for-e2e.outputs.should_run_android == 'true'
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=4096m"
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v5
      - name: 🧹 Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: 🔨 Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: 'true'
          react-native-gradle-downloads: 'true'
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: 🤖 Build and publish Android artifacts (apps/brownfield-tester/expo-app)
        run: |
          npx expo prebuild --clean -p android
          npx expo-brownfield build:android --repo MavenLocal --verbose
        working-directory: apps/brownfield-tester/expo-app
      - name: 🏗️ Build Debug APK
        run: |
          ./gradlew clean assembleDebug --refresh-dependencies
        working-directory: apps/brownfield-tester/android-integrated
      - name: 💾 Store Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-brownfield-android-debug
          path: apps/brownfield-tester/android-integrated/app/build/outputs/apk/debug/app-debug.apk
      - name: 🏗️ Build Release APK
        run: |
          ./gradlew clean
          ./gradlew assembleRelease --refresh-dependencies
        working-directory: apps/brownfield-tester/android-integrated
      - name: 💾 Store Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-brownfield-android-release
          path: apps/brownfield-tester/android-integrated/app/build/outputs/apk/release/app-release.apk

  android-e2e:
    runs-on: ubuntu-24.04
    needs: android-build
    strategy:
      matrix:
        api-level: [36]
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v5
      - name: 🧹 Cleanup GitHub Linux runner disk space
        uses: ./.github/actions/cleanup-linux-disk-space
      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: 🌠 Download build (Release)
        uses: actions/download-artifact@v4
        with:
          name: expo-brownfield-android-release
          path: apps/brownfield-tester/android-integrated/apk
      - name: 🌠 Download build (Debug)
        uses: actions/download-artifact@v4
        with:
          name: expo-brownfield-android-debug
          path: apps/brownfield-tester/android-integrated/apk
      - name: 🍺 Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: 🧪 Run e2e tests (Release)
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: 
            ./packages/expo-brownfield/e2e/scripts/run-e2e-android.sh
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: 🚇 Start Metro server
        run: |
          pnpm start --clear &
          npx wait-on http://localhost:8081 --timeout 60000
        working-directory: apps/brownfield-tester/expo-app
      - name: 🧪 Run e2e tests (Debug)
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: |
            CONFIGURATION=Debug ./packages/expo-brownfield/e2e/scripts/run-e2e-android.sh
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_android }}
          channel: '#expo-android'
          author_name: E2E Test Suite for Expo Brownfield

  ios-build-and-e2e:
    runs-on: macos-15
    needs: detect-platform-for-e2e
    if: needs.detect-platform-for-e2e.outputs.should_run_ios == 'true'
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v5
      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
          # TODO(cedric): swap `latest` back once the issue is resolved
          bun-version: latest
      - name: 🔨 Switch to Xcode 26.2
        run: sudo xcode-select --switch /Applications/Xcode_26.2.app
      - name: 🍺 Install required tools
        run: |
          brew install watchman || true
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      - name: 🔄 Setup ccache
        uses: ./.github/actions/setup-ccache
      - name: ♻️ Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/.ccache
          key: ccache-ios-brownfield-${{ hashFiles('pnpm-lock.yaml', '**/Podfile.lock') }}-${{ github.sha }}
          restore-keys: |
            ccache-ios-brownfield-${{ hashFiles('pnpm-lock.yaml', '**/Podfile.lock') }}-
            ccache-ios-brownfield-
      - name: 🔄 Reset ccache statistics
        run: ccache -z
      - name: 💎 Install xcodeproj gem
        run: gem install xcodeproj
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: 🍏 Build iOS artifacts (Release)
        run: |
          npx expo prebuild --clean -p ios
          npx expo-brownfield build:ios -r --verbose -a ../../../artifacts -p BrownfieldPackage
        working-directory: apps/brownfield-tester/expo-app
      - name: 🔨 Add XCFrameworks to SwiftUI project
        run: ruby packages/expo-brownfield/e2e/scripts/add_xcframeworks.rb
      - name: 🍺 Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
      - name: 🧪 Run e2e tests (Release)
        run: ./packages/expo-brownfield/e2e/scripts/run-e2e-ios.sh
      # Tests are unstable on GitHub macOS runner - might be
      # the best to migrate them to EAS
      # - name: 🍏 Build iOS artifacts (Debug)
      #   run: |
      #     npx expo-brownfield build:ios -d --verbose -a ../../../artifacts -p BrownfieldPackage
      #   working-directory: apps/brownfield-tester/expo-app
      # - name: 🔨 Add XCFrameworks to SwiftUI project
      #   run: ruby packages/expo-brownfield/e2e/scripts/add_xcframeworks.rb
      # - name: 🚇 Start Metro server
      #   run: |
      #     yarn start --clear &
      #     npx wait-on http://localhost:8081 --timeout 60000
      #   working-directory: apps/brownfield-tester/expo-app
      # - name: 🧪 Run e2e tests (Debug)
      #   run: CONFIGURATION=Debug ./packages/expo-brownfield/e2e/scripts/run-e2e-ios.sh
      - name: 💾 Save ccache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ${{ runner.temp }}/.ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}
      - name: Show ccache stats
        run: ccache -s -v
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_ios }}
          channel: '#expo-ios'
          author_name: E2E Test Suite for Expo Brownfield
