name: Test Suite macOS

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/test-suite-macos.yml
      - apps/bare-expo/macos/**
      - packages/expo/**
      - packages/expo-asset/**
      - packages/expo-constants/**
      - packages/expo-crypto/**
      - packages/expo-dev-client/**
      - packages/expo-dev-launcher/**
      - packages/expo-dev-menu/**
      - packages/expo-eas-client/**
      - packages/expo-file-system/**
      - packages/expo-font/**
      - packages/expo-keep-awake/**
      - packages/expo-linking/**
      - packages/expo-local-authentication/**
      - packages/expo-manifests/**
      - packages/expo-mesh-gradient/**
      - packages/expo-modules-autolinking/**
      - packages/expo-modules-core/**
      - packages/expo-sqlite/**
      - packages/expo-structured-headers/**
      - packages/expo-updates/**
      - packages/expo-updates-interface/**
      - packages/expo-web-browser/**
      - '!packages/**/android/**'
      # Common ignores from detect-platform-change action
      - '!**/*.md'
      - '!**/LICENSE*'
      - '!**/.gitignore'
      - '!**/CHANGELOG*'
      - '!**/.npmignore'
      - '!**/.eslintrc*'
      - '!**/.prettierrc*'
      - '!**/.gitattributes'
      - '!**/.watchmanconfig'
      - '!**/.fingerprintignore'
      - '!**/__tests__/**'
      - '!**/__mocks__/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-build:
    runs-on: macos-15
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: true
      - name: 🔨 Switch to Xcode 26.2
        run: sudo xcode-select --switch /Applications/Xcode_26.2.app
      - name: 🍺 Install required tools
        run: |
          brew install watchman || true
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 💎 Setup Ruby and install gems
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          bare-expo-macos-pods: 'true'
      - name: 📦 Install node modules
        run: pnpm install --frozen-lockfile
      - name: 🕵️ Debug CocoaPods lockfiles
        run: git diff Podfile.lock Pods/Manifest.lock
        working-directory: apps/bare-expo/macos
        continue-on-error: true
      - name: 🌳 Display pod environment
        run: pod env
        working-directory: apps/bare-expo/macos
      - name: 🖥️ Run bare-expo macos setup script
        run: ./scripts/setup-macos-project.sh
        working-directory: apps/bare-expo/
      - name: 🥥 Install pods in apps/bare-expo/macos
        if: steps.expo-caches.outputs.bare-expo-pods-hit != 'true'
        run: pod install
        working-directory: apps/bare-expo/macos
      - name: 🏗️ Build macOS project
        run: |
          set -o pipefail
          xcodebuild -workspace macos/BareExpo-macOS.xcworkspace -scheme ExpoMacOS-macOS -sdk macosx -derivedDataPath "macos/build" | xcpretty
        working-directory: apps/bare-expo
        timeout-minutes: 55
        env:
          EXPO_DEBUG: 1
          NODE_ENV: production
      - name: 📸 Upload builds
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: bare-expo-macos-builds
          path: apps/bare-expo/macos/build/BareExpo.app
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        with:
          webhook: ${{ secrets.slack_webhook_ios }}
          channel: '#expo-ios'
          author_name: Test Suite (macOS)
