name: Validate owners of packages on npm

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * *' # 8:00 AM UTC time every day

jobs:
  validate-npm-owners:
    runs-on: ubuntu-24.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: 🔨 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 🔨 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
      - name: 🔎 Validate
        run: pnpm expotools validate-npm-owners
        env:
          NPM_TOKEN_READ_ONLY: ${{ secrets.NPM_TOKEN_READ_ONLY }}
      - name: 🔔 Notify on Slack
        uses: ./.github/actions/slack-notify
        if: failure()
        with:
          webhook: ${{ secrets.slack_webhook_api }}
          author_name: Validate npm owners
