/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type TintStyle = any;

export type ViewProps = {
  tint: TintStyle;
  intensity: number;
};

export function View(props: ViewProps) {}
