name: 'Cleanup GitHub Linux Runner Disk Space'
description: 'Cleanup unused preinstalled packages on the GitHub Ubuntu runners'

runs:
  using: 'composite'
  steps:
    - name: '🧹 Cleanup preinstalled packages'
      shell: bash
      run: |
        echo 'Disk space before cleanup'
        df -aH
        sudo apt-get remove -y --purge '^mysql-.*' '^mongodb-.*' '^mssql-.*' '^postgresql-.*' '^aspnetcore-*' '^dotnet-.*' '^php.*-.*' 'mono-complete' '^llvm-.*' 'powershell' 'google-chrome-*' 'microsoft-edge-*' 'firefox' 'nginx' 'apache2' 'ghc' '^ghc-*'
        sudo apt-get autoremove -y
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/.ghcup /opt/ghc
        echo 'Showing Android SDKs'
        ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list
        ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall 'ndk;24.0.8215888' 'ndk;25.2.9519653' 'ndk;26.2.11394342'
        echo 'Removing all Docker images'
        docker rmi -f $(docker images -aq)
        echo 'Disk space after cleanup'
        df -aH
