require File.join(File.dirname(`node --print "require.resolve('react-native-macos/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

prepare_react_native_project!

target 'BareExpo-macOS' do
  platform :macos, '10.15'
  config = use_native_modules!

  use_expo_modules!

  use_react_native!(
    :path => "#{config[:reactNativePath]}-macos",
    :hermes_enabled => false,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end
